-- Leave type rules are stored in public.system_settings using:
-- category = 'leave_rules'
-- setting_key = 'leave_type_rules'
--
-- settings JSON shape:
-- {
--   "version": 1,
--   "rules": [
--     {
--       "id": "LT-001",
--       "name": "特休",
--       "isPaid": true,
--       "payMode": "全薪",
--       "deductAttendanceBonus": false,
--       "minimumUnitMinutes": 60,
--       "minimumUnitHours": 1,
--       "maxDailyHours": 8,
--       "annualQuotaHours": null,
--       "attachmentRequirement": "不需附件",
--       "attachmentNote": "依到職年資自動計算額度",
--       "enabled": true
--     }
--   ],
--   "updatedAt": "ISO-8601 timestamp"
-- }
