import {
  ArchiveX,
  Building2,
  CalendarClock,
  Clock3,
  ClipboardList,
  FileClock,
  FileSearch,
  FileText,
  Home,
  HandCoins,
  LogOut,
  MailOpen,
  Package,
  Stamp,
  TriangleAlert,
  UploadCloud,
  UserPlus,
  UserRoundCog,
  Wrench,
  type LucideIcon,
} from "lucide-react";
import type { DemoRequestType } from "@/lib/requests/workflow-store";
import type { Permission } from "@/lib/auth/rbac";

export type RequestFieldType = "text" | "date" | "time" | "number" | "select";

export type RequestField = {
  name: string;
  type?: RequestFieldType;
  required?: boolean;
  options?: string[];
  placeholder?: string;
};

export type RequestFormDefinition = {
  id: string;
  type: DemoRequestType;
  title: string;
  category: string;
  subtitle: string;
  description: string;
  estimatedMinutes: number;
  owner: string;
  attachmentHint: string;
  policyNotes: string[];
  icon: LucideIcon;
  permissions: Permission[];
  fields: RequestField[];
  requiresAttachment?: boolean;
};

export const requestFormDefinitions: RequestFormDefinition[] = [
  {
    id: "leave",
    type: "請假",
    title: "請假單",
    category: "假勤類",
    subtitle: "特休、事假、病假、家庭照顧假",
    description: "填寫假別、日期、時數與職務代理人，送出後進入主管與人資簽核。",
    estimatedMinutes: 3,
    owner: "員工本人",
    attachmentHint: "病假、產假、陪產檢及陪產假等需依公司規則補證明。",
    policyNotes: ["送出前檢查假別餘額、附件與性別平等工作法保護假別。", "核准後會連動出勤月曆與薪資扣薪或支薪規則。"],
    icon: CalendarClock,
    permissions: ["request:create", "form:attendance:create"],
    requiresAttachment: true,
    fields: [
      { name: "假別", type: "select", required: true, options: ["特休", "事假", "病假", "生理假", "家庭照顧假", "公假", "產假", "產檢假", "陪產檢及陪產假", "育嬰留職停薪"] },
      { name: "開始日期", type: "date", required: true },
      { name: "結束日期", type: "date", required: true },
      { name: "開始時間", type: "time", required: true },
      { name: "結束時間", type: "time", required: true },
      { name: "請假時數", type: "number", required: true },
      { name: "職務代理人", type: "select", required: true, options: ["陳怡霖", "潘雨柔", "陳羽俊", "劉巧涵", "李佳泰"] },
    ],
  },
  {
    id: "pre-overtime",
    type: "加班",
    title: "預先加班單",
    category: "假勤類",
    subtitle: "事前申請加班核准",
    description: "員工在預計加班前先填寫日期、時間、原因與預估工作內容，核准後才進入正式加班與薪資前置流程。",
    estimatedMinutes: 3,
    owner: "員工本人",
    attachmentHint: "可附主管指派紀錄、活動通知或工作排程。",
    policyNotes: ["預先加班單核准後，實際加班仍需依打卡或加班單確認。", "系統會檢查每日工時、休息日/例假日與月加班上限。"],
    icon: Clock3,
    permissions: ["request:create", "form:attendance:create"],
    fields: [
      { name: "預計加班日期", type: "date", required: true },
      { name: "預計開始時間", type: "time", required: true },
      { name: "預計結束時間", type: "time", required: true },
      { name: "加班類型", type: "select", required: true, options: ["平日加班", "休息日加班", "例假日出勤", "國定假日出勤"] },
      { name: "補休或加班費", type: "select", required: true, options: ["加班費", "補休"] },
      { name: "預計工作內容", required: true, placeholder: "請簡述預計加班處理事項" },
      { name: "主管事前指派", type: "select", required: true, options: ["是", "否"] },
    ],
  },
  {
    id: "overtime",
    type: "加班",
    title: "加班單",
    category: "假勤類",
    subtitle: "平日、休息日、例假日、國定假日",
    description: "填寫加班日期、時間與補償方式，後續可銜接加班費或補休。",
    estimatedMinutes: 3,
    owner: "員工本人",
    attachmentHint: "必要時附工作紀錄、活動紀錄或主管指派截圖。",
    policyNotes: ["系統會檢查每日工時、月加班上限與例假日出勤原因。", "核准後才可進入加班費或補休計算。"],
    icon: Clock3,
    permissions: ["request:create", "form:attendance:create"],
    fields: [
      { name: "加班日期", type: "date", required: true },
      { name: "開始時間", type: "time", required: true },
      { name: "結束時間", type: "time", required: true },
      { name: "加班類型", type: "select", required: true, options: ["平日加班", "休息日加班", "例假日出勤", "國定假日出勤"] },
      { name: "補休或加班費", type: "select", required: true, options: ["加班費", "補休"] },
      { name: "是否已有預先加班單", type: "select", required: true, options: ["是", "否"] },
      { name: "工作內容", required: true, placeholder: "請簡述加班處理事項" },
    ],
  },
  {
    id: "punch",
    type: "補卡",
    title: "忘刷申請",
    category: "假勤類",
    subtitle: "補上班卡、補下班卡、修正時間",
    description: "填寫補卡類型、日期、時間與原因，簽核後應回寫出勤紀錄。",
    estimatedMinutes: 2,
    owner: "員工本人",
    attachmentHint: "需上傳服務紀錄、定位截圖、主管說明或其他佐證。",
    policyNotes: ["補卡會回寫出勤與薪資來源，缺少佐證不得送出。", "核准後會更新出勤異常與薪資草稿。"],
    icon: FileClock,
    permissions: ["request:create", "form:attendance:create"],
    requiresAttachment: true,
    fields: [
      { name: "補卡類型", type: "select", required: true, options: ["補上班卡", "補下班卡", "修正打卡時間"] },
      { name: "補卡日期", type: "date", required: true },
      { name: "補卡時間", type: "time", required: true },
      { name: "異常原因", required: true, placeholder: "例如：手機沒電、忘記刷卡、服務地點網路異常" },
    ],
  },
  {
    id: "remote",
    type: "遠端辦公",
    title: "居家遠端辦公申請單",
    category: "假勤類",
    subtitle: "居家、臨時遠端辦公",
    description: "填寫辦公日期、地點、工作項目與可聯繫時段，核准後仍需保留出勤與工作成果紀錄。",
    estimatedMinutes: 2,
    owner: "員工本人",
    attachmentHint: "可附工作計畫、主管指派或服務紀錄。",
    policyNotes: ["遠端辦公仍需保留出勤與工作成果紀錄。", "主管可依部門需求退回補件。"],
    icon: Home,
    permissions: ["request:create", "form:attendance:create"],
    fields: [
      { name: "辦公日期", type: "date", required: true },
      { name: "開始時間", type: "time", required: true },
      { name: "結束時間", type: "time", required: true },
      { name: "辦公地點", required: true },
      { name: "工作項目", required: true },
      { name: "可聯繫時段", required: true },
      { name: "是否可視訊/電話聯繫", type: "select", required: true, options: ["是", "否"] },
    ],
  },
  {
    id: "position-change",
    type: "人事異動",
    title: "職務調動",
    category: "異動類",
    subtitle: "部門、職稱、據點、主管異動",
    description: "填寫員工職務調動前後資料、生效日期與異動原因，核准後回寫員工異動紀錄與主檔。",
    estimatedMinutes: 4,
    owner: "主管 / 人資",
    attachmentHint: "可附調動簽呈、主管溝通紀錄或員工同意文件。",
    policyNotes: ["職務調動需留下異動前後、原因、生效日與建立人。", "涉及薪資、工時或工作地點重大變更時，應由人資確認勞動契約與個資留痕。"],
    icon: UserRoundCog,
    permissions: ["request:create", "form:change:create"],
    fields: [
      { name: "異動員工", required: true, placeholder: "請輸入員工姓名或員工編號" },
      { name: "原部門", required: true },
      { name: "新部門", required: true },
      { name: "原職稱", required: true },
      { name: "新職稱", required: true },
      { name: "原直屬主管", required: true },
      { name: "新直屬主管", required: true },
      { name: "生效日期", type: "date", required: true },
      { name: "異動原因", required: true, placeholder: "請說明職務調動原因" },
    ],
  },
  {
    id: "salary-change",
    type: "薪資調整",
    title: "薪資異動",
    category: "異動類",
    subtitle: "本薪、津貼、投保級距調整",
    description: "填寫薪資異動項目、調整前後金額與生效日期，核准後進入薪資主檔與薪資調整紀錄。",
    estimatedMinutes: 4,
    owner: "人資 / 行政部門主任",
    attachmentHint: "可附核薪簽呈、考核紀錄或任用條件確認文件。",
    policyNotes: ["薪資異動屬敏感資料，主管不得查看完整薪資內容。", "核准後應建立薪資調整紀錄，薪資鎖定後不得任意覆蓋。"],
    icon: HandCoins,
    permissions: ["request:create", "form:change:create"],
    fields: [
      { name: "異動員工", required: true, placeholder: "請輸入員工姓名或員工編號" },
      { name: "異動項目", type: "select", required: true, options: ["本薪", "職務津貼", "證照津貼", "交通津貼", "全勤獎金", "主管加給", "投保級距", "其他"] },
      { name: "調整前金額", type: "number", required: true },
      { name: "調整後金額", type: "number", required: true },
      { name: "生效日期", type: "date", required: true },
      { name: "調整原因", required: true, placeholder: "請說明調薪、津貼或級距調整原因" },
      { name: "是否影響當月薪資", type: "select", required: true, options: ["是", "否"] },
    ],
  },
  {
    id: "resignation",
    type: "人事異動",
    title: "離職申請",
    category: "異動類",
    subtitle: "離職、交接、最後工作日",
    description: "填寫預計離職日、離職原因與交接安排，核准後進入離職流程、薪資結算與帳號停用檢核。",
    estimatedMinutes: 4,
    owner: "員工本人 / 主管",
    attachmentHint: "可附離職申請書、交接清單或主管溝通紀錄。",
    policyNotes: ["離職流程需連動薪資結算、證照文件、帳號權限與交接紀錄。", "離職原因屬敏感資料，需依角色權限控管。"],
    icon: LogOut,
    permissions: ["request:create", "form:change:create"],
    requiresAttachment: true,
    fields: [
      { name: "離職員工", required: true, placeholder: "請輸入員工姓名或員工編號" },
      { name: "預計離職日", type: "date", required: true },
      { name: "最後工作日", type: "date", required: true },
      { name: "離職原因類型", type: "select", required: true, options: ["個人生涯規劃", "家庭因素", "健康因素", "轉職", "留停未復職", "資遣", "其他"] },
      { name: "交接人", required: true },
      { name: "交接完成日", type: "date", required: true },
      { name: "是否需離職面談", type: "select", required: true, options: ["是", "否"] },
    ],
  },
  {
    id: "new-hire",
    type: "人事異動",
    title: "新進人員",
    category: "異動類",
    subtitle: "到職建檔、任職資料、帳號開通",
    description: "填寫新進人員基本任職資料，核准後建立員工主檔、帳號、薪資前置與證照/教育訓練待辦。",
    estimatedMinutes: 5,
    owner: "人資",
    attachmentHint: "可附錄取通知、報到文件、身分證明、證照或銀行帳戶資料。",
    policyNotes: ["新進人員建立後需檢查資料完整度、帳號權限、勞健保與薪資設定。", "個資與薪資欄位需依角色權限保護。"],
    icon: UserPlus,
    permissions: ["request:create", "form:change:create"],
    requiresAttachment: true,
    fields: [
      { name: "中文姓名", required: true },
      { name: "手機", required: true },
      { name: "Email", required: true },
      { name: "到職日", type: "date", required: true },
      { name: "公司", required: true },
      { name: "據點", required: true },
      { name: "部門", required: true },
      { name: "職稱", required: true },
      { name: "直屬主管", required: true },
      { name: "薪資型態", type: "select", required: true, options: ["月薪", "時薪", "日薪", "件計"] },
    ],
  },
  {
    id: "document",
    type: "文件證明",
    title: "文件證明申請單",
    category: "文件類",
    subtitle: "通用證明與其他文件",
    description: "申請一般文件證明或特殊用途文件，由人資確認內容後製作並通知領取。",
    estimatedMinutes: 2,
    owner: "員工本人",
    attachmentHint: "特殊用途可附申請機關要求、格式範本或補充說明。",
    policyNotes: ["人資製作文件後會回寫文件附件與通知。", "涉及薪資或個資內容需依權限控管。"],
    icon: FileText,
    permissions: ["request:create", "form:document:create"],
    fields: [
      { name: "文件類型", type: "select", required: true, options: ["離職證明", "薪資證明", "服務證明", "其他證明"] },
      { name: "用途", required: true },
      { name: "領取方式", type: "select", required: true, options: ["現場領取", "Email", "郵寄"] },
      { name: "收件地址" },
    ],
  },
  {
    id: "labor-health-insurance-certificate",
    type: "文件證明",
    title: "勞健保證明申請單",
    category: "文件類",
    subtitle: "勞保、健保、投保資料證明",
    description: "申請勞保、健保或投保級距相關證明，由人資依員工主檔與保險資料製作。",
    estimatedMinutes: 2,
    owner: "員工本人",
    attachmentHint: "如申請機關有指定格式，可上傳範本或說明。",
    policyNotes: ["勞健保資料屬個資，員工只能申請本人資料。", "人資製作後需保留發放紀錄與用途。"],
    icon: FileText,
    permissions: ["request:create", "form:document:create"],
    fields: [
      { name: "證明類型", type: "select", required: true, options: ["勞保投保證明", "健保投保證明", "勞健保合併證明", "投保級距證明"] },
      { name: "申請用途", required: true, placeholder: "例如：銀行貸款、租屋、政府補助、學校申請" },
      { name: "資料期間", required: true, placeholder: "例如：2026-01 至 2026-05，或填寫目前在職期間" },
      { name: "領取方式", type: "select", required: true, options: ["現場領取", "Email", "郵寄"] },
      { name: "收件地址" },
    ],
  },
  {
    id: "employment-certificate",
    type: "文件證明",
    title: "在職證明申請單",
    category: "文件類",
    subtitle: "在職證明、任職資料證明",
    description: "申請在職證明，由人資依員工任職資料、部門、職稱與到職日製作。",
    estimatedMinutes: 2,
    owner: "員工本人",
    attachmentHint: "如需指定抬頭、格式或英文版，可附申請單位要求。",
    policyNotes: ["在職證明只能申請本人資料。", "如需英文姓名、職稱或薪資資訊，須由人資確認個資與薪資權限。"],
    icon: FileText,
    permissions: ["request:create", "form:document:create"],
    fields: [
      { name: "證明用途", required: true, placeholder: "例如：銀行貸款、租屋、簽證、學校申請" },
      { name: "證明語言", type: "select", required: true, options: ["中文", "英文", "中英文"] },
      { name: "是否顯示薪資", type: "select", required: true, options: ["否", "是"] },
      { name: "指定抬頭" },
      { name: "領取方式", type: "select", required: true, options: ["現場領取", "Email", "郵寄"] },
      { name: "收件地址" },
    ],
  },
  {
    id: "internal-approval",
    type: "內部簽核",
    title: "內部簽核",
    category: "業務類",
    subtitle: "一般事項、採購、制度、專案簽核",
    description: "提交公司內部需要主管、行政主任或人資確認的事項，送出後依固定簽核流程留痕。",
    estimatedMinutes: 3,
    owner: "員工本人 / 主管",
    attachmentHint: "可附報價單、制度草案、專案說明或其他佐證。",
    policyNotes: ["內部簽核需留下申請事項、目的、影響範圍與附件。", "涉及金額、員工權益或個資時，後續應由行政主任或人資覆核。"],
    icon: ClipboardList,
    permissions: ["request:create", "form:business:create"],
    fields: [
      { name: "簽核主旨", required: true, placeholder: "例如：申請採購辦公設備" },
      { name: "簽核類型", type: "select", required: true, options: ["一般事項", "採購", "專案", "制度", "人員支援", "其他"] },
      { name: "申請日期", type: "date", required: true },
      { name: "需求完成日", type: "date", required: true },
      { name: "影響部門", required: true, placeholder: "例如：行政部、人資部、全公司" },
      { name: "是否涉及費用", type: "select", required: true, options: ["否", "是"] },
      { name: "預估金額", type: "number" },
    ],
  },
  {
    id: "meeting-minutes",
    type: "會議記錄",
    title: "會議記錄上傳",
    category: "業務類",
    subtitle: "會議紀錄、決議事項、追蹤待辦",
    description: "上傳或登錄會議紀錄，將決議、負責人與完成期限留下正式紀錄。",
    estimatedMinutes: 4,
    owner: "會議召集人 / 紀錄人",
    attachmentHint: "請上傳會議紀錄、簽到表、簡報或相關附件。",
    policyNotes: ["會議紀錄需保留會議日期、出席對象、決議與待辦事項。", "涉及個資、薪資或重大營運決議時，需依權限控管。"],
    icon: UploadCloud,
    permissions: ["request:create", "form:business:create"],
    requiresAttachment: true,
    fields: [
      { name: "會議名稱", required: true },
      { name: "會議日期", type: "date", required: true },
      { name: "開始時間", type: "time", required: true },
      { name: "結束時間", type: "time", required: true },
      { name: "會議類型", type: "select", required: true, options: ["主管會議", "部門會議", "個案會議", "行政會議", "專案會議", "其他"] },
      { name: "主席", required: true },
      { name: "紀錄人", required: true },
      { name: "出席人員", required: true, placeholder: "請填寫出席人員或部門" },
      { name: "決議事項", required: true, placeholder: "請摘要本次會議決議與追蹤事項" },
    ],
  },
  {
    id: "incident-report",
    type: "異常通報",
    title: "異常事件通報",
    category: "業務類",
    subtitle: "營運異常、客訴、服務風險、資安事件",
    description: "通報公司營運、服務、職安或資安異常事件，讓主管與人資可即時追蹤處理。",
    estimatedMinutes: 4,
    owner: "發現人 / 主管",
    attachmentHint: "建議上傳照片、截圖、對話紀錄、服務紀錄或其他佐證。",
    policyNotes: ["異常事件需記錄發生時間、地點、影響對象、即時處置與後續改善。", "涉及個資、性騷擾、職災或重大違規時，需依權限與法規流程處理。"],
    icon: TriangleAlert,
    permissions: ["request:create", "form:business:create"],
    requiresAttachment: true,
    fields: [
      { name: "事件類型", type: "select", required: true, options: ["營運異常", "客訴", "服務風險", "職安事件", "資安事件", "人員衝突", "其他"] },
      { name: "事件日期", type: "date", required: true },
      { name: "事件時間", type: "time", required: true },
      { name: "發生地點", required: true },
      { name: "影響對象", required: true, placeholder: "例如：員工、個案、家屬、公司資料、設備" },
      { name: "嚴重程度", type: "select", required: true, options: ["低", "中", "高", "重大"] },
      { name: "是否已即時處理", type: "select", required: true, options: ["是", "否"] },
      { name: "即時處置", required: true, placeholder: "請說明已採取的處置或需要協助的事項" },
    ],
  },
  {
    id: "equipment-request",
    type: "總務",
    title: "設備請領申請單",
    category: "總務類",
    subtitle: "辦公設備、耗材、工作用品請領",
    description: "申請工作所需設備或耗材，由總務確認庫存、領用紀錄與後續歸還責任。",
    estimatedMinutes: 3,
    owner: "員工本人 / 主管",
    attachmentHint: "可附需求照片、設備規格或主管指派紀錄。",
    policyNotes: ["設備請領需留下品項、數量、用途與保管人。", "核准後應回寫財產或耗材領用紀錄。"],
    icon: Package,
    permissions: ["request:create", "form:general_affairs:create"],
    fields: [
      { name: "請領品項", required: true, placeholder: "例如：筆電、手機、制服、文具耗材" },
      { name: "數量", type: "number", required: true },
      { name: "需求日期", type: "date", required: true },
      { name: "使用人", required: true },
      { name: "使用地點", required: true },
      { name: "請領原因", required: true },
      { name: "是否需歸還", type: "select", required: true, options: ["是", "否"] },
    ],
  },
  {
    id: "document-access-general",
    type: "總務",
    title: "各式文件調閱申請單（總務）",
    category: "總務類",
    subtitle: "合約、憑證、歸檔文件調閱",
    description: "申請調閱總務或行政歸檔文件，保留用途、期間、借閱人與歸還紀錄。",
    estimatedMinutes: 3,
    owner: "員工本人 / 主管",
    attachmentHint: "可附調閱依據、案件編號或主管要求。",
    policyNotes: ["文件調閱需記錄用途、保管單位、借閱期限與是否可影印。", "涉及個資或合約機密時需由行政主任覆核。"],
    icon: FileSearch,
    permissions: ["request:create", "form:general_affairs:create"],
    fields: [
      { name: "文件名稱", required: true },
      { name: "文件類型", type: "select", required: true, options: ["合約", "發票/憑證", "公文", "財產文件", "會議資料", "其他"] },
      { name: "調閱用途", required: true },
      { name: "借閱日期", type: "date", required: true },
      { name: "預計歸還日", type: "date", required: true },
      { name: "是否需要影印", type: "select", required: true, options: ["否", "是"] },
    ],
  },
  {
    id: "official-mail-receipt",
    type: "總務",
    title: "公文收件申請單",
    category: "總務類",
    subtitle: "公文、掛號、重要郵件收件登錄",
    description: "登錄公司收到的公文或重要郵件，指定承辦人並追蹤處理期限。",
    estimatedMinutes: 3,
    owner: "總務 / 行政人員",
    attachmentHint: "可附公文掃描檔、信封照片或收件證明。",
    policyNotes: ["公文收件需記錄收件日、來文單位、承辦人與處理期限。", "逾期未處理應產生提醒。"],
    icon: MailOpen,
    permissions: ["request:create", "form:general_affairs:create"],
    fields: [
      { name: "收件日期", type: "date", required: true },
      { name: "來文單位", required: true },
      { name: "公文主旨", required: true },
      { name: "公文號碼" },
      { name: "承辦部門", required: true },
      { name: "承辦人", required: true },
      { name: "處理期限", type: "date", required: true },
    ],
  },
  {
    id: "company-seal-request",
    type: "總務",
    title: "公司對外用印申請",
    category: "總務類",
    subtitle: "合約、申請文件、正式對外文件用印",
    description: "申請公司印章或對外文件用印，控管用印目的、文件份數、對象與留存檔案。",
    estimatedMinutes: 4,
    owner: "員工本人 / 主管",
    attachmentHint: "需附待用印文件、合約或對外送件資料。",
    policyNotes: ["公司用印需清楚記錄文件名稱、對象、份數與印章類型。", "涉及契約、費用或法律責任時需行政主任或執行長覆核。"],
    icon: Stamp,
    permissions: ["request:create", "form:general_affairs:create"],
    requiresAttachment: true,
    fields: [
      { name: "文件名稱", required: true },
      { name: "用印目的", required: true },
      { name: "對外單位", required: true },
      { name: "用印日期", type: "date", required: true },
      { name: "印章類型", type: "select", required: true, options: ["公司大章", "負責人章", "合約章", "發票章", "其他"] },
      { name: "文件份數", type: "number", required: true },
      { name: "是否需留存正本", type: "select", required: true, options: ["是", "否"] },
    ],
  },
  {
    id: "venue-rental",
    type: "總務",
    title: "公司場地租借",
    category: "總務類",
    subtitle: "會議室、教室、活動場地借用",
    description: "申請借用公司場地，確認日期、時段、用途、人數與設備需求。",
    estimatedMinutes: 3,
    owner: "員工本人 / 主管",
    attachmentHint: "可附活動流程、課程大綱或外部來賓名單。",
    policyNotes: ["場地租借需避免時段衝突，並留下使用人與復原責任。", "外部單位或收費活動需行政主任確認。"],
    icon: Building2,
    permissions: ["request:create", "form:general_affairs:create"],
    fields: [
      { name: "場地名稱", required: true },
      { name: "使用日期", type: "date", required: true },
      { name: "開始時間", type: "time", required: true },
      { name: "結束時間", type: "time", required: true },
      { name: "使用目的", required: true },
      { name: "預估人數", type: "number", required: true },
      { name: "設備需求", placeholder: "例如：投影機、麥克風、白板" },
    ],
  },
  {
    id: "equipment-repair",
    type: "總務",
    title: "設備維修申請書",
    category: "總務類",
    subtitle: "設備故障、維修、檢測申請",
    description: "通報設備故障或維修需求，讓總務安排檢測、維修廠商與完成紀錄。",
    estimatedMinutes: 3,
    owner: "設備使用人 / 主管",
    attachmentHint: "建議上傳故障照片、錯誤訊息或設備編號照片。",
    policyNotes: ["維修申請需記錄設備編號、故障情況、影響程度與處理結果。", "維修完成後應回寫財產狀態。"],
    icon: Wrench,
    permissions: ["request:create", "form:general_affairs:create"],
    requiresAttachment: true,
    fields: [
      { name: "設備名稱", required: true },
      { name: "財產編號" },
      { name: "故障日期", type: "date", required: true },
      { name: "故障地點", required: true },
      { name: "故障狀況", required: true },
      { name: "影響程度", type: "select", required: true, options: ["低", "中", "高", "無法作業"] },
      { name: "是否需備用設備", type: "select", required: true, options: ["否", "是"] },
    ],
  },
  {
    id: "asset-disposal",
    type: "總務",
    title: "財產報廢申請",
    category: "總務類",
    subtitle: "固定資產、設備、用品報廢",
    description: "申請公司財產報廢，記錄資產資料、報廢原因、處理方式與核准紀錄。",
    estimatedMinutes: 4,
    owner: "保管人 / 主管 / 總務",
    attachmentHint: "需附財產照片、維修判定或報廢佐證。",
    policyNotes: ["財產報廢需留下資產編號、保管人、殘值與處理方式。", "核准後應回寫財產台帳，避免帳實不符。"],
    icon: ArchiveX,
    permissions: ["request:create", "form:general_affairs:create"],
    requiresAttachment: true,
    fields: [
      { name: "財產名稱", required: true },
      { name: "財產編號", required: true },
      { name: "保管人", required: true },
      { name: "存放地點", required: true },
      { name: "取得日期", type: "date" },
      { name: "報廢原因", required: true },
      { name: "處理方式", type: "select", required: true, options: ["報廢回收", "捐贈", "出售", "交由廠商處理", "其他"] },
    ],
  },
];

export function getRequestFormDefinition(formId: string) {
  return requestFormDefinitions.find((definition) => definition.id === formId) ?? null;
}

export function getInitialRequestValues(fields: RequestField[]) {
  return Object.fromEntries(fields.map((field) => [field.name, ""]));
}
