#!/usr/bin/env node
'use strict';
// Actual sealed declaration, readers, UI status and deferred caller. Only local
// transport/identity surroundings are fictional; no live DB or user claims.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(path.resolve(__dirname,'../index.html'),'utf8');
function extract(name){let start=source.indexOf('function '+name+'(');assert(start>=0,name);if(source.slice(start-6,start)==='async ')start-=6;for(let end=source.indexOf('{',start);end<source.length;end++){if(source[end]!=='}')continue;const code=source.slice(start,end+1);try{new vm.Script(code);return code;}catch{}}throw Error('Cannot extract '+name);}
const names=['finance_approval_workflow_admin_health','finance_approval_workflow_catalog','finance_approval_workflow_engine_health','finance_approval_workflow_definition'];
const clone=x=>JSON.parse(JSON.stringify(x)),flush=async()=>{for(let n=0;n<4;n++)await new Promise(r=>setImmediate(r));};
let checks=0;async function test(name,run){await run();checks++;console.log('PASS '+name);}
function fixture(enabled=false){
 let next=0,now=0;const timers=new Map();
 const c={S:{user:{id:'FICT-ADMIN',authUserId:'AUTH-FICT',role:'ceo'},demoLogin:false},tenant:'TENANT-FICT',environment:'test',financeWorkspaceIdentityBlocked:false,financeAuthIdentityEpoch:1,financeUsersDirectoryRevision:1,ROLE_PERMISSIONS:{ceo:{settings:true}},CURRENT_PERMISSION_SNAPSHOT:{revision:1},WORKFLOW_ENGINE_CATALOG:[],WORKFLOW_ENGINE_HEALTH:[],WORKFLOW_ADMIN_HEALTH:null,WORKFLOW_ADMIN_DEFINITIONS:{},WORKFLOW_ADMIN_RPC_AVAILABLE:null,WORKFLOW_OPTIONAL_READ_SEQUENCE:{},WORKFLOW_OPTIONAL_READ_ERRORS:{},APPROVAL_RUNTIME_AVAILABLE:true,APPROVAL_RUNTIME_DISABLED_REASON:'',calls:[],warnings:[],peripheral:[],Object,Array,Promise,JSON,Error,Date,
  setTimeout(fn,ms){const id=++next;timers.set(id,{fn,at:now+(ms||0)});return id;},clearTimeout(id){timers.delete(id);},console:{warn:(...a)=>c.warnings.push(a)}};
 const client={rpc(name,args){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});c.calls.push({name,args:clone(args),resolve,reject});return promise;}};
 Object.assign(c,{getSb:()=>client,currentFinanceAuthUserId:()=>c.S.user?.authUserId||'',currentTenantId:()=>c.tenant,activeDataEnvironment:()=>c.environment,normalizedRoleKey:u=>u.role,normalizeSettingValue:x=>x,num:x=>Number(x||0),isRpcMissing:e=>e?.code==='PGRST202',escAttr:x=>String(x),hasSupabase:()=>true,canManageOrgChart:()=>c.S.user?.role==='ceo',membershipPermissionOrRoleFallback:()=>false,refreshMembershipOrgGraph:async()=>c.peripheral.push('org'),refreshCurrentPermissionSnapshotRuntime:async()=>c.peripheral.push('permission'),refreshApprovalOrgAdminRuntime:async()=>c.peripheral.push('admin')});
 vm.createContext(c);
 const declaration=source.slice(source.indexOf('var FINANCE_OPTIONAL_READ_CAPABILITIES='),source.indexOf('function financeOptionalReadCapability('));
 vm.runInContext(declaration,c);
 for(const name of ['financeOptionalReadCapability','financeOptionalReadAvailable','financeStartupReadIdentity','withOperationTimeout','workflowOptionalReadAvailable','workflowAdminReadsEnabled','clearDisabledWorkflowRead','readWorkflowOptionalRpc','refreshWorkflowEngineObservability','normalizeWorkflowAdminHealth','refreshWorkflowAdminHealth','refreshWorkflowAdminDefinition','mapWorkflowEngineCatalog','mapWorkflowEngineHealth','scheduleDeferredFinanceRuntimeRefresh','workflowAdminCatalogEntry','workflowAdminDraftInfo','workflowAdminMissingPublished','workflowAdminBrokenCount','workflowAdminStatusBadgeClass','workflowAdminStatusText','canManageWorkflowAdminFrontend','workflowAdminStatusHtml','approvalRuntimeLikelyAvailable','systemHealthProbeRead','probeSystemHealthRpc','healthStatusLabel','healthIsZeroishResult','healthBriefJson','healthErrorMessage'])vm.runInContext(extract(name),c);
 vm.runInContext(source.slice(source.indexOf('var SYSTEM_HEALTH_RPC_CHECKS='),source.indexOf('function healthStatusLabel(')),c);
 c.enable=(name,value=true)=>{c.FINANCE_OPTIONAL_READ_CAPABILITIES=Object.freeze({...c.FINANCE_OPTIONAL_READ_CAPABILITIES,[name]:Object.freeze({available:value,policy:'fixture_installed'})});};
 if(enabled)names.forEach(name=>c.enable(name));
 c.respond=async(index,data)=>{c.calls[index].resolve({data});await flush();};
 c.advance=async ms=>{const end=now+ms;for(;;){const due=[...timers].filter(([,t])=>t.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!due)break;now=due[1].at;timers.delete(due[0]);due[1].fn();await flush();}now=end;await flush();};
 return c;
}
const health={workflows_with_drafts:[{workflow_key:'FICT',draft_count:1}],workflows_missing_published:[],broken_versions:[]};
const readers={health:c=>c.refreshWorkflowAdminHealth(),definition:c=>c.refreshWorkflowAdminDefinition('FICT'),engine:c=>c.refreshWorkflowEngineObservability()};
function state(c){return clone({health:c.WORKFLOW_ADMIN_HEALTH,definitions:c.WORKFLOW_ADMIN_DEFINITIONS,catalog:c.WORKFLOW_ENGINE_CATALOG,engine:c.WORKFLOW_ENGINE_HEALTH,available:c.WORKFLOW_ADMIN_RPC_AVAILABLE,errors:c.WORKFLOW_OPTIONAL_READ_ERRORS,core:c.APPROVAL_RUNTIME_AVAILABLE,warnings:c.warnings});}
async function respondAll(c){for(let n=0;n<c.calls.length;n++)await c.respond(n,c.calls[n].name.endsWith('admin_health')?health:c.calls[n].name.endsWith('definition')?{ok:true,version:{status:'published'}}:[{workflow_key:'FICT',section:'core',status:'ok'}]);}
(async()=>{
 await test('real release declaration disables only exact optional endpoints, unknown is denied',()=>{const c=fixture();for(const name of names){assert.equal(c.financeOptionalReadAvailable(name),false);assert.equal(c.financeOptionalReadCapability(name).policy,'disabled_until_manifested');}assert.equal(c.financeOptionalReadAvailable('finance_approval_tasks_for_current_user'),false);assert.equal(c.financeOptionalReadCapability('toString').policy,'unknown_deny');});
 await test('disabled readers issue zero RPC, discard stale optional results, preserve core approval readiness',async()=>{const c=fixture();c.WORKFLOW_ADMIN_HEALTH=health;c.WORKFLOW_ADMIN_RPC_AVAILABLE=true;c.WORKFLOW_ADMIN_DEFINITIONS.FICT={version:{status:'published'}};c.WORKFLOW_ENGINE_CATALOG=[{workflowKey:'OLD'}];c.WORKFLOW_ENGINE_HEALTH=[{status:'ok'}];await Promise.all(Object.values(readers).map(read=>read(c)));assert.equal(c.calls.length,0);assert.equal(c.WORKFLOW_ADMIN_HEALTH,null);assert.deepEqual(clone(c.WORKFLOW_ADMIN_DEFINITIONS),{});assert.deepEqual(clone(c.WORKFLOW_ENGINE_CATALOG),[]);assert.deepEqual(clone(c.WORKFLOW_ENGINE_HEALTH),[]);assert.equal(c.approvalRuntimeLikelyAvailable(),true);assert.equal(c.APPROVAL_RUNTIME_DISABLED_REASON,'');assert.equal(c.workflowAdminStatusText('published',false,false,0),'RPC 未安裝');const html=c.workflowAdminStatusHtml({id:'FICT'});assert.match(html,/未執行健檢/);assert.match(html,/發布 draft<\/button>/);assert.match(html,/class="btn-p"[^>]* disabled/);assert.doesNotMatch(html,/簽核權限正常|流程引擎健康正常/);});
 await test('actual deferred sync skips missing workflow endpoint but keeps independent diagnostics',async()=>{const c=fixture();c.scheduleDeferredFinanceRuntimeRefresh('AUTH-FICT');await c.advance(1);assert.equal(c.calls.length,0);assert.deepEqual(c.peripheral,['org','permission','admin']);assert.equal(c.WORKFLOW_ADMIN_RPC_AVAILABLE,false);});
 await test('actual health spec marks only the optional workflow check uninstalled, never healthy',async()=>{const c=fixture(),spec=c.SYSTEM_HEALTH_RPC_CHECKS.find(x=>x.name==='finance_approval_workflow_engine_health');assert.equal(c.SYSTEM_HEALTH_RPC_CHECKS.filter(x=>x.optionalReadCapability).length,1);const result=await c.probeSystemHealthRpc(spec);assert.equal(c.calls.length,0);assert.equal(result.status,'skip');assert.equal(c.healthStatusLabel(result.status),'未檢查');assert.match(result.detail,/未啟用.*未執行檢查/);});
 await test('manifest does not bypass unrelated required health or swallow RLS failure',async()=>{const c=fixture(),spec=c.SYSTEM_HEALTH_RPC_CHECKS.find(x=>x.name==='finance_approval_actor_health');const pending=c.probeSystemHealthRpc(spec);assert.equal(c.calls.length,1);assert.deepEqual(c.calls[0].args,{p_data_environment:'test'});c.calls[0].resolve({error:{message:'permission denied by RLS'}});const result=await pending;assert.equal(result.status,'fail');assert.match(result.detail,/RLS/);});
 await test('explicitly enabled system health probe still executes and reports real warning',async()=>{const c=fixture(true),spec=c.SYSTEM_HEALTH_RPC_CHECKS.find(x=>x.name==='finance_approval_workflow_engine_health');const pending=c.probeSystemHealthRpc(spec);assert.equal(c.calls.length,1);await c.respond(0,[{status:'warn',missing_count:2}]);assert.equal((await pending).status,'warn');});
 await test('enabled readers keep exact RPC arguments and successful real mapping',async()=>{const c=fixture(true);c.APPROVAL_RUNTIME_AVAILABLE=null;const pending=Promise.all(Object.values(readers).map(read=>read(c)));await respondAll(c);await pending;assert.equal(c.calls.length,4);assert.deepEqual(c.calls.find(x=>x.name.endsWith('definition')).args,{p_workflow_key:'FICT',p_version_id:null});assert.equal(c.WORKFLOW_ADMIN_HEALTH.workflows_with_drafts[0].draft_count,1);assert.equal(c.WORKFLOW_ADMIN_DEFINITIONS.FICT.version.status,'published');assert.equal(c.WORKFLOW_ENGINE_CATALOG[0].workflowKey,'FICT');assert.equal(c.WORKFLOW_ENGINE_HEALTH[0].status,'ok');assert.equal(c.APPROVAL_RUNTIME_AVAILABLE,true);assert.equal(c.WORKFLOW_ADMIN_RPC_AVAILABLE,true);assert.equal(c.workflowAdminStatusText('published',false,false,0),'正式中');});
 await test('unknown or missing capability helper cannot probe an endpoint',async()=>{const c=fixture();await c.readWorkflowOptionalRpc(null,'unlisted_rpc',{});delete c.financeOptionalReadAvailable;await c.refreshWorkflowAdminHealth();assert.equal(c.calls.length,0);});
 for(const invalid of [null,{},[],{workflows_with_drafts:[],workflows_missing_published:[]}])await test('malformed health is unavailable, never a successful empty health '+JSON.stringify(invalid),async()=>{const c=fixture(true),pending=c.refreshWorkflowAdminHealth();await c.respond(0,invalid);assert.equal(await pending,null);assert.notEqual(c.WORKFLOW_ADMIN_RPC_AVAILABLE,true);assert.equal(c.WORKFLOW_ADMIN_HEALTH,null);assert.equal(c.workflowAdminStatusText('published',false,false,0),'讀取失敗');});
 for(const error of [{code:'42501',message:'permission denied'},{code:'57014',message:'statement timeout'},{code:'PGRST202',message:'RPC absent'}])await test('enabled endpoint retains visible failure '+error.code,async()=>{const c=fixture(true);c.WORKFLOW_ADMIN_HEALTH=health;c.WORKFLOW_ADMIN_RPC_AVAILABLE=true;const pending=c.refreshWorkflowAdminHealth();c.calls[0].resolve({error});await pending;assert.equal(c.calls.length,1);assert.equal(c.warnings.length,1);assert.equal(c.workflowAdminStatusText('published',false,false,0),error.code==='PGRST202'?'RPC 未安裝':'讀取失敗');assert.match(c.workflowAdminStatusHtml({id:'FICT'}),/class="btn-p"[^>]* disabled/);const retry=c.refreshWorkflowAdminHealth();await c.respond(1,health);assert.equal(await retry,c.WORKFLOW_ADMIN_HEALTH);assert.deepEqual(clone(c.WORKFLOW_OPTIONAL_READ_ERRORS),{});});
 await test('bounded hang reports error and late success does not publish',async()=>{const c=fixture(true),pending=c.refreshWorkflowAdminHealth();await c.advance(12000);assert.equal(await pending,null);assert.equal(c.workflowAdminStatusText('published',false,false,0),'讀取失敗');await c.respond(0,health);assert.equal(c.WORKFLOW_ADMIN_HEALTH,null);});
 await test('enabled engine failure is not converted into successful empty arrays',async()=>{const c=fixture(true);c.APPROVAL_RUNTIME_AVAILABLE=null;const pending=c.refreshWorkflowEngineObservability();c.calls[0].resolve({error:{code:'42501',message:'denied'}});await c.respond(1,[]);assert.equal(await pending,false);assert.equal(c.APPROVAL_RUNTIME_AVAILABLE,null);assert.equal(c.workflowAdminStatusText('published',false,false,0),'讀取失敗');});
 const changes={actor:c=>c.S.user.id='OTHER',auth:c=>c.S.user.authUserId='OTHER',tenant:c=>c.tenant='OTHER',environment:c=>c.environment='production',role:c=>c.S.user.role='employee',permission:c=>c.CURRENT_PERMISSION_SNAPSHOT={revision:2},epoch:c=>c.financeAuthIdentityEpoch++,lock:c=>c.financeWorkspaceIdentityBlocked=true};
 for(const [label,change]of Object.entries(changes))await test('late workflow results cannot cross '+label,async()=>{const c=fixture(true);const pending=Promise.all(Object.values(readers).map(read=>read(c)));change(c);const before=state(c);await respondAll(c);await pending;assert.deepEqual(state(c),before);});
 await test('newest same-owner health response wins; old finally cannot replace it',async()=>{const c=fixture(true),first=c.refreshWorkflowAdminHealth(),second=c.refreshWorkflowAdminHealth();await c.respond(1,health);await second;await c.respond(0,{...health,broken_versions:[{id:'OLD'}]});await first;assert.deepEqual(clone(c.WORKFLOW_ADMIN_HEALTH.broken_versions),[]);});
 await test('demo and locked workspace never dispatch enabled optional reads',async()=>{for(const demo of [true,false]){const c=fixture(true);c.S.demoLogin=demo;c.financeWorkspaceIdentityBlocked=!demo;await Promise.all(Object.values(readers).map(read=>read(c)));assert.equal(c.calls.length,0);}});
 console.log('Workflow optional reads: '+checks+' checks PASS');
})().catch(error=>{console.error(error);process.exitCode=1;});
