'use strict';
// True dashboard loader/adapter functions; only the read-only transport is fictional.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const args=process.argv.slice(2),before=args.includes('--before'),sourcePath=before?'/tmp/finance-dashboard-aggregate-before-20260913.html':path.join(__dirname,'../index.html'),source=fs.readFileSync(sourcePath,'utf8');
function extract(name){const start=source.indexOf('function '+name+'(');assert(start>=0,name);const end=source.indexOf('\n',start),first=source.slice(start,end);return first.endsWith('}')?first:source.slice(start,source.indexOf('\n}',end)+2);}
const scope={mode:'range',eid:'E1',from:'2026-09',to:'2026-09',start:'2026-09-01',end:'2026-09-30',prevStart:'2026-08-01',prevEnd:'2026-08-31'};
const clone=x=>JSON.parse(JSON.stringify(x));
function payload(s=scope){return {version:3,environment:'production',entityId:s.eid,period:{start:s.start,end:s.end,previousStart:s.prevStart,previousEnd:s.prevEnd,trendStart:s.start},generatedAt:'2026-09-13T02:00:00Z',summary:{balanceDiff:0,missingSourceCount:0},receivables:{complete:true,total:120,count:1,overdueTotal:120,over90Total:0,unknownDue:0,items:[{invoiceId:'fictional-i1',invoiceNo:'DEMO-1',entityId:'E1',balance:120,overdueDays:12,buyer:'虛構買方',due:'2026-09-18'}],buckets:['unknown','not_due','d1','d31','d61','d90'].map(key=>({key,label:key,count:key==='d1'?1:0,total:key==='d1'?120:0}))},previousReceivables:{total:20,count:1},reconciliation:{revenue:{},expense:{}},rowCounts:{ledger_rows:2,expense_rows:0,invoice_rows:1}};}
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};}
async function flush(){for(let i=0;i<10;i++)await Promise.resolve();}
function fixture(){let transport=()=>Promise.resolve({data:payload()}),identity='auth1',tenant='tenant1',environment='production',rpcCalls=0,paints=0,now=0,next=1;const timers=new Map(),nodes={};
 const c={Promise,Date,Number,String,Object,Array,Math,AbortController,console:{warn(){}},S:{user:{id:'u1',authUserId:'auth1',role:'accountant'},demoLogin:false,dashDataVersion:0},financeWorkspaceIdentityBlocked:false,CURRENT_PERMISSION_SNAPSHOT:{version:1},scope:clone(scope),DASH_FINANCIAL_CACHE:{key:'',value:null},DASH_REMOTE_AGGREGATES:{},DASH_REMOTE_PENDING:{},DASH_REMOTE_ERRORS:{},DASH_REMOTE_IDENTITY:'',DASH_REMOTE_EPOCH:0,DASH_REMOTE_SEQUENCE:0,DASH_REMOTE_TIMEOUT_MS:15000,normalizedRoleKey:user=>{assert(user&&typeof user==='object','normalizedRoleKey requires the whole Finance user');return user.role||'';},num:v=>Number(v)||0,hasSupabase:()=>true,isFinance:()=>true,currentTenantId:()=>tenant,activeDataEnvironment:()=>environment,currentFinanceAuthUserId:()=>identity,approvalFastBootstrapIdentity:()=>identity,dashboardScope:()=>c.scope,el:id=>nodes[id]||(nodes[id]={textContent:'',innerHTML:''}),buildDash:()=>{paints++;},getSb:()=>({rpc(name,p){assert.equal(name,'finance_executive_dashboard_v3');rpcCalls++;return transport(p);}}),setTimeout(fn,ms){const id=next++;timers.set(id,{fn,at:now+ms});return id;},clearTimeout(id){timers.delete(id);}};
 vm.createContext(c);const names=before?['dashboardRemoteKey','dashboardTrendStart','ensureRemoteDashboardAggregate','dashboardBundleFromRemote','dashboardRenderReceivables','invalidateDashboardFinancialCache']:['dashboardRemoteIdentity','clearDashboardRemoteReads','invalidateDashboardFinancialModel','invalidateDashboardFinancialCache','dashboardRemoteKey','dashboardTrendStart','validateDashboardAggregate','dashboardBundleFromRemote','ensureRemoteDashboardAggregate'];vm.runInContext(names.map(extract).join('\n'),c);
 return {c,run:code=>vm.runInContext(code,c),transport(fn){transport=fn;},calls:()=>rpcCalls,paints:()=>paints,nodes,timers,async advance(ms){now+=ms;for(const[id,t]of [...timers])if(t.at<=now){timers.delete(id);t.fn();}await flush();},switchUser(){c.S.user={id:'u2',authUserId:'auth2'};identity='auth2';},tenant(v){tenant=v;},environment(v){environment=v;}};
}
let checks=0;async function check(name,fn){await fn();checks++;console.log('PASS '+name);}
(async()=>{
 if(before){
  let f=fixture();f.transport(()=>{throw Error('synchronous transport failure');});assert.throws(()=>f.run('ensureRemoteDashboardAggregate(scope)'),/synchronous/);assert.equal(Object.keys(f.c.DASH_REMOTE_PENDING).length,1);checks++;
  f=fixture();f.transport(()=>Promise.resolve({error:{code:'57014',message:'canceling statement due to statement timeout'}}));f.run('ensureRemoteDashboardAggregate(scope)');await flush();f.c.bundle={scope:f.c.scope,officialSource:'local_bootstrap',receivables:{}};f.run('dashboardRenderReceivables(bundle)');assert.match(f.nodes['dash-ar-summary'].textContent,/正在核對/);f.run('ensureRemoteDashboardAggregate(scope,{force:true})');await flush();assert.equal(f.calls(),1);checks++;
  f=fixture();const wrong=f.run('dashboardBundleFromRemote({},scope,{officialSource:"local_bootstrap"})');assert.equal(wrong.officialSource,'remote_full');assert.equal(wrong.receivables.total,0);checks++;
  f=fixture();const key=f.run('dashboardRemoteKey(scope)');f.switchUser();assert.equal(f.run('dashboardRemoteKey(scope)'),key);checks++;
  console.log('CONFIRMED before: '+checks+' defects (sync pending, error-as-loading/no retry, empty result as zero, cross-identity cache key)');return;
 }
 await check('cold online initialization publishes pending promise before dispatch and coalesces paints',async()=>{const f=fixture(),d=deferred();f.transport(()=>d.promise);const p=f.run('ensureRemoteDashboardAggregate(scope)'),p2=f.run('ensureRemoteDashboardAggregate(scope)');assert.strictEqual(p,p2);assert.equal(f.calls(),0);assert.equal(Object.keys(f.c.DASH_REMOTE_PENDING).length,1);await flush();assert.equal(f.calls(),1);d.resolve({data:payload()});assert.equal((await p).receivables.total,120);assert.equal(f.paints(),1);assert.equal(f.timers.size,0);assert.equal(Object.keys(f.c.DASH_REMOTE_PENDING).length,0);assert.equal(f.run('dashboardBundleFromRemote(DASH_REMOTE_AGGREGATES[dashboardRemoteKey(scope)],scope,{summary:{net:7}}).summary.net'),7);});
 await check('57014 is terminal until explicit retry; redraw cannot start a retry storm',async()=>{const f=fixture();f.transport(()=>Promise.resolve({error:{code:'57014',message:'query timeout'}}));await f.run('ensureRemoteDashboardAggregate(scope)');assert.match(Object.values(f.c.DASH_REMOTE_ERRORS)[0],/query timeout/);await f.run('ensureRemoteDashboardAggregate(scope)');assert.equal(f.calls(),1);f.transport(()=>Promise.resolve({data:payload()}));await f.run('ensureRemoteDashboardAggregate(scope,{force:true})');assert.equal(f.calls(),2);assert.equal(Object.keys(f.c.DASH_REMOTE_ERRORS).length,0);});
 await check('synchronous getSb/RPC throws resolve error and release the pending lock',async()=>{for(const mode of['client','rpc']){const f=fixture();if(mode==='client')f.c.getSb=()=>{throw Error('client creation failed');};else f.transport(()=>{throw Error('rpc failed');});assert.equal(await f.run('ensureRemoteDashboardAggregate(scope)'),null);assert.equal(Object.keys(f.c.DASH_REMOTE_PENDING).length,0);assert.equal(Object.keys(f.c.DASH_REMOTE_ERRORS).length,1);assert.equal(f.timers.size,0);}});
 await check('never-settling request becomes error at 15s and aborts without waiting for transport',async()=>{const f=fixture(),d=deferred();let signal;f.transport(()=>({abortSignal(s){signal=s;return d.promise;}}));const p=f.run('ensureRemoteDashboardAggregate(scope)');await flush();await f.advance(14999);assert.equal(signal.aborted,false);assert.equal(Object.keys(f.c.DASH_REMOTE_ERRORS).length,0);await f.advance(1);assert.equal(await p,null);assert.equal(signal.aborted,true);assert.match(Object.values(f.c.DASH_REMOTE_ERRORS)[0],/逾時/);d.resolve({data:payload()});await flush();assert.equal(Object.keys(f.c.DASH_REMOTE_AGGREGATES).length,0);});
 await check('transport rejection and abortSignal throw are contained',async()=>{for(const mode of['reject','abort']){const f=fixture();f.transport(()=>mode==='reject'?Promise.reject(Error('network offline')):{abortSignal(){throw Error('abort binding failed');}});assert.equal(await f.run('ensureRemoteDashboardAggregate(scope)'),null);assert.equal(Object.keys(f.c.DASH_REMOTE_ERRORS).length,1);assert.equal(Object.keys(f.c.DASH_REMOTE_PENDING).length,0);}});
 await check('forced retry aborts old request and ignores its later success/error',async()=>{for(const fail of[false,true]){const f=fixture(),d=deferred();let signal;f.transport(()=>({abortSignal(s){signal=s;return d.promise;}}));const old=f.run('ensureRemoteDashboardAggregate(scope)');await flush();const fresh=payload();fresh.receivables.total=260;fresh.receivables.items[0].balance=260;fresh.receivables.overdueTotal=260;f.transport(()=>Promise.resolve({data:fresh}));await f.run('ensureRemoteDashboardAggregate(scope,{force:true})');assert.equal(await old,null);assert(signal.aborted);fail?d.reject(Error('old failed')):d.resolve({data:payload()});await flush();assert.equal(f.run('DASH_REMOTE_AGGREGATES[dashboardRemoteKey(scope)].receivables.total'),260);assert.equal(Object.keys(f.c.DASH_REMOTE_ERRORS).length,0);}});
 await check('refresh invalidation aborts pending and rejects the late result at an unchanged period',async()=>{const f=fixture(),d=deferred();let signal;f.transport(()=>({abortSignal(s){signal=s;return d.promise;}}));const p=f.run('ensureRemoteDashboardAggregate(scope)');await flush();f.run('invalidateDashboardFinancialCache()');assert(signal.aborted);assert.equal(await p,null);d.resolve({data:payload()});await flush();assert.equal(Object.keys(f.c.DASH_REMOTE_AGGREGATES).length,0);assert.equal(Object.keys(f.c.DASH_REMOTE_PENDING).length,0);});
 for(const mode of['user','tenant','environment','lock','role','permission'])await check(mode+' change cannot publish a late response or display another identity cache',async()=>{const f=fixture(),d=deferred();f.transport(()=>d.promise);const p=f.run('ensureRemoteDashboardAggregate(scope)');await flush();const key=f.run('dashboardRemoteKey(scope)');if(mode==='user')f.switchUser();if(mode==='tenant')f.tenant('tenant2');if(mode==='environment')f.environment('test');if(mode==='lock')f.c.financeWorkspaceIdentityBlocked=true;if(mode==='role')f.c.S.user.role='employee';if(mode==='permission')f.c.CURRENT_PERMISSION_SNAPSHOT={version:2};assert.notEqual(f.run('dashboardRemoteKey(scope)'),key);d.resolve({data:payload()});await flush();await f.advance(15000);assert.equal(await p,null);assert.equal(f.paints(),0);assert.equal(Object.keys(f.c.DASH_REMOTE_AGGREGATES).length,0);});
 await check('scope A late response does not redraw scope B or replace its confirmed amounts',async()=>{const f=fixture(),d=deferred();f.transport(()=>d.promise);const old=f.run('ensureRemoteDashboardAggregate(scope)');await flush();f.c.scope=Object.assign({},f.c.scope,{eid:'E2'});const fresh=payload(f.c.scope);fresh.receivables.items[0].entityId='E2';f.transport(()=>Promise.resolve({data:fresh}));await f.run('ensureRemoteDashboardAggregate(scope)');const paints=f.paints();d.resolve({data:payload()});await old;assert.equal(f.paints(),paints);assert.equal(f.run('DASH_REMOTE_AGGREGATES[dashboardRemoteKey(scope)].entityId'),'E2');});
 await check('a failed forced refresh retains verified prior data and separately exposes the error',async()=>{const f=fixture();await f.run('ensureRemoteDashboardAggregate(scope)');f.transport(()=>Promise.reject(Error('refresh unavailable')));await f.run('ensureRemoteDashboardAggregate(scope,{force:true})');assert.equal(f.run('DASH_REMOTE_AGGREGATES[dashboardRemoteKey(scope)].receivables.total'),120);assert.match(Object.values(f.c.DASH_REMOTE_ERRORS)[0],/refresh unavailable/);});
 const invalid=[['null',()=>null],['empty',()=>({})],['array',()=>[]],['wrong version',p=>Object.assign(p,{version:2})],['wrong environment',p=>Object.assign(p,{environment:'test'})],['wrong company',p=>Object.assign(p,{entityId:'E2'})],['wrong period',p=>(p.period.end='2026-08-31',p)],['missing generation',p=>(delete p.generatedAt,p)],['null total',p=>(p.receivables.total=null,p)],['false total',p=>(p.receivables.total=false,p)],['missing AR complete',p=>(delete p.receivables.complete,p)],['partial page',p=>(p.receivables.count=2,p)],['duplicate source',p=>(p.receivables.items.push(clone(p.receivables.items[0])),p.receivables.count=2,p)],['wrong total',p=>(p.receivables.total=999,p)],['foreign-company item',p=>(p.receivables.items[0].entityId='E2',p)],['missing buckets',p=>(p.receivables.buckets=[],p)],['null overdue with known due',p=>(p.receivables.items[0].overdueDays=null,p)],['unknown due without bucket',p=>(Object.assign(p.receivables.items[0],{due:null,dueDate:null,overdueDays:null}),p)],['negative open balance',p=>(p.receivables.items[0].balance=-120,p)],['null previous total',p=>(p.previousReceivables.total=null,p)],['null balance difference',p=>(p.summary.balanceDiff=null,p)],['missing reconciliation',p=>(delete p.reconciliation,p)],['missing counts',p=>(delete p.rowCounts,p)]];
 for(const[label,change]of invalid)await check('reject malformed payload: '+label,async()=>{const f=fixture(),bad=change(payload());f.transport(()=>Promise.resolve({data:bad}));assert.equal(await f.run('ensureRemoteDashboardAggregate(scope)'),null);assert.equal(Object.keys(f.c.DASH_REMOTE_AGGREGATES).length,0);f.c.bad=bad;const adapted=f.run('dashboardBundleFromRemote(bad,scope,{officialSource:"local_bootstrap",receivables:{total:null}})');assert.equal(adapted.officialSource,'local_bootstrap');assert.equal(adapted.receivables.total,null);});
 await check('validated empty company is a real zero, including negative credit aging bucket',async()=>{const f=fixture(),p=payload();Object.assign(p.receivables,{total:0,count:0,overdueTotal:0,over90Total:0,items:[]});p.receivables.buckets.forEach(x=>{x.count=0;x.total=0;});p.receivables.buckets[0].total=-20;p.receivables.buckets[0].count=1;f.transport(()=>Promise.resolve({data:p}));assert.equal((await f.run('ensureRemoteDashboardAggregate(scope)')).receivables.total,0);});
 await check('real canonical missing due date preserves null overdueDays and remains usable',async()=>{const f=fixture(),p=payload();Object.assign(p.receivables,{overdueTotal:0,unknownDue:1});Object.assign(p.receivables.items[0],{due:null,dueDate:null,overdueDays:null,agingBucket:'unknown'});p.receivables.buckets.forEach(x=>{x.count=x.key==='unknown'?1:0;x.total=x.key==='unknown'?120:0;});f.transport(()=>Promise.resolve({data:p}));await f.run('ensureRemoteDashboardAggregate(scope)');const b=f.run('dashboardBundleFromRemote(DASH_REMOTE_AGGREGATES[dashboardRemoteKey(scope)],scope,{officialSource:"local_bootstrap"})');assert.equal(b.officialSource,'remote_full');assert.equal(b.receivables.total,120);assert.equal(b.receivables.unknownDue,1);assert.equal(b.receivables.items[0].overdueDays,null);assert.equal(b.receivables.items[0].due,'');});
 await check('canonical PostgreSQL numeric strings retain exact AR totals',async()=>{const f=fixture(),p=payload();p.receivables.total='120.00';p.receivables.items[0].balance='120.00';p.previousReceivables.total='20.00';f.transport(()=>Promise.resolve({data:p}));await f.run('ensureRemoteDashboardAggregate(scope)');const b=f.run('dashboardBundleFromRemote(DASH_REMOTE_AGGREGATES[dashboardRemoteKey(scope)],scope,{officialSource:"local_bootstrap"})');assert.equal(b.receivables.total,120);assert.equal(b.previousReceivables.total,20);assert.equal(b.officialSource,'remote_full');});
 await check('client unavailable becomes explicit retryable failure, never silent idle',async()=>{const f=fixture();f.c.getSb=()=>null;await f.run('ensureRemoteDashboardAggregate(scope)');assert.match(Object.values(f.c.DASH_REMOTE_ERRORS)[0],/連線尚未就緒/);assert.equal(Object.keys(f.c.DASH_REMOTE_PENDING).length,0);});
 await check('render exception does not turn successful transport into false data error',async()=>{const f=fixture();f.c.buildDash=()=>{throw Error('paint failure');};assert.equal((await f.run('ensureRemoteDashboardAggregate(scope)')).receivables.total,120);assert.equal(Object.keys(f.c.DASH_REMOTE_ERRORS).length,0);assert.equal(Object.keys(f.c.DASH_REMOTE_PENDING).length,0);});
 console.log('PASS dashboard aggregate '+checks+' real handler, deadline, retry, scope and payload checks');
})().catch(error=>{console.error(error);process.exitCode=1;});
