#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict'),engine=require('../assets/engines/tax-report-engine.js');
const clone=x=>JSON.parse(JSON.stringify(x));let count=0;
function test(name,fn){fn();count++;console.log('PASS '+name);}
const period={start:'2026-07-01',end:'2026-08-31'};
const profile={schemaVersion:1,tax:{formType:'401',taxId:'12345675',legalName:'Fixture company',taxRegistrationNo:'registration',responsiblePerson:'Reviewer',address:'Fixture address',filingFrequency:'bimonthly',filingMode:'individual',periods:{'2026-07-01/2026-08-31':{priorCarryforwardTax:0,refundLimitConfirmedTax:0}}}};
const sale={id:'sale1',entityId:'A',date:'2026-08-01',number:'AA00000001',formatCode:'35',taxClass:'taxable',netAmount:2000,originalTaxAmount:100,grossAmount:2100,evidenceReference:'invoice:sale1'};
const purchase={id:'purchase1',entityId:'A',date:'2026-08-02',number:'BB00000001',formatCode:'25',taxClass:'taxable',netAmount:1000,originalTaxAmount:50,grossAmount:1050,bookTaxAmount:50,description:'文具',sellerTaxId:'87654321',buyerTaxId:'12345675',assetKind:'expense',deduction:'eligible',usage:'common',evidenceReference:'receipt:purchase1'};
function build(patch={}){return engine.buildWorkpaper({profile:clone(profile),entityId:'A',period:clone(period),sales:[clone(sale)],purchases:[clone(purchase)],completeness:{sales:true,purchases:true},...patch});}
function field(w,id){return w.fields.find(f=>f.code===String(id)).value;}
function has(w,code){return w.checks.some(c=>c.code===code);}
test('Known 401 keeps official electronic sale/input field codes and payable arithmetic',()=>{let w=build();assert.equal(w.status,'ready_for_review');assert.equal(w.filingReady,false);assert.equal(field(w,5),2000);assert.equal(field(w,6),100);assert.equal(field(w,33),50);assert.equal(field(w,111),50);});
test('Unknown company form remains null and never guessed from source data',()=>{let w=build({profile:{tax:{}}});assert.equal(w.form,null);assert.equal(w.status,'needs_configuration');assert(w.fields.every(f=>f.value===null));assert.equal(w.summary.deductibleInputTax,null);});
for(const key of ['legalName','taxId','taxRegistrationNo','responsiblePerson','address','filingFrequency','filingMode'])test('Missing profile '+key+' prevents complete review',()=>{let p=clone(profile);delete p.tax[key];assert.equal(build({profile:p}).status,'needs_configuration');});
for(const key of ['id','date','number','evidenceReference','netAmount','originalTaxAmount','grossAmount','taxClass','formatCode','sellerTaxId','buyerTaxId','assetKind','deduction'])test('Missing purchase '+key+' remains blocked',()=>{let r=clone(purchase);delete r[key];let w=build({purchases:[r]});assert.notEqual(w.status,'ready_for_review');assert.equal(field(w,107),null);});
test('Book zero tax is not inferred as original exempt tax',()=>{let r={...purchase,description:'水費11508',bookTaxAmount:0,originalTaxAmount:null};let w=build({purchases:[r]});assert(has(w,'ORIGINAL_AMOUNTS'));assert.equal(w.documents[1].originalTaxAmount,null);});
test('Utility gross expense preserves original tax without claiming input',()=>{let w=build({purchases:[{...purchase,description:'水費11508',bookTaxAmount:0,deduction:'not_claimed_policy'}]});assert.equal(field(w,107),0);assert.equal(w.summary.originalInputTax,50);assert.equal(w.summary.policyExcludedInputTax,50);assert.equal(w.documents[1].originalTaxAmount,50);assert.equal(w.status,'ready_for_review');});
test('Claiming utility tax inconsistent with gross expense requires accountant reconciliation',()=>assert(has(build({purchases:[{...purchase,description:'電費',bookTaxAmount:0}]}),'UTILITY_BOOK_TAX_RECONCILIATION')));
test('Water/electric engineering not classified as utility bill',()=>assert(!has(build({purchases:[{...purchase,description:'水電工程',bookTaxAmount:0}]}),'UTILITY_BOOK_TAX_RECONCILIATION')));
test('Mismatched original amounts cannot populate numeric official totals',()=>{let w=build({purchases:[{...purchase,grossAmount:1000}]});assert(has(w,'ORIGINAL_AMOUNT_MISMATCH'));assert.equal(field(w,45),null);});
test('Incomplete source fetch cannot certify totals',()=>{let w=build({completeness:{sales:false,purchases:true}});assert(has(w,'SALES_INCOMPLETE'));assert.equal(field(w,101),null);});
test('Cross-company source is rejected from sums',()=>{let w=build({sales:[{...sale,entityId:'B'}]});assert(has(w,'CROSS_ENTITY_DOCUMENT'));assert.equal(field(w,22),null);});
test('All-company tax filing cannot be silently calculated',()=>assert(has(build({entityId:'all'}),'ENTITY_REQUIRED')));
test('Duplicate certificate rejected rather than doubled',()=>{let w=build({purchases:[purchase,clone(purchase)]});assert(has(w,'DUPLICATE_DOCUMENT'));assert.equal(w.documents.filter(d=>d.kind==='purchase'&&d.included).length,1);});
test('401 exempt sales require company form review',()=>assert(has(build({sales:[{...sale,taxClass:'exempt',originalTaxAmount:0,grossAmount:2000}]}),'FORM_401_HAS_EXEMPT')));
test('Sales and purchase returns subtract the original tax once',()=>{let w=build({sales:[sale,{...sale,id:'return',formatCode:'33',isReturn:true,originalDocumentId:sale.id,netAmount:1000,originalTaxAmount:50,grossAmount:1050}],purchases:[purchase,{...purchase,id:'preturn',formatCode:'23',isReturn:true,originalDocumentId:purchase.id,netAmount:200,originalTaxAmount:10,grossAmount:210}]});assert.equal(field(w,18),50);assert.equal(field(w,41),10);assert.equal(field(w,101),50);assert.equal(field(w,107),40);assert.equal(field(w,111),10);});
test('Return without original link cannot complete',()=>assert(has(build({purchases:[{...purchase,isReturn:true,formatCode:'23'}]}),'RETURN_EVIDENCE')));
test('Return flag with a normal sale or purchase format never increments ordinary totals',()=>{for(const kind of ['sales','purchases']){let r={...(kind==='sales'?sale:purchase),isReturn:true,originalDocumentId:'original'};assert(has(build({[kind]:[r]}),'RETURN_FORMAT'));}});
test('Fixed asset input occupies its own official columns',()=>{let w=build({purchases:[{...purchase,assetKind:'fixed_asset'}]});assert.equal(field(w,34),1000);assert.equal(field(w,35),50);assert.equal(field(w,49),1000);assert.equal(field(w,45),0);});
test('Zero rated exports require category and evidence',()=>{let w=build({sales:[{...sale,taxClass:'zero_rated',originalTaxAmount:0,grossAmount:2000}]});assert(has(w,'ZERO_RATE_EVIDENCE'));});
test('Customs/noncustoms export codes are distinct',()=>{let w=build({sales:[{...sale,taxClass:'zero_rated',zeroRateExport:'customs',originalTaxAmount:0,grossAmount:2000}]});assert.equal(field(w,15),2000);assert.equal(field(w,7),0);});
function mixed(method='proportional'){let p=clone(profile);p.tax.formType='403';p.tax.deductionMethod=method;p.tax.directMethodSince='2024-01-01';Object.assign(p.tax.periods['2026-07-01/2026-08-31'],{foreignServicePayableTax:0,specialTaxPayableTax:0,annualAdjustmentPayableTax:0,annualAdjustmentRefundTax:0,yearEndAdjustmentRequired:false,annualAdjustmentReviewed:false,nonDeductibleRatio:.2,ratioExclusionsReviewed:true});return p;}
test('403 proportional excludes article19 before common percentage',()=>{let w=build({profile:mixed(),purchases:[purchase,{...purchase,id:'excluded',deduction:'article19_excluded'}]});assert.equal(field(w,50),20);assert.equal(field(w,51),40);assert.equal(w.summary.originalInputTax,100);assert.equal(w.status,'ready_for_review');});
test('403 direct taxable-only fully deducts and exempt-only never deducts',()=>{let w=build({profile:mixed('direct'),purchases:[{...purchase,usage:'taxable_only'},{...purchase,id:'exempt',usage:'exempt_only'},{...purchase,id:'common',usage:'common'}]});assert.equal(field(w,51),90);assert.deepEqual(w.documents.filter(d=>d.kind==='purchase').map(d=>d.claimedTaxAmount),[50,0,40]);});
test('403 unknown use cannot complete direct calculation',()=>assert(has(build({profile:mixed('direct'),purchases:[{...purchase,usage:null}]}),'DIRECT_USAGE_UNKNOWN')));
test('403 unknown ratio never assumes zero percent',()=>{let p=mixed();p.tax.periods['2026-07-01/2026-08-31'].nonDeductibleRatio=null;assert.equal(field(build({profile:p}),51),null);});
test('403 official integer percentage requirement does not silently round',()=>{let p=mixed();p.tax.periods['2026-07-01/2026-08-31'].nonDeductibleRatio=.33333;assert(has(build({profile:p}),'RATIO_PRECISION'));});
test('403 annual applicability itself must be explicitly reviewed',()=>{let p=mixed();delete p.tax.periods['2026-07-01/2026-08-31'].yearEndAdjustmentRequired;p.tax.periods['2026-07-01/2026-08-31'].annualAdjustmentReviewed=true;assert(has(build({profile:p}),'ANNUAL_ADJUSTMENT'));});
test('Year-end annual totals calculate adjustment and catch disagreement',()=>{let p=mixed();Object.assign(p.tax.periods['2026-07-01/2026-08-31'],{yearEndAdjustmentRequired:true,annualAdjustmentReviewed:true,annualTotals:{inputTax:1000,article19ExcludedTax:100,deductedInputTax:800,nonDeductibleRatio:.2},annualAdjustmentPayableTax:80});let w=build({profile:p});assert.equal(w.summary.annualAdjustmentEstimate,80);assert(!has(w,'ANNUAL_RECONCILIATION'));p.tax.periods['2026-07-01/2026-08-31'].annualAdjustmentPayableTax=50;assert(has(build({profile:p}),'ANNUAL_RECONCILIATION'));});
test('Positive unsupported foreign/special amounts stay review-required',()=>{let p=mixed();p.tax.periods['2026-07-01/2026-08-31'].specialTaxPayableTax=20;assert(has(build({profile:p}),'SUPPLEMENTAL_TAX_REVIEW'));});
test('403 rounding discrepancy is explicit and sums back to total',()=>{let p=mixed();p.tax.periods['2026-07-01/2026-08-31'].nonDeductibleRatio=.5;let w=build({profile:p,purchases:[{...purchase,netAmount:10,originalTaxAmount:1,grossAmount:11},{...purchase,id:'two',netAmount:10,originalTaxAmount:1,grossAmount:11}]});assert.equal(w.summary.deductibleInputTax,1);assert.equal(w.summary.inputRoundingAdjustment,-1);assert(has(w,'INPUT_ROUNDING'));});
test('Carryforward and confirmed refund limited independently',()=>{let p=clone(profile);p.tax.periods['2026-07-01/2026-08-31']={priorCarryforwardTax:100,refundLimitConfirmedTax:30};let w=build({profile:p});assert.equal(field(w,112),50);assert.equal(field(w,114),30);assert.equal(field(w,115),20);});
test('Original arrays remain immutable across workpaper calculations',()=>{let input={profile:clone(profile),sales:[clone(sale)],purchases:[clone(purchase)]},before=clone(input);build(input);assert.deepEqual(input,before);});
test('Explicitly excluded non-VAT payroll needs evidence and a reason but no invented invoice/tax zero',()=>{let w=build({purchases:[{id:'payroll',entityId:'A',date:'2026-08-01',taxClass:'out_of_scope',classificationReason:'Payroll is outside VAT purchases',evidenceReference:'payroll-approved',grossAmount:50000,originalTaxAmount:null}]});assert.equal(w.status,'ready_for_review');assert.equal(w.documents[1].originalTaxAmount,null);assert.equal(w.documents[1].explicitlyExcluded,true);assert.equal(field(w,107),0);});
test('Exclusion without a recorded reason or source evidence does not complete review',()=>{let w=build({purchases:[{id:'payroll',entityId:'A',date:'2026-08-01',taxClass:'out_of_scope'}]});assert(has(w,'EXCLUSION_REASON'));assert(has(w,'CERTIFICATE_EVIDENCE'));assert.notEqual(w.status,'ready_for_review');});
test('Claimed completeness cannot disguise an invalid source array',()=>assert(has(build({sales:null}),'SALES_SOURCE_FORMAT')));
test('Direct deduction method cannot be applied before its recorded start',()=>{let p=mixed('direct');p.tax.directMethodSince='2026-09-01';assert(has(build({profile:p}),'DIRECT_METHOD_PERIOD'));});
test('Workbook preserves official field codes/source URL/hash and never claims filing success',()=>{let w=build(),s=engine.workbookSheets(w);assert.equal(s.length,5);assert.equal(s[1].name,'401欄位核對');assert(s[0].rows.some(r=>r.some(v=>String(v).includes('f78296b7'))));assert(s[0].rows.some(r=>r[0]==='正式申報完成'&&r[1]===false));assert(s[3].rows[0].includes('原始稅額'));assert(s[3].rows[0].includes('帳面進項稅'));});
console.log(JSON.stringify({ok:true,tests:count,filingReady:false}));
