#!/usr/bin/env node
'use strict';
// Runs actual new migration/RPC SQL locally; no credentials or network access.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{PGlite}=require('@electric-sql/pglite');
const db=new PGlite();const t='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',other='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';let tests=0,revision=0,profile;
const run=async(sql,args=[])=>db.query(sql,args),read=async()=> (await run("select public.finance_reporting_profile_read_v1('A','test') result")).rows[0].result;
async function check(name,fn){await fn();tests++;console.log('PASS '+name);}
async function as(role='ceo'){await db.exec('reset role');await run("select set_config('fixture.actor',$1,false),set_config('fixture.tenant',$2,false),set_config('fixture.permission','true',false)",[role,t]);await db.exec('set role authenticated');}
async function admin(sql,args=[]){await db.exec('reset role');return run(sql,args);}
async function save(p=profile,rev=revision,reason='Reviewed change'){const r=(await run("select public.finance_reporting_profile_save_v1('A',$1,$2,$3,'test') result",[rev,JSON.stringify(p),reason])).rows[0].result;profile=r.profile;revision=r.revision;return r;}
async function denied(fn,code){let err;try{await fn();}catch(e){err=e;}assert(err,'expected rejection');assert.equal(err.code,code,err.message);}
function clone(x){return JSON.parse(JSON.stringify(x));}
(async()=>{
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema private;
create table public.finance_users(id text,role text,tenant_id uuid,auth_user_id uuid,active boolean,google_link_status text);
create table public.system_settings(tenant_id uuid,key text,value jsonb,primary key(tenant_id,key));
create table public.finance_department_units(tenant_id uuid,id uuid,code text,active boolean,is_posting_unit boolean);
create table public.finance_department_entity_scopes(tenant_id uuid,unit_id uuid,entity_code text,active boolean);
create table public.invoices(id text,tenant_id uuid,entity_id text,data_environment text,amount numeric,tax numeric);
create table public.expense_requests(id text,tenant_id uuid,entity_id text,data_environment text,form_payload jsonb);
create function auth.uid() returns uuid language sql stable as $$select case when current_setting('fixture.actor',true)='anonymous' then null::uuid else '11111111-1111-1111-1111-111111111111'::uuid end$$;
create function public.current_tenant_id() returns uuid language sql stable as $$select current_setting('fixture.tenant')::uuid$$;
create function public.current_finance_user_id() returns text language sql stable as $$select current_setting('fixture.actor')$$;
create function public.current_finance_role() returns text language sql stable as $$select current_setting('fixture.actor')$$;
create function public.is_finance_admin() returns boolean language sql stable as $$select public.current_finance_role() in ('ceo','admin_director')$$;
create function private.finance_expense_optional_permission_allows(uuid,text,text,jsonb) returns boolean language sql stable as $$select current_setting('fixture.permission',true)='true' and coalesce(current_setting('fixture.denied_entity',true),'')<>$4->>'entity_id'$$;
`);
for(const role of ['ceo','admin_director','accountant','board','external_audit','employee','anonymous'])await run('insert into public.finance_users values($1,$1,$2,$3,true,$4)',[role,t,'11111111-1111-1111-1111-111111111111','bound']);
for(const tenant of [t,other]){
 await run('insert into public.system_settings values($1,$2,$3)',[tenant,'entities',JSON.stringify([{id:'A'},{id:'B'}])]);await run('insert into public.system_settings values($1,$2,$3)',[tenant,'accounts',JSON.stringify([{c:'4101'},{c:'6202'},{c:'1130'},{c:'2136'}])]);
}
await run('insert into public.system_settings values($1,$2,$3)',[t,'role_permissions',JSON.stringify({ceo:{reports:'edit',settings:'edit'},accountant:{reports:'edit',settings:'none'},admin_director:['reports','settings'],board:['reports'],external_audit:['reports']})]);
for(const [i,c,e]of [[1,'D1','A'],[2,'D2','A'],[3,'D3','B']]){const id=`00000000-0000-0000-0000-00000000000${i}`;await run('insert into public.finance_department_units values($1,$2,$3,true,true)',[t,id,c]);await run('insert into public.finance_department_entity_scopes values($1,$2,$3,true)',[t,id,e]);}
for(const [id,tenant,e,env]of [['inv-a',t,'A','test'],['inv-b',t,'B','test'],['inv-prod',t,'A','production'],['inv-other',other,'A','test']])await run('insert into public.invoices values($1,$2,$3,$4,100,5)',[id,tenant,e,env]);
await run('insert into public.expense_requests values($1,$2,$3,$4,$5)', ['req-a',t,'A','test',JSON.stringify({accountingLines:[{description:'水費',netAmount:105,taxAmount:0,grossAmount:105}]})]);
const migration=fs.readFileSync(path.join(__dirname,'../supabase/migrations/20260910064325_finance_reporting_profiles_v1.sql'),'utf8');
await db.exec('begin;'+migration+'\ncommit;');await as();
await check('Missing profile returns explicit unknown version-zero template and server capabilities',async()=>{const r=await read();assert.equal(r.revision,0);assert.equal(r.profile.tax.formType,undefined);assert.equal(r.canEdit,true);assert.equal(r.canEditWorkpaper,true);profile=r.profile;});
await check('Authenticated first save appends matching immutable version',async()=>{const r=await save();assert.equal(r.revision,1);const h=(await run("select public.finance_reporting_profile_history_v1('A','test') h")).rows[0].h;assert.equal(h.length,1);assert.deepEqual(h[0].profile,r.profile);});
await check('Stale CAS including competing initial creation rejects atomically',async()=>{await denied(()=>save(profile,0),'40001');assert.equal((await read()).revision,1);});
await check('Full company tax configuration and explicit account/OCI mapping persist',async()=>{const p=clone(profile);p.tax={formType:'403',taxId:'12345675',filingFrequency:'bimonthly',deductionMethod:'direct',directMethodSince:'2024-01-01'};p.accountMappings={'4101':{statementClass:'revenue',ociCategory:null},'1130':{statementClass:'asset',cashFlowClass:'investing'}};p.costCenters=[{departmentCode:'D1',kind:'shared',name:'Shared'}];const r=await save(p);assert.equal(r.profile.tax.formType,'403');assert.equal(r.profile.accountMappings['4101'].ociCategory,null);});
for(const [label,mutate] of [
 ['unknown top key',p=>p.arbitrary='no'],['unknown nested tax key',p=>p.tax.secret='no'],['invalid enum',p=>p.tax.formType='404'],['invalid date',p=>p.tax.directMethodSince='2026-02-30'],['invalid tax period',p=>p.tax.periods={'2026-02-30/2026-03-31':{}}],['ratio outside range',p=>p.tax.periods={'2026-07-01/2026-08-31':{nonDeductibleRatio:2}}],['boolean amount',p=>p.tax.periods={'2026-07-01/2026-08-31':{priorCarryforwardTax:false}}],['unknown account',p=>p.accountMappings['9999']={statementClass:'expense'}],['foreign department',p=>p.costCenters=[{departmentCode:'D3',kind:'cost',name:'Wrong'}]],['duplicate center',p=>p.costCenters.push(clone(p.costCenters[0]))]
])await check('Strict validation rejects '+label+' without revision/audit mutation',async()=>{let p=clone(profile);mutate(p);await denied(()=>save(p),'22023');assert.equal((await read()).revision,revision);});
await check('Document tax classification preserves source expense and original certificate independently',async()=>{let p=clone(profile);p.documents.water={sourceType:'expense_request',sourceId:'req-a',sourceLineId:'water',taxClass:'taxable',formatCode:'25',deduction:'not_claimed_policy',originalNetAmount:100,originalTaxAmount:5,grossAmount:105,classificationReason:'Original invoice transcription'};await save(p);assert.equal(profile.documents.water.originalTaxAmount,5);await admin('select 1');let source=(await run("select form_payload from public.expense_requests where id='req-a'")).rows[0].form_payload;assert.equal(source.accountingLines[0].taxAmount,0);await as();});
for(const id of ['inv-b','inv-prod','inv-other','missing'])await check('Source scope blocks '+id,async()=>{let p=clone(profile);p.documents.bad={sourceType:'invoice',sourceId:id,classificationReason:'Classify'};await denied(()=>save(p),'42501');});
await check('Changed classification needs a reason and original amounts must reconcile',async()=>{let p=clone(profile);p.documents.water.taxClass='exempt';p.documents.water.classificationReason='';await denied(()=>save(p),'22023');p=clone(profile);p.documents.water.grossAmount=106;await denied(()=>save(p),'22023');});
await check('Accountant report edit has only workpaper capability and can update exact documents/tax.periods',async()=>{await as('accountant');let r=await read();assert.equal(r.canEdit,false);assert.equal(r.canEditWorkpaper,true);let p=clone(profile);p.documents.water.classificationReason='Reviewed receipt';p.tax.periods={'2026-07-01/2026-08-31':{priorCarryforwardTax:0,nonDeductibleRatio:.2}};await save(p);});
for(const [label,mutate]of [['company form',p=>p.tax.formType='401'],['account mapping',p=>p.accountMappings={}],['cost center',p=>p.costCenters=[]],['attestation',p=>p.periodChecks={'2026-08':{ociReviewed:true}}],['top injection',p=>p.extra=true]])await check('Accountant cannot modify '+label,async()=>{let p=clone(profile);mutate(p);await denied(()=>save(p),'42501');});
await check('Configured report view permits read but denies accountant edits',async()=>{await admin("update public.system_settings set value=jsonb_set(value,'{accountant,reports}','\"view\"') where key='role_permissions'");await as('accountant');assert.equal((await read()).canEditWorkpaper,false);await denied(()=>save(),'42501');});
await check('Configured report deny blocks read and workpaper write',async()=>{await admin("update public.system_settings set value=jsonb_set(value,'{accountant,reports}','\"none\"') where key='role_permissions'");await as('accountant');await denied(()=>read(),'42501');await denied(()=>save(),'42501');});
await check('Saved numeric page levels match the real browser normalization including fractional clamp values',async()=>{const vm=require('node:vm'),context={window:{FinanceV4Engines:{register(){}}}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../assets/engines/permission-engine.js'),'utf8'),context);for(const value of [-1,-.5,0,.5,1,1.5,2,2.5,3,3.5,4]){await admin("update public.system_settings set value=jsonb_set(value,'{accountant,reports}',$1::jsonb) where key='role_permissions'",[JSON.stringify(value)]);const actual=(await run("select private.finance_reporting_page_level_v1($1,'accountant','reports') level",[t])).rows[0].level;assert.equal(actual,context.window.FinancePermissionEngine.normalizePermissionLevel(value),'numeric value '+value);await as('accountant');if(actual==='none'){await denied(()=>read(),'42501');await denied(()=>save(),'42501');}else assert.equal((await read()).canEditWorkpaper,['edit','delete'].includes(actual));}await admin("update public.system_settings set value=jsonb_set(value,'{accountant,reports}','\"none\"') where key='role_permissions'");await as('accountant');});
await check('Settings explicit deny supersedes executive role for settings writes',async()=>{await admin("update public.system_settings set value=jsonb_set(value,'{ceo,settings}','\"none\"') where key='role_permissions'");await as();assert.equal((await read()).canEdit,false);await denied(()=>save(),'42501');await admin("update public.system_settings set value=jsonb_set(value,'{ceo,settings}','\"edit\"') where key='role_permissions'");await as();});
await check('Legacy array settings/report allowlist preserves existing admin behavior',async()=>{await as('admin_director');assert.equal((await read()).canEdit,true);await as();});
for(const role of ['board','external_audit'])await check(role+' can read scoped workpapers but cannot edit',async()=>{await as(role);assert.equal((await read()).canEditWorkpaper,false);await denied(()=>save(),'42501');});
await check('Anonymous, ordinary employee and unbound identities cannot read',async()=>{for(const role of ['anonymous','employee']){await as(role);await denied(()=>read(),'42501');}await admin("update public.finance_users set google_link_status='unbound' where id='ceo'");await as();await denied(()=>read(),'42501');await admin("update public.finance_users set google_link_status='bound' where id='ceo'");await as();});
await check('Existing optional permission explicit deny is honored',async()=>{await run("select set_config('fixture.permission','false',false)");await denied(()=>read(),'42501');await run("select set_config('fixture.permission','true',false)");});
const allocation={id:'shared-cost',name:'Shared occupancy',sourceDepartmentCode:'D1',accountCodes:['6202'],basis:'fixed_percentage',targets:[{departmentCode:'D1',weight:.4},{departmentCode:'D2',weight:.6}],status:'reviewed',effectiveFrom:'2026-09-01',effectiveTo:null,reviewReason:'Confirmed explicit ratio'};
await check('Reviewed allocation receives authoritative actor/time/revision, forged values ignored',async()=>{let p=clone(profile);p.allocations=[{...allocation,reviewedBy:'forged',reviewedRevision:999,reviewedAt:'fake'}];await save(p);assert.equal(profile.allocations[0].reviewedBy,'ceo');assert.equal(profile.allocations[0].reviewedRevision,revision);assert.notEqual(profile.allocations[0].reviewedAt,'fake');});
await check('Editing a reviewed allocation invalidates approval until a new explicit review',async()=>{let p=clone(profile);p.allocations[0].targets=[{departmentCode:'D1',weight:.5},{departmentCode:'D2',weight:.5}];await save(p);assert.equal(profile.allocations[0].status,'draft');assert.equal(profile.allocations[0].reviewedAt,undefined);p=clone(profile);p.allocations[0].status='reviewed';await save(p);assert.equal(profile.allocations[0].reviewedRevision,revision);});
await check('Unchanged reviewed rule metadata survives unrelated workpaper save',async()=>{const a=clone(profile.allocations[0]);let p=clone(profile);p.tax.periods['2026-07-01/2026-08-31'].priorCarryforwardTax=20;await save(p);assert.deepEqual(profile.allocations[0],a);});
await check('Reviewed allocation unbalanced weights rejected',async()=>{let p=clone(profile);p.allocations[0].targets[0].weight=.1;await denied(()=>save(p),'22023');});
const elim={id:'pair',name:'Intercompany receivable/payable',counterpartyEntityId:'B',period:'2026-09',status:'reviewed',effectiveFrom:'2026-09-01',reviewReason:'Reconciled source pair',lines:[{entityId:'A',departmentCode:'D1',accountCode:'1130',debit:0,credit:100,sourceRef:'A-ledger-ref'},{entityId:'B',departmentCode:'D3',accountCode:'2136',debit:100,credit:0,sourceRef:'B-ledger-ref'}]};
await check('Balanced reviewed intercompany workpaper preserves separate company dimensions',async()=>{let p=clone(profile);p.eliminations=[elim];await save(p);assert.equal(profile.eliminations[0].reviewedRevision,revision);});
await check('Counterparty explicit scope denial prevents adding elimination',async()=>{await run("select set_config('fixture.denied_entity','B',false)");let p=clone(profile);await denied(()=>save(p),'42501');await run("select set_config('fixture.denied_entity','',false)");});
await check('Elimination unbalanced, unknown source or third-company lines are rejected',async()=>{let p=clone(profile);p.eliminations[0].lines[0].credit=90;await denied(()=>save(p),'22023');p=clone(profile);p.eliminations[0].lines[0].sourceRef='';await denied(()=>save(p),'22023');p=clone(profile);p.eliminations[0].lines[0].entityId='C';await denied(()=>save(p),'42501');});
await check('Accountant can prepare documents after managers configured reviewed eliminations',async()=>{await admin("update public.system_settings set value=jsonb_set(value,'{accountant,reports}','\"edit\"') where key='role_permissions'");await as('accountant');let p=clone(profile);p.documents.water.classificationReason='Later accountant review';await save(p);assert.equal(profile.eliminations[0].status,'reviewed');await as();});
await check('Revoked counterparty scope blocks profile and historical exposure',async()=>{await run("select set_config('fixture.denied_entity','B',false)");await denied(()=>read(),'42501');await denied(()=>run("select public.finance_reporting_profile_history_v1('A','test')"),'42501');await run("select set_config('fixture.denied_entity','',false)");});
await check('All-company/foreign-tenant/environment arguments cannot bypass exact scope',async()=>{await denied(()=>run("select public.finance_reporting_profile_read_v1('all','test')"),'22023');await denied(()=>run("select public.finance_reporting_profile_read_v1('missing','test')"),'42501');await denied(()=>run("select public.finance_reporting_profile_read_v1('A','other')"),'22023');let prod=(await run("select public.finance_reporting_profile_read_v1('A','production') x")).rows[0].x;assert.equal(prod.revision,0);});
await check('Direct table reads/writes and private helper execution denied to authenticated',async()=>{for(const sql of ['select * from public.finance_reporting_profiles',"update public.finance_reporting_profiles set revision=999","select private.finance_reporting_default_v1()",'select * from private.finance_reporting_profile_revisions_v1'])await denied(()=>run(sql),'42501');});
await check('Anonymous/service-role RPC calls have no execute grants',async()=>{for(const role of ['anon','service_role']){await db.exec('reset role;set role '+role);await denied(()=>read(),'42501');}await as();});
await check('Audit snapshots are append-only even owner cannot rewrite with DML',async()=>{await admin('select 1');await denied(()=>run('update private.finance_reporting_profile_revisions_v1 set reason=\'changed\''),'42501');await denied(()=>run('delete from private.finance_reporting_profile_revisions_v1'),'42501');await as();});
await check('Outer rollback restores both profile and audit revision atomically',async()=>{let before=await read(),localProfile=clone(profile),oldrev=revision;await db.exec('begin');localProfile.tax.periods['2026-07-01/2026-08-31'].priorCarryforwardTax=99;await save(localProfile);await db.exec('rollback');profile=before.profile;revision=oldrev;assert.deepEqual(await read(),before);let h=(await run("select public.finance_reporting_profile_history_v1('A','test') h")).rows[0].h;assert.equal(h[0].revision,oldrev);});
await check('Repeatable read-only postflight passes after all scoped saves',async()=>{await admin('select 1');const q=fs.readFileSync(path.join(__dirname,'finance_reporting_profiles_postflight.sql'),'utf8').replace(/^\\set ON_ERROR_STOP on\s*/,'');await db.exec(q);});
await check('Unmodified release canary switches real authenticated roles and rolls profiles/audit back',async()=>{
 await admin('select 1');const canaryTenant='00000000-0000-0000-0000-000000000001';
 for(const [id,role,uuid]of [['canary-manager','ceo','33333333-3333-3333-3333-333333333333'],['canary-accountant','accountant','44444444-4444-4444-4444-444444444444']])await run('insert into public.finance_users values($1,$2,$3,$4,true,$5)',[id,role,canaryTenant,uuid,'bound']);
 await run('insert into public.system_settings select $1,key,value from public.system_settings where tenant_id=$2',[canaryTenant,t]);
 await db.exec(`alter table public.finance_users add column email text default 'fixture@example.invalid';
 create or replace function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create or replace function public.current_tenant_id() returns uuid language sql stable as $$select nullif(current_setting('app.current_tenant_id',true),'')::uuid$$;
 create or replace function public.current_finance_user_id() returns text language sql stable security definer as $$select id from public.finance_users where active and tenant_id=public.current_tenant_id() and auth_user_id=auth.uid() limit 1$$;
 create or replace function public.current_finance_role() returns text language sql stable security definer as $$select role from public.finance_users where active and tenant_id=public.current_tenant_id() and auth_user_id=auth.uid() limit 1$$;
 create function public.finance_user_is_approval_identity_ready(t uuid,u text) returns boolean language sql stable as $$select exists(select 1 from public.finance_users where tenant_id=t and id=u and active and google_link_status='bound' and auth_user_id is not null)$$;
 grant usage on schema auth to authenticated;
 `);
 const snapshot=async()=>JSON.stringify((await run("select (select jsonb_agg(to_jsonb(p) order by tenant_id,data_environment,entity_id) from public.finance_reporting_profiles p) p,(select jsonb_agg(to_jsonb(h) order by tenant_id,data_environment,entity_id,revision) from private.finance_reporting_profile_revisions_v1 h) h")).rows);
 const before=await snapshot(),canary=fs.readFileSync(path.join(__dirname,'finance_reporting_profiles_canary.sql'),'utf8');assert(!/^\\/m.test(canary));const results=await db.exec(canary);assert.deepEqual(results.at(-1).rows[0].reporting_profiles_canary_result,{canary:'authenticated_reporting_profiles_v1',ok:true,rolled_back:true,profile_authority_preserved:true});assert.equal(await snapshot(),before);
});
console.log(JSON.stringify({ok:true,tests,migration:'20260910064325',sourceWrites:0}));await db.close();
})().catch(async e=>{console.error(e);process.exitCode=1;await db.close();});
