'use strict';
// Usage: node scripts/check_report_org_performance_browser.cjs --output /tmp/after
// Baseline without modifying checkout: add --baseline-ref <same-repository-commit>.
// agent-browser must be installed; all records and transport are fictional.
// Real index closure + shipped readers/renderers. Only localhost configuration,
// fictional Supabase transport and the clock are replaced; no product test hook.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{execFile}=require('node:child_process'),{promisify}=require('node:util');
const run=promisify(execFile),args=process.argv.slice(2),arg=(key,fallback)=>args.includes(key)?args[args.indexOf(key)+1]:fallback,root=path.resolve(arg('--root',path.join(__dirname,'..'))),out=path.resolve(arg('--output','/tmp/finance-report-org-performance-20260913')),baseline=arg('--baseline-ref',''),session='report-org-performance-'+process.pid,bin=process.env.AGENT_BROWSER_BIN||'agent-browser';
const readSource=relative=>baseline?require('node:child_process').execFileSync('git',['show',baseline+':'+relative],{cwd:root,encoding:'utf8',maxBuffer:12e6}):fs.readFileSync(path.join(root,relative),'utf8');
assert(out!==root&&!out.startsWith(root+path.sep));const source=readSource('index.html'),engineSource=readSource('assets/engines/reporting-workspace.js'),{applyBuildEnvironment}=require(path.join(root,'scripts/finance_build_environment'));
const anchor='bootAuthGate();\n\n})();';assert(source.includes(anchor));let html=applyBuildEnvironment(source,{target:'local',supabaseUrl:'',supabaseAnonKey:''}).replace(anchor,'window.__dashboardQA={run:async function(code){return await eval(code)}};\n'+anchor).replace(/<script\b[^>]*src=["']https?:[^>]*><\/script>/gi,'').replace('<head>','<head><meta http-equiv="Content-Security-Policy" content="connect-src \'self\'; form-action \'none\'; img-src \'self\' data: blob:">');
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(p!==root&&!p.startsWith(root+path.sep)){res.writeHead(403);return res.end();}if(p===root||p===path.join(root,'index.html')){res.setHeader('content-type','text/html; charset=utf-8');return res.end(html);}if(p===path.join(root,'assets/engines/reporting-workspace.js')){res.setHeader('content-type','text/javascript');return res.end(engineSource);}if(!fs.existsSync(p)||!fs.statSync(p).isFile()){res.writeHead(404);return res.end();}res.setHeader('content-type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(p));});
const b=async(...args)=>(await run(bin,['--session',session,...args],{maxBuffer:12e6,timeout:45000})).stdout;
async function scope(code){let v=JSON.parse(await b('eval','--base64',Buffer.from('(async()=>JSON.stringify(await window.__dashboardQA.run('+JSON.stringify(code)+')))()').toString('base64')));return typeof v==='string'?JSON.parse(v):v;}
async function until(code){return scope('(async function(){for(var i=0;i<600;i++){if('+code+')return true;await new Promise(r=>setTimeout(r,20));}return false;})()');}
const evidence={baselineRef:baseline||null,scope:'Local actual dashboard/statement/core/profile/AR loaders and DOM. Fictional read transport, no real employee login or production access. Deadlines accelerated only by the fixture clock.',sourceHash:crypto.createHash('sha256').update(source).digest('hex'),engineHash:crypto.createHash('sha256').update(engineSource).digest('hex'),checks:[],screens:[]};
function check(label,ok){assert(ok,label);evidence.checks.push(label);console.log('PASS '+label);}
const setup=`(function(mode){
USERS=[{id:'qa-accountant',n:'許晴川',email:'accountant@example.invalid',authUserId:'10000000-0000-0000-0000-000000000001',role:'accountant',rL:'會計',eid:'F1',dc:'D1',active:true}];ENTS=[{id:'F1',s:'星河照護',full:'星河照護股份有限公司',active:true}];DEPTS=[{c:'D1',n:'行政課',eid:'F1',entityCodes:['F1'],newFormEntityCodes:['F1'],lv:3,active:true,isPostingUnit:true}];REQS=[];INVS=[];BILLS=[];NOTIFS=[];VOUCHERS=[];LEDGER=[];DRAFTS=[];ORG_CHART=[];quickLogin('accountant');S.user.authUserId=USERS[0].authUserId;S.demoLogin=false;S.dashEntity='F1';S.dashMonth='2026-09';S.dashMonthFrom='2026-09';S.dashMonthTo='2026-09';S.dashPeriodMode='month';
window.__mode=mode;window.__reads=[];window.__blockedWrites=[];window.__late=[];window.__aborts=[];window.__broadDone=false;window.__broadError="";window.__started=performance.now();
var nativeTimer=window.setTimeout;window.setTimeout=function(fn,ms){return nativeTimer(fn,ms)};window.fetch=function(){throw Error('External network is disabled in the offline fixture')};window.alert=function(){};
ENTS=Array.from({length:11},function(_,i){return{id:'F'+(i+1),s:'虛構法人'+(i+1),full:'虛構照護公司'+(i+1),active:true}});DEPTS=Array.from({length:30},function(_,i){return{c:'D'+(i+1),n:'虛構部門'+(i+1),eid:'F'+(Math.floor(i/3)+1),lv:3,active:true,entityCodes:['F'+(Math.floor(i/3)+1)],newFormEntityCodes:['F'+(Math.floor(i/3)+1)],isPostingUnit:true}});S.dashEntity='all';var tenant=currentTenantId(),environment=activeDataEnvironment();var data={finance_users:[{id:'qa-accountant',name:'許晴川',email:'accountant@example.invalid',auth_user_id:S.user.authUserId,tenant_id:tenant,role:'accountant',department_code:'D1',entity_id:'F1',active:true}],system_settings:[],expense_requests:[],invoices:[],bills:[],ledger_entries:[{id:'fixture-ledger-1',tenant_id:tenant,data_environment:environment,entity_id:'F1',department_code:'D1',source_id:'fixture-expense',source_type:'expense',entry_date:'2026-09-13',account_code:'6207',account_name:'文具用品',debit:1050,credit:0},{id:'fixture-ledger-2',tenant_id:tenant,data_environment:environment,entity_id:'F1',department_code:'D1',source_id:'fixture-expense',source_type:'expense',entry_date:'2026-09-13',account_code:'1112',account_name:'銀行存款',debit:0,credit:1050}],notifications:[],vouchers:[]};
data.ledger_entries=Array.from({length:4034},function(_,i){return{id:'fixture-ledger-'+i,tenant_id:tenant,data_environment:environment,entity_id:'F'+(Math.floor(i/2)%10+1),department_code:'D'+((Math.floor(i/2)%10)*3+1),source_id:'fixture-expense-'+Math.floor(i/2),source_type:'expense',entry_date:'2026-09-13',account_code:i%2?'1112':'6207',account_name:i%2?'銀行存款':'文具用品',debit:i%2?0:1050,credit:i%2?1050:0}});function aggregate(args,amount){amount=amount||120;return{version:3,environment:args.p_data_environment,entityId:args.p_entity_id||'all',period:{start:args.p_start,end:args.p_end,previousStart:args.p_previous_start,previousEnd:args.p_previous_end,trendStart:args.p_trend_start},generatedAt:'2026-09-13T02:00:00Z',summary:{balanceDiff:0,missingSourceCount:0},receivables:{complete:true,total:amount+50,count:2,overdueTotal:amount,over90Total:0,unknownDue:1,items:[{invoiceId:'fixture-invoice',invoiceNo:'FIXTURE-INV-001',entityId:args.p_entity_id||'F1',balance:amount,overdueDays:12,buyer:'虛構買方',due:'2026-09-01'},{invoiceId:'fixture-unknown-due',invoiceNo:'FIXTURE-INV-002',entityId:args.p_entity_id||'F1',balance:50,overdueDays:null,buyer:'虛構缺付款日買方',due:null,agingBucket:'unknown'}],buckets:['unknown','not_due','d1','d31','d61','d90'].map(key=>({key:key,label:key,count:key==='d1'||key==='unknown'?1:0,total:key==='d1'?amount:key==='unknown'?50:0}))},previousReceivables:{total:20,count:1},reconciliation:{revenue:{},expense:{}},rowCounts:{ledger_rows:2,expense_rows:0,invoice_rows:1}};}
function transport(name,args,payload){var entry={name:name,args:args,started:performance.now()-window.__started};window.__reads.push(entry);var mode=window.__mode,signal;return{abortSignal:function(s){signal=s;s.addEventListener('abort',function(){window.__aborts.push(name)});return this;},then:function(resolve,reject){var result;if(mode==='optional-hang'&&name==='vouchers'||mode==='profile-hang'&&name==='finance_reporting_profile_read_v1')result=new Promise(function(){});else if(mode==='late'&&(name==='finance_executive_dashboard_v3'||name==='finance_reporting_profile_read_v1'))result=new Promise(function(r){window.__late.push({name:name,args:args,payload:payload,resolve:r})});else result=new Promise(function(r){nativeTimer(function(){r(mode==='ar-error'&&name==='finance_executive_dashboard_v3'?{error:{code:'57014',message:'虛構測試：應收核對逾時'}}:payload)},name==='finance_reporting_profile_read_v1'?600:10)});return result.then(function(value){entry.ended=performance.now()-window.__started;return value;}).then(resolve,reject);}};}
getSb=function(){return{from:function(table){var from=0,to=999;var q={select:function(){return this},eq:function(){return this},in:function(){return this},order:function(){return this},limit:function(n){to=n-1;return this},range:function(a,b){from=a;to=b;return this},abortSignal:function(signal){q.signal=signal;return this},then:function(resolve,reject){var rows=data[table]||[],operation=transport(table,{}, {data:rows.slice(from,to+1),count:rows.length,error:null});if(q.signal)operation.abortSignal(q.signal);return operation.then(resolve,reject)}};['insert','upsert','update','delete'].forEach(function(method){q[method]=function(){window.__blockedWrites.push({table:table,method:method});return Promise.resolve({error:{code:'42501',message:'Offline fixture refuses writes'}})}});return q;},rpc:function(name,args){args=args||{};var payload;if(name==='finance_reporting_profile_read_v1')payload={data:{ok:true,entityId:args.p_entity_id,dataEnvironment:args.p_data_environment,revision:1,profile:{schemaVersion:1,tax:{},accountMappings:{},costCenters:[],budgets:[],allocations:[],eliminations:[],periodChecks:{},documents:{}},canEdit:false,canEditWorkpaper:false}};else if(name==='finance_executive_dashboard_v3')payload={data:aggregate(args)};else payload={error:{code:'42501',message:'Offline fixture only authorizes dashboard read APIs: '+name}};return transport(name,args,payload);},auth:{getSession:async function(){return{data:{session:null},error:null}}}}};hasSupabase=function(){return true};
S.page='perf-fixture';return true;})`;
async function open(mode){await b('open','http://finance-report-qa.localhost:'+server.address().port);await b('set','viewport','1440','1000');await scope(setup+'('+JSON.stringify(mode)+')');}
async function screenshot(label,width){await b('set','viewport',String(width),width===390?'844':'1000');check(label+' '+width+' has no document overflow',!(await scope('document.documentElement.scrollWidth>innerWidth+1')));await b('screenshot',path.join(out,label+'-'+width+'.png'));evidence.screens.push(label+'-'+width+'.png');}
(async()=>{
fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const instrument=`(function(){window.__cpu={};window.__wrapPerf=function(fn,name){return function(){var t=performance.now();try{return fn.apply(this,arguments)}finally{var r=window.__cpu[name]||(window.__cpu[name]={count:0,ms:0});r.count++;r.ms+=performance.now()-t;}}};statementReportModel=window.__wrapPerf(statementReportModel,'statementReportModel');statementScopedLedger=window.__wrapPerf(statementScopedLedger,'statementScopedLedger');statementCashEvents=window.__wrapPerf(statementCashEvents,'statementCashEvents');statementCashFlowOverrides=window.__wrapPerf(statementCashFlowOverrides,'statementCashFlowOverrides');buildTaxReport=window.__wrapPerf(buildTaxReport,'buildTaxReport');buildTrialBalance=window.__wrapPerf(buildTrialBalance,'buildTrialBalance');buildBS=window.__wrapPerf(buildBS,'buildBS');buildPL=window.__wrapPerf(buildPL,'buildPL');buildCF=window.__wrapPerf(buildCF,'buildCF');renderStatementInvestorView=window.__wrapPerf(renderStatementInvestorView,'renderStatementInvestorView');renderReportHealthGate=window.__wrapPerf(renderReportHealthGate,'renderReportHealthGate');buildComboChart=window.__wrapPerf(buildComboChart,'buildComboChart');window.__reportRenders=0;new MutationObserver(function(){window.__reportRenders++}).observe(el('finance-report-workspace'),{childList:true});return true})()`;
await open('ok');await scope(instrument);await scope('(function(){S.page="dashboard";S.dashEntity="all";window.__t=performance.now();window.__core=loadDashboardFinancialSources(true);return true})()');
check('required company profiles and complete ledger settle dashboard',await until('dashboardFinancialReadState(dashboardScope()).ready'));
evidence.dashboard=await scope('({elapsedMs:performance.now()-window.__t,entities:ENTS.length,ledger:LEDGER.length,reads:window.__reads,cpu:window.__cpu,verified:dashboardFinancialReadState(dashboardScope()).ready})');
await screenshot('dashboard-ready',1440);await screenshot('dashboard-ready',390);
await open('ok');await scope(instrument);await scope('(async function(){S.page="perf-fixture";var sourceResult=await loadStatementSourcePages(getSb(),"ledger_entries");if(sourceResult.error)throw sourceResult.error;LEDGER=sourceResult.data.map(mapLedger);refreshEntitySelectors();el("rpt-ent").value="all";window.__cpu={};window.__reads=[];window.__t=performance.now();nav("reports",null);window.__syncReportMs=performance.now()-window.__t;return true})()');
check('all source companies are ready before reports render verified amounts',await until('Array.from(new Set(LEDGER.map(r=>r.eid))).every(id=>FinanceReportingWorkspace.profileRecord(id)?.loaded)&&!!el("rw-report-panel")&&!el("rw-report-panel").innerText.includes("正在讀取公司報表設定")&&!el("rw-report-panel").innerText.includes("正式分類帳")'));
evidence.reports=await scope('({elapsedMs:performance.now()-window.__t,syncMs:window.__syncReportMs,cpu:window.__cpu,profileReads:window.__reads.filter(x=>x.name==="finance_reporting_profile_read_v1"),reportRenders:window.__reportRenders,legacyOpen:document.querySelector(".report-legacy-analysis").open,ledger:LEDGER.length})');
await screenshot('reports-ready',1440);await screenshot('reports-ready',390);await b('set','viewport','1440','1000');
evidence.warmReports=await scope('(function(){window.__cpu={};var t=performance.now();buildReports();return {elapsedMs:performance.now()-t,cpu:window.__cpu}})()');
check('complete report model preserves all source rows and balanced expense totals',await scope('(function(){var m=statementReportModel("all","2026-09",{comparisonPeriod:null});return m.completeness.complete&&m.current.pl.netProfit===-2117850&&m.current.cf.end===-2117850})()'));
if(!baseline){check('closed legacy analysis has no hidden legacy render',!evidence.warmReports.cpu.renderStatementInvestorView&&!evidence.warmReports.cpu.buildComboChart);await scope('(function(){window.__cpu={};document.querySelector(".report-legacy-analysis").open=true;return true})()');check('opening legacy analysis renders its real current source on demand',await until('window.__cpu.renderStatementInvestorView?.count>0'));}
await open('ok');await scope(`(async function(){S.user.role='ceo';var originalClient=getSb();window.__orgReads=[];var names=['finance_org_department_list','finance_org_position_list','finance_org_employee_role_list','finance_org_admin_health','finance_front_office_permission_runtime_health','finance_department_runtime_health'];getSb=function(){return Object.assign({},originalClient,{rpc:function(name,args){if(names.indexOf(name)<0)return originalClient.rpc(name,args);var t=performance.now(),r={name:name,at:t};window.__orgReads.push(r);return new Promise(resolve=>setTimeout(()=>{r.end=performance.now();resolve({data:name.includes('_list')?[]:{ok:true,missing_primary_role_count:0},error:null})},1100))}})};window.__t=performance.now();var result=await refreshApprovalOrgAdminRuntime(getSb(),'manual_perf_probe',{force:true});return {result:result.ok}})()`);
evidence.orgDiagnostic=await scope('({elapsedMs:Math.max(...window.__orgReads.map(r=>r.end))-window.__t,reads:window.__orgReads})');
if(!baseline)check('six independent org health reads start concurrently',Math.max(...evidence.orgDiagnostic.reads.map(r=>r.at))-Math.min(...evidence.orgDiagnostic.reads.map(r=>r.at))<100);
const fixture=require(path.join(root,'scripts/fixtures/department_workspace.cjs'))('readonly');
await scope(`(function(f){S.demoLogin=true;USERS=f.users;S.user=Object.assign({},f.users[0],{role:'ceo'});ENTS=f.entities.map(e=>({id:e.code,s:e.short_name,full:e.legal_name}));DEPTS=f.units.filter(u=>u.is_posting_unit).map(u=>({c:u.code,n:u.name,lv:3,eid:'F1',active:true}));MEMBERSHIP_ORG_RUNTIME=f.runtime;MEMBERSHIP_ORG_DRAFT=f.draft;ORG_CHART=[];window.__renderCosts=[];for(var i=0;i<3;i++){var t=performance.now();buildOrgChart();window.__renderCosts.push({kind:'org',ms:performance.now()-t});t=performance.now();SETTINGS_TAB='departments';buildSettings();window.__renderCosts.push({kind:'settings',ms:performance.now()-t})}return true})(${JSON.stringify(fixture)})`);
evidence.orgRender=await scope('({users:USERS.length,units:MEMBERSHIP_ORG_RUNTIME.graph.units.length,costs:window.__renderCosts})');
if(!baseline){await open('late');await scope('(function(){window.__profileOld=FinanceReportingWorkspace.loadProfile("F1",true);return true})()');check('real profile transport started before identity change',await until('window.__late.some(x=>x.name==="finance_reporting_profile_read_v1")'));await scope('(async function(){S.user.authUserId="10000000-0000-0000-0000-000000000002";window.__mode="ok";await FinanceReportingWorkspace.loadProfile("F1",true);window.__late.forEach(function(x){if(x.name==="finance_reporting_profile_read_v1")x.payload.data.profile.accountingFramework="stale-old-identity";x.resolve(x.payload)});await window.__profileOld;return true})()');check('old authenticated profile response cannot overwrite the current identity snapshot',await scope('FinanceReportingWorkspace.profileRecord("F1").loaded&&FinanceReportingWorkspace.profileFor("F1").accountingFramework!=="stale-old-identity"'));}
if(!baseline){
await open('ok');await scope(`(function(){S.user.role='ceo';S.user.rL='執行長';var original=getSb();window.__healthReads=[];getSb=function(){return Object.assign({},original,{rpc:function(name,args){if(!SYSTEM_HEALTH_RPC_CHECKS.some(x=>x.name===name))return original.rpc(name,args);var entry={name:name,at:performance.now()},signal;window.__healthReads.push(entry);return {abortSignal:function(s){signal=s;return this},then:function(resolve,reject){return new Promise(r=>setTimeout(()=>{entry.ended=performance.now();r({data:{missing_count:0},error:null})},name==='finance_approval_actor_health'?6500:40)).then(resolve,reject)}}}})};nav('health',null);window.__healthStarted=performance.now();window.__healthPromise=runSystemHealth();window.__healthSamePromise=runSystemHealth()===window.__healthPromise;window.__healthPromise.then(result=>{window.__healthDone={result:result,ms:performance.now()-window.__healthStarted}});return true})()`);
check('real health DOM publishes fast results while one >3s actor check remains in flight',await until('SYSTEM_HEALTH_STATE.running&&SYSTEM_HEALTH_STATE.completed>=30&&el("health-body").innerText.includes("Data API 可讀")&&el("health-body").innerText.includes("健檢進行中")'));
evidence.healthProgress=await scope('({firstUsableMs:performance.now()-window.__healthStarted,completed:SYSTEM_HEALTH_STATE.completed,total:SYSTEM_HEALTH_STATE.total,running:SYSTEM_HEALTH_STATE.running,samePromise:window.__healthSamePromise,healthCompleteEvents:OPS_EVENTS.filter(x=>x.title==="系統健檢完成").length})');
check('health does not claim full completion or duplicate RPCs while results are partial',evidence.healthProgress.samePromise&&evidence.healthProgress.healthCompleteEvents===0&&evidence.healthProgress.completed<evidence.healthProgress.total);
await screenshot('health-progress',1440);await screenshot('health-progress',390);
check('mobile overview visibly exposes current health progress rather than only hidden DOM text',await scope('(function(){var notice=el("health-summary").querySelector("[role=status]");return !!notice&&notice.getClientRects().length>0&&getComputedStyle(notice).display!=="none"&&notice.innerText.includes("31 / 32")})()')); 
check('the slow actor RPC eventually settles and all 32 actual health definitions complete',await until('window.__healthDone?.result.ok===true&&SYSTEM_HEALTH_STATE.completed===SYSTEM_HEALTH_STATE.total'));
evidence.healthComplete=await scope('({elapsedMs:window.__healthDone.ms,reads:window.__healthReads,total:SYSTEM_HEALTH_STATE.total,completed:SYSTEM_HEALTH_STATE.completed,actorCalls:window.__healthReads.filter(x=>x.name==="finance_approval_actor_health").length})');
check('health timing retains the real slow read rather than reducing its timeout',evidence.healthComplete.elapsedMs>=6500&&evidence.healthComplete.actorCalls===1);
}
evidence.errors=(await b('errors')).trim();evidence.blockedFictionalWrites=await scope('window.__blockedWrites');check('actual browser has no uncaught page errors',!evidence.errors);evidence.scope='Read-only loopback .localhost timing probe (production runtime scope policy) of actual functions; 4034 fictional ledger rows and 11 entities match current aggregate scale. Profile network delays controlled at600ms, org health1100ms, full-health actor RPC6500ms; not a production latency measurement.';
fs.writeFileSync(path.join(out,'timing.json'),JSON.stringify(evidence,null,2));console.log(JSON.stringify({dashboard:evidence.dashboard.elapsedMs,reports:evidence.reports.elapsedMs,sync:evidence.reports.syncMs,warm:evidence.warmReports,org:evidence.orgDiagnostic.elapsedMs,render:evidence.orgRender,errors:evidence.errors,output:out},null,2));
})().catch(async e=>{console.error(e);fs.mkdirSync(out,{recursive:true});let debug;try{debug=await scope('({reads:window.__reads,text:document.body.innerText,profile:FinanceReportingWorkspace.profileRecord("F1")})')}catch(_){}fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:e.message,evidence,debug},null,2));process.exitCode=1}).finally(async()=>{await b('close').catch(()=>{});server.close()});
