'use strict';
// Executes shipped handlers, draft identity/cache helpers and attachment normalization.
// Only form/DOM surroundings and persistence transports are fictional; no network.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
function fn(name,windowHandler=false){
 const marker=windowHandler?'window.'+name+'=':'function '+name+'(';
 let start=source.indexOf(marker);assert(start>=0,'Actual source exists: '+name);
 if(!windowHandler&&source.slice(start-6,start)==='async ')start-=6;
 const eol=source.indexOf('\n',start),first=source.slice(start,eol);
 if(first.endsWith(windowHandler?'};':'}'))return first;
 const end=source.indexOf(windowHandler?'\n};':'\n}',eol);assert(end>=0,'Actual source closes: '+name);
 return source.slice(start,end+(windowHandler?3:2));
}
const clone=x=>JSON.parse(JSON.stringify(x)),tick=()=>new Promise(r=>setImmediate(r));
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return{promise,resolve,reject};}
let passed=0;function pass(label){passed++;console.log('PASS '+label);}
const file=(name='fixture.pdf')=>({name,type:'application/pdf',size:315,path:'fixture-private/drafts/'+name,storagePath:'fixture-private/drafts/'+name,bucket:'finance-attachments',kind:'draft_file',dataEnv:'production'});
function fixture(options={}){
 const c={Date,Promise,Object,Array,String,Number,Error,Math,AbortController,console:{error(){},warn(){}},setTimeout(){return 1},clearTimeout(){},
  tenant:'tenant-a',environment:'production',financeWorkspaceIdentityBlocked:false,CURRENT_PERMISSION_SNAPSHOT:{verified:true,pages:['newreq','approvals']},
  S:{user:{id:'finance-a',authUserId:'auth-a',email:'a@example.invalid',n:'匿名員工',role:'employee'},demoLogin:false,page:'newreq',aT:'drafts',nrType:'expense_reimbursement',nrRec:'invoice',nrPay:'bank',nrStep:3,lazyMode:true,nrDraftId:'',nrSavingDraft:false,nrFiles:[file()],nrDirtyBaseline:'unsaved'},
  DRAFTS:[],REQS:[],lastSyncAt:'2026-09-13T00:00:00Z',SUPABASE_ATTACHMENT_BUCKET:'finance-attachments',DATA_ENV_PRODUCTION:'production',DATA_ENV_TEST:'test',DEFAULT_TENANT_ID:'tenant-a',FINANCE_ATTACHMENT_RECORD_TYPES:['draft_requests','expense_requests'],
  FINANCE_DRAFT_IDENTITY_EPOCH:0,approvalBootstrapGeneration:0,APPROVAL_HISTORY_RUNTIME:{},approvalHistorySearchTimer:null,
  FINANCE_DRAFT_READ_RUNTIME:{identity:'',status:'idle',complete:false,total:null,loadedCount:0,rows:[],generation:0},APPROVAL_SOURCE_COMPLETENESS:{identity:''},
  counts:{writes:0,deletes:0,notify:0,clean:0,renders:0,counters:0,builds:0,opens:0,closes:0,localWrites:0},alerts:[],saved:[],deleted:[],nodes:{'nr-ok':{style:{display:'none'},textContent:''}},
  form:{fields:{'nr-app':'匿名員工','nr-amt':'136','nr-desc-purpose':'虛構水費','nr-desc':'不可遺失的草稿備註'},lazyRows:[{item:'水費',amount:136,tax:0}],travelFiles:{ticket:[file('ticket.pdf')]},travelRows:[{date:'2026-09-13',amount:100}],nrPettyGeneralRows:[{item:'文具',amount:90}]}
 };
 c.window=c;c.FinanceV4Engines={register(){}};
 Object.assign(c,{currentTenantId:()=>c.tenant,activeDataEnvironment:()=>c.environment,approvalFastBootstrapIdentity:()=>c.tenant+'|'+(c.S.user&&c.S.user.authUserId||''),normalizedRoleKey:u=>u.role,
  num:x=>Number(x)||0,hasSupabase:()=>true,requireRemotePersistence:()=>true,allowLocalPersistence:()=>false,allowSchemaFallback:()=>false,tenantColumnsEnabled:()=>true,
  isExpenseApplicantRevisionMode:()=>!!c.revisionMode,requestTypeLabel:x=>x,collectNRFormState:()=>clone(c.form),syncTravelRows(){},applyPurchaseSummary(){},applyHrSummary(){},
  serializeDraftFiles:async()=>clone(c.S.nrFiles),localPersistenceDisabledMessage:()=> '正式環境不可改存本機',friendlyErrorMessage:e=>e&&e.message||'未確認保存',alert:m=>c.alerts.push(String(m)),confirm:()=>options.confirm!==false,
  renderDrafts:()=>c.counts.renders++,updateDraftCounters:()=>c.counts.counters++,buildApprovals:()=>c.counts.builds++,markNRClean:()=>{c.counts.clean++;c.S.nrDirtyBaseline='clean'},el:id=>c.nodes[id]||null,
  safeJsonSet:()=>{c.counts.localWrites++;return false},financeAttachmentEngine:()=>c.FinanceAttachmentEngine,
  requestIsRejected:r=>r.status==='rejected',requestIsMine:r=>r.applicantId===c.S.user.id,requestReviewAmount:r=>r.amt,isLazyRequestType:()=>true,
  rejectedRequestDraftState:r=>clone(r.formPayload),requestRejectReason:()=>({comment:'請補正附件'}),closeAppr:()=>c.counts.closes++,openDraft:id=>{c.counts.opens++;c.opened=id},
  remoteTableMissing:()=>false,isSchemaCacheMiss:()=>false,approvalFastBootstrapCacheKey:()=> 'fixture-cache',sessionRemoveItem(){},updateApprovalTodoBadge(){},
  loadCurrentUserDrafts:()=>{throw Error('This mutation fixture already has a complete read; unexpected background load')}
 });
 vm.createContext(c);
 vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets/engines/attachment-engine.js'),'utf8'),c);
 ['rowDataEnvironment','rowTenantId','withRequiredTenantColumn','financeDraftReadIdentity','draftReadinessForCurrentUser','clearApprovalFastBootstrapState','resetApprovalSourceCompleteness','setApprovalSourceCompleteness','sanitizeDraftFile','sanitizeTravelDraftFiles','sanitizeDraftForStorage','draftBelongsToCurrentUser','stampDraftOwner','loadDrafts','saveDrafts','notifyDraftMutation','attachmentEngineOptions','normalizeFiles','draftDbRow','saveDraftRemote','deleteDraftRemote'].forEach(n=>vm.runInContext(fn(n),c));
 ['nrSaveDraft','deleteDraft','deleteDraftFromApprovals','copyRejectedRequestToDraft'].forEach(n=>vm.runInContext(fn(n,true),c));
 const notify=c.notifyDraftMutation;c.notifyDraftMutation=(...args)=>{c.counts.notify++;return notify(...args)};
 c.seed=(rows=[])=>{const state=c.draftReadinessForCurrentUser();const owned=rows.map(r=>c.sanitizeDraftForStorage(Object.assign({ownerId:c.S.user.id,ownerEmail:c.S.user.email,tenantId:c.tenant,dataEnv:c.environment,files:[file()],state:clone(c.form)},r)));c.DRAFTS=owned;Object.assign(state,{status:'ready',complete:true,total:owned.length,loadedCount:owned.length,rows:owned,previousComplete:true});return owned;};
 c.seed(options.rows||[]);
 c.switchIdentity=(kind='auth')=>{if(kind==='auth')c.S.user={...c.S.user,id:'finance-b',authUserId:'auth-b',email:'b@example.invalid'};if(kind==='tenant')c.tenant='tenant-b';if(kind==='env')c.environment='test';if(kind==='blocked')c.financeWorkspaceIdentityBlocked=true;if(kind==='role')c.S.user.role='accountant';if(kind==='epoch')c.clearApprovalFastBootstrapState();if(kind==='permission')c.CURRENT_PERMISSION_SNAPSHOT={verified:true,pages:[]};c.seed([{id:'other-session',title:'另一個登入狀態的草稿'}]);c.S.nrDraftId='other-session';c.S.nrDirtyBaseline='new-session-unsaved';};
 if(!options.realWriter){c.saveDraftRemote=async d=>{c.counts.writes++;c.saved.push(clone(d));return options.save?options.save(d,c):true};c.deleteDraftRemote=async id=>{c.counts.deletes++;c.deleted.push(id);return options.remove?options.remove(id,c):true};}
 return c;
}
function expectNoSuccess(c){assert.equal(c.counts.notify,0);assert.equal(c.counts.clean,0);assert.equal(c.nodes['nr-ok'].style.display,'none');assert(!c.alerts.some(a=>/已暫存到正式|草稿已暫存$|已建立修正草稿/.test(a)));}
function writerTransport(c,result){const calls=[];c.getSb=()=>({from(table){const q={table,filters:[],select(columns){calls.push({method:'select',columns});return q},upsert(row){calls.push({method:'upsert',row:clone(row)});return q},delete(){calls.push({method:'delete'});return q},eq(key,value){q.filters.push([key,value]);calls.push({method:'eq',key,value});return q},or(value){calls.push({method:'or',value});return q},then(resolve,reject){return Promise.resolve(typeof result==='function'?result(q,calls):result).then(resolve,reject)}};return q}});return calls;}
function rejected(c){const r={id:'request-rejected',no:'TEST-REJECTED',applicantId:c.S.user.id,status:'rejected',type:'expense_reimbursement',amt:136,app:'匿名員工',files:[file('receipt.pdf')],passbookFiles:[file('proof.pdf')],formPayload:clone(c.form)};c.REQS=[r];return r;}

(async()=>{
 {const gate=deferred(),c=fixture({save:()=>gate.promise}),before=clone(c.form);const run=c.nrSaveDraft();await tick();assert.equal(c.counts.writes,1);assert.equal(c.DRAFTS.length,0);assert.equal(c.S.nrDraftId,c.saved[0].id);assert.equal(c.S.nrSavingDraft,true);expectNoSuccess(c);assert.deepEqual(c.saved[0].state,before);assert.deepEqual(c.saved[0].files,[file()]);assert.equal(await c.nrSaveDraft(),false);assert.equal(c.counts.writes,1);gate.resolve(true);assert.equal(await run,true);assert.equal(c.DRAFTS.length,1);assert.equal(c.counts.notify,1);assert.equal(c.counts.clean,1);assert.equal(c.S.nrSavingDraft,false);assert.equal(c.FINANCE_DRAFT_READ_RUNTIME.total,1);assert.deepEqual(clone(c.DRAFTS[0].files).map(f=>f.path),[file().path]);pass('formal save stays unpublished while pending; exact form/files preserved; one writer and confirmed callback');}
 for(const reject of [false,true]){const c=fixture({rows:[{id:'existing',title:'原草稿'}],save:async()=>{if(reject)throw Error('fixture write rejected');return false}});c.S.nrDraftId='existing';const before=clone(c.DRAFTS),form=clone(c.form);assert.equal(await c.nrSaveDraft(),false);assert.deepEqual(clone(c.DRAFTS),before);assert.deepEqual(c.form,form);assert.equal(c.S.nrDraftId,'existing');assert.equal(c.counts.localWrites,0);expectNoSuccess(c);assert(c.alerts.some(a=>a.includes('暫存失敗')));pass('formal '+(reject?'rejected':'unconfirmed')+' save preserves old draft, dirty form and attachments without success');}
 {let calls=0;const c=fixture({save:async()=>++calls>1});assert.equal(await c.nrSaveDraft(),false);const firstId=c.saved[0].id;assert.equal(c.S.nrDraftId,firstId);assert.equal(c.DRAFTS.length,0);expectNoSuccess(c);assert.equal(await c.nrSaveDraft(),true);assert.equal(c.saved[1].id,firstId);assert.equal(c.DRAFTS.length,1);assert.equal(c.counts.notify,1);pass('unconfirmed save retains exact draft id for retry without publishing a duplicate');}
 {const c=fixture({rows:[{id:'existing',title:'原草稿'}]});c.S.nrDraftId='existing';assert.equal(await c.nrSaveDraft(),true);assert.equal(c.DRAFTS.length,1);assert.equal(c.DRAFTS[0].id,'existing');assert.equal(c.FINANCE_DRAFT_READ_RUNTIME.rows[0].state.fields['nr-desc'],c.form.fields['nr-desc']);pass('confirmed edit replaces only its existing draft and keeps collected content');}
 for(const kind of ['auth','tenant','env','blocked','role','permission','epoch']){const gate=deferred(),c=fixture({save:()=>gate.promise}),run=c.nrSaveDraft();await tick();c.switchIdentity(kind);const current=clone(c.DRAFTS);gate.resolve(true);assert.equal(await run,false);assert.deepEqual(clone(c.DRAFTS),current);assert.equal(c.S.nrDraftId,'other-session');expectNoSuccess(c);assert.equal(c.alerts.length,0);pass('late save under changed '+kind+' cannot publish or show success in replacement scope');}
 {const files=deferred(),c=fixture();c.serializeDraftFiles=()=>files.promise;const run=c.nrSaveDraft();c.switchIdentity();files.resolve([file()]);assert.equal(await run,false);assert.equal(c.counts.writes,0);expectNoSuccess(c);pass('identity changes during attachment serialization stop before writer');}
 {const files=deferred(),c=fixture();c.serializeDraftFiles=()=>files.promise;const run=c.nrSaveDraft();c.switchIdentity();const replacement={identity:c.financeDraftReadIdentity()};c.S.nrDraftSaveOperation=replacement;c.S.nrSavingDraft=true;files.reject(Error('old upload failed'));assert.equal(await run,false);assert.equal(c.alerts.length,0);assert.equal(c.S.nrSavingDraft,true);assert.equal(c.S.nrDraftSaveOperation,replacement);pass('old attachment error neither alerts new identity nor unlocks its save operation');}
 {const first=deferred(),second=deferred(),c=fixture({save:(_,ctx)=>ctx.counts.writes===1?first.promise:second.promise});const a=c.nrSaveDraft();await tick();c.switchIdentity();c.S.nrSavingDraft=false;const b=c.nrSaveDraft();await tick();const currentOperation=c.S.nrDraftSaveOperation;first.resolve(true);assert.equal(await a,false);assert.equal(c.S.nrSavingDraft,true);assert.equal(c.S.nrDraftSaveOperation,currentOperation);second.resolve(true);assert.equal(await b,true);assert.equal(c.counts.notify,1);assert.equal(c.DRAFTS[0].ownerId,'finance-b');pass('older save finally cannot unlock a newer actual save after account switch');}
 {const c=fixture();c.revisionMode=true;assert.equal(await c.nrSaveDraft(),false);assert.equal(c.counts.writes,0);c.revisionMode=false;c.S.nrType='';assert.equal(await c.nrSaveDraft(),false);assert.equal(c.counts.writes,0);pass('applicant revision and missing type still prevent creating new draft');}
 {const gate=deferred(),c=fixture({rows:[{id:'own'}],remove:()=>gate.promise}),before=clone(c.DRAFTS);const run=c.deleteDraft('own');await tick();assert.deepEqual(clone(c.DRAFTS),before);assert.equal(c.counts.notify,0);gate.resolve(true);assert.equal(await run,true);assert.equal(c.DRAFTS.length,0);assert.equal(c.counts.notify,1);assert.equal(c.FINANCE_DRAFT_READ_RUNTIME.total,0);pass('delete retains displayed draft/files until confirmed; then updates complete cache');}
 for(const reject of [false,true]){const c=fixture({rows:[{id:'own'}],remove:async()=>{if(reject)throw Error('fixture delete denied');return false}}),before=clone(c.DRAFTS);assert.equal(await c.deleteDraft('own'),false);assert.deepEqual(clone(c.DRAFTS),before);assert.equal(c.counts.notify,0);assert(c.alerts.some(a=>a.includes('草稿仍保留')));pass('delete '+(reject?'failure':'without confirmation')+' preserves draft and attachments');}
 for(const kind of ['auth','tenant','env','blocked','epoch']){const gate=deferred(),c=fixture({rows:[{id:'own'}],remove:()=>gate.promise}),run=c.deleteDraft('own');await tick();c.switchIdentity(kind);const before=clone(c.DRAFTS);gate.resolve(true);assert.equal(await run,false);assert.deepEqual(clone(c.DRAFTS),before);assert.equal(c.counts.notify,0);assert.equal(c.alerts.length,0);pass('late deletion cannot remove or notify changed '+kind+' scope');}
 {const c=fixture({rows:[{id:'foreign',ownerId:'finance-other',ownerEmail:'a@example.invalid'}]});assert.equal(await c.deleteDraft('foreign'),false);assert.equal(c.counts.deletes,0);assert.equal(c.draftBelongsToCurrentUser({ownerId:'finance-a',tenantId:'tenant-other',dataEnv:'production'}),false);pass('same email cannot override nonempty foreign owner; cross-tenant local draft rejected');}
 {const c=fixture({rows:[{id:'legacy',ownerId:'',ownerEmail:'  A@EXAMPLE.INVALID  '}]});const before=clone(c.DRAFTS);assert.equal(c.draftBelongsToCurrentUser(c.DRAFTS[0]),true);c.loadDrafts();assert.deepEqual(clone(c.DRAFTS),before);assert.equal(c.FINANCE_DRAFT_READ_RUNTIME.total,1);assert.equal(c.FINANCE_DRAFT_READ_RUNTIME.complete,true);pass('verified legacy null-owner email remains visible after true loadDrafts with case and surrounding spaces');}
 {const c=fixture({rows:[{id:'own'}]});assert.equal(await c.deleteDraftFromApprovals('own'),true);assert.equal(c.counts.deletes,1);assert.equal(c.DRAFTS.length,0);pass('approval delete button delegates to confirmed common handler');}
 {const gate=deferred(),c=fixture({save:()=>gate.promise}),r=rejected(c),before=clone(r);const run=c.copyRejectedRequestToDraft(r.id);await tick();assert.equal(c.DRAFTS.length,0);assert.equal(c.counts.opens,0);assert.equal(c.counts.notify,0);assert.equal(c.saved[0].sourceRejectedRequestId,r.id);assert.deepEqual(c.saved[0].files.map(f=>f.path),[file('receipt.pdf').path,file('proof.pdf').path]);gate.resolve(true);await run;assert.equal(c.DRAFTS.length,1);assert.equal(c.counts.notify,1);assert.equal(c.counts.opens,1);assert.equal(c.opened,c.DRAFTS[0].id);assert.deepEqual(r,before);assert.deepEqual(clone(c.DRAFTS[0].state),clone(c.sanitizeDraftForStorage({state:before.formPayload}).state));pass('rejected copy waits for persistence, keeps both source attachments and form, then opens confirmed draft');}
 {const c=fixture({save:async()=>{throw Error('fixture unavailable')}}),r=rejected(c),before=clone(r);await c.copyRejectedRequestToDraft(r.id);assert.equal(c.DRAFTS.length,0);assert.equal(c.counts.opens,0);assert.equal(c.counts.notify,0);assert.equal(c.counts.closes,0);assert.deepEqual(r,before);assert(c.alerts.some(a=>a.includes('草稿失敗')));pass('failed rejected copy leaves original request open and unchanged');}
 for(const kind of ['auth','env','blocked','epoch']){const gate=deferred(),c=fixture({save:()=>gate.promise}),r=rejected(c),run=c.copyRejectedRequestToDraft(r.id);await tick();c.switchIdentity(kind);const current=clone(c.DRAFTS);gate.resolve(true);await run;assert.deepEqual(clone(c.DRAFTS),current);assert.equal(c.counts.opens,0);assert.equal(c.counts.notify,0);assert.equal(c.counts.closes,0);assert.equal(c.alerts.length,0);pass('late rejected-copy save cannot open old request under changed '+kind+' identity');}
 {const c=fixture({rows:[{id:'old'}]}),oldIdentity=c.financeDraftReadIdentity(),oldDraft=clone(c.DRAFTS[0]),actor=clone(c.S.user);let cancelled=0;c.FINANCE_DRAFT_READ_RUNTIME.cancel=()=>cancelled++;c.clearApprovalFastBootstrapState();assert.equal(c.FINANCE_DRAFT_IDENTITY_EPOCH,1);assert.equal(cancelled,1);assert.notEqual(c.financeDraftReadIdentity(),oldIdentity);assert.deepEqual(c.S.user,actor);assert.equal(c.DRAFTS.length,0);c.seed([{id:'new-login'}]);const current=clone(c.DRAFTS);assert.equal(c.notifyDraftMutation(oldDraft,oldDraft.id,oldIdentity),false);assert.equal(c.notifyDraftMutation(null,'new-login',oldIdentity),false);assert.deepEqual(clone(c.DRAFTS),current);pass('true session clear advances epoch, cancels old read, and rejects old save/delete notification under same account');}
 {const c=fixture({realWriter:true}),draft=c.stampDraftOwner({id:'own',dataEnv:'production',files:[file()],state:clone(c.form)});const calls=writerTransport(c,{data:[{id:'own'}],error:null});assert.equal(await c.saveDraftRemote(draft),true);const row=calls.find(x=>x.method==='upsert').row;assert.equal(row.tenant_id,'tenant-a');assert.equal(row.owner_id,'finance-a');assert.equal(row.data_environment,'production');assert.deepEqual(row.files.map(f=>f.path),[file().path]);assert(calls.some(x=>x.method==='select'&&x.columns==='id'));pass('actual upsert explicitly stamps tenant/owner/environment and confirms returned id');}
 for(const result of [{data:[],error:null},{data:null,error:null},{data:[{id:'other'}],error:null},{data:null,error:{message:'RLS rejected'}}]){const c=fixture({realWriter:true});writerTransport(c,result);await assert.rejects(c.saveDraftRemote({id:'own',files:[file()]}));pass('actual save rejects missing/mismatched receipt id or RLS error');}
 {const c=fixture({realWriter:true,rows:[{id:'own'}]}),calls=writerTransport(c,{data:[{id:'own'}],error:null});assert.equal(await c.deleteDraftRemote('own'),true);for(const [key,value] of [['id','own'],['tenant_id','tenant-a'],['data_environment','production']])assert(calls.some(x=>x.method==='eq'&&x.key===key&&x.value===value));assert(calls.some(x=>x.method==='select'&&x.columns==='id'));pass('actual delete scopes id/tenant/environment and requires returned id');}
 for(const result of [{data:[],error:null},{data:null,error:null},{data:[{id:'other'}],error:null},{data:null,error:{message:'RLS rejected'}}]){const c=fixture({realWriter:true,rows:[{id:'own'}]});writerTransport(c,result);await assert.rejects(c.deleteDraftRemote('own'));pass('actual delete rejects zero affected/mismatched id or RLS error');}
 console.log('OK: '+passed+' actual draft mutation readiness checks');
})().catch(error=>{console.error(error);process.exitCode=1});
