#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict'),{PGlite}=require('@electric-sql/pglite');
const {createAuditReadinessFixture,migration}=require('./fixtures/finance_audit_readiness_fixture.cjs');
let checks=0;const clone=x=>JSON.parse(JSON.stringify(x));
async function check(name,fn){await fn();checks++;console.log('PASS '+name);}
async function denied(fn,code){let e;try{await fn();}catch(x){e=x;}assert(e,'expected rejection');assert.equal(e.code,code,e.message);}
(async()=>{const db=new PGlite(),f=await createAuditReadinessFixture(db);let current;
const run=(sql,args=[])=>db.query(sql,args),read=async(e='A',p='2026',env='test')=>(await run('select public.finance_audit_case_read_v1($1,$2,$3) x',[e,p,env])).rows[0].x;
const save=async(p=current.caseData,rev=current.revision,fp=current.sourceFingerprint,reason='Fictional preparation',e='A',period='2026',env='test')=>{current=(await run('select public.finance_audit_case_save_v1($1,$2,$3,$4,$5,$6,$7) x',[e,period,rev,fp,p,reason,env])).rows[0].x;return current;};
const history=async(e='A',p='2026',env='test')=>(await run('select public.finance_audit_case_history_v1($1,$2,$3) x',[e,p,env])).rows[0].x.rows;
try{
 await check('New migration rehearses and fully rolls back private schema',async()=>{await db.exec('begin;'+migration()+'rollback;');assert.equal((await run("select to_regclass('private.finance_audit_cases_v1') x")).rows[0].x,null);});
 await db.exec(migration());await f.as();
 await check('Verified accountant receives 12 unknown items and exact all-row company counts',async()=>{current=await read();assert.equal(current.canEdit,true);assert.equal(current.revision,0);assert.equal(Object.keys(current.caseData.items).length,12);assert.deepEqual(current.sourceCounts,{ledger:2,invoices:2,expense_requests:1});assert.match(current.sourceFingerprint,/^[a-f0-9]{64}$/);assert.equal(current.currentFingerprint,current.sourceFingerprint);});
 await check('Year month and quarter keys are isolated; malformed periods rejected',async()=>{for(const p of ['2026','2026-09','2026-Q4'])assert.equal((await read('A',p)).revision,0);for(const p of ['2026-00','2026-13','2026-Q0','2026-Q5','0000','26','2026-09-01',null])await denied(()=>read('A',p),'22023');});
 await check('First provided item records server actor/time and immutable revision',async()=>{const p=clone(current.caseData);Object.assign(p.items.A01,{ownerId:'accountant',evidenceReference:'Internal document register A01',status:'provided',applicability:'applicable',preparedBy:'forged',preparedAt:'forged',reviewedBy:'forged',reviewedAt:'forged',reviewedFingerprint:'forged'});await save(p);assert.equal(current.revision,1);assert.equal(current.caseData.items.A01.preparedBy,'accountant');assert.notEqual(current.caseData.items.A01.preparedAt,'forged');assert.equal(current.caseData.items.A01.reviewedBy,null);assert.deepEqual((await history())[0].caseData,current.caseData);});
 await check('CAS and forged source fingerprint reject without case/audit writes',async()=>{const baseline=clone(current);await denied(()=>save(baseline.caseData,0),'40001');await denied(()=>save(baseline.caseData,baseline.revision,'0'.repeat(64)),'40001');assert.equal((await read()).revision,baseline.revision);assert.equal((await history()).length,1);});
 await check('Preparer cannot self-review even when spoofing preparation metadata',async()=>{const p=clone(current.caseData);Object.assign(p.items.A01,{status:'reviewed',preparedBy:'ceo',reviewedBy:'ceo'});await denied(()=>save(p),'42501');});
 await check('Different authorized reviewer stamps current source fingerprint',async()=>{await f.as('ceo');current=await read();const p=clone(current.caseData);p.items.A01.status='reviewed';await save(p);assert.equal(current.caseData.items.A01.reviewedBy,'ceo');assert.equal(current.caseData.items.A01.preparedBy,'accountant');assert.equal(current.caseData.items.A01.reviewedFingerprint,current.sourceFingerprint);});
 await check('Unrelated item edit preserves review; changed reviewed content invalidates it',async()=>{const prior=clone(current.caseData.items.A01);const p=clone(current.caseData);p.items.A02.notes='Collect invoices';await save(p);assert.deepEqual(current.caseData.items.A01,prior);const q=clone(current.caseData);q.items.A01.notes='Updated evidence description';await save(q);assert.equal(current.caseData.items.A01.status,'provided');assert.equal(current.caseData.items.A01.preparedBy,'ceo');assert.equal(current.caseData.items.A01.reviewedBy,null);});
 await check('Changed company engagement invalidates all previous item reviews',async()=>{await f.as('accountant');current=await read();let p=clone(current.caseData);p.items.A01.status='reviewed';await save(p);p=clone(current.caseData);p.engagementType='financial';await save(p);assert.equal(current.caseData.items.A01.status,'provided');assert.equal(current.caseData.items.A01.reviewedFingerprint,null);});
 await check('Valid source links persist; absent foreign tenant/company/environment links reject',async()=>{let p=clone(current.caseData);p.items.A03.sourceLinks=[{sourceType:'invoice',sourceId:'inv-a'},{sourceType:'expense_request',sourceId:'req-a'}];p.items.A03.status='provided';p.items.A03.applicability='applicable';await save(p);for(const id of ['missing','inv-b','inv-other','inv-prod']){p=clone(current.caseData);p.items.A03.sourceLinks=[{sourceType:'invoice',sourceId:id}];await denied(()=>save(p),'42501');}});
 await check('Invalid owner IDs, duplicate links and unknown fields fail closed',async()=>{for(const id of ['missing','other-owner']){const p=clone(current.caseData);p.items.A02.ownerId=id;await denied(()=>save(p),'42501');}let p=clone(current.caseData);p.items.A03.sourceLinks.push(clone(p.items.A03.sourceLinks[0]));await denied(()=>save(p),'22023');p=clone(current.caseData);p.items.A01.secret='extra';await denied(()=>save(p),'22023');p=clone(current.caseData);delete p.items.A12;await denied(()=>save(p),'22023');});
 await check('Provided/reviewed need evidence and not-applicable needs justification',async()=>{let p=clone(current.caseData);p.items.A04.status='provided';await denied(()=>save(p),'22023');p=clone(current.caseData);p.items.A04.applicability='not_applicable';await denied(()=>save(p),'22023');p.items.A04.notes='No relevant transactions';await save(p);assert.equal(current.caseData.items.A04.status,'pending');});
 await check('Unknown applicability permits preparation but cannot receive an internal review',async()=>{let p=clone(current.caseData);Object.assign(p.items.A08,{status:'provided',evidenceReference:'Provisional evidence register'});await save(p);assert.equal(current.caseData.items.A08.status,'provided');await f.as('ceo');current=await read();p=clone(current.caseData);p.items.A08.status='reviewed';await denied(()=>save(p),'22023');await f.as('accountant');current=await read();});
 await check('Source changes retain original reviewed history but reject stale save',async()=>{await f.as('ceo');current=await read();let p=clone(current.caseData);p.items.A03.status='reviewed';await save(p);const old=clone(current),oldHistory=await history();await f.admin("update public.invoices set amount=101 where id='inv-a'");await f.as('ceo');current=await read();assert.notEqual(current.sourceFingerprint,old.sourceFingerprint);assert.equal(current.caseData.items.A03.reviewedFingerprint,old.sourceFingerprint);assert.deepEqual(await history(),oldHistory);await denied(()=>save(old.caseData,old.revision,old.sourceFingerprint),'40001');});
 await check('Unrelated roundtrip cannot silently refresh stale review',async()=>{const old=clone(current.caseData.items.A03),p=clone(current.caseData);p.items.A05.notes='Unrelated preparation';await save(p);assert.deepEqual(current.caseData.items.A03,old);assert.notEqual(current.caseData.items.A03.reviewedFingerprint,current.sourceFingerprint);});
 await check('Explicit re-review intent is revalidated and stamped by a different preparer',async()=>{let p=clone(current.caseData);p.items.A03.reviewedFingerprint=current.sourceFingerprint;await save(p);assert.equal(current.caseData.items.A03.reviewedFingerprint,current.sourceFingerprint);assert.equal(current.caseData.items.A03.reviewedBy,'ceo');});
 await check('Source fingerprints detect same-count ledger, expense, future and voided changes',async()=>{for(const sql of ["update public.ledger_entries set debit=106 where debit=105","update public.expense_requests set files='[{\"path\":\"changed.pdf\"}]' where id='req-a'","update public.invoices set invoice_date='2099-12-31' where id='inv-a'","update public.invoices set description='Changed voided source' where id='inv-void'"]){const before=(await read()).sourceFingerprint;await f.admin(sql);await f.as('ceo');assert.notEqual((await read()).sourceFingerprint,before);}});
 await check('Reporting profile/check changes invalidate the same source fingerprint',async()=>{const before=(await read()).sourceFingerprint;const profile=(await run("select public.finance_reporting_profile_read_v1('A','test') x")).rows[0].x;profile.profile.periodChecks={'2026-08':{bankReconciled:true}};await run("select public.finance_reporting_profile_save_v1('A',$1,$2,'Fictional check','test')",[profile.revision,profile.profile]);assert.notEqual((await read()).sourceFingerprint,before);});
 await check('Other company/tenant/environment edits do not contaminate selected fingerprint',async()=>{const before=(await read()).sourceFingerprint;await f.admin("update public.invoices set amount=999 where id in ('inv-b','inv-other','inv-prod')");await f.as('ceo');assert.equal((await read()).sourceFingerprint,before);});
 await check('External auditor and board with explicit full source visibility only read; employee/anonymous denied',async()=>{for(const role of ['external_audit','board']){await f.as(role);await run("select set_config('fixture.explicit_all_source_access','true',false)");current=await read();assert.equal(current.canEdit,false);await denied(()=>save(),'42501');assert((await history()).length>0);await run("select set_config('fixture.explicit_all_source_access','false',false)");}for(const role of ['employee','anonymous']){await f.as(role);await denied(()=>read(),'42501');await denied(()=>history(),'42501');}await f.as();current=await read();});
 await check('External/board reporting role alone never grants missing source-row visibility',async()=>{for(const role of ['external_audit','board']){await f.as(role);await denied(()=>read(),'42501');await denied(()=>history(),'42501');}await f.as();current=await read();});
 await check('Configured page deny/view override role; unbound or inactive actor rejected',async()=>{await f.admin("update public.system_settings set value=jsonb_set(value,'{accountant,reports}','\"view\"') where key='role_permissions'");await f.as();current=await read();assert.equal(current.canEdit,false);await denied(()=>save(),'42501');await f.admin("update public.system_settings set value=jsonb_set(value,'{accountant,reports}','\"none\"') where key='role_permissions'");await f.as();await denied(()=>read(),'42501');await f.admin("update public.system_settings set value=jsonb_set(value,'{accountant,reports}','\"edit\"') where key='role_permissions';update public.finance_users set active=false where id='accountant'");await f.as();await denied(()=>read(),'42501');await f.admin("update public.finance_users set active=true,google_link_status='unbound' where id='accountant'");await f.as();await denied(()=>read(),'42501');await f.admin("update public.finance_users set google_link_status='bound' where id='accountant'");await f.as();});
 await check('Membership company, department and row denies prevent count/hash/history disclosure',async()=>{for(const [setting,value] of [['fixture.denied_entity','A'],['fixture.denied_department','D1'],['fixture.denied_row','req-a'],['fixture.denied_row','inv-a'],['fixture.permission','false']]){await run('select set_config($1,$2,false)',[setting,value]);await denied(()=>read(),'42501');await denied(()=>history(),'42501');await run('select set_config($1,$2,false)',[setting,setting==='fixture.permission'?'true':'']);}});
 await check('Unknown/all company and wrong environment fail closed; known empty scope is zero',async()=>{await denied(()=>read('all'),'22023');await denied(()=>read('unknown'),'42501');await denied(()=>read('A','2026','other'),'22023');assert.deepEqual((await read('EMPTY')).sourceCounts,{ledger:0,invoices:0,expense_requests:0});assert.equal((await read('A','2026','production')).revision,0);});
 await check('Direct table and private helper access remain forbidden',async()=>{for(const sql of ['select * from private.finance_audit_cases_v1','select * from private.finance_audit_case_revisions_v1','select private.finance_audit_case_default_v1()'])await denied(()=>run(sql),'42501');await f.admin('select 1');await denied(()=>run("update private.finance_audit_case_revisions_v1 set reason='replace'"),'42501');await denied(()=>run('delete from private.finance_audit_case_revisions_v1'),'42501');await f.as();});
 await check('Revoked or removed linked sources cannot be exposed through saved or historical cases',async()=>{await f.admin('begin');await f.admin("delete from public.invoices where id='inv-a'");await f.as();for(const action of [read,history]){await db.exec('savepoint inaccessible_source');await denied(()=>action(),'42501');await db.exec('rollback to savepoint inaccessible_source');}await db.exec('rollback');await f.as();});
 await check('No content mutation can silently upgrade external reader or edit historic reviewer identity',async()=>{current=await read();let p=clone(current.caseData);p.items.A03.preparedBy='employee';p.items.A03.reviewedBy='external_audit';p.items.A03.reviewedFingerprint='forged';const old=clone(current.caseData.items.A03);await save(p);assert.deepEqual(current.caseData.items.A03,old);await f.admin("update public.finance_users set active=false where id='ceo'");p=clone(current.caseData);p.items.A07.ownerId='ceo';await denied(()=>save(p),'42501');await f.admin("update public.finance_users set active=true where id='ceo'");await f.as();});
 await check('Audit insertion failure rolls back case update atomically',async()=>{current=await read();await f.admin("create function private.fixture_reject_audit() returns trigger language plpgsql as $$begin raise exception 'fixture audit failure';end$$;create trigger fixture_reject before insert on private.finance_audit_case_revisions_v1 for each row execute function private.fixture_reject_audit()");await f.as();const before=current.revision,p=clone(current.caseData);p.items.A06.notes='Must rollback';await denied(()=>save(p),'P0001');assert.equal((await read()).revision,before);await f.admin('drop trigger fixture_reject on private.finance_audit_case_revisions_v1');await f.as();});
 await check('Read-only postflight verifies installed authority and template semantics',async()=>{await f.admin('select 1');await db.exec(f.readSource('scripts/finance_audit_readiness_postflight.sql').replace(/^\\set ON_ERROR_STOP on\r?\n/,''));});
 await check('Exact authenticated release canary preserves operational sources and case/history on rollback',async()=>{await f.admin('select 1');const before=await f.state();const result=await db.exec(f.readSource('scripts/finance_audit_readiness_canary.sql'));assert.deepEqual(result.flatMap(x=>x.rows||[]).find(x=>x.audit_readiness_canary_result).audit_readiness_canary_result,{canary:'authenticated_audit_readiness_v1',ok:true,rolled_back:true,audit_scope_preserved:true});assert.equal(await f.state(),before);});
 await check('First-installation migration plus real authenticated canary rollback handles absent new tables',async()=>{const isolated=new PGlite();try{const fixture=await createAuditReadinessFixture(isolated);const canary=fixture.readSource('scripts/finance_audit_readiness_canary.sql');const core=canary.split('-- FINANCE_AUTHENTICATED_CANARY_CORE_BEGIN')[1].split('-- FINANCE_AUTHENTICATED_CANARY_CORE_END')[0];const rollback=canary.split('-- FINANCE_AUTHENTICATED_CANARY_ROLLBACK_CHECK_BEGIN')[1].split('-- FINANCE_AUTHENTICATED_CANARY_ROLLBACK_CHECK_END')[0];await isolated.exec('begin isolation level repeatable read;savepoint audit_rehearsal;'+migration()+core+'rollback to savepoint audit_rehearsal;'+rollback+'rollback;');assert.equal((await isolated.query("select to_regclass('private.finance_audit_cases_v1') x")).rows[0].x,null);}finally{await isolated.close();}});
 console.log('Audit readiness: '+checks+' checks passed. Local PostgreSQL only.');
}finally{await db.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
