'use strict';
// Fictional local browser only. All Supabase and payment endpoints are mocked.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const {applyBuildEnvironment}=require('./finance_build_environment');
const root=path.resolve(__dirname,'..'),out=process.env.LABOR_UI_EVIDENCE||'/tmp/finance-electronic-labor-ui-20260928';
const anchor='bootAuthGate();\n\n})();';
let html=applyBuildEnvironment(fs.readFileSync(path.join(root,'index.html'),'utf8'),{target:'local',supabaseUrl:'',supabaseAnonKey:''});
assert(html.includes(anchor));
html=html.replace(anchor,'window.__laborTest={run:async function(code){return await eval(code);}};\n'+anchor).replace(/<script\b[^>]*src=["']https?:[^>]*><\/script>/gi,'');
const zip=Buffer.concat([Buffer.from([80,75,5,6]),Buffer.alloc(18)]);
const server=http.createServer((req,res)=>{
  if(req.url==='/functions/v1/finance-labor-external/export/month'){
    let body='';req.on('data',chunk=>body+=chunk);req.on('end',()=>{
      const valid=req.headers.authorization==='Bearer fictional-jwt'&&JSON.parse(body).paidMonth==='2026-09';
      if(!valid){res.writeHead(401);return res.end();}
      res.writeHead(200,{'content-type':'application/zip','content-disposition':'attachment; filename="fixture.zip"','x-export-incomplete-count':process.env.LABOR_TEST_INCOMPLETE||'0'});res.end(zip);
    });return;
  }
  const file=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);
  if(file!==root&&!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}
  if(file===root||file===path.join(root,'index.html')){res.setHeader('content-type','text/html');return res.end(html);}
  if(!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}
  res.setHeader('content-type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(file));
});
let browser,checks=0;
function equal(actual,expected,message){assert.deepEqual(actual,expected,message);checks++;}
(async()=>{
  fs.mkdirSync(out,{recursive:true});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const origin='http://127.0.0.1:'+server.address().port;
  browser=await chromium.launch({headless:true,...(process.env.FINANCE_BROWSER_CHANNEL==='chromium'?{}:{channel:process.env.PLAYWRIGHT_CHANNEL||'chrome'})});
  const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
  await context.route('**/*',route=>new URL(route.request().url()).origin===origin||/^(blob|data):/.test(route.request().url())?route.continue():route.abort());
  const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));page.on('dialog',dialog=>dialog.dismiss());
  await page.goto(origin);await page.waitForFunction(()=>window.__laborTest);
  const run=code=>page.evaluate(code=>window.__laborTest.run(code),code);
  await run(`(async()=>{
    window.__role='employee';currentRoleKey=function(){return window.__role;};isFinance=function(){return ['accountant','ceo','admin_director'].includes(window.__role);};hasSupabase=function(){return true;};financeStartupReadIdentity=function(){return 'fictional';};financeAuthIdentityEpoch=1;currentTenantId=function(){return '11111111-1111-4111-8111-111111111111';};activeDataEnvironment=function(){return 'production';};currentUserEntityId=function(){return 'F1';};
    S.user={id:'employee',n:'虛構員工',role:'employee',dc:'D1',eid:'F1'};S.demoLogin=false;S.page='detail';S.detailRid='labor-req';
    ENTS=[{id:'F1',n:'虛構付款公司',s:'虛構付款公司',active:true}];DEPTS=[{c:'D1',n:'虛構課程部門',eid:'F1',active:true}];
    window.__lineId='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';window.__statementId='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
    REQS=[{id:'labor-req',no:'TEST-202609-001',eid:'F1',dc:'D1',status:'pending_external_labor_settlement',type:'hr_expense_request',amt:1250.75,formPayload:{electronicLabor:{version:1,status:'pending_invite',signerName:'虛構講師',inviteEmail:'lecturer@example.invalid',period:'2026-09',totalGrossCents:125075,serviceLines:[{id:window.__lineId,courseRef:'COURSE-A',courseType:'教學',description:'虛構課程',serviceDate:'2026-09-15',departmentCode:'D1',grossCents:125075}]}}}];
    window.__serverState={statementId:window.__statementId,requestId:'labor-req',version:3,status:'accrued',entityId:'F1',totalGrossCents:125075,totalPaidGrossCents:0,outstandingGrossCents:125075,serviceLines:[{id:window.__lineId,courseRef:'COURSE-A',courseType:'教學',description:'虛構課程',serviceDate:'2026-09-15',departmentCode:'D1',grossCents:125075,paidGrossCents:0,outstandingGrossCents:125075}],payments:[]};
    window.__calls=[];window.__client={rpc:async function(name,args){window.__calls.push({name,args});if(name==='finance_labor_request_status_v1')return{data:{requestId:'labor-req',statementId:window.__statementId,status:window.__serverState.status,version:window.__serverState.version}};if(name==='finance_labor_staff_for_request_v1')return{data:window.__serverState};if(name==='finance_labor_staff_pay_v1'){window.__serverState=Object.assign({},window.__serverState,{status:'partially_paid',version:window.__serverState.version+1,totalPaidGrossCents:args.p_allocations[0].grossCents,outstandingGrossCents:window.__serverState.totalGrossCents-args.p_allocations[0].grossCents,serviceLines:[Object.assign({},window.__serverState.serviceLines[0],{paidGrossCents:args.p_allocations[0].grossCents,outstandingGrossCents:window.__serverState.totalGrossCents-args.p_allocations[0].grossCents})],payments:[{id:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',paidOn:args.p_paid_on,grossCents:args.p_allocations[0].grossCents}]});return{data:{status:'partially_paid',version:window.__serverState.version}};}if(name==='finance_labor_staff_list_v1')return{data:{items:[{statementId:window.__statementId,requestId:'labor-req',entityId:'F1',status:window.__serverState.status,totalGrossCents:125075}],nextCursor:null}};return{error:{message:'unexpected '+name}};},functions:{invoke:async function(name,options){window.__calls.push({name,body:options.body instanceof FormData?'formdata':options.body});if(name==='finance-labor-external/staff/evidence/upload')return{data:{bucket:'finance-external-labor',path:'11111111-1111-4111-8111-111111111111/'+window.__statementId+'/payment_evidence/dddddddd-dddd-4ddd-8ddd-dddddddddddd',sha256:'a'.repeat(64),sizeBytes:options.body.get('file').size,mime:'image/png'}};if(name==='finance-labor-external/export/preview')return{data:{payerEntityId:'F1',actualPaidMonth:'2026-09',paymentCount:1,statementCount:1,incompleteCount:0,pendingCount:0,uninvitedCount:0,ready:true}};return{error:{message:'unexpected '+name}};}},auth:{getSession:async function(){return{data:{session:{access_token:'fictional-jwt'}}};}}};getSb=function(){return window.__client;};SUPABASE_URL=${JSON.stringify(origin)};SUPABASE_ANON_KEY='public-fixture';
    window.openDetail=function(rid){S.detailRid=rid;S.page='detail';document.getElementById('labor-fixture').innerHTML=laborElectronicDetailHtml(REQS[0],laborElectronicCached(REQS[0]));};
    document.body.innerHTML='<main id="labor-test-host" style="box-sizing:border-box;max-width:960px;padding:12px;margin:0 auto"><div id="labor-fixture"></div><div id="labor-tracker-slot"></div></main>';
    document.documentElement.style.cssText='height:auto!important;min-height:100vh!important;overflow:auto!important';
    document.body.style.cssText='height:auto!important;min-height:100vh!important;overflow:visible!important;display:block!important';
    await loadLaborElectronicDetail('labor-req',true);
  })()`);
  equal(await run("window.__calls.filter(c=>c.name.startsWith('finance_labor')).map(c=>c.name)"),['finance_labor_request_status_v1'],'employee only reads low sensitivity status');
  equal(await page.getByRole('button',{name:'確認本次實際付款並產生專用傳票'}).count(),0,'employee has no payment action');
  await run(`(async()=>{window.__role='section_chief';S.user.role='section_chief';await loadLaborElectronicDetail('labor-req',true);})()`);
  equal(await run("window.__calls.at(-1).name"),'finance_labor_request_status_v1','manager only reads low sensitivity status');
  equal(await page.getByRole('button',{name:'確認本次實際付款並產生專用傳票'}).count(),0,'manager has no payment action');
  equal(await run("(async()=>{REQS[0].status='pending_section_chief';REQS[0].steps=[{rk:'section_chief',a:''}];canActRequest=function(){return true;};window.__managerReached=false;approvalActionPayload=async function(){window.__managerReached=true;throw new Error('fixture_stop_after_manager_gate');};await doApprove('labor-req').catch(function(){});return window.__managerReached;})()"),true,'manager approval is not blocked by unsigned lecturer');
  equal(await run("(async()=>{REQS[0].status='pending_accountant';REQS[0].steps=[{rk:'accountant',a:''}];LABOR_DETAIL_CACHE['labor-req']={identity:laborElectronicIdentity(),loaded:true,data:{status:'invited'}};window.__managerReached=false;await doApprove('labor-req').catch(function(){});return window.__managerReached;})()"),false,'accountant legacy step stays blocked before signature and review');
  await run("REQS[0].status='pending_external_labor_settlement';REQS[0].steps=[];window.__serverState.status='accrued';");
  await run("(async()=>{window.__role='accountant';S.user.role='accountant';REQS[0].status='pending_accountant';REQS[0].steps=[{rk:'accountant',a:''}];window.__serverState.status='pending_invite';window.__serverState.statementId=null;window.__originalInvoke=window.__client.functions.invoke;window.__client.functions.invoke=async function(name,options){window.__calls.push({name,body:options.body});if(name==='finance-labor-external/invite/create'){window.__serverState.status='invited';window.__serverState.statementId=window.__statementId;window.__serverState.version=1;return{data:{statementId:window.__statementId,inviteId:'dddddddd-dddd-4ddd-8ddd-dddddddddddd',invitationUrl:'https://finance.suiyuecare.com/external-remuneration.html#t=fictional-token',delivery:'copy_link'}};}return window.__originalInvoke(name,options);};await loadLaborElectronicDetail('labor-req',true);})()");
  equal(await page.getByRole('button',{name:'建立講師邀請連結'}).count(),1,'accountant can invite only after manager route');
  await page.getByRole('button',{name:'建立講師邀請連結'}).click();
  equal(await run("window.__calls.find(c=>c.name==='finance-labor-external/invite/create').body.lines[0].grossCents"),125075,'invite uses submitted gross course snapshot');
  equal(await page.locator('#labor-invite-link').inputValue(),'https://finance.suiyuecare.com/external-remuneration.html#t=fictional-token','one-time invite URL visible to accountant');
  await run("window.__client.functions.invoke=window.__originalInvoke;REQS[0].status='pending_external_labor_settlement';REQS[0].steps=[];window.__serverState.status='accrued';window.__serverState.version=3;");
  await run(`(async()=>{window.__role='cashier';S.user.role='cashier';await loadLaborElectronicDetail('labor-req',true);})()`);
  equal(await run("window.__calls.at(-1).name"),'finance_labor_request_status_v1','cashier only reads low sensitivity status');
  equal(await page.getByRole('button',{name:'確認本次實際付款並產生專用傳票'}).count(),0,'cashier cannot use old or new payment action');
  await run(`(async()=>{window.__role='accountant';S.user.role='accountant';await loadLaborElectronicDetail('labor-req',true);})()`);
  equal(await run("window.__calls.at(-1).name"),'finance_labor_staff_for_request_v1','accountant reads dedicated detail');
  equal(await page.getByRole('button',{name:'確認本次實際付款並產生專用傳票'}).count(),1,'accountant can enter bank reconciled payment');
  await page.setViewportSize({width:390,height:844});
  equal(await page.evaluate(()=>document.querySelector('#labor-test-host').getBoundingClientRect().width>=360),true,'phone retains readable content width');
  equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'payment form has no phone overflow');
  equal(await page.getByRole('button',{name:'確認本次實際付款並產生專用傳票'}).isVisible(),true,'payment action visible on phone');
  await page.screenshot({path:path.join(out,'labor-payment-390.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('#labor-pay-gross-0').fill('2000.00');await page.locator('#labor-pay-date').fill('2026-09-20');await page.locator('#labor-pay-bank-ref').fill('BANK-REF-TEST-001');await page.locator('#labor-pay-tax-basis').fill('虛構所得稅依據：依法核定');await page.locator('#labor-pay-nhi-basis').fill('虛構補充保費依據：依法核定');
  await page.getByRole('button',{name:'確認本次實際付款並產生專用傳票'}).click();
  equal(await run("window.__calls.filter(c=>c.name==='finance_labor_staff_pay_v1').length"),0,'overpayment blocked client side');
  await page.locator('#labor-pay-gross-0').fill('100.25');await page.locator('#labor-pay-tax-0').fill('10.00');await page.locator('#labor-pay-nhi-0').fill('5.00');
  await page.getByRole('button',{name:'確認本次實際付款並產生專用傳票'}).click();
  equal(await run("window.__calls.filter(c=>c.name==='finance_labor_staff_pay_v1').length"),0,'payment without verified evidence blocked');
  await page.locator('#labor-pay-proof').setInputFiles({name:'fictional-bank.png',mimeType:'image/png',buffer:Buffer.from([137,80,78,71,13,10,26,10,0])});
  await page.getByRole('button',{name:'上傳並核對銀行證據'}).click();await page.getByText('銀行對帳佐證已安全上傳並核對',{exact:false}).waitFor();
  equal(await run("window.__calls.filter(c=>c.name==='finance-labor-external/staff/evidence/upload').length"),1,'bank evidence goes through authenticated Edge');
  await page.getByRole('button',{name:'確認本次實際付款並產生專用傳票'}).click();await page.getByText('部分已付款',{exact:false}).waitFor();
  const payment=await run("window.__calls.find(c=>c.name==='finance_labor_staff_pay_v1').args");
  equal(payment.p_allocations,[{serviceLineId:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',grossCents:10025,incomeTaxCents:1000,nhiCents:500}],'exact cents in partial allocation');
  equal(payment.p_evidence.bankStatementSha256,'a'.repeat(64),'bank proof hash used in posting');
  equal(payment.p_bank_ref,'BANK-REF-TEST-001','actual bank reference used');
  equal(await run("window.__serverState.outstandingGrossCents"),115050,'remaining amount tracked');
  await run(`(async()=>{window.__role='ceo';S.user.role='ceo';window.__serverState.status='reviewed';await loadLaborElectronicDetail('labor-req',true);})()`);
  equal(await page.getByRole('button',{name:'確認應計入帳'}).count(),1,'independent CEO can accrue');
  equal(await page.getByRole('button',{name:'確認本次實際付款並產生專用傳票'}).count(),0,'CEO cannot post payment');
  await run(`(async()=>{window.__role='admin_director';S.user.role='admin_director';await loadLaborElectronicDetail('labor-req',true);})()`);
  equal(await page.getByRole('button',{name:'確認應計入帳'}).count(),1,'independent admin director can accrue');
  equal(await page.getByRole('button',{name:'確認本次實際付款並產生專用傳票'}).count(),0,'admin director cannot post payment');
  await run(`(async()=>{window.__role='accountant';S.user.role='accountant';window.__serverState.status='paid';await loadLaborElectronicDetail('labor-req',true);LABOR_TRACKER.open=true;LABOR_TRACKER.entityId='F1';LABOR_TRACKER.period='2026-09';renderLaborElectronicTracker();})()`);
  await page.getByRole('button',{name:'檢查本月交付資料'}).click();await page.getByRole('button',{name:'下載完整月交 ZIP'}).waitFor();
  const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'下載完整月交 ZIP'}).click();const download=await downloadPromise;equal(download.suggestedFilename(),'external_labor_F1_2026-09.zip','complete monthly export downloaded');
  await download.saveAs(path.join(out,'fictional-complete.zip'));
  equal(await run("(()=>{LABOR_EXPORT.preview={ready:true,paymentCount:1,incompleteCount:0,pendingCount:1,uninvitedCount:1};LABOR_EXPORT.identity=laborElectronicIdentity();LABOR_EXPORT.entityId='F1';LABOR_EXPORT.period='2026-09';renderLaborElectronicTracker();return document.querySelector('#labor-tracker-panel').textContent.includes('未邀請 1 筆');})()"),true,'month preview identifies uninvited statements');
  equal(await page.getByRole('button',{name:'下載完整月交 ZIP'}).count(),0,'incomplete monthly roster never offers complete export');
  const intake=await run(`(()=>{window.__role='employee';S.user.role='employee';S.nrType='hr_expense_request';S.hrItem='labor_electronic';S.hrPeriod='2026-09';S.nrLaborLines=[{id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',courseRef:'A',courseType:'講座',description:'虛構課一',serviceDate:'2026-09-15',departmentCode:'D1',grossValue:'100.25'},{id:'dddddddd-dddd-4ddd-8ddd-dddddddddddd',courseRef:'B',courseType:'教學',description:'虛構課二',serviceDate:'2026-09-16',departmentCode:'D1',grossValue:'50.05'}];S.nrLaborPlannedDates=['2026-10-15','2026-10-16','2026-10-17'];S.nrLaborSignerName='虛構講師';S.nrLaborInviteEmail='TEACHER@example.invalid';normalizeRequestEntityDept=function(){return{ok:true};};let host=document.querySelector('#labor-test-host');host.insertAdjacentHTML('beforeend','<input id="hr-period" value="2026-09"><input id="nr-ent" value="F1">');let info=collectHrExpenseInfo();return{gross:info.totalGrossCents,lines:info.serviceLines.map(x=>x.grossCents),dates:info.plannedPaymentDates,email:info.inviteEmail,missing:info.missing};})()`);
  equal(intake,{gross:15030,lines:[10025,5005],dates:['2026-10-15','2026-10-16','2026-10-17'],email:'teacher@example.invalid',missing:[]},'employee intake preserves exact gross cents, mixed course lines, scheduled dates');
  equal(await run("(()=>{S.nrLaborPlannedDates=[];document.querySelector('#labor-test-host').insertAdjacentHTML('beforeend','<div id=\"labor-plan-panel\">'+laborElectronicPaymentHtml()+'</div>');return Array.from(document.querySelectorAll('#labor-plan-fields input[data-labor-plan-date]')).map(x=>x.value);})()"),[''],'new request starts with one blank date, not a fictional payment schedule');
  equal(await run("collectHrExpenseInfo().missing.some(x=>x.includes('預計付款日'))"),true,'blank first payment date blocks submission');
  await page.locator('#labor-plan-1').fill('2026-10-15');
  equal(await run("({dates:collectHrExpenseInfo().plannedPaymentDates,missing:collectHrExpenseInfo().missing})"),{dates:['2026-10-15'],missing:[]},'one planned payment date is sufficient');
  await page.getByRole('button',{name:'＋ 新增分期付款日'}).click();
  equal(await page.locator('#labor-plan-2').inputValue(),'','additional installment is blank until entered');
  await page.locator('#labor-plan-2').fill('2026-10-16');
  equal(await run("collectHrExpenseInfo().missing"),[],'two chronological payment dates accepted');
  const twoDateDraft=await run("collectNRFormState()");
  equal(twoDateDraft.nrLaborPlannedDates,['2026-10-15','2026-10-16'],'draft captures dynamic planned dates');
  await run("(()=>{document.querySelector('#labor-plan-panel').innerHTML=laborElectronicPaymentHtml();applyNRFormState("+JSON.stringify(twoDateDraft)+");})()");
  equal(await page.locator('#labor-plan-fields input[data-labor-plan-date]').evaluateAll(nodes=>nodes.map(node=>node.value)),['2026-10-15','2026-10-16'],'draft reopen restores two dates');
  await page.getByRole('button',{name:'＋ 新增分期付款日'}).click();
  await page.locator('#labor-plan-3').fill('2026-10-17');
  equal(await run("collectHrExpenseInfo().plannedPaymentDates"),['2026-10-15','2026-10-16','2026-10-17'],'existing three-date schedule remains valid');
  await page.locator('#labor-plan-3').fill('2026-10-16');
  equal(await run("collectHrExpenseInfo().missing.some(x=>x.includes('預計付款日'))"),true,'duplicate installment date blocked');
  await page.locator('#labor-plan-3').fill('2026-10-14');
  equal(await run("collectHrExpenseInfo().missing.some(x=>x.includes('預計付款日'))"),true,'out of order installment date blocked');
  await page.locator('#labor-plan-3').fill('2026-10-17');
  await page.getByRole('button',{name:'移除第 3 次預計付款日'}).click();
  equal(await run("collectHrExpenseInfo().plannedPaymentDates"),['2026-10-15','2026-10-16'],'remove installment keeps earlier dates');
  const twelveDates=Array.from({length:12},(_,i)=>'2026-10-'+String(i+1).padStart(2,'0'));
  await run("(()=>{S.nrLaborPlannedDates="+JSON.stringify(twelveDates)+";renderLaborElectronicPaymentDates();})()");
  equal(await page.locator('#labor-plan-fields input[data-labor-plan-date]').count(),12,'all twelve permitted payment dates render');
  equal(await page.getByRole('button',{name:'＋ 新增分期付款日'}).count(),0,'thirteenth payment date cannot be added');
  equal(await run("collectHrExpenseInfo().missing"),[],'twelve chronological payment dates accepted');
  await run("(()=>{S.nrLaborPlannedDates=['2026-10-15','2026-10-16','2026-10-17'];renderLaborElectronicPaymentDates();})()");
  const legacyThreeDateDraft=await run("collectNRFormState()");
  await run("(()=>{S.nrLaborPlannedDates=[];document.querySelector('#labor-plan-panel').innerHTML=laborElectronicPaymentHtml();applyNRFormState("+JSON.stringify(legacyThreeDateDraft)+");})()");
  equal(await page.locator('#labor-plan-fields input[data-labor-plan-date]').evaluateAll(nodes=>nodes.map(node=>node.value)),['2026-10-15','2026-10-16','2026-10-17'],'legacy three-date draft reopens without loss');
  const returnedDates=await run("(()=>{var saved=Object.assign({},REQS[0],{formPayload:{electronicLabor:{version:1,plannedPaymentDates:"+JSON.stringify(twelveDates)+",serviceLines:[]}}});var returned=returnedRequestFormState(saved),rejected=rejectedRequestDraftState(saved);return{returned:returned.nrLaborPlannedDates,rejected:rejected.nrLaborPlannedDates,returnedLast:returned.fields['labor-plan-12'],rejectedLast:rejected.fields['labor-plan-12']};})()");
  equal(returnedDates,{returned:twelveDates,rejected:twelveDates,returnedLast:'2026-10-12',rejectedLast:'2026-10-12'},'returned and rejected requests retain all twelve payment dates');
  await run("(()=>{S.nrLaborPlannedDates="+JSON.stringify(twelveDates.concat('2026-10-13'))+";document.querySelector('#labor-plan-panel').innerHTML='';})()");
  equal(await run("collectHrExpenseInfo().missing.some(x=>x.includes('預計付款日'))"),true,'tampered thirteenth payment date blocked at submission');
  equal(await run("(()=>{LABOR_INVITE_ONCE['labor-req']={identity:laborElectronicIdentity(),url:'https://finance.suiyuecare.com/#secret'};LABOR_PAYMENT_DRAFT['labor-req']={bankStatementPath:'private/path',bankStatementSha256:'a'.repeat(64)};window.__role='cashier';S.user.role='cashier';laborElectronicCached(REQS[0]);return Object.keys(LABOR_INVITE_ONCE).length+Object.keys(LABOR_PAYMENT_DRAFT).length;})()"),0,'role switch clears one-time invite and private bank draft');
  await run(`(async()=>{window.__role='accountant';S.user.role='accountant';S.nrType=null;window.__serverState.status='signed_pending_archive';window.__serverState.version=8;window.__serverState.statementId=window.__statementId;window.__repairInvoke=window.__client.functions.invoke;window.__client.functions.invoke=async function(name,options){if(name==='finance-labor-external/staff/archive/repair'){window.__calls.push({name,body:options.body});window.__serverState.status='signed';window.__serverState.version++;return{data:{statementId:window.__statementId,version:window.__serverState.version,status:'signed',replayed:false}};}return window.__repairInvoke(name,options);};await loadLaborElectronicDetail('labor-req',true);})()`);
  equal(await page.getByRole('button',{name:'重試封存簽署資料'}).count(),1,'accountant sees archive recovery only while pending');
  await page.getByRole('button',{name:'重試封存簽署資料'}).click();
  equal(await run("window.__calls.filter(x=>x.name==='finance-labor-external/staff/archive/repair').at(-1).body.statementId"),'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','archive repair sends only the existing statement ID');
  equal(await page.getByRole('button',{name:'重試封存簽署資料'}).count(),0,'repaired signed record exits pending archive');
  await run("window.__client.functions.invoke=window.__repairInvoke;window.__serverState.status='paid';LABOR_TRACKER.open=true;LABOR_TRACKER.entityId='F1';LABOR_TRACKER.period='2026-09';renderLaborElectronicTracker();");
  for(const width of [1440,390]){await page.setViewportSize({width,height:width===390?844:1000});await page.locator('#labor-fixture').scrollIntoViewIfNeeded();equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'no '+width+'px overflow');await page.screenshot({path:path.join(out,'labor-'+width+'.png'),fullPage:true});}
  equal(await run("[laborElectronicUninvited({loaded:true,error:{message:'timeout'},data:{status:'pending_invite'}}),laborElectronicUninvited({loaded:true,data:null}),laborElectronicUninvited({loaded:true,data:{status:'pending_invite',statementId:window.__statementId}})]"),[false,false,false],'revision stays closed on load error, unknown status, or existing statement');
  const revisionOpen=await run(`(()=>{let r=REQS[0];r.status='pending_applicant_revision';r.app='虛構員工';r.applicantId='employee';r.steps=[{rk:'applicant_revision',a:''}];window.__role='employee';S.user.role='employee';S.user.id='employee';S.page='detail';laborElectronicEnsureIdentity();LABOR_DETAIL_CACHE[r.id]={identity:laborElectronicIdentity(),loaded:true,data:{requestId:r.id,status:'pending_invite',statementId:null},error:null};window.__revisionAlerts=[];window.alert=function(message){window.__revisionAlerts.push(message);};requestIsMine=function(){return true;};canActRequest=function(){return true;};returnedRequestFormState=function(){return{hrItem:'labor_electronic',hrPeriod:'2026-09',nrLaborLines:S.nrLaborLines,nrLaborSignerName:'虛構講師',nrLaborInviteEmail:'lecturer@example.invalid',nrLaborPlannedDates:['2026-10-15','2026-10-16','2026-10-17']};};closeAppr=function(){};renderNR=function(){};applyNRFormState=function(){};markNRClean=function(){};openDetail=function(){};document.querySelector('#labor-test-host').insertAdjacentHTML('beforeend','<div id="pg-newreq" class="pg"></div><div id="page-title"></div>');openReturnedRequestEditor(r.id);return{page:S.page,rid:S.nrRevisionRid};})()`);
  equal(revisionOpen,{page:'newreq',rid:'labor-req'},'returned electronic request opens pre-invite applicant editor');
  const revisionSubmit=await run(`(async()=>{window.__revisionRpcCalls=0;expenseTransactionIdentityCurrent=function(){return true;};loadExpenseRevisionPending=function(){return null;};expenseApplicantRevisionGuard=function(){return{ok:true};};showSubmitConfirm=async function(){return true;};showActionFeedback=function(){};completeActionFeedback=function(){};uploadExpenseRevisionDelta=async function(){return{requestFiles:[],passbookFiles:[],stepFiles:[]};};expenseApplicantRevisionRpc=async function(record,action,comment,patch){window.__revisionRpcCalls++;window.__revisionPatch=patch;return{ok:true};};buildAll=function(){};clearExpenseApplicantRevisionMode=function(){};let ctx={hrInfo:{digital:true,item:'labor_electronic',period:'2026-09',totalGrossCents:15030,serviceLines:S.nrLaborLines.map(x=>({id:x.id,courseRef:x.courseRef,courseType:x.courseType,description:x.description,serviceDate:x.serviceDate,departmentCode:x.departmentCode,grossCents:laborElectronicCents(x.grossValue)})),plannedPaymentDates:['2026-10-15','2026-10-16','2026-10-17'],signerName:'虛構講師',inviteEmail:'lecturer@example.invalid',summary:'虛構'},amount:150.30,isFixedExpense:false,description:'虛構課程',payment:{},purpose:'虛構課程',note:'',requestDate:'2026-09-15'};window.__revisionCtx=ctx;await submitExpenseApplicantRevisionFromForm(ctx);return{calls:window.__revisionRpcCalls,gross:window.__revisionPatch&&window.__revisionPatch.form_payload.electronicLabor.totalGrossCents};})()`);
  equal(revisionSubmit,{calls:1,gross:15030},'pre-invite resubmission reaches guarded RPC with updated gross snapshot');
  const invitedBlock=await run(`(async()=>{let r=REQS[0];S.nrRevisionRid=r.id;S.nrRevisionExpected=expenseApplicantRevisionExpectedSnapshot(r);S.page='detail';LABOR_DETAIL_CACHE[r.id]={identity:laborElectronicIdentity(),loaded:true,data:{requestId:r.id,status:'invited',statementId:window.__statementId},error:null};openReturnedRequestEditor(r.id);let pageAfterOpen=S.page;await submitExpenseApplicantRevisionFromForm(window.__revisionCtx);return{page:pageAfterOpen,calls:window.__revisionRpcCalls};})()`);
  equal(invitedBlock,{page:'detail',calls:1},'created invitation blocks both editor and resubmission');
  equal(errors,[],'no browser page errors');
  console.log('PASS electronic labor UI '+checks+' fictional browser checks; evidence '+out);
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();await new Promise(resolve=>server.close(resolve));});
