#!/usr/bin/env node
'use strict';
// Execute the real inline summary loader, detail hydrator, group helpers and
// list renderer. Only the wire transport / surrounding modal UI are fictional.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const fn=name=>{const a=html.indexOf('function '+name+'(');assert(a>=0,name);return html.slice(a,html.indexOf('\n}',a)+2);};
const handler=name=>{const a=html.indexOf('window.'+name+'=function(');assert(a>=0,name);return html.slice(a,html.indexOf('\n};',a)+3);};
const history=html.slice(html.indexOf('function approvalHistoryIdentity(){'),html.indexOf('function financeReadSourceSnapshot('));
const flush=async()=>{for(let n=0;n<3;n++)await new Promise(r=>setImmediate(r));};
const plain=x=>JSON.parse(JSON.stringify(x));
let passed=0;
async function check(name,work){await work();passed++;console.log('PASS '+name);}
function fixture(){
 const elements=new Map(),node=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',value:'',attributes:{},setAttribute(k,v){this.attributes[k]=v;}});return elements.get(id);};
 const c={window:{},console:{warn(){},error(){}},AbortController,Promise,Date,Set,Map,Number,String,Math,Array,Object,JSON,Error,setTimeout,clearTimeout,
  S:{user:{id:'FICT',authUserId:'AUTH',role:'accountant'},page:'approvals',aT:'h',apprPage:1,apprQuery:''},REQS:[],BILLS:[],INVS:[],tenant:'T',env:'test',financeWorkspaceIdentityBlocked:false,financeAuthIdentityEpoch:0,CURRENT_PERMISSION_SNAPSHOT:{reports:'edit'},approvalHistorySearchTimer:null,
  APPROVAL_HISTORY_RUNTIME:{identity:'',status:'idle',items:[],total:0,allTotal:0,page:1,limit:50,query:'',error:'',updatedAt:'',promise:null,requestSeq:0},calls:[],opened:[],frames:[],measures:[],now:10};
 Object.assign(c,{DEFAULT_TENANT_ID:'T',currentTenantId:()=>c.tenant,activeDataEnvironment:()=>c.env,approvalFastBootstrapIdentity:()=>c.tenant+'|'+c.S.user?.authUserId,
  getSb:()=>({rpc(name,args){let resolve;const p=new Promise(r=>resolve=r),call={name,args,resolve,aborts:0};c.calls.push(call);return{abortSignal(signal){signal.addEventListener('abort',()=>call.aborts++);return this;},then(ok,bad){return p.then(ok,bad);}};}}),
  performance:{now:()=>c.now,measure:(name,options)=>c.measures.push({name,...options})},requestAnimationFrame:f=>c.frames.push(f),
  buildApprovals(){},updateApprovalTodoBadge(){},remoteReadIssueText:e=>e.message,recordRemoteReadIssue(){},el:node,
  escAttr:x=>String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;'),
  mapReq:x=>({...x,formPayload:x.form_payload}),mapBill:x=>({...x,batchId:x.batch_id}),mapInv:x=>({...x,batchId:x.batch_id}),
  document:{querySelectorAll:()=>[]},setTopSyncStatus(){},approvalItemAvailability:item=>{assert(item.historyTrusted&&!item.historySummary,'only full validated detail enters original read gate');return{ok:true};},
  invoiceGroupActionRow:r=>r,canActInvoice:()=>false,canActReceipt:()=>false,
  showApprD:r=>c.opened.push({kind:'req',raw:r}),showBillApprD:r=>c.opened.push({kind:'bill',raw:r,rows:c.billGroupRows(r)}),showInvApprD:r=>c.opened.push({kind:'inv',raw:r,rows:c.invoiceGroupRows(r)}),showReceiptTaskD:r=>c.opened.push({kind:'recv',raw:r,rows:c.invoiceGroupRows(r)}),
  invoiceBatchFallbackKey:i=>i.legacy||'',billCreatedBucket:b=>b.legacy||'',syncApprovalWaitTimer(){},approvalShortDate:x=>String(x||'—').slice(0,10),draftTime:x=>x,
  approvalTableHeaderHtml:()=>'<thead><tr><th>選取</th><th>簽核日期</th></tr></thead>',approvalPagerHtml:(total,page,pages)=>'<footer>'+[total,page,pages].join('/')+'</footer>'});
 vm.createContext(c);vm.runInContext([fn('withOperationTimeout'),history,fn('remoteRowKey'),fn('mergeRemoteRowsByKey'),fn('financeReadSourceSnapshot'),fn('invoiceGroupKey'),fn('invoiceGroupRows'),fn('billGroupKey'),fn('billGroupRows'),fn('openApprovalFullItem'),handler('openApprovalItem'),fn('renderApprovalHistorySummaries')].join('\n'),c);
 c.node=node;c.respond=async(n,data,error)=>{c.calls[n].resolve(error?{error}:{data});await flush();};
 return c;
}
function identity(c){return{auth_user_id:c.S.user.authUserId,finance_user_id:c.S.user.id,tenant_id:c.tenant,data_environment:c.env};}
function summary(c,{table='invoices',kind='inv',key='invoices:B',id='I1',amount=1250.5,count=2,attachments=true,total=1}={}){return{ok:true,mode:'summary',identity:identity(c),total,all_total:737,page:{limit:50,offset:0,has_more:false},items:total?[{history_key:key,kind,record_type:table,record_id:id,record_no:'20260915001',batch_id:'B',personally_acted:true,last_participated_at:'2026-09-15T01:00:00Z',summary:{type:'invoice',type_label:'開立發票',applicant:'虛構人',description:'日照自費',entity_id:'E',entity_name:'虛構單位',department_code:'D',department_name:'日間照顧課',amount,source_count:count,has_attachments:attachments,request_date:'2026-09-15'}}]:[]};}
function detail(c,{table='invoices',kind='inv',key='invoices:B',id='I1',ids=['I1','I2']}={}){return{ok:true,identity:identity(c),item:{history_key:key,kind,record_type:table,record_id:id,batch_id:'B',source_count:ids.length,participant_steps:[],source_rows:ids.map(id=>({id,tenant_id:c.tenant,data_environment:c.env,batch_id:'B',row_version:7,files:[{name:'完整憑證.pdf',storage_path:'fictional/proof'}],form_payload:{accountingLines:[{item:'日照',net:1250,tax:0,gross:1250,manualOverride:true}]}}))}};}
async function seed(c,opts){const p=c.loadApprovalHistoryPage();await flush();await c.respond(0,summary(c,opts));assert((await p).ok);c.renderApprovalHistorySummaries(c.APPROVAL_HISTORY_RUNTIME);}

function permissionRefreshFixture(){
 const c=fixture(),baseClient=c.getSb();
 Object.assign(c,{currentPermissionSnapshotReadSeq:0,permissionReads:[],timers:[],
  membershipRuntimeArray:x=>Array.isArray(x)?x:[],uniqueRemoteStrings:x=>[...new Set(x.filter(Boolean))],normalizedRoleKey:u=>u.role,
  isRpcMissing:e=>e&&e.code==='PGRST202',isTransientRemoteReadError:e=>e&&e.code==='57014',applyRolePermissions(){},canAccessPage:()=>true,recordOpsEvent(){},friendlyErrorMessage:e=>e.message,
  setApprovalTabVisual(){},canReviseAccountingDetails:()=>false,currentRoleKey:()=>c.S.user.role,
  setTimeout(callback,ms){const timer={callback,ms,active:true};c.timers.push(timer);return timer;},clearTimeout(timer){if(timer)timer.active=false;},
  getSb:()=>({rpc(name,args){if(name!=='membership_current_permission_snapshot')return baseClient.rpc(name,args);return new Promise(resolve=>c.permissionReads.push({resolve}));}})
 });
 vm.runInContext([fn('currentPermissionSnapshotReadIdentity'),fn('captureApprovalHistoryPermissionRefreshIntent'),fn('resumeApprovalHistoryAfterPermissionRefresh'),fn('applyRemotePermissionSnapshotResult'),'async '+fn('refreshCurrentPermissionSnapshotRuntime'),fn('buildApprovals'),handler('apprSearch')].join('\n'),c);
 c.permissionPayload=(tag='read')=>({data:{membership_user_id:'FICT-MEMBERSHIP',primary_role_code:'accountant',role_codes:['accountant'],permissions:[{permission_key:'finance.request.view.all',tag}]}});
 c.respondPermission=async(index,result)=>{c.permissionReads[index].resolve(result||c.permissionPayload());await flush();};
 c.fireDebounce=async()=>{const timer=c.timers.filter(t=>t.active&&t.ms<=250).at(-1);assert(timer,'real debounce exists');timer.active=false;timer.callback();await flush();};
 return c;
}

(async()=>{
 await check('summaries preserve all authoritative cache bytes and render counts/decimal amounts',async()=>{const c=fixture();c.REQS=[{id:'R',files:['a'],formPayload:{manualOverride:true}}];c.INVS=[{id:'OLD',steps:[1],rowVersion:11}];const before=JSON.stringify([c.REQS,c.BILLS,c.INVS]);await seed(c);assert.equal(JSON.stringify([c.REQS,c.BILLS,c.INVS]),before);assert(!('raw' in c.APPROVAL_HISTORY_RUNTIME.items[0]));assert.match(c.node('appr-sub').textContent,/全部曾參與 737 組/);assert.match(c.node('appr-list').innerHTML,/1,250\.5/);assert.match(c.node('appr-list').innerHTML,/data-history-open/);});
 await check('a true zero and unknown attachment state are not forged as missing data',async()=>{const c=fixture();await seed(c,{amount:0,attachments:null});assert.match(c.node('appr-list').innerHTML,/NT\$0/);assert(!c.node('appr-list').innerHTML.includes('附有憑證'));});
 await check('summary display is escaped and never treats description as markup',async()=>{const c=fixture(),p=c.loadApprovalHistoryPage();await flush();const x=summary(c);x.items[0].summary.description='<img src=x onerror=alert(1)>';await c.respond(0,x);assert((await p).ok);c.renderApprovalHistorySummaries(c.APPROVAL_HISTORY_RUNTIME);assert(!c.node('appr-list').innerHTML.includes('<img'));assert(c.node('appr-list').innerHTML.includes('&lt;img'));});
 await check('full source rows accidentally returned as summary are rejected before caching',async()=>{const c=fixture(),p=c.loadApprovalHistoryPage();await flush();const x=summary(c);x.items[0].source_rows=detail(c).item.source_rows;await c.respond(0,x);assert(!(await p).ok);assert.equal(c.INVS.length,0);});
 await check('opening summary calls fresh detail once; no modal/actions before success',async()=>{const c=fixture();await seed(c);const p=c.window.openApprovalItem('invoices:B'),p2=c.window.openApprovalItem('invoices:B');await flush();assert.equal(p,p2);assert.equal(c.calls.length,2);assert.equal(c.calls[1].name,'finance_approval_history_detail_v1');assert.deepEqual(plain(c.calls[1].args),{p_history_key:'invoices:B',p_data_environment:'test'});assert.equal(c.opened.length,0);assert.equal(c.INVS.length,0);await c.respond(1,detail(c));assert((await p).ok);assert.equal(c.opened.length,1);assert.equal(c.opened[0].rows.length,2);assert.equal(c.INVS[0].row_version,7);assert(c.INVS[0].formPayload===undefined);assert.equal(c.INVS[0].form_payload.accountingLines[0].manualOverride,true);assert.equal(c.INVS[0].files[0].name,'完整憑證.pdf');});
 await check('fresh exact group excludes an old cached sibling without deleting unrelated cache',async()=>{const c=fixture();c.INVS=[{id:'I3',batchId:'B',form_payload:{original:true}},{id:'OTHER',batchId:'OTHER'}];await seed(c);const p=c.openApprovalHistoryItem('invoices:B');await flush();await c.respond(1,detail(c));assert((await p).ok);assert.deepEqual(plain(c.opened[0].rows.map(r=>r.id)),['I1','I2']);assert.equal(c.INVS.length,4);assert(c.INVS.some(r=>r.id==='I3'));});
 await check('exact fresh membership may legitimately grow since the summary was read',async()=>{const c=fixture();await seed(c);const p=c.openApprovalHistoryItem('invoices:B');await flush();await c.respond(1,detail(c,{ids:['I1','I2','I3']}));assert((await p).ok);assert.equal(c.opened[0].rows.length,3);});
 for(const table of ['expense_requests','bills'])await check(table+' follows its existing detail dispatcher with full fields',async()=>{const c=fixture(),kind=table==='bills'?'bill':'req',key=table+':B';await seed(c,{table,kind,key});const p=c.openApprovalHistoryItem(key);await flush();await c.respond(1,detail(c,{table,kind,key}));assert((await p).ok);assert.equal(c.opened[0].kind,kind);assert.equal((table==='bills'?c.BILLS:c.REQS).length,2);});
 for(const bad of ['truncated','duplicate','wrong-auth','wrong-tenant','wrong-env','wrong-key','wrong-table','missing-steps','missing-count','wrong-kind'])await check('detail rejects '+bad+' atomically with retry available',async()=>{const c=fixture();await seed(c);const before=JSON.stringify([c.REQS,c.BILLS,c.INVS]),p=c.openApprovalHistoryItem('invoices:B');await flush();const x=detail(c);if(bad==='truncated')x.item.source_rows.pop();if(bad==='duplicate')x.item.source_rows[1]=x.item.source_rows[0];if(bad==='wrong-auth')x.identity.auth_user_id='OTHER';if(bad==='wrong-tenant')x.item.source_rows[0].tenant_id='OTHER';if(bad==='wrong-env')x.item.source_rows[0].data_environment='production';if(bad==='wrong-key')x.item.history_key='invoices:OTHER';if(bad==='wrong-table')x.item.record_type='bills';if(bad==='missing-steps')delete x.item.participant_steps;if(bad==='missing-count')delete x.item.source_count;if(bad==='wrong-kind')x.item.kind='req';await c.respond(1,x);assert(!(await p).ok);assert.equal(c.opened.length,0);assert.equal(JSON.stringify([c.REQS,c.BILLS,c.INVS]),before);assert.equal(c.APPROVAL_HISTORY_DETAIL_RUNTIME.status,'error');assert.equal(c.APPROVAL_HISTORY_DETAIL_RUNTIME.promise,null);});
 for(const change of ['auth','user','tenant','env','role','permissions','lock','epoch','query','page','tab','navigation'])await check('late detail cannot cache or open after '+change+' changes',async()=>{const c=fixture();await seed(c);const p=c.openApprovalHistoryItem('invoices:B');await flush();const x=detail(c);if(change==='auth')c.S.user.authUserId='OTHER';if(change==='user')c.S.user.id='OTHER';if(change==='tenant')c.tenant='OTHER';if(change==='env')c.env='production';if(change==='role')c.S.user.role='employee';if(change==='permissions')c.CURRENT_PERMISSION_SNAPSHOT={reports:'none'};if(change==='lock')c.financeWorkspaceIdentityBlocked=true;if(change==='epoch')c.financeAuthIdentityEpoch++;if(change==='query')c.APPROVAL_HISTORY_RUNTIME.query='other';if(change==='page')c.APPROVAL_HISTORY_RUNTIME.page=2;if(change==='tab')c.S.aT='p';if(change==='navigation')c.S.page='dashboard';await c.respond(1,x);assert((await p).stale);assert.equal(c.INVS.length,0);assert.equal(c.opened.length,0);});
 await check('mapping failure midway through a full group cannot partly change any cache',async()=>{const c=fixture();await seed(c);let n=0;c.mapInv=r=>{if(++n===2)throw Error('malformed');return r;};const p=c.openApprovalHistoryItem('invoices:B');await flush();await c.respond(1,detail(c));assert(!(await p).ok);assert.equal(c.INVS.length,0);assert.equal(c.opened.length,0);});
 await check('a confirmed local update during the detail read is preserved and requires retry',async()=>{const c=fixture();c.INVS=[{id:'I1',row_version:6}];await seed(c);const p=c.openApprovalHistoryItem('invoices:B');await flush();c.INVS[0].row_version=8;await c.respond(1,detail(c));assert(!(await p).ok);assert.equal(c.INVS[0].row_version,8);assert.equal(c.opened.length,0);});
 await check('access denial does not fall back to old full-history RPC or cached data',async()=>{const c=fixture();await seed(c);const p=c.openApprovalHistoryItem('invoices:B');await flush();await c.respond(1,null,{code:'42501',message:'not authorized'});assert(!(await p).ok);assert.equal(c.calls.length,2);assert.equal(c.opened.length,0);assert.equal(c.APPROVAL_HISTORY_RUNTIME.items.length,1);const retry=c.openApprovalHistoryItem('invoices:B');await flush();await c.respond(2,detail(c));assert((await retry).ok);});
 await check('same-person token refresh and summary reload preserve the already-open exact modal group',async()=>{const c=fixture();c.INVS=[{id:'STALE',batchId:'B'}];await seed(c);const p=c.openApprovalHistoryItem('invoices:B');await flush();await c.respond(1,detail(c));assert((await p).ok);c.financeAuthIdentityEpoch++;const reload=c.loadApprovalHistoryPage({force:true});await flush();await c.respond(2,summary(c));assert((await reload).ok);assert.deepEqual(plain(c.invoiceGroupRows(c.INVS.find(r=>r.id==='I1')).map(r=>r.id)),['I1','I2']);});
 await check('an open group never falls back to global siblings after role/identity revocation',async()=>{const c=fixture();c.INVS=[{id:'STALE',batchId:'B'}];await seed(c);const p=c.openApprovalHistoryItem('invoices:B');await flush();await c.respond(1,detail(c));assert((await p).ok);c.S.user.role='employee';assert.throws(()=>c.invoiceGroupRows(c.INVS.find(r=>r.id==='I1')),/登入或權限/);});
 await check('a legacy non-batch detail never absorbs cached fallback-group members',async()=>{const c=fixture();c.INVS=[{id:'LEGACY-SIBLING',legacy:'shared',batchId:''}];await seed(c,{count:1});c.mapInv=x=>({...x,batchId:'',legacy:'shared'});const p=c.openApprovalHistoryItem('invoices:B');await flush();await c.respond(1,detail(c,{ids:['I1']}));assert((await p).ok);assert.deepEqual(plain(c.opened[0].rows.map(r=>r.id)),['I1']);});
 await check('paint timing only measures the current visible result after two animation frames',async()=>{const c=fixture();await seed(c);c.frames=[];c.now=20;c.approvalHistoryMarkPaint(c.APPROVAL_HISTORY_RUNTIME);assert.equal(c.measures.length,0);c.frames.shift()();assert.equal(c.measures.length,0);c.now=30;c.frames.shift()();assert.equal(c.measures.length,1);assert.equal(c.measures[0].name,'finance.approvalHistory.inputToPaint');assert.equal(c.measures[0].detail.inputToPaintMs,20);assert(!JSON.stringify(c.measures).includes('日照'));});
 await check('obsolete frame callbacks never claim the new query was painted',async()=>{const c=fixture();await seed(c);c.frames=[];c.approvalHistoryMarkPaint(c.APPROVAL_HISTORY_RUNTIME);c.frames.shift()();c.APPROVAL_HISTORY_RUNTIME.requestSeq++;c.frames.shift()();assert.equal(c.measures.length,0);});
 await check('direct or queued history load cannot start while the history page is hidden',async()=>{const c=fixture();c.S.aT='p';assert((await c.loadApprovalHistoryPage()).skipped);assert.equal(c.calls.length,0);c.S.aT='h';const pending=c.loadApprovalHistoryPage();c.S.page='dashboard';await flush();assert((await pending).stale);assert.equal(c.calls.length,0);assert.equal(c.APPROVAL_HISTORY_RUNTIME.status,'idle');});
 await check('leaving during a read releases loading so returning can read again',async()=>{const c=fixture(),old=c.loadApprovalHistoryPage();await flush();c.S.page='dashboard';await c.respond(0,summary(c));assert((await old).stale);assert.equal(c.APPROVAL_HISTORY_RUNTIME.status,'idle');c.S.page='approvals';const retry=c.ensureApprovalHistoryCurrent();await flush();await c.respond(1,summary(c));assert((await retry).ok);assert.equal(c.INVS.length,0);});
 await check('real buildApprovals does not prefetch history from a non-history tab',async()=>{const c=fixture();Object.assign(c,{setApprovalTabVisual(){},canReviseAccountingDetails:()=>false,currentRoleKey:()=> 'employee',loadDrafts(){},expenseRevisionRecoveryHtml:()=>'',approvalFastShouldHoldSkeleton:()=>false,approvalAllItems:()=>[],approvalPendingCandidateItems:()=>[],approvalItemIsCashierTask:()=>false,approvalItemIsMine:()=>false,approvalRejectedItems:()=>[],RL:{employee:'員工'},approvalFastCurrentCounts:()=>null,applyApprovalBootstrapSnapshot(){},approvalTodoBadgeApplyOptions:x=>x,draftCountForDisplay:()=>0,approvalDataLoadWarningHtml:()=>'',approvalManagerSummaryHtml:()=>'',approvalBulkBarHtml:()=>'',approvalActionableItems:x=>x,renderApprList(){}});vm.runInContext(fn('buildApprovals'),c);c.S.aT='p';c.buildApprovals();await flush();assert.equal(c.calls.length,0);assert.equal(c.APPROVAL_HISTORY_RUNTIME.status,'idle');});
 await check('real history renderer does not wait for broad bootstrap or scan global lists',async()=>{const c=fixture();await seed(c);Object.assign(c,{setApprovalTabVisual(){},canReviseAccountingDetails:()=>false,currentRoleKey:()=> 'employee',loadDrafts(){throw Error('draft scan forbidden');},approvalFastShouldHoldSkeleton(){throw Error('broad bootstrap forbidden');},approvalAllItems(){throw Error('global scan forbidden');}});vm.runInContext(fn('buildApprovals'),c);c.buildApprovals();assert.match(c.node('appr-list').innerHTML,/日照自費/);assert.equal(c.calls.length,1);});
 await check('deferred permission refresh resumes a pending real history RPC and paints only its fresh response',async()=>{
  const c=permissionRefreshFixture();c.S.apprQuery='自費';c.now=100;const old=c.loadApprovalHistoryPage();await flush();
  const started=c.APPROVAL_HISTORY_RUNTIME.timing.startedAt;c.now=500;const refresh=c.refreshCurrentPermissionSnapshotRuntime('load_remote_data_deferred');await c.respondPermission(0);assert.equal(await refresh,true);assert.equal(c.calls.length,2);assert.equal(c.calls[1].args.p_search,'自費');assert.equal(c.APPROVAL_HISTORY_RUNTIME.timing.startedAt,started);
  await c.respond(0,summary(c));assert((await old).stale);assert.equal(c.node('appr-list').attributes['data-history-status'],'loading');assert(c.APPROVAL_HISTORY_RUNTIME.promise,'old finally must not clear replacement');
  await c.respond(1,summary(c));assert.equal(c.node('appr-list').attributes['data-history-status'],'ready');assert.match(c.node('appr-list').innerHTML,/data-history-key/);c.now=700;while(c.frames.length)c.frames.shift()();assert.equal(c.measures.at(-1).detail.inputToPaintMs,600);assert.equal(c.calls.length,2);
 });
 await check('permission refresh reads the latest pending input and retains its remaining debounce interval',async()=>{
  const c=permissionRefreshFixture();c.S.apprQuery='舊查詢';const refresh=c.refreshCurrentPermissionSnapshotRuntime('load_remote_data_deferred');c.now=100;c.window.apprSearch('最新自費',{isComposing:false});c.now=200;
  await c.respondPermission(0);await refresh;assert.equal(c.calls.length,0);assert.equal(c.S.apprQuery,'最新自費');assert.equal(c.timers.filter(t=>t.active&&t.ms<=250).at(-1).ms,150);assert.equal(c.APPROVAL_HISTORY_RUNTIME.timing.startedAt,100);
  await c.fireDebounce();assert.equal(c.calls.length,1);assert.equal(c.calls[0].args.p_search,'最新自費');await c.respond(0,summary(c));assert.equal(c.node('appr-list').attributes['data-history-status'],'ready');
 });
 await check('permission refresh never dispatches an unfinished IME composition',async()=>{
  const c=permissionRefreshFixture();c.now=100;c.window.apprSearch('日',{isComposing:true});const refresh=c.refreshCurrentPermissionSnapshotRuntime('load_remote_data_deferred');c.now=170;await c.respondPermission(0);await refresh;
  assert.equal(c.calls.length,0);assert.equal(c.APPROVAL_HISTORY_RUNTIME.searchComposing,true);assert.equal(c.timers.filter(t=>t.active&&t.ms<=250).length,0);
  c.now=250;c.window.apprSearch('日照',{isComposing:false});await c.fireDebounce();assert.equal(c.calls.length,1);assert.equal(c.calls[0].args.p_search,'日照');await c.respond(0,summary(c));
 });
 await check('unchanged permission snapshot does not cancel or duplicate an in-flight history read',async()=>{
  const c=permissionRefreshFixture(),payload=c.permissionPayload();c.applyRemotePermissionSnapshotResult(payload,true,[]);c.S.apprQuery='日照';const history=c.loadApprovalHistoryPage();await flush();const current=c.APPROVAL_HISTORY_RUNTIME,refresh=c.refreshCurrentPermissionSnapshotRuntime('same');await c.respondPermission(0,payload);await refresh;
  assert.equal(c.calls.length,1);assert.equal(c.APPROVAL_HISTORY_RUNTIME,current);assert.equal(c.calls[0].aborts,0);await c.respond(0,summary(c));assert((await history).ok);
 });
 await check('a completed history query revalidates with a fresh permission-refresh clock',async()=>{
  const c=permissionRefreshFixture();c.S.apprQuery='日照';c.now=100;const first=c.loadApprovalHistoryPage();await flush();await c.respond(0,summary(c));assert((await first).ok);c.now=200;while(c.frames.length)c.frames.shift()();assert.equal(c.APPROVAL_HISTORY_RUNTIME.timing.measured,true);
  c.now=30200;const refresh=c.refreshCurrentPermissionSnapshotRuntime('late-background');await c.respondPermission(0);await refresh;assert.equal(c.APPROVAL_HISTORY_RUNTIME.timing.startedAt,30200);assert.equal(c.APPROVAL_HISTORY_RUNTIME.timing.trigger,'permission-refresh');await c.respond(1,summary(c));c.now=30300;while(c.frames.length)c.frames.shift()();assert.equal(c.measures.at(-1).detail.inputToPaintMs,100);
 });
 await check('role changes before an equivalent permission response still resume the raw old history intent',async()=>{
  const c=permissionRefreshFixture(),payload=c.permissionPayload();c.applyRemotePermissionSnapshotResult(payload,true,[]);c.S.apprQuery='自費';const old=c.loadApprovalHistoryPage();await flush();const refresh=c.refreshCurrentPermissionSnapshotRuntime('org-role-change');c.S.user.role='employee';await c.respondPermission(0,payload);await refresh;assert.equal(c.calls.length,2);assert.equal(c.calls[1].args.p_search,'自費');await c.respond(0,summary(c));assert((await old).stale);await c.respond(1,summary(c));assert.equal(c.node('appr-list').attributes['data-history-status'],'ready');
 });
 await check('permission refresh preserves the current history page and query',async()=>{
  const c=permissionRefreshFixture();c.S.apprQuery='日照';c.S.apprPage=2;const old=c.loadApprovalHistoryPage();await flush();const refresh=c.refreshCurrentPermissionSnapshotRuntime('page-two');await c.respondPermission(0);await refresh;assert.equal(c.calls.length,2);assert.equal(c.calls[1].args.p_offset,50);assert.equal(c.S.apprPage,2);
  const payload=summary(c);payload.total=51;payload.page={limit:50,offset:50,has_more:false};await c.respond(0,payload);assert((await old).stale);await c.respond(1,payload);assert.equal(c.APPROVAL_HISTORY_RUNTIME.status,'ready');assert.equal(c.APPROVAL_HISTORY_RUNTIME.page,2);
 });
 for(const change of ['auth','user','tenant','env','lock'])await check('late permission response cannot alter another scope after '+change,async()=>{
  const c=permissionRefreshFixture(),before=JSON.stringify(c.CURRENT_PERMISSION_SNAPSHOT);const refresh=c.refreshCurrentPermissionSnapshotRuntime('late');
  if(change==='auth')c.S.user.authUserId='OTHER';if(change==='user')c.S.user.id='OTHER';if(change==='tenant')c.tenant='OTHER';if(change==='env')c.env='production';if(change==='lock')c.financeWorkspaceIdentityBlocked=true;
  await c.respondPermission(0);assert.equal(await refresh,false);assert.equal(JSON.stringify(c.CURRENT_PERMISSION_SNAPSHOT),before);assert.equal(c.calls.length,0);
 });
 await check('an older concurrent permission read cannot replace newer grants or restart history',async()=>{
  const c=permissionRefreshFixture();c.S.page='settings';c.renderMembershipRoleControl=()=>{};c.renderSettingPermissions=()=>{};const old=c.refreshCurrentPermissionSnapshotRuntime('old'),newer=c.refreshCurrentPermissionSnapshotRuntime('new');await c.respondPermission(1,c.permissionPayload('new'));assert.equal(await newer,true);const current=JSON.stringify(c.CURRENT_PERMISSION_SNAPSHOT);await c.respondPermission(0,c.permissionPayload('old'));assert.equal(await old,false);assert.equal(JSON.stringify(c.CURRENT_PERMISSION_SNAPSHOT),current);assert.equal(c.calls.length,0);
 });
 await check('lost page permission removes old rows and does not resume a denied history read',async()=>{
  const c=permissionRefreshFixture();c.S.apprQuery='日照';const old=c.loadApprovalHistoryPage();await flush();c.canAccessPage=()=>false;const refresh=c.refreshCurrentPermissionSnapshotRuntime('revoked');await c.respondPermission(0);await refresh;assert.equal(c.calls.length,1);assert.equal(c.APPROVAL_HISTORY_RUNTIME.status,'error');assert.equal(c.APPROVAL_HISTORY_RUNTIME.items.length,0);assert.equal(c.node('appr-list').attributes['data-history-status'],'error');await c.respond(0,summary(c));assert((await old).stale);
 });
 await check('hidden history stays quiet after permission refresh',async()=>{
  const c=permissionRefreshFixture();c.S.aT='p';const refresh=c.refreshCurrentPermissionSnapshotRuntime('hidden');await c.respondPermission(0);assert.equal(await refresh,true);assert.equal(c.calls.length,0);
 });
 console.log('History summary frontend: '+passed+' checks passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
