'use strict';
// Local actual DOM + actual doConfirmVoucher and recovery helpers. Only transport,
// authority fixture and unrelated whole-app refresh are replaced. No product hook.
// Also exercises the original applicant-revision result confirmation after unknown.
// Usage: node scripts/check_expense_posting_browser.cjs /tmp/finance-posting-ui-evidence
// Requires agent-browser on PATH or AGENT_BROWSER_BIN. SQL is tested separately.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{execFile}=require('node:child_process'),{promisify}=require('node:util');
const run=promisify(execFile),root=path.resolve(__dirname,'..'),out=path.resolve(process.argv[2]||'/tmp/finance-employee-browserqa-evidence-20260912/posting'),session='expense-posting-'+process.pid,bin=process.env.AGENT_BROWSER_BIN||'agent-browser';
assert.ok(out!==root&&!out.startsWith(root+path.sep),'Browser evidence must be outside the source worktree');
const {applyBuildEnvironment}=require('./finance_build_environment');const source=fs.readFileSync(path.join(root,'index.html'),'utf8'),sourceHash=crypto.createHash('sha256').update(source).digest('hex');
let html=applyBuildEnvironment(source,{target:'local',supabaseUrl:'',supabaseAnonKey:''}),anchor='bootAuthGate();\n\n})();';assert.ok(html.includes(anchor));
html=html.replace(anchor,'window.__postingBrowser={run:async function(code){return await eval(code)}};\n'+anchor).replace(/<script\b[^>]*src=["']https?:[^>]*><\/script>/gi,'').replace('<head>','<head><meta http-equiv="Content-Security-Policy" content="connect-src \'self\'; form-action \'none\'; img-src \'self\' data: blob:">');
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(p!==root&&!p.startsWith(root+'/')){res.writeHead(403);return res.end();}if(p===root||p===path.join(root,'index.html')){res.setHeader('content-type','text/html; charset=utf-8');return res.end(html);}if(!fs.existsSync(p)||!fs.statSync(p).isFile()){res.writeHead(404);return res.end();}res.setHeader('content-type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.png')?'image/png':'application/octet-stream');res.end(fs.readFileSync(p));});
const b=async(...args)=>(await run(bin,['--session',session,...args],{maxBuffer:8e6,timeout:45000})).stdout;
async function scope(code){let v=JSON.parse(await b('eval','--base64',Buffer.from('(async()=>JSON.stringify(await window.__postingBrowser.run('+JSON.stringify(code)+')))()').toString('base64')));return typeof v==='string'?JSON.parse(v):v;}
const evidence={sourceHash,scope:'Local actual UI, fictional authorized accountant/transport; no real login, tokens or production API; DB idempotency verified in separate PGlite suite',screens:[],checks:[],layoutFailures:[]};
function check(name,value){assert.ok(value,name);evidence.checks.push(name);console.log('PASS '+name);}
const fixture=`(function(){
window.__postingAlerts=[];window.alert=function(m){window.__postingAlerts.push(String(m));};window.fetch=function(){throw Error('Offline fixture forbids network')};
USERS=[{id:'fixture-accountant',n:'許晴川',email:'accountant@example.invalid',role:'accountant',rL:'會計',eid:'F1',dc:'DAYCARE',active:true},{id:'fixture-employee',n:'林星河',email:'employee@example.invalid',role:'employee',rL:'組員',eid:'F1',dc:'DAYCARE',active:true}];ENTS=[{id:'F1',s:'星河照護',full:'星河照護股份有限公司',active:true}];DEPTS=[{c:'DAYCARE',n:'日間照顧課',eid:'F1',entityCodes:['F1'],newFormEntityCodes:['F1'],lv:4,active:true,isPostingUnit:true}];REQS=[];INVS=[];BILLS=[];NOTIFS=[];VOUCHERS=[];LEDGER=[];ORG_CHART=[];quickLogin('accountant');S.user.authUserId='10000000-0000-0000-0000-000000000001';S.user.tenantId=currentTenantId();
window.__originalTimeout=withOperationTimeout;withOperationTimeout=function(p,label,ms){return window.__originalTimeout(p,label,window.__postingMode==='never'&&/傳票入帳|確認傳票/.test(label)?60:ms)};
window.__postingCalls=[];window.__postingSerials=0;window.__postingUploads=0;window.__postingNotices=0;window.__postingReads=0;window.__postingMode='never';window.__postingRuns=[];window.__unrelatedReads=[];
// Keep the real canActRequest pending gate; simulate only its server-authorized step boundary.
canActStep=function(r,step){return !financeWorkspaceIdentityBlocked&&S.user.id==='fixture-accountant'&&r.status==='pending_voucher'&&step&&step.rk==='accountant_final'&&step.uid===S.user.id};
ensureOpenPostingPeriod=function(){return true};allowLegacyClientFlowRepair=function(){return false};
buildAll=function(){window.__wholeAppRefresh=(window.__wholeAppRefresh||0)+1};
nextVoucherNo=async function(){window.__postingSerials++;return 'V-FIXTURE-'+window.__postingSerials};
uploadApprovalFiles=async function(p){window.__postingUploads++;return p};
getSb=function(){return{rpc:function(name,args){if(name!=='finalize_expense_request')throw Error('Unexpected fixture RPC '+name);window.__postingCalls.push(JSON.parse(JSON.stringify(args)));if(window.__postingMode==='never')return new Promise(function(){});if(window.__postingMode==='deferred')return new Promise(function(resolve){window.__resolvePosting=resolve});return Promise.resolve({data:{ok:true,idempotent:true,voucher_id:args.p_voucher_id},error:null})},from:function(table){window.__unrelatedReads.push(table);var filters={};return{select:function(){return this},eq:function(k,v){filters[k]=v;return this},in:function(){return this},order:function(){return this},range:function(){return this},limit:function(){return this},maybeSingle:function(){return this},then:function(resolve,reject){var args=window.__postingCalls[window.__postingCalls.length-1],out={data:null,error:{code:'FIXTURE_SCOPE',message:'Offline fixture does not load unrelated source tables'}};if(window.__committedRow&&filters.request_id===args.p_request_id&&filters.tenant_id===currentTenantId()&&filters.data_environment===activeDataEnvironment()){if(table==='vouchers'&&filters.id===args.p_voucher_id)out={data:{id:args.p_voucher_id,no:args.p_voucher_no,request_id:args.p_request_id,entity_id:'F1',tenant_id:currentTenantId(),data_environment:activeDataEnvironment(),entries:args.p_voucher_entries,total:args.p_voucher_total,posted:true,posted_at:args.p_form_payload.ledgerPostedAt,voided_at:null},error:null};if(table==='application_accounting_lines')out={data:args.p_form_payload.accountingLines.map(function(line,i){return{id:line.id,request_id:args.p_request_id,request_no:window.__fixtureRaw.no,line_index:i+1,source:'detail',entity_id:'F1',tenant_id:currentTenantId(),data_environment:activeDataEnvironment(),department_code:line.departmentCode,net_amount:line.netAmount,tax_amount:line.taxAmount,gross_amount:line.grossAmount,debit_account:line.debitAccount,debit_account_name:line.debitAccountName,credit_account:line.creditAccount,credit_account_name:line.creditAccountName,payload:line}}),error:null};}return Promise.resolve(out).then(resolve,reject)}}}}};
reloadRequestsByIds=async function(ids){window.__postingReads++;var args=window.__postingCalls[window.__postingCalls.length-1];window.__committedRow=Object.assign({},window.__fixtureRaw,{status:'completed',step:args.p_step,steps:args.p_steps,voucher_id:args.p_voucher_id,ledger_posted_at:args.p_form_payload.ledgerPostedAt,posting_locked_at:args.p_form_payload.postingLockedAt,form_payload:args.p_form_payload});REQS=[mapReq(window.__committedRow)];return true};
dbInsertOnce=async function(table,row){if(table!=='notifications')throw Error('Unexpected write '+table);window.__postingNotices++;return {ok:true,duplicate:true}};deliverExternalNotification=function(){throw Error('No external delivery in fixture')};
var originalHandler=window.doConfirmVoucher;window.doConfirmVoucher=function(){var promise=originalHandler.apply(this,arguments);window.__postingRuns.push(promise);return promise};
window.__fixtureRaw={id:'fixture-posting',no:'UX-POST-001',tenant_id:currentTenantId(),data_environment:activeDataEnvironment(),entity_id:'F1',department_code:'DAYCARE',applicant_id:'fixture-employee',applicant:'林星河',type:'payment_request',type_label:'付款申請',amount:1050,debit_account:'6207',debit_account_name:'文具用品',credit_account:'2134',credit_account_name:'其他應付款',bank_fee_amount:0,cash_posted_at:'2026-09-12T02:00:00Z',status:'pending_voucher',step:3,ver:3,request_date:'2026-09-12',description:'離線測試：已撥款 1,050 元，等待會計最後入帳',files:[],steps:[{rk:'applicant_submit',uid:'fixture-employee',r:'申請人',a:'approved',at:'2026-09-12T01:00:00Z'},{rk:'applicant_confirm',uid:'fixture-employee',r:'申請人確認',a:'approved',at:'2026-09-12T03:00:00Z'},{rk:'accountant_final',uid:'fixture-accountant',r:'會計',a:'',status:'pending_voucher'}],form_payload:{accountingLines:[{id:'line-a',itemName:'文具用品',debitAccount:'6207',debitAccountName:'文具用品',creditAccount:'2134',creditAccountName:'其他應付款',netAmount:1050,taxAmount:0,grossAmount:1050,quantity:1,departmentCode:'DAYCARE',manualFields:[],accountingSource:'human'}]}};
REQS=[mapReq(window.__fixtureRaw)];openDetail('fixture-posting');S.demoLogin=false;
return{status:REQS[0].status,canAct:canActRequest(REQS[0]),page:S.page};})()`;
const revisionFixture=`(function(){
S.user=Object.assign({},USERS[1],{authUserId:'10000000-0000-0000-0000-000000000002',tenantId:currentTenantId()});S.demoLogin=false;
window.__revisionCalls=[];window.__revisionRuns=[];window.__revisionMode='never';window.__revisionReads=0;window.__revisionCleanup=0;
withOperationTimeout=function(p,label,ms){return window.__originalTimeout(p,label,window.__revisionMode==='never'&&label==='確認補件交易'?60:ms)};
canActStep=function(r,step){return !financeWorkspaceIdentityBlocked&&S.user.id==='fixture-employee'&&r.status==='pending_applicant_confirm'&&step&&step.rk==='applicant_revision'&&step.uid===S.user.id};
window.__revisionRaw=Object.assign({},window.__fixtureRaw,{id:'fixture-revision',no:'UX-REV-001',cash_posted_at:null,status:'pending_applicant_confirm',step:2,ver:1,updated_at:'2026-09-12T01:00:00Z',description:'離線測試：原補件內容與附件保留',files:[{path:'test/fixture-revision/original.pdf',n:'原始憑據.pdf'}],steps:[{rk:'applicant_submit',uid:'fixture-employee',a:'approved',files:[]},{rk:'applicant_revision',uid:'fixture-employee',a:'',files:[]},{rk:'accountant',uid:'fixture-accountant',a:'',status:'pending_accountant',files:[]}],form_payload:{requestPurpose:'離線補件範例'}});
REQS=[mapReq(window.__revisionRaw)];window.__revisionExpected=expenseApplicantRevisionExpectedSnapshot(REQS[0]);
window.__revisionPatch={amount:1050,description:'離線測試：已補齊用途說明',files:window.__revisionRaw.files,form_payload:{requestPurpose:'離線補件範例',requestNote:'本機測試補充說明'}};
getSb=function(){return{rpc:function(name,args){if(name!=='finance_expense_resubmit_applicant_revision')throw Error('Unexpected revision RPC '+name);window.__revisionCalls.push(JSON.parse(JSON.stringify(args)));if(window.__revisionMode==='never')return new Promise(function(){});return new Promise(function(resolve){window.__resolveRevision=resolve});},from:function(table){return{select:function(){return this},eq:function(){return this},limit:function(){return Promise.resolve({data:null,error:{code:'FIXTURE_READ_UNAVAILABLE',message:'Offline readback unavailable'}})}}}}};
reloadRequestsByIds=async function(ids){window.__revisionReads++;var args=window.__revisionCalls[window.__revisionCalls.length-1],steps=JSON.parse(JSON.stringify(window.__revisionRaw.steps));steps[1].a='approved';steps[1].files=args.p_step_files;steps[1].actionLog=[{action:'補件完成並重新送出',byId:S.user.id,comment:args.p_comment,at:'2026-09-12T04:00:00Z'}];window.__revisionCommitted=Object.assign({},window.__revisionRaw,args.p_form_patch,{status:'pending_accountant',step:3,ver:2,updated_at:'2026-09-12T04:00:00Z',steps:steps});REQS=[mapReq(window.__revisionCommitted)];return true};
cleanupUploadedSupabaseAttachments=function(){window.__revisionCleanup++;throw Error('Recovery cannot delete attachments')};
var original=window.reconcilePendingExpenseRevision;window.reconcilePendingExpenseRevision=function(){var promise=original.apply(this,arguments);window.__revisionRuns.push(promise);return promise};
openDetail('fixture-revision');hasSupabase=function(){return true};return{canAct:canActRequest(REQS[0]),expected:window.__revisionExpected};})()`;
(async()=>{
fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;await b('open',url);
const setup=await scope(fixture);check('actual accountant detail exposes initial posting action',setup.canAct&&setup.page==='detail');
// Formal branch is enabled only after all unrelated initial local rendering.
await scope(`(function(){hasSupabase=function(){return true};return true;})()`);
await b('set','viewport','1440','1000');await b('click','#detail-act button[onclick*="doConfirmVoucher"]');
await scope(`(async function(){await Promise.all(window.__postingRuns);return true;})()`);
const unknown=await scope(`({status:REQS[0].status,locked:requestPostingLocked(REQS[0]),calls:window.__postingCalls.length,serials:window.__postingSerials,uploads:window.__postingUploads,pending:!!loadExpensePostingPending('fixture-posting'),inFlight:!!POSTING_IN_FLIGHT['request-ledger:fixture-posting'],text:el('detail-act').innerText,alerts:window.__postingAlerts})`);evidence.unknown=unknown;
check('two missing responses stay unknown with original request uncommitted',unknown.calls===2&&unknown.status==='pending_voucher'&&!unknown.locked&&unknown.pending&&!unknown.inFlight);
check('unknown state leaves a real same-action retry entrance',/確認原入帳結果/.test(unknown.text)&&unknown.alerts.some(x=>x.includes('不能判定失敗或完成')));
for(const width of [1440,390]){await b('set','viewport',String(width),width===390?'844':'1000');await b('scrollintoview','#detail-act button[onclick*="doConfirmVoucher"]');const m=await scope(`(function(){var button=el('detail-act').querySelector('button[onclick*="doConfirmVoucher"]'),r=button.getBoundingClientRect();return{width:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth+1,button:{text:button.innerText,width:r.width,height:r.height,visible:r.top>=0&&r.bottom<=innerHeight},text:el('detail-hd').innerText}})()`);evidence.screens.push(m);if(m.overflow||!m.button.visible||m.button.height<44||m.button.width<44)evidence.layoutFailures.push({check:'recovery visible/touch/overflow',...m});else check('recovery button visible with 44px target and no overflow '+width,true);await b('screenshot',path.join(out,'posting-unknown-'+width+'.png'));}
const firstArgs=await scope(`window.__postingCalls[0]`);check('automatic retry reused exact frozen args',JSON.stringify(firstArgs)===JSON.stringify(await scope(`window.__postingCalls[1]`)));
await scope(`(function(){window.__postingMode='deferred';window.__postingRuns=[];return true;})()`);
// Dispatch two genuine DOM click events before the first promise resolves.
await scope(`(function(){var button=el('detail-act').querySelector('button[onclick*="doConfirmVoucher"]');button.click();button.click();return true;})()`);
const inflight=await scope(`({calls:window.__postingCalls.length,lock:!!POSTING_IN_FLIGHT['request-ledger:fixture-posting'],serials:window.__postingSerials,uploads:window.__postingUploads})`);
evidence.inflight=inflight;
check('double click sends one recovery RPC and allocates no second serial/upload',inflight.calls===3&&inflight.lock&&inflight.serials===unknown.serials&&inflight.uploads===unknown.uploads);
await scope(`(async function(){window.__resolvePosting({data:{ok:true,idempotent:true,voucher_id:window.__postingCalls[0].p_voucher_id},error:null});await Promise.all(window.__postingRuns);await ensurePostedAccountingView(REQS[0]);return true;})()`);
const done=await scope(`({status:REQS[0].status,locked:requestPostingLocked(REQS[0]),voucher:REQS[0].voucherId,header:el('detail-hd').innerText,actions:el('detail-act').innerText,pending:!!loadExpensePostingPending('fixture-posting'),calls:window.__postingCalls.length,readbacks:window.__postingReads,notices:window.__postingNotices,accountingView:postedAccountingView(REQS[0]).status,alerts:window.__postingAlerts})`);evidence.done=done;
check('authoritative fixture readback renders completed detail and voucher action',done.status==='completed'&&done.locked&&done.voucher===firstArgs.p_voucher_id&&/已完成/.test(done.header)&&done.actions.includes(done.voucher)&&!done.pending&&done.readbacks===1&&done.calls===3);
check('actual posted accounting view verifies source voucher and canonical lines',done.accountingView==='ready');
check('completion feedback says prior transaction confirmed without duplicate posting',done.alerts.some(x=>x.includes('已確認先前交易，未重複建立分錄')));
check('recovery sends the exact original request and voucher payload',JSON.stringify(firstArgs)===JSON.stringify(await scope(`window.__postingCalls[2]`)));
// Capture phone completion in its original viewport before the desktop resize.
for(const width of [390,1440]){await b('set','viewport',String(width),width===390?'844':'1000');await scope(`(function(){el('detail-hd').scrollIntoView({block:'start',inline:'nearest'});return true;})()`);check('completed detail has no document overflow '+width,!(await scope(`document.documentElement.scrollWidth>innerWidth+1`)));evidence.screens.push({completed:true,width,containers:await scope(`(function(){var n=el('detail-hd'),rows=[];while(n){var r=n.getBoundingClientRect();rows.push({tag:n.tagName,id:n.id,className:n.className,left:r.left,right:r.right,width:r.width,scrollLeft:n.scrollLeft,scrollWidth:n.scrollWidth,clientWidth:n.clientWidth});n=n.parentElement;}return rows;})()`)});await b('screenshot',path.join(out,'posting-completed-'+width+'.png'));}
await b('set','viewport','390','844');
await scope(`(function(){var host=document.createElement('div');host.id='fixture-preview-host';host.style.cssText='position:fixed;top:70px;left:10px;background:white;z-index:99999';el('detail-body').append(host);var bytes=Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg=='),function(c){return c.charCodeAt(0)});FinanceEmployeeFormUX.renderFiles(host,[new File([bytes],'身分隔離測試.png',{type:'image/png'})]);return true;})()`);
await b('click','#fixture-preview-host button');check('actual local attachment preview opens',await scope(`!!document.querySelector('.efux-preview[open]')`));
await scope(`(function(){setFinanceWorkspaceIdentityBlocked(true);showFinanceAuthRecovery({reason:'auth_identity_mismatch',message:'離線測試：身分已切換，附件預覽已關閉。'},'繼續使用');return true;})()`);
const lock=await scope(`({preview:!!document.querySelector('.efux-preview'),inert:el('main-wrap').inert,visibility:el('main-wrap').style.visibility,dialog:el('finance-auth-recovery').open})`);evidence.lock=lock;check('identity lock closes image preview and hides old document',!lock.preview&&lock.inert&&lock.visibility==='hidden'&&lock.dialog);
await b('screenshot',path.join(out,'identity-preview-closed-390.png'));
const postingErrors=(await b('errors')).trim();assert.equal(postingErrors,'');
// New page isolates the employee revision fixture from the accountant identity.
await b('open',url);await scope(fixture);const revisionSetup=await scope(revisionFixture);check('actual original employee revision guard accepts the fictional own request',revisionSetup.canAct);
const revisionUnknown=await scope(`(async function(){var result=await expenseApplicantRevisionRpc(REQS[0],'resubmit','已補充用途',window.__revisionPatch,[{path:'test/fixture-revision/addendum.pdf',n:'補件附件.pdf'}],window.__revisionExpected);openDetail('fixture-revision');return{unknown:result.unknown,calls:window.__revisionCalls.length,pending:loadExpenseRevisionPending(),canAct:canActRequest(REQS[0]),status:REQS[0].status};})()`);
evidence.revision={unknown:revisionUnknown,screens:[]};check('two missing revision responses preserve original payload and block a new mutation',revisionUnknown.unknown&&revisionUnknown.calls===2&&revisionUnknown.pending&&!revisionUnknown.canAct&&revisionUnknown.status==='pending_applicant_confirm');
for(const width of [1440,390]){await b('set','viewport',String(width),width===390?'844':'1000');await b('scrollintoview','#detail-act button[onclick*="reconcilePendingExpenseRevision"]');const m=await scope(`(function(){var button=el('detail-act').querySelector('button[onclick*="reconcilePendingExpenseRevision"]'),r=button.getBoundingClientRect();return{width:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth+1,button:{text:button.innerText,width:r.width,height:r.height,visible:r.top>=0&&r.bottom<=innerHeight}}})()`);evidence.revision.screens.push(m);if(m.overflow||!m.button.visible||m.button.height<44||m.button.width<44)evidence.layoutFailures.push({check:'revision recovery visible/touch/overflow',...m});else check('revision recovery visible with 44px target and no overflow '+width,true);await b('screenshot',path.join(out,'revision-unknown-'+width+'.png'));}
await scope(`(function(){window.__revisionMode='deferred';var button=el('detail-act').querySelector('button[onclick*="reconcilePendingExpenseRevision"]');button.click();button.click();return true;})()`);
const revisionInflight=await scope(`({calls:window.__revisionCalls.length,locked:!!POSTING_IN_FLIGHT['expense-revision:fixture-revision']})`);check('double click revision recovery sends one exact original operation',revisionInflight.calls===3&&revisionInflight.locked);
await scope(`(async function(){window.__resolveRevision({data:{ok:true,id:'fixture-revision',action:'resubmit',idempotent_replay:true,ver:2,status:'pending_accountant'},error:null});await Promise.all(window.__revisionRuns);return true;})()`);
const revisionDone=await scope(`({status:REQS[0].status,header:el('detail-hd').innerText,actions:el('detail-act').innerText,pending:!!loadExpenseRevisionPending(),calls:window.__revisionCalls,reads:window.__revisionReads,cleanups:window.__revisionCleanup,files:REQS[0].files,stepFiles:REQS[0].steps[1].files,alerts:window.__postingAlerts})`);evidence.revision.done=revisionDone;
check('revision recovery renders authoritative waiting-accountant state without deleting originals',revisionDone.status==='pending_accountant'&&/待會計/.test(revisionDone.header)&&!revisionDone.pending&&revisionDone.reads===1&&revisionDone.cleanups===0&&revisionDone.files[0].path==='test/fixture-revision/original.pdf'&&revisionDone.stepFiles[0].path==='test/fixture-revision/addendum.pdf');
check('revision recovery retains exact frozen key, version, patch and attachment references',revisionDone.calls.length===3&&revisionDone.calls.every(args=>JSON.stringify(args)===JSON.stringify(revisionUnknown.pending.rpcArgs)));
check('revision feedback confirms resubmission without claiming final approval',revisionDone.alerts.some(x=>x.includes('已確認完成補件並重新送出'))&&!revisionDone.alerts.some(x=>x.includes('已核准')));
await scope(`(function(){el('detail-hd').scrollIntoView({block:'start',inline:'start'});return true;})()`);await b('screenshot',path.join(out,'revision-recovered-390.png'));check('recovered revision no mobile overflow',!(await scope(`document.documentElement.scrollWidth>innerWidth+1`)));
const errors=(await b('errors')).trim();evidence.errors=errors;assert.equal(errors,'');check('on-disk source unchanged' ,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'index.html'))).digest('hex')===sourceHash);
fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify(evidence,null,2));assert.deepEqual(evidence.layoutFailures,[],'all visible recovery controls meet 44px and layout requirements');if(fs.existsSync(path.join(out,'failure.json')))fs.unlinkSync(path.join(out,'failure.json'));console.log('PASS actual posting recovery browser: '+out);
})().catch(e=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:e.message,evidence},null,2));console.error(e);process.exitCode=1;}).finally(async()=>{await b('close').catch(()=>{});server.close();});
