#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),engine=require('../assets/engines/tax-report-engine.js');
const source=fs.readFileSync(path.join(__dirname,'../assets/engines/reporting-workspace.js'),'utf8');
const marker='  global.FinanceReportingWorkspace=api;';assert.equal(source.split(marker).length,2);
const context={console,Map,Set,Intl,FormData:class {constructor(form){this.values=form.values||{};}forEach(fn){Object.entries(this.values).forEach(([k,v])=>fn(v,k));}},document:{getElementById:id=>elements[id]||null,addEventListener(){}},FinanceTaxReportEngine:engine};context.window=context;
// Expose private functions only in this in-memory test copy. No production hook.
vm.runInNewContext(source.replace(marker,"  global.__taxAdapterTest={taxScope,taxDocuments,taxWorkpaper,profileCopy,submitProfileForm};\n"+marker),context);
const clone=x=>JSON.parse(JSON.stringify(x)),elements={'rpt-ent':{value:'A'},'rpt-month':{value:'2026-08'},'finance-report-dialog':{dataset:{entity:'A',revision:'0'},close(){}}};
const profile={schemaVersion:1,accountingFramework:null,tax:{formType:'401',taxId:'12345675',legalName:'Fixture',taxRegistrationNo:'registration',responsiblePerson:'Reviewer',address:'address',filingMode:'individual',filingFrequency:'bimonthly',periods:{'2026-07-01/2026-08-31':{priorCarryforwardTax:0,refundLimitConfirmedTax:0}}},accountMappings:{},costCenters:[],budgets:[],allocations:[],eliminations:[],periodChecks:{},documents:{}};
let invoices=[],requests=[],saved=clone(profile),posted=[],lastSave=null,complete=true,tests=0;
const rt={tenant:()=> 'fixture',environment:()=> 'test',user:()=>({id:'accountant'}),role:()=> 'accountant',today:()=> '2026-09-10',invoices:()=>invoices,requests:()=>requests,postedAccountingLines:()=>posted,completeness:()=>({tables:{invoices:{complete},expense_requests:{complete}}}),state:()=>({page:'reports'}),rpc:async(name,args)=>{if(name==='finance_reporting_profile_save_v1'){lastSave=clone(args);saved=clone(args.p_profile);return{data:{ok:true,profile:saved,revision:1,canEdit:false,canEditWorkpaper:true}};}return {data:{ok:true,profile:clone(saved),revision:0,canEdit:false,canEditWorkpaper:true}};}};
context.FinanceReportingWorkspace.install(rt);const api=context.__taxAdapterTest;
async function load(p){saved=clone(p);await context.FinanceReportingWorkspace.loadProfile('A',true);}
async function test(name,fn){await fn();tests++;console.log('PASS '+name);}
function classification(type,id,extra={}){return {sourceType:type,sourceId:id,formatCode:type==='invoice'?'35':'25',taxClass:'taxable',deduction:'eligible',assetKind:'expense',sellerTaxId:'87654321',buyerTaxId:'12345675',number:'AA00000001',date:'2026-08-10',originalNetAmount:100,originalTaxAmount:5,grossAmount:105,evidenceReference:'fixture-original',classificationReason:'Verified original',...extra};}
(async()=>{
await load(profile);
await test('Bimonthly scope handles either month, invalid month never rolls into another year',()=>{assert.deepEqual(clone(api.taxScope({period:'2026-08'},profile)),{start:'2026-07-01',end:'2026-08-31'});assert.equal(api.taxScope({period:'2026-13'},profile),null);});
await test('A selected tax workpaper excludes complete original certificates from other periods',async()=>{invoices=[{id:'current',eid:'A',date:'2026-08-10',no:'AA00000001',amt:100,tax:5,total:105},{id:'old',eid:'A',date:'2026-05-01',no:'AA00000002',amt:200,tax:10,total:210}];let p=clone(profile);p.documents['invoice:current']=classification('invoice','current');p.documents['invoice:old']=classification('invoice','old',{date:'2026-05-01',originalNetAmount:200,originalTaxAmount:10,grossAmount:210});await load(p);let w=api.taxWorkpaper({eid:'A',period:'2026-08'});assert.equal(w.documents.length,1);assert.equal(w.summary.outputTax,5);assert.equal(w.status,'ready_for_review');});
await test('Explicit accountant-null original tax stays unknown instead of reverting to source tax',async()=>{let p=clone(saved);p.documents['invoice:current'].originalTaxAmount=null;await load(p);let w=api.taxWorkpaper({eid:'A',period:'2026-08'});assert.equal(w.documents[0].originalTaxAmount,null);assert.notEqual(w.status,'ready_for_review');});
await test('Voided invoice is never revived by a retained classification',async()=>{invoices[0].voidedAt='2026-09-01';let docs=api.taxDocuments({eid:'A'},saved);assert(!docs.sales.some(d=>d.sourceId==='current'));delete invoices[0].voidedAt;});
await test('An orphan classification remains unresolved rather than generating tax without source',async()=>{let p=clone(profile);p.documents['invoice:missing']=classification('invoice','missing');await load(p);let w=api.taxWorkpaper({eid:'A',period:'2026-08'});assert(w.checks.some(c=>c.code==='SOURCE_UNAVAILABLE'));assert.equal(w.documents.find(d=>d.sourceId==='missing').included,false);});
await test('Water original tax and verified book tax remain independent and use stable match',async()=>{invoices=[];requests=[{id:'water',eid:'A',amt:105,date:'2026-08-01',formPayload:{lazyRows:[{id:'raw-water',item:'水費',date:'2026-08-10',grossAmount:105,taxAmount:5}],accountingLines:[{description:'水費',grossAmount:105,taxAmount:5}]}}];posted=[{id:'line_1',description:'水費',grossAmount:105,taxAmount:0}];let p=clone(profile);p.documents['expense_request:water:raw-water']=classification('expense_request','water',{sourceLineId:'raw-water'});await load(p);let w=api.taxWorkpaper({eid:'A',period:'2026-08'});assert.equal(w.documents[0].originalTaxAmount,5);assert.equal(w.documents[0].bookTaxAmount,0);assert(w.checks.some(c=>c.code==='UTILITY_BOOK_TAX_RECONCILIATION'));});
await test('Ambiguous canonical rows never guess the book tax by position',()=>{posted=[{description:'水費',grossAmount:105,taxAmount:0},{description:'水費',grossAmount:105,taxAmount:5}];let docs=api.taxDocuments({eid:'A'},saved);assert.equal(docs.purchases[0].bookTaxAmount,null);});
await test('Missing posted source never substitutes preserved raw or stale form-payload tax',()=>{posted=null;let docs=api.taxDocuments({eid:'A'},saved);assert.equal(docs.purchases[0].bookTaxAmount,null);assert(api.taxWorkpaper({eid:'A',period:'2026-08'}).checks.some(c=>c.code==='UTILITY_BOOK_TAX_RECONCILIATION'));});
await test('Company-policy excluded utility retains original VAT yet claims zero',async()=>{let p=clone(saved);p.documents['expense_request:water:raw-water'].deduction='not_claimed_policy';await load(p);let w=api.taxWorkpaper({eid:'A',period:'2026-08'});assert.equal(w.summary.deductibleInputTax,0);assert.equal(w.summary.originalInputTax,5);assert.equal(w.status,'ready_for_review');});
await test('Incomplete source loader marks figures incomplete even if visible docs classify',()=>{complete=false;assert.notEqual(api.taxWorkpaper({eid:'A',period:'2026-08'}).status,'ready_for_review');complete=true;});
await test('profileCopy roundtrips saved schema exactly for accountant path diff',async()=>{let p=clone(profile);delete p.accountingFramework;await load(p);assert.deepEqual(clone(api.profileCopy('A')),p);});
await test('Real document submit sends only strict whitelist and preserves company configuration',async()=>{let p=clone(profile);await load(p);let before=clone(saved),v=classification('expense_request','water');const values={...v,reason:'Transcribed original',isReturn:'no',usage:'',assetKind:'expense',zeroRateExport:'',originalDocumentId:'',date:'2026-08-10'};await api.submitProfileForm({dataset:{rwForm:'document',document:'expense_request:water:raw-water'},values});assert.deepEqual(lastSave.p_profile.tax,before.tax);assert.deepEqual(lastSave.p_profile.accountMappings,before.accountMappings);assert.equal(lastSave.p_profile.documents['expense_request:water:raw-water'].originalTaxAmount,5);assert(!Object.prototype.hasOwnProperty.call(lastSave.p_profile.documents['expense_request:water:raw-water'],'bookTaxAmount'));});
await test('Tax adjustment form stays anchored to the opened period if main selector changes',async()=>{await load(profile);elements['finance-report-dialog'].dataset={entity:'A',revision:'0',period:'2026-08',taxPeriodStart:'2026-07-01',taxPeriodEnd:'2026-08-31'};elements['rpt-month'].value='2026-10';let vals={reason:'Reviewed fiscal period',priorCarryforwardTax:'0',foreignServicePayableTax:'0',specialTaxPayableTax:'0',annualAdjustmentPayableTax:'0',annualAdjustmentRefundTax:'0',refundLimitConfirmedTax:'0',nonDeductibleRatio:'20',yearEndAdjustmentRequired:'no',annualAdjustmentReviewed:'no',ratioExclusionsReviewed:'yes','annual:inputTax':'100','annual:article19ExcludedTax':'0','annual:exemptOnlyInputTax':'0','annual:commonInputTax':'100','annual:deductedInputTax':'80','annual:nonDeductibleRatio':'20'};await api.submitProfileForm({dataset:{rwForm:'tax-adjustments'},values:vals});assert.equal(lastSave.p_profile.tax.periods['2026-09-01/2026-10-31'],undefined);assert.equal(lastSave.p_profile.tax.periods['2026-07-01/2026-08-31'].annualTotals.nonDeductibleRatio,.2);assert.equal(lastSave.p_profile.tax.periods['2026-07-01/2026-08-31'].priorCarryforwardTax,0);});
console.log(JSON.stringify({ok:true,tests,productionHooksAdded:0}));
})().catch(e=>{console.error(e);process.exitCode=1;});
