'use strict';
// Local source UI with fictional records and RPC-boundary fixtures only.
// No real Google accounts, production reads or writes are used by this test.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {applyBuildEnvironment}=require('./finance_build_environment');
const args=process.argv.slice(2),arg=(k,f)=>args.includes(k)?args[args.indexOf(k)+1]:f;
const root=path.resolve(arg('--root',path.join(__dirname,'..'))),output=path.resolve(arg('--output','/tmp/finance-report-workspace-browser-20260910'));
const baseline=args.includes('--before'),original=fs.readFileSync(path.join(root,'index.html'),'utf8');
const anchor='bootAuthGate();\n\n})();';assert.ok(original.includes(anchor));
let html=applyBuildEnvironment(original,{target:'local',supabaseUrl:'',supabaseAnonKey:''});
html=html.replace(anchor,'window.__reportTest={run:async function(code){return await eval(code);}};\n'+anchor).replace(/<script\b[^>]*src=["']https?:[^>]*><\/script>/gi,'');
html=html.replace('</head>','<script src="/fixture-xlsx.js"></script></head>');
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname==='/fixture-xlsx.js'){res.setHeader('content-type','application/javascript');return res.end(fs.readFileSync('/tmp/finance-report-xlsx-0.18.5.js'));}const file=path.resolve(root,'.'+url.pathname);if(file!==root&&!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}if(file===root||file===path.join(root,'index.html')){res.setHeader('content-type','text/html');return res.end(html);}if(!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}res.setHeader('content-type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(file));});
const ledger=[];function pair(id,date,dc,dr,cr,amount,description){ledger.push({id:id+'-dr',eid:'F1',dc,ac:dr,an:dr,dr:amount,cr:0,date,desc:description,ref:id,sourceId:id,sourceNo:id,voucherNo:id,dataEnv:'test'},{id:id+'-cr',eid:'F1',dc,ac:cr,an:cr,dr:0,cr:amount,date,desc:description,ref:id,sourceId:id,sourceNo:id,voucherNo:id,dataEnv:'test'});}
pair('opening','2026/08/01','ADMIN','1112','3111',1000,'期初');pair('aug-sale','2026/08/31','CARE','1123','4101',100,'八月服務');pair('sep-sale','2026/09/30','CARE','1123','4101',100,'九月服務');pair('sep-allowance','2026/09/30','CARE','4101','1123',20,'折讓');pair('sep-receipt','2026/09/30','CARE','1112','1123',40,'實際收款');pair('repair','2026/09/30','CARE','6204','1112',50,'設備維修費');pair('shared','2026/09/30','ADMIN','6202','1112',100.01,'共同費用');pair('bank-transfer','2026/09/30','ADMIN','111201','111202',100,'銀行互轉');
const profile={schemaVersion:1,accountingFramework:'eas',tax:{formType:'401',taxId:'12345675',legalName:'星河照護股份有限公司',taxRegistrationNo:'123456789',responsiblePerson:'林星河',address:'虛構測試地址',filingFrequency:'bimonthly',filingMode:'individual',periods:{}},accountMappings:{},costCenters:[{departmentCode:'ADMIN',kind:'shared',name:'行政中心'},{departmentCode:'CARE',kind:'profit',name:'照護服務'}],budgets:[],allocations:[{id:'fixture-allocation',name:'依人數分攤',sourceDepartmentCode:'ADMIN',accountCodes:['6202'],basis:'headcount',targets:[{departmentCode:'CARE',weight:0.5},{departmentCode:'HOME',weight:0.5}],status:'reviewed',effectiveFrom:'2026-09-01',effectiveTo:null,reviewedBy:'fixture-ceo',reviewedAt:'2026-09-01T00:00:00Z',reviewedRevision:1,reviewReason:'核對人數'}],eliminations:[],periodChecks:{},documents:{}};
const items=[{invoiceId:'inv-aug',invoiceNo:'FA00000001',entityId:'F1',departmentCode:'CARE',buyer:'林星河',invoiceDate:'2026-08-31',dueDate:null,originalAmount:100,recognizedAmount:100,allowanceAmount:0,arAllowanceAmount:0,receivedAmount:0,outstandingAmount:100,pendingReceiptAmount:0,balanceStatus:'unpaid',status:'unpaid',rowVersion:1,metadataVersion:0,agingBucket:'unknown',ownerName:'',refundPayable:0,refundedAmount:0},{invoiceId:'inv-sep',invoiceNo:'FA00000002',entityId:'F1',departmentCode:'CARE',buyer:'陳晴川',invoiceDate:'2026-09-01',dueDate:'2026-09-05',originalAmount:100,recognizedAmount:100,allowanceAmount:20,arAllowanceAmount:20,receivedAmount:40,outstandingAmount:40,pendingReceiptAmount:0,balanceStatus:'partial',status:'partial',rowVersion:2,metadataVersion:0,agingBucket:'d1',overdueDays:25,ownerName:'林星河',ownerId:'fixture-accountant',nextActionDate:'2026-10-01',refundPayable:0,refundedAmount:0}];
let browser;
(async()=>{fs.mkdirSync(output,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port+'/';const{chromium}=require('playwright');browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'chrome'});const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const blocked=[];await context.route('**/*',route=>{if(new URL(route.request().url()).origin===new URL(url).origin||/^(blob|data):/.test(route.request().url()))return route.continue();blocked.push(route.request().url());return route.abort();});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.dismiss());await page.goto(url);await page.waitForFunction(()=>window.__reportTest);const scope=code=>page.evaluate(code=>window.__reportTest.run(code),code);
await scope(`(async()=>{
 USERS=[{id:'fixture-ceo',n:'許晴川',email:'ceo@example.invalid',role:'ceo',rL:'執行長',eid:'F1',dc:'ADMIN',active:true},{id:'fixture-accountant',n:'林星河',email:'accountant@example.invalid',role:'accountant',rL:'會計',eid:'F1',dc:'ADMIN',active:true}];
 ENTS=[{id:'F1',n:'星河照護股份有限公司',full:'星河照護股份有限公司',s:'星河照護',active:true,color:'#286448'},{id:'F2',n:'晴川居護有限公司',full:'晴川居護有限公司',s:'晴川居護',active:true,color:'#5673a0'}];
 DEPTS=[{c:'ADMIN',n:'行政中心',eid:'F1',lv:2,active:true},{c:'CARE',n:'日間照顧',eid:'F1',lv:3,active:true},{c:'HOME',n:'居家服務',eid:'F1',lv:3,active:true}];
 ORG_CHART=[];REQS=[];INVS=[];BILLS=[];VOUCHERS=[];NOTIFS=[];quickLogin('ceo');
 LEDGER=${JSON.stringify(ledger)};INVS=${JSON.stringify(items)}.map(function(i){return mapInv({id:i.invoiceId,no:i.invoiceNo,entity_id:i.entityId,entity_name:'星河照護',department_code:i.departmentCode,buyer:i.buyer,amount:i.originalAmount,tax:0,total:i.originalAmount,invoice_date:i.invoiceDate,status:i.status,row_version:i.rowVersion,revenue_posted:true,approval_status:'completed',data_environment:'test',tenant_id:currentTenantId()});});
 todayIso=function(){return'2026-09-30';};todayMonth=function(){return'2026-09';};
 window.__rwWrites=[];window.__rwProfile=${JSON.stringify(profile)};window.__rwItems=${JSON.stringify(items)};window.__rwRevision=1;
 if(typeof statementDataCompleteness==='function')statementDataCompleteness=function(){return{complete:true,status:'complete',rowCount:LEDGER.length,tables:{ledger:{complete:true,status:'complete',rowCount:LEDGER.length},invoices:{complete:true,status:'complete',rowCount:INVS.length},expense_requests:{complete:true,status:'complete',rowCount:0}}};};
 hasSupabase=function(){return true;};ensureRemoteDashboardAggregate=function(){};
 getSb=function(){return{rpc:async function(name,args){
 if(name==='finance_reporting_tax_sources_v1'){var sources={};args.p_documents.forEach(function(d){var i=INVS.find(function(i){return i.id===d.sourceId;});if(d.sourceType!=='invoice'||!i)throw new Error('Unexpected tax source fixture');sources[d.key]={available:true,binding:{version:1,fingerprint:'a'.repeat(64)},snapshot:{sourceType:'invoice',sourceId:i.id,entityId:i.eid,revision:Number(i.rowVersion)||0,number:i.no||'',date:String(i.date||'').split('/').join('-').slice(0,10),netAmount:i.amt==null?null:Number(i.amt),taxAmount:i.tax==null?null:Number(i.tax),grossAmount:i.total==null?null:Number(i.total),description:i.desc||'',buyerTaxId:i.taxId||''}};});return{data:{entityId:args.p_entity_id,dataEnvironment:args.p_data_environment,sources:sources}};}
 if(name==='finance_reporting_profile_read_v1')return{data:{ok:true,profile:args.p_entity_id==='F1'?window.__rwProfile:{schemaVersion:1,tax:{},accountMappings:{},costCenters:[],budgets:[],allocations:[],eliminations:[],periodChecks:{},documents:{}},revision:window.__rwRevision,canEdit:true,canEditWorkpaper:true}};
 if(name==='finance_reporting_profile_save_v1'){window.__rwWrites.push({name,args});if(args.p_expected_revision!==window.__rwRevision)return{error:{message:'版本衝突'}};window.__rwProfile=args.p_profile;return{data:{ok:true,profile:args.p_profile,revision:++window.__rwRevision,canEdit:true,canEditWorkpaper:true}};}
 if(name==='finance_receivables_v1')return{data:{version:1,asOf:args.p_as_of,complete:true,totalCount:window.__rwItems.length,items:window.__rwItems,summary:{outstandingAmount:140,receivedAmount:40,allowanceAmount:20,overdueAmount:40,unrecognizedAmount:0,creditAmount:0,refundPayable:0},buckets:[],reconciliation:{bankVisible:true,bankScope:'company',unmatchedBankItems:[{id:'bank-fixture',date:'2026-09-30',description:'部分核銷款',amount:100,matchedAmount:40,remainingAmount:60}],unmatchedBankAmount:60}}};
 if(name==='finance_update_receivable_terms_v1'){window.__rwWrites.push({name,args});var item=window.__rwItems.find(function(x){return x.invoiceId===args.p_invoice_id;});Object.assign(item,args.p_patch,{metadataVersion:item.metadataVersion+1});return{data:{ok:true,invoiceId:item.invoiceId,metadataVersion:item.metadataVersion}};}
 return{data:null,error:{message:'Unexpected fixture RPC '+name}};
 }};};
 loadRemoteData=async function(){return true;};
 if(window.FinanceReportingWorkspace){await window.FinanceReportingWorkspace.loadProfile('F1',true);await window.FinanceReportingWorkspace.loadProfile('F2',true);}
 await nav('reports');refreshEntitySelectors();el('rpt-ent').value='F1';el('rpt-ent').dispatchEvent(new Event('change',{bubbles:true}));syncReportPeriodOptions('2026-09');el('rpt-month').value='2026-09';buildReports();
})()`);
if(!baseline)await page.waitForFunction(()=>window.FinanceReportingWorkspace.profileFor('F1'));
await page.evaluate(()=>{window.__capturedReports=[];const write=XLSX.writeFile;XLSX.writeFile=function(wb,name){window.__capturedReports.push({name,sheets:wb.SheetNames.map(name=>({name,rows:XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:null})}))});return write.apply(this,arguments);};});
const tableStyles=[];
let financialPdfChecks=null;
async function capture(name,width,selector){await page.setViewportSize({width,height:width<600?844:1000});await page.locator(selector).scrollIntoViewIfNeeded();await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const dimension=await page.evaluate(()=>({w:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(dimension.scroll<=width,'no page overflow '+name+': '+JSON.stringify(dimension));if(!baseline&&width<600){const tables=await page.locator(selector).evaluate(box=>Array.from(box.querySelectorAll('table.rw-table')).filter(t=>t.getBoundingClientRect().width>0).map(t=>{const wrap=t.parentElement,oldScroll=wrap.scrollLeft;wrap.scrollLeft=32;const moved=wrap.scrollLeft;wrap.scrollLeft=oldScroll;return{tableWidth:t.getBoundingClientRect().width,minWidth:parseFloat(getComputedStyle(t).minWidth),wrapperWidth:wrap.clientWidth,scrollWidth:wrap.scrollWidth,scrollMoved:moved,headers:Array.from(t.querySelectorAll('th')).map(th=>({text:th.textContent,whiteSpace:getComputedStyle(th).whiteSpace,wordBreak:getComputedStyle(th).wordBreak}))};}));if(name==='reports')assert.ok(tables.length>0,'mobile statement must retain a readable scrollable table');for(const table of tables){assert.ok(table.minWidth>=620&&table.tableWidth>=620,'mobile table minimum width '+name+': '+JSON.stringify(table));assert.ok(table.scrollWidth>table.wrapperWidth&&table.scrollMoved>0,'mobile table must actually scroll within its wrapper '+name);for(const header of table.headers)assert.equal(header.whiteSpace,'nowrap','mobile header must remain on one line '+name+': '+header.text);}tableStyles.push({view:name,width,tables});}await page.screenshot({path:path.join(output,(baseline?'before-':'after-')+name+'-'+width+'.png')});}
for(const width of[1440,390])await capture('reports',width,baseline?'#rpt-investor-kpis':'#finance-report-workspace');
if(!baseline){await page.setViewportSize({width:1440,height:1000});await page.getByRole('tab',{name:'資產負債表',exact:true}).click();const financialPopupPromise=page.waitForEvent('popup');await page.locator('[data-rw-action=export-pdf]').click();const financialPopup=await financialPopupPromise;await financialPopup.waitForLoadState();financialPdfChecks=await financialPopup.evaluate(()=>{const first=document.querySelector('section'),rows=Array.from(first.querySelectorAll('tbody tr')).map(r=>Array.from(r.cells).map(c=>c.textContent));return{headers:Array.from(first.querySelectorAll('thead th')).map(c=>c.textContent),assetTotal:rows.find(r=>r[0]==='資產合計'),sectionBreaks:Array.from(document.querySelectorAll('section')).map(s=>({title:s.querySelector('h2').textContent,breakBefore:getComputedStyle(s).breakBefore})),repeatHeader:getComputedStyle(first.querySelector('thead')).display,rowBreak:getComputedStyle(first.querySelector('tbody tr')).breakInside};});assert.deepEqual(financialPdfChecks.headers,['項目','本期末','前期末','差額'],'financial PDF uses the real header following its full introduction');assert.deepEqual(financialPdfChecks.assetTotal.slice(1).map(Number),[1029.99,1100,-70.01],'PDF financial amounts must match the actual statement model');assert.equal(financialPdfChecks.repeatHeader,'table-header-group');assert.equal(financialPdfChecks.rowBreak,'avoid');assert.equal(financialPdfChecks.sectionBreaks[0].breakBefore,'auto');assert.ok(financialPdfChecks.sectionBreaks.length>=6);assert(financialPdfChecks.sectionBreaks.slice(1).every(s=>s.breakBefore==='page'),'each following statement begins a new print section');await financialPopup.pdf({path:path.join(output,'financial-statements.pdf'),format:'A4',landscape:true,printBackground:true});await financialPopup.close();}
if(!baseline){
 await page.getByRole('tab',{name:'綜合損益表',exact:true}).click();await page.locator('[name=rw-department]').selectOption('CARE');
 const departmentDownload=page.waitForEvent('download');await page.locator('[data-rw-action=export-xlsx]').click();await (await departmentDownload).saveAs(path.join(output,'company-and-department.xlsx'));
 const exported=await page.evaluate(()=>window.__capturedReports.at(-1));const v=(name,label)=>exported.sheets.find(s=>s.name===name).rows.find(r=>r[0]===label)[1];
 assert.equal(v('資產負債表','資產合計'),1029.99);assert.equal(v('現金流量表','期末現金'),889.99);assert.equal(v('綜合損益表','本期損益'),-70.01);assert.equal(v('部門綜合損益表','本期損益'),30);assert.match(exported.name,/含日間照顧損益/);
 await page.locator('[name=rw-department]').selectOption('all');
}
if(!baseline){await page.setViewportSize({width:1440,height:1000});await page.getByRole('tab',{name:'綜合損益表',exact:true}).click();assert.ok((await page.locator('#rw-report-panel').innerText()).includes('本期綜合損益總額'));await page.getByRole('tab',{name:'現金流量表',exact:true}).click();assert.ok((await page.locator('#rw-report-panel').innerText()).includes('889.99'));await page.getByRole('tab',{name:'公司與部門',exact:true}).click();assert.ok((await page.locator('#rw-report-panel').innerText()).includes('50.01'));for(const width of[1440,390])await capture('management',width,'#finance-report-workspace');await page.setViewportSize({width:1440,height:1000});await page.getByRole('tab',{name:'401／403',exact:true}).click();for(const width of[1440,390])await capture('tax',width,'#finance-report-workspace');await page.setViewportSize({width:1440,height:1000});
const downloadPromise=page.waitForEvent('download');await page.locator('[data-rw-action=export-xlsx]').click();const download=await downloadPromise;await download.saveAs(path.join(output,'reports.xlsx'));
const popupPromise=page.waitForEvent('popup');await page.locator('[data-rw-action=export-pdf]').click();const popup=await popupPromise;await popup.waitForLoadState();await popup.pdf({path:path.join(output,'tax-workpaper.pdf'),format:'A4',landscape:true,printBackground:true});await popup.close();
await page.locator('[data-rw-action=settings]').click();await page.locator('#finance-report-dialog').waitFor({state:'visible'});await page.locator('#finance-report-dialog [name=reason]').fill('虛構測試：確認申報設定保存');await page.locator('#finance-report-dialog button[type=submit]').click();await page.waitForFunction(()=>window.__rwWrites.some(x=>x.name==='finance_reporting_profile_save_v1'));assert.equal(await scope('window.__rwWrites.filter(x=>x.name===\'finance_reporting_profile_save_v1\').length'),1);
}
await scope(`(async function(){S.recvEntity='F1';await nav('recv');buildRecv();})()`);
if(!baseline){await page.waitForFunction(()=>document.querySelector('#finance-receivable-workspace').textContent.includes('140'));assert.ok((await page.locator('#finance-receivable-workspace').innerText()).includes('40'));const legacySummary=await scope('recvCanonicalSummary(INVS,recvCanonicalSnapshot())');assert.equal(legacySummary.ready,true,JSON.stringify(legacySummary.errors));assert.deepEqual([legacySummary.originalAmount,legacySummary.allowanceAmount,legacySummary.receivedAmount,legacySummary.outstandingAmount],[200,20,40,140]);assert(!(await page.locator('#recv-kpis').innerText()).includes('未核對'),'legacy KPIs must use the same complete canonical amounts');for(const width of[1440,390])await capture('receivables',width,'#finance-receivable-workspace');await page.setViewportSize({width:1440,height:1000});await page.locator('.rw-desktop-only [data-rw-action=receivable-detail][data-invoice=inv-sep]').click();await page.locator('[data-rw-action=receivable-terms]').click();await page.locator('#finance-report-dialog [name=dueDate]').fill('2026-10-10');await page.locator('#finance-report-dialog [name=reason]').fill('虛構測試：核對合約付款日');await page.locator('#finance-report-dialog button[type=submit]').click();await page.waitForFunction(()=>window.__rwWrites.some(x=>x.name==='finance_update_receivable_terms_v1'));assert.equal(await scope('window.__rwWrites.filter(x=>x.name===\'finance_update_receivable_terms_v1\')[0].args.p_expected_version'),0);
}else for(const width of[1440,390])await capture('receivables',width,'#recv-kpis');
assert.deepEqual(errors,[],'no browser runtime errors');const report={root,baseline,fixture:'fictional companies, users, ledgers and canonical RPC payload; no real employee auth or production writes',errors,blocked,writes:await scope('window.__rwWrites'),tableStyles,financialPdfChecks,output};fs.writeFileSync(path.join(output,(baseline?'before':'after')+'-result.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({ok:true,baseline,output,writes:report.writes.length,errors,tableStyles,financialPdfChecks}));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();await new Promise(r=>server.close(r));});
