// Executable identity-race checks of the shipped readback/retry/outbox functions.
// Fictional source records and deferred transports; no network or DB writes.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
function fn(name){const start=source.search(new RegExp('^(?:async )?function '+name+'\\(','m'));assert.ok(start>=0,name);const rest=source.slice(start),next=rest.slice(1).search(/^(?:(?:async )?function |window\.|var )/m);return rest.slice(0,next<0?undefined:next+1);}
function windowAssignment(name,nextMarker){const start=source.indexOf('window.'+name+'=async function(){');const end=source.indexOf(nextMarker,start);assert.ok(start>=0&&end>start,name);return source.slice(start,end);}
function install(ctx,names){vm.createContext(ctx);for(const name of names)vm.runInContext(fn(name),ctx);return ctx;}
const base=['currentFinanceAuthUserId','expenseSubmissionOperationIdentity','expenseSubmissionOperationCurrent','expenseSubmissionIdentityChanged'];
const record=()=>({id:'r-a',no:'TEST-A',applicantId:'person-a',app:'匿名員工甲',eid:'E1',dc:'D1',type:'expense_reimbursement',amt:100,tenantId:'tenant-a',dataEnv:'production',files:[],formPayload:{submissionAttemptId:'attempt-a'}});
const user=()=>({id:'person-a',authUserId:'auth-a',email:'a@example.invalid',role:'employee',active:true});
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
const tick=()=>new Promise(resolve=>setImmediate(resolve));
let checks=0;const pass=n=>{checks++;console.log('PASS '+n);};
function fixture(names=[]){let tenant='tenant-a',env='production';const counts={reads:0,merged:0,writes:0,cleanup:0,clear:0,finalize:0};
 const pending={tenantId:tenant,dataEnv:env,applicantId:'person-a',requestId:'r-a',attemptId:'attempt-a',expected:record(),retryRecord:record()};
 const c=install({S:{user:user(),demoLogin:false,nrSubmissionConfirmationPending:pending},financeWorkspaceIdentityBlocked:false,currentTenantId:()=>tenant,activeDataEnvironment:()=>env,
  num:v=>Number(v)||0,mapReq:r=>r,REQS:[],expenseRevisionContainsFilePaths:()=>true,withAbortableOperationTimeout:p=>p,withOperationTimeout:p=>p,
  mergeCommittedExpenseRequest:r=>{counts.merged++;return r;},clearExpenseSubmissionPending:()=>{counts.clear++;c.S.nrSubmissionConfirmationPending=null;},loadExpenseSubmissionPending:()=>pending,
  finalizeRecoveredExpenseSubmission:async()=>{counts.finalize++;return {state:'committed'};},cleanupUploadedSupabaseAttachments:async()=>{counts.cleanup++;},recordOpsEvent(){},console,setTimeout:(f)=>setTimeout(f,0),clearTimeout,
 },[...base,...names]);
 return {c,counts,pending,env:value=>env=value,tenant:value=>tenant=value,switch:()=>{c.S.user={...user(),id:'person-b',authUserId:'auth-b',email:'b@example.invalid'};c.S.nrSubmissionConfirmationPending={requestId:'r-b',attemptId:'attempt-b'};}};
}
function readTransport(f){const d=deferred();f.c.getSb=()=>({from(){f.counts.reads++;return{select(){return this},eq(){return this},limit(){return d.promise}}}});return d;}
(async()=>{
 for(const change of ['auth','tenant','env','blocked']){
  const f=fixture(['expenseSubmissionRecordMatches','readExpenseSubmissionCommit']);const d=readTransport(f);const run=f.c.readExpenseSubmissionCommit(record());
  if(change==='auth')f.switch();if(change==='tenant')f.tenant('tenant-b');if(change==='env')f.env('test');if(change==='blocked')f.c.financeWorkspaceIdentityBlocked=true;
  d.resolve({data:[record()],error:null});const r=await run;assert.equal(r.identityChanged,true);assert.equal(f.counts.merged,0);assert.equal(r.record,undefined);pass('late committed read '+change+' change: no merge or returned old record');
 }
 {const f=fixture(['expenseSubmissionRecordMatches','readExpenseSubmissionCommit']);const d=readTransport(f),run=f.c.readExpenseSubmissionCommit(record());d.resolve({data:[record()],error:null});assert.equal((await run).state,'committed');assert.equal(f.counts.merged,1);pass('unchanged owner can read and merge exact committed attempt');}
 {const f=fixture(['expenseSubmissionRecordMatches','readExpenseSubmissionCommit']);readTransport(f);assert.equal((await f.c.readExpenseSubmissionCommit({...record(),applicantId:'person-b'})).identityChanged,true);assert.equal(f.counts.reads,0);pass('different applicant blocked before any read');}
 {const f=fixture(['readExpenseSubmissionCommitWithDelays']);let resolveTimer;f.c.setTimeout=resolve=>{resolveTimer=resolve};f.c.readExpenseSubmissionCommit=async()=>{f.counts.reads++;return{state:'absent'}};const run=f.c.readExpenseSubmissionCommitWithDelays(record(),[1]);f.switch();resolveTimer();assert.equal((await run).identityChanged,true);assert.equal(f.counts.reads,0);pass('identity switch while delay waits causes zero query');}
 for(const code of ['57014','CLIENT_TIMEOUT']){
  const f=fixture(['expenseApplicantRevisionRpcErrorIsAmbiguous','readExpenseSubmissionCommitWithDelays']);
  f.c.supabaseAuthErrorInfo=error=>({code:error.code,status:0,message:error.message});
  f.c.readExpenseSubmissionCommit=async()=>{f.counts.reads++;return f.counts.reads===1?{state:'unknown',error:{code,message:'statement timeout'}}:{state:'committed',record:record()}};
  const result=await f.c.readExpenseSubmissionCommitWithDelays(record(),[0,1]);
  assert.equal(result.state,'committed');assert.equal(f.counts.reads,2);
  assert.equal(f.counts.writes,0);assert.equal(f.counts.cleanup,0);assert.equal(f.counts.clear,0);
  pass('transient '+code+' readback retries exact request without write or cleanup');
 }
 {const f=fixture(['expenseApplicantRevisionRpcErrorIsAmbiguous','readExpenseSubmissionCommitWithDelays']);f.c.supabaseAuthErrorInfo=error=>({code:error.code,status:403,message:error.message});f.c.readExpenseSubmissionCommit=async()=>{f.counts.reads++;return{state:'unknown',error:{code:'42501',message:'permission denied'}}};const result=await f.c.readExpenseSubmissionCommitWithDelays(record(),[0,1]);assert.equal(result.state,'unknown');assert.equal(f.counts.reads,1);assert.equal(f.counts.clear,0);pass('authorization failure stops readback retries and keeps pending lock');}
 {const f=fixture(['expenseApplicantRevisionRpcErrorIsAmbiguous','readExpenseSubmissionCommitWithDelays']);f.c.supabaseAuthErrorInfo=error=>({code:error.code,status:500,message:error.message});f.c.readExpenseSubmissionCommit=async()=>{f.counts.reads++;return{state:'unknown',error:{code:'EXPENSE_SUBMISSION_ID_COLLISION',message:'network collision'}}};const result=await f.c.readExpenseSubmissionCommitWithDelays(record(),[0,1]);assert.equal(result.error.code,'EXPENSE_SUBMISSION_ID_COLLISION');assert.equal(f.counts.reads,1);assert.equal(f.counts.writes,0);pass('request identity collision never retries even if error looks transient');}
 {const f=fixture(['expenseSubmissionRecoveryPanelHtml','nrSubmitActionsHtml']);f.c.isExpenseApplicantRevisionMode=()=>false;f.c.escAttr=value=>String(value);const html=f.c.nrSubmitActionsHtml();assert.match(html,/前次送件待確認/);assert.match(html,/confirmPendingExpenseSubmission\(\)/);assert.match(html,/事件識別：attempt-a/);assert.doesNotMatch(html,/onclick="submitNR\(\)"/);assert.match(source,/id="nr-submission-recovery" hidden aria-live="polite"/);pass('durable pending replaces submit action with same-attempt confirmation on original request page');}
 {const f=fixture(['buildNR']);const originalFiles=[{name:'receipt.pdf'}],originalPassbook={name:'passbook.pdf'};f.c.S.nrType='expense_reimbursement';f.c.S.nrStep=3;f.c.S.nrFiles=originalFiles;f.c.S.nrPassbookFile=originalPassbook;let rendered=0,refreshed=0,childCount=1;f.c.el=()=>({childElementCount:childCount});f.c.renderNR=()=>{rendered++};f.c.refreshExpenseSubmissionRecoveryActions=()=>{refreshed++};f.c.buildNR();assert.equal(refreshed,1);assert.equal(rendered,0);assert.equal(f.c.S.nrType,'expense_reimbursement');assert.equal(f.c.S.nrStep,3);assert.equal(f.c.S.nrFiles,originalFiles);assert.equal(f.c.S.nrPassbookFile,originalPassbook);childCount=0;f.c.buildNR();assert.equal(rendered,1);assert.equal(f.c.S.nrFiles,originalFiles);pass('re-entering New Request preserves pending live form and only renders an empty recovery page after reload');}
 {const f=fixture(['expenseSubmissionPendingStorageKey','expenseSubmissionPendingInCurrentScope','loadExpenseSubmissionPending','reconcilePendingExpenseSubmission']);f.c.EXPENSE_SUBMISSION_PENDING_KEY_BASE='test_pending';const storage=new Map();f.c.sessionGetItem=key=>storage.get(key)||null;f.c.safeJsonGet=()=>null;storage.set(f.c.expenseSubmissionPendingStorageKey(),JSON.stringify(f.pending));f.c.S.user={...user(),id:'person-b',authUserId:'auth-b',email:'b@example.invalid'};assert.equal(f.c.loadExpenseSubmissionPending(),null);assert.equal(f.c.S.nrSubmissionConfirmationPending,null);f.c.readExpenseSubmissionCommitWithDelays=()=>{throw Error('old account must not read')};assert.equal((await f.c.reconcilePendingExpenseSubmission({allowRetry:true})).state,'none');f.c.S.user=user();assert.equal(f.c.loadExpenseSubmissionPending().requestId,f.pending.requestId);assert.match(source,/function clearFinanceLoginState\(\)[\s\S]*?S\.nrSubmissionConfirmationPending=null;[\s\S]*?S\.user=null;/);pass('account switch discards only old in-memory pointer and original owner reloads scoped pending');}
 {const f=fixture(['reconcilePendingExpenseSubmission']);let guarded=0;f.c.guardSubmissionIdentityDirectory=async()=>{guarded++;return false};f.c.readExpenseSubmissionCommitWithDelays=async()=>({state:'committed',record:record()});assert.equal((await f.c.reconcilePendingExpenseSubmission({allowRetry:true,requireDirectoryForRetry:true})).state,'committed');assert.equal(guarded,0);assert.equal(f.counts.finalize,1);pass('exact-ID committed readback completes before any slow directory sync');}
 {const f=fixture(['reconcilePendingExpenseSubmission']);let guarded=0,writes=0;f.c.guardSubmissionIdentityDirectory=async()=>{guarded++;return false};f.c.readExpenseSubmissionCommitWithDelays=async()=>({state:'absent'});f.c.submitExpenseRequestWithAmbiguousRecovery=async()=>{writes++;return{ok:true}};const result=await f.c.reconcilePendingExpenseSubmission({allowRetry:true,requireDirectoryForRetry:true});assert.equal(result.state,'unknown');assert.equal(result.reason,'directory_unavailable_retry_deferred');assert.equal(guarded,1);assert.equal(writes,0);assert.equal(f.counts.clear,0);pass('directory check only gates same-ID retry after confirmed-absent readback');}
 {const f=fixture(['reconcilePendingExpenseSubmission','expenseSubmissionRecoveryPanelHtml','nrSubmitActionsHtml']);const originalFiles=[{path:'test/original-receipt.pdf'}],originalPassbook={path:'test/original-passbook.pdf'};f.pending.retryRecord.files=originalFiles;f.pending.retryRecord.passbookFiles=[originalPassbook];f.c.S.nrFiles=originalFiles;f.c.S.nrPassbookFile=originalPassbook;f.c.readExpenseSubmissionCommitWithDelays=async()=>({state:'absent'});let retriedRecord;f.c.submitExpenseRequestWithAmbiguousRecovery=async r=>{retriedRecord=r;return{ok:false,unknown:false,error:Error('rejected')}};const result=await f.c.reconcilePendingExpenseSubmission({allowRetry:true,retainAttachmentsOnFailure:true});assert.equal(result.state,'deterministic_failure');assert.equal(result.pending,f.pending);assert.equal(retriedRecord,f.pending.retryRecord);assert.equal(retriedRecord.id,f.pending.requestId);assert.equal(retriedRecord.formPayload.submissionAttemptId,f.pending.attemptId);assert.equal(f.c.S.nrFiles,originalFiles);assert.equal(f.c.S.nrPassbookFile,originalPassbook);assert.equal(f.counts.writes,0);assert.equal(f.counts.cleanup,0);assert.equal(f.counts.clear,0);assert.equal(f.c.S.nrSubmissionConfirmationPending,f.pending);f.c.EXPENSE_SUBMISSION_PENDING_KEY_BASE='test_pending';f.c.sessionGetItem=()=>JSON.stringify(f.pending);f.c.safeJsonGet=()=>f.pending;f.c.escAttr=value=>String(value);f.c.isExpenseApplicantRevisionMode=()=>false;vm.runInContext(fn('expenseSubmissionPendingStorageKey')+fn('expenseSubmissionPendingInCurrentScope')+fn('loadExpenseSubmissionPending'),f.c);f.c.S.nrSubmissionConfirmationPending=null;f.c.S.nrFiles=[];f.c.S.nrPassbookFile=null;const afterReload=f.c.nrSubmitActionsHtml();assert.match(afterReload,/前次送件待確認/);assert.match(afterReload,/事件識別：attempt-a/);assert.match(afterReload,/confirmPendingExpenseSubmission\(\)/);assert.doesNotMatch(afterReload,/onclick="submitNR\(\)"/);assert.equal(f.c.S.nrSubmissionConfirmationPending.retryRecord.files[0].path,originalFiles[0].path);assert.equal(f.c.S.nrSubmissionConfirmationPending.retryRecord.passbookFiles[0].path,originalPassbook.path);pass('failed explicit confirmation keeps durable exact attempt and attachment paths recoverable after reload');}
 {const f=fixture(['expenseSubmissionRecoveryPanelHtml','nrSubmitActionsHtml']);f.c.window=f.c;f.c.isExpenseApplicantRevisionMode=()=>false;f.c.escAttr=value=>String(value);f.c.guardSubmissionIdentityDirectory=async()=>true;f.c.showActionFeedback=()=>{};f.c.failActionFeedback=()=>{};f.c.completeActionFeedback=()=>{};f.c.openApprovalTab=()=>{throw Error('unexpected navigation')};f.c.refreshExpenseSubmissionRecoveryActions=()=>{};const alerts=[];f.c.alert=message=>alerts.push(message);const d=deferred(),calls=[];f.c.reconcilePendingExpenseSubmission=opts=>{calls.push(opts);return d.promise};vm.runInContext(windowAssignment('confirmPendingExpenseSubmission','async function submitExpenseRequestWithAmbiguousRecovery'),f.c);const html=f.c.nrSubmitActionsHtml();const onclick=html.match(/onclick="([^"]*confirmPendingExpenseSubmission\(\)[^"]*)"/);assert.ok(onclick,'rendered recovery button has click handler');const click=()=>vm.runInContext(onclick[1],f.c);const run=click();await tick();assert.equal(f.c.S.nrSubmitting,true);await click();assert.equal(calls.length,1);d.resolve({state:'unknown'});await run;assert.equal(f.c.S.nrSubmitting,false);assert.equal(calls[0].allowRetry,true);assert.equal(calls[0].retainAttachmentsOnFailure,true);assert.equal(f.counts.cleanup,0);assert.equal(f.counts.clear,0);assert.equal(f.c.S.nrSubmissionConfirmationPending,f.pending);assert.match(alerts[0],/原帳號、原瀏覽器.*確認前次送件/);pass('rendered confirmation button click only reconciles original pending attempt and remains fail-closed on unknown');}
 {const f=fixture(['reconcilePendingExpenseSubmission']);const d=deferred();f.c.readExpenseSubmissionCommitWithDelays=()=>d.promise;const run=f.c.reconcilePendingExpenseSubmission({allowRetry:true});f.switch();const replacement=f.c.S.nrSubmissionConfirmationPending;d.resolve({state:'committed',record:record()});assert.equal((await run).identityChanged,true);assert.deepEqual(f.counts,{reads:0,merged:0,writes:0,cleanup:0,clear:0,finalize:0});assert.equal(f.c.S.nrSubmissionConfirmationPending,replacement);assert.equal(f.pending.requestId,'r-a');pass('reconciliation discards committed late response without finalize, cleanup or replacing another pending');}
 {const f=fixture(['reconcilePendingExpenseSubmission']);const d=deferred();f.c.readExpenseSubmissionCommitWithDelays=()=>d.promise;f.c.submitExpenseRequestWithAmbiguousRecovery=async()=>{f.counts.writes++;return{ok:false}};const run=f.c.reconcilePendingExpenseSubmission({allowRetry:true});f.switch();d.resolve({state:'absent'});assert.equal((await run).identityChanged,true);assert.equal(f.counts.writes,0);assert.equal(f.counts.cleanup,0);assert.equal(f.counts.clear,0);pass('absent late read never retries or deletes attachments under replacement identity');}
 {const f=fixture(['reconcilePendingExpenseSubmission']);f.c.readExpenseSubmissionCommitWithDelays=async()=>({state:'absent'});const d=deferred();f.c.submitExpenseRequestWithAmbiguousRecovery=()=>d.promise;const run=f.c.reconcilePendingExpenseSubmission({allowRetry:true});await tick();f.switch();const replacement=f.c.S.nrSubmissionConfirmationPending;d.resolve({ok:false,unknown:false,error:Error('denied')});assert.equal((await run).identityChanged,true);assert.equal(f.counts.cleanup,0);assert.equal(f.counts.clear,0);assert.equal(f.c.S.nrSubmissionConfirmationPending,replacement);pass('late deterministic retry failure preserves original staged files and both pending identities');}
 {const f=fixture(['submitExpenseRequestWithAmbiguousRecovery']);const d=deferred();f.c.callExpenseSubmissionOnce=()=>{f.counts.writes++;return d.promise};const run=f.c.submitExpenseRequestWithAmbiguousRecovery(record());f.switch();d.resolve({ok:true});assert.equal((await run).identityChanged,true);assert.equal(f.counts.writes,1);pass('late successful submission response is not confirmed under replacement identity');}
 {const f=fixture(['submitExpenseRequestWithAmbiguousRecovery']);f.c.callExpenseSubmissionOnce=async()=>{f.counts.writes++;return{ok:false,error:Error('timeout')}};f.c.expenseApplicantRevisionRpcErrorIsAmbiguous=()=>true;const d=deferred();f.c.readExpenseSubmissionCommitWithDelays=()=>d.promise;const run=f.c.submitExpenseRequestWithAmbiguousRecovery(record());await tick();f.switch();d.resolve({state:'absent'});assert.equal((await run).identityChanged,true);assert.equal(f.counts.writes,1);pass('ambiguous submission stops exact retry after identity changes during read');}
 {const f=fixture(['submitExpenseRequestWithAmbiguousRecovery']);const args=[];f.c.callExpenseSubmissionOnce=async r=>{args.push(r);return args.length===1?{ok:false,error:Error('timeout')}:{ok:true,data:{}}};f.c.expenseApplicantRevisionRpcErrorIsAmbiguous=()=>true;f.c.readExpenseSubmissionCommitWithDelays=async()=>({state:'absent'});const r=record();assert.equal((await f.c.submitExpenseRequestWithAmbiguousRecovery(r)).ok,true);assert.equal(args.length,2);assert.equal(args[0],args[1]);pass('same owner keeps exact request/attempt identity on legitimate retry');}
 {const f=fixture(['finalizeRecoveredExpenseSubmission']);f.c.ensureExpensePostCommitOutbox=()=>({ok:true});const d=deferred();f.c.runExpensePostCommitOutbox=()=>d.promise;f.c.buildAll=()=>{f.counts.finalize++};f.c.pruneCompletedExpensePostCommitOutbox=()=>{f.counts.clear++};const run=f.c.finalizeRecoveredExpenseSubmission(f.pending,record());f.switch();const replacement=f.c.S.nrSubmissionConfirmationPending;d.resolve({ok:true,failed:[]});assert.equal((await run).identityChanged,true);assert.equal(f.counts.finalize,0);assert.equal(f.counts.clear,0);assert.equal(f.c.S.nrSubmissionConfirmationPending,replacement);pass('late outbox completion cannot clear pending or build old success screen');}
 {const f=fixture(['expensePostCommitTaskState','runExpensePostCommitOutbox']);const entry={id:'out-a',tenantId:'tenant-a',dataEnv:'production',record:record(),tasks:{},notification:{id:'n-a'}};f.c.EXPENSE_POST_COMMIT_OUTBOX_RUN_PROMISE=null;f.c.loadExpensePostCommitOutbox=()=>[entry];let saved=0;f.c.saveExpensePostCommitOutboxEntry=()=>{saved++;return true};const d=deferred();f.c.persistAccountingLinesRemote=()=>{f.counts.writes++;return d.promise};f.c.dbUpsert=()=>{f.counts.writes++;return{ok:true}};f.c.persistExpenseExternalNotificationSchedule=()=>{f.counts.writes++;return{ok:true}};f.c.formatStorageUploadError=e=>e.message;const run=f.c.runExpensePostCommitOutbox();await tick();assert.equal(saved,1);f.switch();d.resolve({ok:true});assert.equal((await run).identityChanged,true);assert.equal(f.counts.writes,1);assert.equal(saved,1);assert.equal(entry.tasks.accounting.status,'running');pass('outbox stops after in-flight response: no new writes, no cross-user cache save, original retry retained');}
 console.log(`${checks} submission identity behavior checks passed`);
})().catch(error=>{console.error(error);process.exitCode=1});
