'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'assets/engines/audit-workspace.js'),'utf8');
const statements=require('../assets/engines/financial-statements.js'),engine=require('../assets/engines/audit-readiness-engine.js');
const clone=x=>JSON.parse(JSON.stringify(x));let tests=0;
function fixture(){
 const ledger=[{id:'dr',eid:'A',date:'2026-09-01',ac:'1112',dr:100,cr:0,dc:'D',voucherNo:'V1',sourceType:'expense_request',sourceId:'req'},{id:'cr',eid:'A',date:'2026-09-01',ac:'3111',dr:0,cr:100,dc:'D',voucherNo:'V1',sourceType:'expense_request',sourceId:'req'}];
 const items=Object.fromEntries(engine.templates().map(t=>[t.id,{status:'pending',applicability:'unknown',sourceLinks:[]}]));
 const f={actor:'ceo',role:'ceo',caseRevision:0,fingerprint:'a'.repeat(64),counts:{ledger:2,invoices:0,expense_requests:1},reloads:0,calls:[],ledger,items,handler:null,reloadHandler:null};
 const elements={'rpt-ent':{value:'A'},'rpt-month':{value:'2026-09'}},listeners={};
 const c={console,Map,Set,Date,JSON,Number,Math,String,Object,Array,Error,Promise,Intl,Uint8Array,TextEncoder,URL,Blob,setTimeout,clearTimeout,crypto:require('node:crypto').webcrypto,document:{getElementById:id=>elements[id]||null,addEventListener:(kind,fn)=>listeners[kind]=fn},FinanceFinancialStatements:statements,FinanceAuditReadinessEngine:engine,FinanceReportingWorkspace:{state:{tab:'audit'},loadProfile:async()=>({loaded:true,profile:{}})}};
 const runtime={state:()=>({page:'home'}),user:()=>({id:f.actor}),role:()=>f.role,tenant:()=> 'tenant',environment:()=> 'test',identityBlocked:()=>false,permissionIdentity:()=> 'scope-A',today:()=> '2026-09-30',entities:()=>[{id:'A',n:'Fictional A'}],users:()=>[{id:'ceo',n:'Reviewer'}],auditLedger:()=>f.ledger,auditSources:()=>({invoices:[],expense_requests:[{id:'req',eid:'A'}]}),completeness:()=>({complete:true,tables:{ledger:{complete:true,rowCount:2,total:2},invoices:{complete:true,rowCount:0,total:0},expense_requests:{complete:true,rowCount:1,total:1}}}),statementModel:()=>statements.buildModel({entityId:'A',period:'2026-09',ledger:f.ledger,completeness:{complete:true}}),reload:async()=>{f.reloads++;if(f.reloadHandler)return await f.reloadHandler();},rpc:async(name,args)=>{f.calls.push({name,args});if(f.handler){const value=await f.handler(name,args);if(value!==undefined)return value;}if(name==='finance_receivables_v1')return{data:{complete:true,asOf:'2026-09-30',totalCount:0,items:[],reconciliation:{arControlAccounts:['1123'],ledgerArBalance:0,invoiceArBalance:0,difference:0,unlinkedLedgerAmount:0,unlinkedLedgerRows:0,unlinkedLedgerDebit:0,unlinkedLedgerCredit:0}}};return{data:{ok:true,entityId:'A',period:'2026-09',revision:f.caseRevision,caseData:{schemaVersion:1,engagementType:'both',items:clone(f.items)},sourceFingerprint:f.fingerprint,sourceCounts:clone(f.counts),canEdit:f.role==='ceo',actorId:f.actor}};}};
 c.window=c;vm.createContext(c);vm.runInContext(source,c);c.FinanceAuditWorkspace.install(runtime);return Object.assign(f,{c,runtime,api:c.FinanceAuditWorkspace,elements,listeners});
}
async function check(name,fn){await fn();tests++;console.log('PASS '+name);}
const scope={eid:'A',period:'2026-09'};
(async()=>{
await check('stable server observations surround a full reload and preserve scope/count metadata',async()=>{const f=fixture(),r=await f.api.load(scope,true);assert.equal(r.status,'ready');assert.equal(f.reloads,1);assert.equal(r.input.receivables.entityId,'A');assert.equal(r.input.completeness.tables.ledger.scopedRowCount,2);assert.deepEqual(f.calls.map(x=>x.name),['finance_audit_case_read_v1','finance_receivables_v1','finance_audit_case_read_v1']);assert(f.calls.every(x=>x.args.p_entity_id==='A'&&x.args.p_data_environment==='test'));});
await check('all-entity and all-time scopes never dispatch source RPCs',async()=>{const f=fixture();assert.match(f.api.view({eid:'all',period:'2026'}),/選擇一間/);assert.match(f.api.view({eid:'A',period:'all'}),/選擇年度/);assert.equal(f.calls.length,0);});
await check('changed source blocks combined-version output',async()=>{const f=fixture();f.reloadHandler=async()=>{f.fingerprint='b'.repeat(64);};assert.equal(await f.api.load(scope,true),null);assert.match(f.api.view(scope),/來源帳務已變更/);assert(!f.api.view(scope).includes('已內部覆核'));});
await check('matching total amounts do not mask missing source rows',async()=>{const f=fixture();f.counts.ledger=3;assert.equal(await f.api.load(scope,true),null);assert.match(f.api.view(scope),/尚未完整核對筆數/);});
await check('transport failure remains retryable without fabricated completeness',async()=>{const f=fixture();f.reloadHandler=async()=>{throw new Error('connection lost');};assert.equal(await f.api.load(scope,true),null);assert.match(f.api.view(scope),/connection lost/);f.reloadHandler=null;assert.equal((await f.api.load(scope,true)).status,'ready');});
await check('AR failure preserves unknown controls while known ledger can be inspected',async()=>{const f=fixture();f.handler=async(name)=>name==='finance_receivables_v1'?{error:{message:'AR denied'}}:undefined;const r=await f.api.load(scope,true);assert.equal(r.status,'ready');assert.equal(r.input.receivables,null);assert.equal(r.model.controls.find(x=>x.id==='C08').status,'unknown');});
await check('identity change discards in-flight source response and does not overwrite next user',async()=>{const f=fixture();let release,first=true;f.handler=async(name)=>{if(first&&name==='finance_audit_case_read_v1'){first=false;return await new Promise(r=>release=r);}};const old=f.api.load(scope,true);await Promise.resolve();f.actor='auditor';f.role='external_audit';const newer=await f.api.load(scope,true);assert.equal(newer.caseRecord.actorId,'auditor');release({data:{ok:true,sourceFingerprint:'a'.repeat(64)}});assert.equal(await old,null);assert.equal((await f.api.load(scope,false)).caseRecord.actorId,'auditor');assert.equal(f.reloads,1);});
await check('a newer forced read wins over an earlier delayed read in the same identity',async()=>{const f=fixture();let release,first=true;f.handler=async(name)=>{if(first&&name==='finance_audit_case_read_v1'){first=false;return await new Promise(r=>release=r);}};const old=f.api.load(scope,true);await Promise.resolve();f.caseRevision=2;const newer=await f.api.load(scope,true);assert.equal(newer.caseRecord.revision,2);release({data:{ok:true,sourceFingerprint:'a'.repeat(64)}});assert.equal(await old,null);assert.equal((await f.api.load(scope,false)).caseRecord.revision,2);});
await check('source/settings text is escaped in the actual renderer',async()=>{const f=fixture();f.items.A01.evidenceReference='<img src=x onerror=alert(1)>';await f.api.load(scope,true);assert(f.api.view(scope).includes('&lt;img'));assert(!f.api.view(scope).includes('<img'));});
await check('actual ledger adapter preserves raw null/invalid amounts and manual/closing flags for audit',async()=>{const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),start=html.indexOf('function mapLedger('),end=html.indexOf('\nfunction mapRemoteDraft(',start),line=html.split('\n').find(l=>l.includes('auditLedger:function(eid)'));
 const c={REQS:[],INVS:[],fromIsoDate:v=>v||'',entityOfDept:()=> 'A',rowDataEnvironment:()=> 'test',rowTenantId:()=> 'tenant',num:v=>Number(v)||0};vm.createContext(c);vm.runInContext(html.slice(start,end),c);const mapped=c.mapLedger({id:'invalid',entry_date:'2026-09-01',entity_id:'A',department_code:'D',debit:null,credit:'not-a-number',account_code:'1112',manual_entry:true,closing_entry:true});assert.equal(mapped.dr,0,'existing accounting display behavior remains separate');c.statementScopedLedger=()=>[mapped];vm.runInContext('var adapter={'+line.trim()+'};',c);const row=c.adapter.auditLedger('A')[0];assert.equal(row.dr,null);assert.equal(row.cr,'not-a-number');assert.equal(row.manualEntry,true);assert.equal(row.closingEntry,true);const m=engine.buildModel({entityId:'A',period:'2026-09',ledger:[row],completeness:{tables:{ledger:{complete:true,rowCount:1,total:1},invoices:{complete:true,rowCount:0,total:0},expense_requests:{complete:true,rowCount:0,total:0}}}});assert.equal(m.controls.find(x=>x.id==='C04').status,'issue');});
console.log('PASS audit workspace runtime checks: '+tests);
})().catch(e=>{console.error(e);process.exitCode=1;});
