'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(path.join(__dirname,'../assets/engines/reporting-workspace.js'),'utf8'),anchor='  global.FinanceReportingWorkspace=api;';
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};};
function good(args,revision=1){return{data:{ok:true,entityId:args.p_entity_id,dataEnvironment:args.p_data_environment,revision,profile:{accountMappings:{}},canEdit:false}};}
function fixture(options={}){
 const env={user:'person',auth:'auth-person',tenant:'tenant',environment:'test',role:'ceo',blocked:false,permission:'p1',page:'dashboard',calls:[],paints:0,aborts:0,timers:[],entities:[{id:'A'},{id:'B'},{id:'C'}]};
 const context={Map,Set,Intl,Date,AbortController,Promise,console,document:{getElementById:()=>null,addEventListener(){}},setTimeout:(fn,ms)=>{env.timers.push(ms);return setTimeout(fn,ms===12000?(options.timeout||100):ms);},clearTimeout};context.window=context;
 vm.runInNewContext(source.replace(anchor,'  global.__profileReadTest={rpc:rpc,pending:pending};\n'+anchor),context);
 const runtime={user:()=>env.user?{id:env.user,authUserId:env.auth}:null,tenant:()=>env.tenant,environment:()=>env.environment,role:()=>env.role,identityBlocked:()=>env.blocked,permissionIdentity:()=>env.permission,entities:()=>env.entities,state:()=>({page:env.page}),refreshDashboard:()=>{env.paints++;if(env.onPaint)env.onPaint();},rpc:(name,args)=>{env.calls.push({name,args});return env.transport?env.transport(name,args):Promise.resolve(good(args));}};
 context.FinanceReportingWorkspace.install(runtime);return{env,w:context.FinanceReportingWorkspace,api:context.__profileReadTest};
}
let count=0;async function test(name,run){await run();count++;console.log('PASS '+name);}
(async()=>{
await test('only requested profile IDs load, including a ledger entity absent from ENTS',async()=>{const f=fixture();await f.w.warmProfiles(['A','OLD-LEDGER','A']);assert.deepEqual(f.env.calls.map(x=>x.args.p_entity_id),['A','OLD-LEDGER']);assert(f.w.profileRecord('OLD-LEDGER').loaded);await sleep(5);assert.equal(f.env.paints,1);});
await test('all overlapping warmups share per-key reads with at most two active RPCs',async()=>{const f=fixture(),queue=[];let active=0,max=0;f.env.transport=(_n,args)=>{active++;max=Math.max(max,active);const d=deferred();queue.push({d,args});return d.promise.finally(()=>active--);};const a=f.w.warmProfiles(['A','B','C']),b=f.w.warmProfiles(['B','C','D']);assert.equal(f.env.calls.length,2);for(let i=0;i<4;i++){await sleep(0);const q=queue[i];q.d.resolve(good(q.args));}await Promise.all([a,b]);assert.equal(f.env.calls.length,4);assert.equal(max,2);});
await test('hung plain-Promise profile read settles as error; explicit retry restores ready',async()=>{const f=fixture({timeout:15});f.env.transport=()=>new Promise(()=>{});await f.w.warmProfiles(['A']);assert.equal(f.w.profileRecord('A').status,'error');assert.match(f.w.profileRecord('A').error,/逾時/);assert.equal(f.api.pending.size,0);f.env.transport=(_n,args)=>Promise.resolve(good(args));await f.w.retryProfiles(['A']);assert(f.w.profileRecord('A').loaded);assert.equal(f.env.calls.length,2);});
await test('Supabase thenable receives abortSignal and timeout aborts transport',async()=>{const f=fixture({timeout:15});f.env.transport=()=>({abortSignal(signal){signal.addEventListener('abort',()=>f.env.aborts++);return this;},then(){return new Promise(()=>{});}});await f.w.warmProfiles(['A']);assert.equal(f.env.aborts,1);assert.equal(f.w.profileRecord('A').status,'error');});
await test('57014 stays explicitly failed through notification/paint warmups until retry',async()=>{const f=fixture();f.env.transport=()=>Promise.resolve({error:{code:'57014',message:'statement timeout'}});f.env.onPaint=()=>f.w.warmProfiles(['A']);await f.w.warmProfiles(['A']);await sleep(5);for(let i=0;i<5;i++)await f.w.warmProfiles(['A']);assert.equal(f.env.calls.length,1);assert.equal(f.env.paints,1);assert.equal(f.w.profileRecord('A').loaded,false);f.env.transport=(_n,args)=>Promise.resolve(good(args));await f.w.retryProfiles(['A']);assert.equal(f.env.calls.length,2);assert.equal(f.w.profileRecord('A').status,'ready');});
await test('scope denial on unknown company is an error, never an empty loaded profile',async()=>{const f=fixture();f.env.transport=()=>Promise.resolve({error:{code:'42501',message:'Company outside authorized scope'}});await f.w.warmProfiles(['LEGACY']);assert.equal(f.w.profileRecord('LEGACY').loaded,false);assert.match(f.w.profileRecord('LEGACY').error,/scope/);});
for(const [name,value]of [['user','other'],['auth','other-auth'],['tenant','other-tenant'],['environment','production'],['role','employee'],['permission','p2'],['blocked',true]])await test(name+' change cancels/invalidates pending and queued profiles without old repaint',async()=>{const f=fixture(),queue=[];f.env.transport=(_n,args)=>{const d=deferred();queue.push({d,args});return d.promise;};const old=f.w.warmProfiles(['A','B','C']);f.env[name]=value;f.w.profileRecord('A');await old;queue.forEach(q=>q.d.resolve(good(q.args)));await sleep(5);assert.equal(f.w.profileRecord('A'),null);assert.equal(f.env.calls.length,2,'queued C must not read under changed identity');assert.equal(f.env.paints,0);});
await test('same-key force retry supersedes old read and cannot lose the newest pending slot',async()=>{const f=fixture(),q=[];f.env.transport=(_n,args)=>{const d=deferred();q.push({d,args});return d.promise;};const old=f.w.loadProfile('A'),newest=f.w.loadProfile('A',true);assert.equal(f.env.calls.length,2);q[1].d.resolve(good(q[1].args,7));await newest;q[0].d.resolve(good(q[0].args,1));await old;assert.equal(f.w.profileRecord('A').revision,7);assert.equal(f.api.pending.size,0);});
await test('force retry replaces a queued generation before it can issue a stale RPC',async()=>{const f=fixture(),q=[];f.env.transport=(_n,args)=>{const d=deferred();q.push({d,args});return d.promise;};const a=f.w.loadProfile('A'),b=f.w.loadProfile('B'),old=f.w.loadProfile('C'),fresh=f.w.loadProfile('C',true);assert.equal(f.env.calls.length,2);q[0].d.resolve(good(q[0].args));await a;await sleep(0);assert.equal(f.env.calls.length,3);assert.equal(q[2].args.p_entity_id,'C');q[1].d.resolve(good(q[1].args));q[2].d.resolve(good(q[2].args,8));await Promise.all([b,old,fresh]);assert.equal(f.w.profileRecord('C').revision,8);assert.equal(f.api.pending.size,0);});
await test('late plain Promise after timeout cannot overwrite retry success',async()=>{const f=fixture({timeout:15}),d=deferred();f.env.transport=()=>d.promise;await f.w.warmProfiles(['A']);f.env.transport=(_n,args)=>Promise.resolve(good(args,4));await f.w.retryProfiles(['A']);d.resolve(good({p_entity_id:'A',p_data_environment:'test'},1));await sleep(5);assert.equal(f.w.profileRecord('A').revision,4);});
for(const mode of ['null','missing-profile','wrong-entity','wrong-environment'])await test('malformed '+mode+' response cannot make profile ready',async()=>{const f=fixture();f.env.transport=(_n,args)=>{const value=good(args);if(mode==='null')value.data=null;if(mode==='missing-profile')delete value.data.profile;if(mode==='wrong-entity')value.data.entityId='OTHER';if(mode==='wrong-environment')value.data.dataEnvironment='production';return Promise.resolve(value);};await f.w.warmProfiles(['A']);assert.equal(f.w.profileRecord('A').loaded,false);});
await test('non-profile readonly RPCs also time out while financial writes remain unbounded',async()=>{const f=fixture({timeout:10});f.env.transport=()=>new Promise(()=>{});for(const name of ['finance_receivables_v1','finance_reporting_profile_history_v1','finance_reporting_tax_sources_v1'])await assert.rejects(f.api.rpc(name,{}),/逾時/);const d=deferred(),before=f.env.timers.length;f.env.transport=()=>d.promise;let done=false;const save=f.api.rpc('finance_reporting_profile_save_v1',{}).then(()=>done=true);await sleep(25);assert.equal(done,false);assert.equal(f.env.timers.length,before);d.resolve({data:{ok:true}});await save;assert(done);});
await test('locked/no-user warmups do not issue formal reads or produce loaded defaults',async()=>{const f=fixture();f.env.blocked=true;await f.w.warmProfiles(['A']);f.env.blocked=false;f.env.user='';await f.w.retryProfiles(['A']);assert.equal(f.env.calls.length,0);assert.equal(f.w.profileRecord('A'),null);});
console.log('Reporting profile readiness: '+count+' checks passed.');
})().catch(error=>{console.error(error);process.exitCode=1;});
