#!/usr/bin/env node
'use strict';
// Real browser functions with anonymous fixtures. No production writes or
// external messages. These scenarios specifically exercise delayed replies.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
function block(start,end){const i=html.indexOf(start),j=html.indexOf(end,i+start.length);assert(i>=0&&j>i,`${start} not found`);return html.slice(i,j);}
function named(name){const re=new RegExp('(?:async )?function '+name+'\\('),m=re.exec(html);assert(m,name);const i=m.index,lineEnd=html.indexOf('\n',i);if(html.slice(i,lineEnd).endsWith('}'))return html.slice(i,lineEnd);const j=html.indexOf('\n}',i);assert(j>i,name);return html.slice(i,j+2);}
function context(extra){const c={console:{error(){},warn(){},info(){}},Date,JSON,Array,Object,String,Number,Boolean,Math,Promise,Error,setTimeout:f=>{f();return 0;},...extra};c.window=c;return vm.createContext(c);}
function deferred(){let resolve;const promise=new Promise(r=>{resolve=r;});return {promise,resolve};}
let checks=0;async function test(name,fn){await fn();checks++;console.log('PASS '+name);}
const clone=x=>JSON.parse(JSON.stringify(x));
function companyFixture(mode='success',type='capital_temp',withFile=true){
  const local=new Map(),session=new Map(),rows=new Map(),calls=[],alerts=[];let serial=0,cleaned=0,notificationRuns=0;
  const controls={'sh-type':{value:type},'sh-amt':{value:'123.45'},'sh-date':{value:'2026-09-01'},'sh-note':{value:'fixture authorized reason'},'sh-offset-required':{value:'no'},'sh-file':{value:'fixture',files:withFile?[{}]:[]}};
  const ctx=context({S:{user:{id:'employee-fixture',n:'Fixture',email:'fixture@example.invalid',role:'ceo'},demoLogin:false},financeAuthIdentityEpoch:1,financeWorkspaceIdentityBlocked:false,DEFAULT_TENANT_ID:'tenant-fixture',REQS:[],NOTIFS:[],POSTING_IN_FLIGHT:{},USERS:[],SH_TXN_ALIAS:{},
    currentFinanceAuthUserId:()=> 'auth-fixture',currentTenantId:()=> 'tenant-fixture',activeDataEnvironment:()=> 'production',hasSupabase:()=>true,
    canAccessPage:()=>true,guardSubmissionIdentityDirectory:async()=>true,el:id=>controls[id]||null,num:v=>Number(v)||0,todayIso:()=> '2026-09-01',
    shareholderParty:side=>({name:side==='payer'?'Source':'Target',type:type.includes('company')?'legal_entity':'natural_person',eid:side==='payer'?'E1':'E2',label:'fixture'}),shareholderAccountingEntityId:()=> 'E1',currentUserDeptForEntity:()=> 'D1',shareholderBankInfo:()=>({summary:''}),
    shareholderTxnMeta:()=>({category:'shareholder_funds',label:type,dr:'1112',cr:'3131',drN:'Bank',crN:'Capital',direction:'inflow',offset:'no'}),isIntercompanyTxn:t=>t.includes('company'),collectShareholderFieldMissing:()=>[],firstUserByRole:()=>({id:'fixture-reviewer'}),cashierUser:()=>({id:'fixture-cashier'}),
    recordOpsEvent:()=>{},applicantSubmitStep:()=>({a:'submit'}),buildShareholderApprovalSteps:()=>[{a:'',r:'Fixture reviewer',status:'pending_accountant'}],prepareApprovalRouteForSubmit:async(_a,_b,_c,_d,steps)=>({ok:true,steps}),p1SubmissionPreflight:async()=>({ok:true}),nextExpenseRequestNo:async()=> '20260901001',
    readStepFiles:async()=>withFile?[{name:'fixture.pdf'}]:[],fileToAttachment:async x=>x,uploadAttachmentsToSupabase:async files=>files.map(x=>({...x,path:'fixture/staged.pdf'})),cloneApprovalStepsForRecord:clone,shareholderPartyTrail:()=> 'Source to Target',shareholderCategoryLabel:()=> 'Fixture',membershipOrgDraftUuid:()=> 'fixture-'+(++serial),currentFinanceReleaseContract:()=>({source_commit:'fixture'}),
    cleanupUploadedSupabaseAttachments:async groups=>{cleaned+=groups.flat().length;return groups.flat().length;},friendlyErrorMessage:e=>e.message||String(e),fmt:String,requestNextStepLabel:()=> 'Fixture reviewer',buildAll:()=>{},renderNotifs:()=>{},updateShareholderPreview:()=>{},alert:m=>alerts.push(m),
    reqDbRow:clone,mapReq:clone,applyMembershipOrgActorsToSteps:()=>{},pushNotification:()=>{throw new Error('notification before commit');},
    normalizeFiles:x=>x||[],expenseRevisionContainsFilePaths:(actual,expected)=>expected.every(f=>actual.some(a=>a.path===f.path)),supabaseAuthErrorInfo:e=>e,
    safeJsonSet:(key,val)=>{local.set(key,clone(val));return true;},safeJsonGet:(key,fallback)=>local.has(key)?clone(local.get(key)):fallback,safeRemoveItem:key=>local.delete(key),sessionSetItem:(key,v)=>{session.set(key,v);return true;},sessionGetItem:key=>session.get(key)||null,sessionRemoveItem:key=>session.delete(key),refreshExpenseSubmissionRecoveryActions:()=>{},
    withOperationTimeout:async x=>await x,withAbortableOperationTimeout:async x=>await x,
    insertMembershipOrgSubmittedRecord:async(_kind,_table,record)=>{calls.push(clone(record));assert(record.formPayload.submissionAttemptId,'must send idempotency key');
      if(mode==='failure')return{ok:false,error:{code:'P0001',message:'fixture deterministic rejection'}};
      if(mode==='unknown')return{ok:false,error:{code:'CLIENT_TIMEOUT',message:'network timeout'}};
      rows.set(record.id,clone(record));
      if(mode==='readback'||mode==='replay'&&calls.length===1)return{ok:false,error:{code:'CLIENT_TIMEOUT',message:'lost response'}};
      return{ok:true,data:{row:clone(rows.get(record.id))}};},
    getSb:()=>({from:()=>{const q={select:()=>q,eq:()=>q,limit:async()=>mode==='unknown'||mode==='replay'&&calls.length===1?{error:{message:'fixture read unavailable'}}:{data:[...rows.values()]}};return q;}}),
    ensureExpensePostCommitOutbox:record=>{assert(rows.has(record.id),'no notification outbox before commit');return{ok:true};},runExpensePostCommitOutbox:async()=>{notificationRuns++;return{failed:[]};},pruneCompletedExpensePostCommitOutbox:()=>{},
    reconcilePendingExpenseSubmission:async()=>({state:'unknown'})
  });
  for(const name of ['expenseApplicantRevisionRpcErrorIsAmbiguous','expenseSubmissionRecordMatches','mergeCommittedExpenseRequest','expenseSubmissionOperationIdentity','expenseSubmissionOperationCurrent','expenseSubmissionIdentityChanged','readExpenseSubmissionCommit','callExpenseSubmissionOnce','readExpenseSubmissionCommitWithDelays'])vm.runInContext(named(name),ctx);
  vm.runInContext(block("var EXPENSE_SUBMISSION_PENDING_KEY_BASE=","var EXPENSE_POST_COMMIT_OUTBOX_KEY_BASE="),ctx);
  vm.runInContext(named('submitExpenseRequestWithAmbiguousRecovery'),ctx);
  vm.runInContext(block('async function submitShareholderApprovalRequest(){','async function finalizeShareholderRequest('),ctx);
  return {ctx,calls,rows,alerts,controls,get cleaned(){return cleaned;},get notificationRuns(){return notificationRuns;},local,session};
}
function orgFixture(){
  const requests=[],alerts=[];const ctx=context({MEMBERSHIP_ORG_CONTEXT_SEQUENCE:0,MEMBERSHIP_ORG_DRAFT:{version:{id:'draft-A',etag:'etag-1',title:'Title',reason:'Reason'},snapshot:{units:[{id:'unit',active:true}],assignments:[]},dirty:true,people:[]},financeAuthIdentityEpoch:1,CURRENT_PERMISSION_SNAPSHOT:{role:'hr'},expenseSubmissionOperationIdentity:()=>ctx.actor||'actor-A',stableSnapshotValue:x=>x,cloneSettingValue:clone,
    getSb:()=>({rpc:(name,args)=>{const d=deferred();requests.push({name,args,d});return d.promise;}}),alert:m=>alerts.push(m),confirm:()=>true,friendlyErrorMessage:e=>e.message,renderMembershipOrgManager:()=>{},setTopSyncStatus:()=>{},membershipRuntimeArray:x=>x||[]
  });
  for(const name of ['membershipOrgOperationIdentity','membershipOrgAsyncScope','membershipOrgAsyncScopeCurrent'])vm.runInContext(named(name),ctx);
  vm.runInContext(block('window.saveMembershipOrgDraft=','window.publishMembershipOrgDraft='),ctx);
  vm.runInContext(named('loadMembershipOrgPeople'),ctx);
  vm.runInContext(block('window.loadMembershipOrgDraft=','window.closeMembershipOrgDraft='),ctx);
  return {ctx,requests,alerts};
}
(async()=>{
  await test('expense in flight prevents a simultaneous company submission',async()=>{const f=companyFixture();f.ctx.S.nrSubmitting=true;assert.equal(await f.ctx.submitShareholderApprovalRequest(),false);assert.equal(f.calls.length,0);assert.equal(f.rows.size,0);assert.equal(f.notificationRuns,0);});
  await test('company in flight prevents a simultaneous expense submission',async()=>{const f=companyFixture();f.ctx.POSTING_IN_FLIGHT.shareholderApproval=true;vm.runInContext(block('window.submitNR=async function(){','function buildExp(){'),f.ctx);await f.ctx.submitNR();assert.equal(f.calls.length,0);assert.equal(f.rows.size,0);assert.equal(f.notificationRuns,0);});
  for(const type of ['capital_temp','company_loan_out','company_loan_repay'])for(const withFile of [false,true])await test(`${type}: successful formal submission ${withFile?'with':'without'} attachment`,async()=>{const f=companyFixture('success',type,withFile);assert.equal(await f.ctx.submitShareholderApprovalRequest(),true);assert.equal(f.rows.size,1);assert.equal(f.ctx.REQS.length,1);assert.equal(f.notificationRuns,1);assert.equal(f.cleaned,0);assert.equal(f.ctx.loadExpenseSubmissionPending(),null);});
  await test('deterministic failure cleans staged attachment and never notifies',async()=>{const f=companyFixture('failure');assert.equal(await f.ctx.submitShareholderApprovalRequest(),false);assert.equal(f.rows.size,0);assert.equal(f.ctx.REQS.length,0);assert.equal(f.cleaned,1);assert.equal(f.notificationRuns,0);assert.equal(f.ctx.loadExpenseSubmissionPending(),null);});
  await test('lost response is confirmed by readback without duplicate',async()=>{const f=companyFixture('readback');assert.equal(await f.ctx.submitShareholderApprovalRequest(),true);assert.equal(f.rows.size,1);assert.equal(f.calls.length,1);assert.equal(f.cleaned,0);assert.equal(f.notificationRuns,1);});
  await test('unavailable readback replays exactly the same request and attempt',async()=>{const f=companyFixture('replay');assert.equal(await f.ctx.submitShareholderApprovalRequest(),true);assert.equal(f.rows.size,1);assert.equal(f.calls.length,2);assert.deepEqual(f.calls[0],f.calls[1]);assert.equal(f.notificationRuns,1);});
  await test('unknown result retains durable pending and attachments; next click cannot create new request',async()=>{const f=companyFixture('unknown');assert.equal(await f.ctx.submitShareholderApprovalRequest(),false);const n=f.calls.length;assert.equal(n,2);assert(f.ctx.loadExpenseSubmissionPending());assert.equal(f.cleaned,0);assert.equal(f.notificationRuns,0);assert.equal(await f.ctx.submitShareholderApprovalRequest(),false);assert.equal(f.calls.length,n);});
  for(const edit of ['unit','head','delegate'])await test(`delayed org save preserves newer ${edit} edit and updates etag`,async()=>{const f=orgFixture(),promise=f.ctx.saveMembershipOrgDraft(),request=f.requests[0];if(edit==='unit')f.ctx.MEMBERSHIP_ORG_DRAFT.snapshot.units[0].active=false;else f.ctx.MEMBERSHIP_ORG_DRAFT.snapshot.assignments.push({id:edit,finance_user_id:'fixture-'+edit});request.d.resolve({data:{version:{id:'draft-A',etag:'etag-2'},snapshot:clone(request.args.p_snapshot),impact:{count:1}}});assert.equal(await promise,false);assert.equal(f.ctx.MEMBERSHIP_ORG_DRAFT.dirty,true);assert.equal(f.ctx.MEMBERSHIP_ORG_DRAFT.version.etag,'etag-2');assert.equal(edit==='unit'?f.ctx.MEMBERSHIP_ORG_DRAFT.snapshot.units[0].active:f.ctx.MEMBERSHIP_ORG_DRAFT.snapshot.assignments[0].id,edit==='unit'?false:edit);});
  await test('late save cannot overwrite a different draft',async()=>{const f=orgFixture(),promise=f.ctx.saveMembershipOrgDraft();const other={version:{id:'draft-B'},snapshot:{new:true},dirty:true};f.ctx.MEMBERSHIP_ORG_DRAFT=other;f.requests[0].d.resolve({data:{version:{id:'draft-A',etag:'etag-2'},snapshot:{old:true}}});assert.equal(await promise,false);assert.equal(f.ctx.MEMBERSHIP_ORG_DRAFT,other);});
  await test('identity epoch change discards late org save response',async()=>{const f=orgFixture(),promise=f.ctx.saveMembershipOrgDraft();f.ctx.financeAuthIdentityEpoch++;f.requests[0].d.resolve({data:{version:{id:'draft-A',etag:'etag-2'},snapshot:{old:true}}});assert.equal(await promise,false);assert.equal(f.ctx.MEMBERSHIP_ORG_DRAFT.version.etag,'etag-1');assert.equal(f.ctx.MEMBERSHIP_ORG_DRAFT.dirty,true);});
  await test('simultaneous org saves issue only one RPC',async()=>{const f=orgFixture(),a=f.ctx.saveMembershipOrgDraft();assert.equal(await f.ctx.saveMembershipOrgDraft(),false);assert.equal(f.requests.length,1);f.requests[0].d.resolve({data:{version:{id:'draft-A',etag:'etag-2'},snapshot:clone(f.requests[0].args.p_snapshot)}});assert.equal(await a,true);});
  await test('new edit during save prevents submit of stale revision',async()=>{const f=orgFixture(),a=f.ctx.submitMembershipOrgDraft();f.ctx.MEMBERSHIP_ORG_DRAFT.snapshot.units[0].active=false;f.requests[0].d.resolve({data:{version:{id:'draft-A',etag:'etag-2'},snapshot:clone(f.requests[0].args.p_snapshot)}});await a;assert.equal(f.requests.length,1);assert.equal(f.ctx.MEMBERSHIP_ORG_DRAFT.dirty,true);});
  await test('out-of-order draft reads preserve most recently requested draft',async()=>{const f=orgFixture(),a=f.ctx.loadMembershipOrgDraft('draft-A'),b=f.ctx.loadMembershipOrgDraft('draft-B');f.requests[1].d.resolve({data:{version:{id:'draft-B'},snapshot:{b:true}}});await new Promise(setImmediate);const people=f.requests.find(r=>r.name==='membership_org_list_people');assert(people,'new draft starts scoped people read');people.d.resolve({data:[]});await b;f.requests[0].d.resolve({data:{version:{id:'draft-A'},snapshot:{a:true}}});await a;assert.equal(f.ctx.MEMBERSHIP_ORG_DRAFT.version.id,'draft-B');});
  await test('people read cannot fill a replaced draft or switched identity',async()=>{const f=orgFixture(),a=f.ctx.loadMembershipOrgPeople();f.ctx.actor='actor-B';f.requests[0].d.resolve({data:[{id:'person-A'}]});assert.deepEqual(Array.from(await a),[]);assert.deepEqual(f.ctx.MEMBERSHIP_ORG_DRAFT.people,[]);});
  await test('draft switch read preserves edits made while the read is pending',async()=>{const f=orgFixture(),a=f.ctx.loadMembershipOrgDraft('draft-B');f.ctx.MEMBERSHIP_ORG_DRAFT.snapshot.units[0].active=false;f.requests[0].d.resolve({data:{version:{id:'draft-B'},snapshot:{b:true}}});await a;assert.equal(f.ctx.MEMBERSHIP_ORG_DRAFT.version.id,'draft-A');assert.equal(f.ctx.MEMBERSHIP_ORG_DRAFT.snapshot.units[0].active,false);assert.equal(f.ctx.MEMBERSHIP_ORG_DRAFT.dirty,true);});
  await test('late validation cannot overwrite a newly edited draft',async()=>{const f=orgFixture();f.ctx.MEMBERSHIP_ORG_DRAFT.dirty=false;const a=f.ctx.validateMembershipOrgDraft();f.ctx.MEMBERSHIP_ORG_DRAFT.snapshot.units[0].active=false;f.ctx.MEMBERSHIP_ORG_DRAFT.dirty=true;f.requests[0].d.resolve({data:{ok:true,version:{id:'draft-A',etag:'validated'},validation:{errors:[],warnings:[]},impact:{}}});await a;assert.equal(f.ctx.MEMBERSHIP_ORG_DRAFT.version.etag,'etag-1');assert.equal(f.ctx.MEMBERSHIP_ORG_DRAFT.dirty,true);assert.equal(f.alerts.length,0);});
  console.log(`PASS ${checks} workflow recovery and organization race checks`);
})().catch(e=>{console.error(e);process.exitCode=1;});
