// Actual shipped OAuth/health functions; fictional identities and no network.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const src=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
function fn(name){let pattern=name.startsWith('window.')?'^'+name.replace('.','\\.')+'=(?:async )?function\\(':'^(?:async )?function '+name+'\\(';let start=src.search(new RegExp(pattern,'m'));assert.ok(start>=0,name);let rest=src.slice(start),next=rest.slice(1).search(/^(?:(?:async )?function |window\.|var |\/\/ Backward-compatible)/m);return next<0?rest:rest.slice(0,next+1);}
function install(c,names){vm.createContext(c);for(const n of names)vm.runInContext(fn(n),c);return c;}
const deferred=()=>{let resolve,reject;let promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};const tick=()=>new Promise(r=>setTimeout(r,0));let count=0;function pass(x){count++;console.log('PASS '+x);}
(async()=>{
 let calls=0,oauth,errors=[],destinations=[],busy=[],storage=new Map();let hint='first@example.invalid';
 const c=install({S:{user:null},financeAuthIdentityEpoch:0,financeInitialOAuthAttempt:null,financeGoogleAccountSwitchInProgress:false,FINANCE_INITIAL_OAUTH_TIMEOUT_MS:20,currentFinanceAuthUserId:()=>'',currentTenantId:()=> 'tenant-a',activeDataEnvironment:()=> 'real',SUPABASE_URL:'https://auth.example.invalid',window:{location:{assign:u=>destinations.push(u)}},URL,setTimeout,clearTimeout,console,
 setFinanceInitialOAuthBusy:b=>busy.push(b),safeSetItem:(k,v)=>storage.set(k,v),safeRemoveItem:k=>storage.delete(k),FINANCE_PORTAL_EMAIL_KEY:'email',FINANCE_PORTAL_EMAIL_AT_KEY:'at',FINANCE_PORTAL_OAUTH_PENDING_KEY:'pending',FINANCE_PORTAL_OAUTH_MODE_KEY:'mode',oauthRedirectUrl:()=> 'https://finance.example.invalid/',showFinanceOAuthFailure:async(...args)=>errors.push(args),isFinanceProductionBuild:()=>true,isCompanyGoogleLoginEmail:()=>true,ensureOfficialHostBeforeOAuth:()=>true,preserveApprovalDeepLinkForOAuth:()=>true,isOAuthBlockedUserAgent:()=>false,financeExpectedLoginEmail:()=>hint,showFinanceLoginAccountGuidance(){},el:()=>null,alert(){},getSb:()=>({auth:{signInWithOAuth(args){calls++;return oauth(args);}}})},['financeReauthenticationIdentity','financeReauthenticationDestination','withOperationTimeout','startFinanceInitialOAuth','cancelFinanceInitialOAuth','startPortalFinanceGoogleLogin','window.googleLogin']);
 for(const mode of ['reject','throw','error','empty']){oauth=()=>mode==='reject'?Promise.reject(Error('network')):mode==='throw'?(()=>{throw Error('sync');})():Promise.resolve(mode==='error'?{error:{message:'provider',code:'provider_error'}}:{});assert.equal(await c.window.googleLogin(),false);assert.equal(c.financeInitialOAuthAttempt,null);assert.equal(storage.has('pending'),false);assert.equal(busy.at(-1),false);}assert.equal(errors.length,4);pass('first-login rejected/thrown/provider/malformed errors are caught, pending flags cleared and retry enabled');
 const slow=deferred();oauth=()=>slow.promise;calls=0;const pending=c.window.googleLogin();assert.equal(await c.window.googleLogin(),false);assert.equal(await c.startPortalFinanceGoogleLogin('other@example.invalid'),false);await pending;assert.equal(calls,1);assert.equal(c.financeInitialOAuthAttempt,null);assert.equal(errors.at(-1)[1],'CLIENT_TIMEOUT');slow.resolve({data:{url:'https://auth.example.invalid/auth/v1/authorize'}});await tick();assert.equal(destinations.length,0);pass('first and Portal login share singleflight; timeout and late result cannot navigate');
 const argsSeen=[];oauth=async args=>{argsSeen.push(args);return{data:{url:'https://auth.example.invalid/auth/v1/authorize?provider=google'}};};assert.equal(await c.window.googleLogin(),true);assert.equal(argsSeen[0].options.skipBrowserRedirect,true);assert.equal(argsSeen[0].options.queryParams.login_hint,hint);assert.equal(argsSeen[0].options.queryParams.prompt,'select_account');assert.equal(destinations.length,1);assert.equal(busy.at(-1),false);pass('retry uses explicit validated OAuth destination and preserves hint/prompt/redirect');
 for(const url of ['https://evil.example.invalid/auth/v1/authorize','https://auth.example.invalid/wrong','https://user@auth.example.invalid/auth/v1/authorize']){oauth=async()=>({data:{url}});assert.equal(await c.window.googleLogin(),false);}assert.equal(destinations.length,1);pass('invalid OAuth destination never navigates');
 for(const invalidate of [()=>c.financeAuthIdentityEpoch++,()=>{c.S.user={id:'other',email:'other@example.invalid'};},()=>c.cancelFinanceInitialOAuth()]){const d=deferred();oauth=()=>d.promise;const old=c.window.googleLogin();await tick();const before=errors.length;invalidate();d.resolve({data:{url:'https://auth.example.invalid/auth/v1/authorize'}});assert.equal(await old,false);assert.equal(destinations.length,1);assert.equal(errors.length,before);}pass('auth epoch, identity change and account-switch cancellation discard old OAuth success');
 oauth=async()=>({error:{code:'bad_state'}});assert.equal(await c.startPortalFinanceGoogleLogin('portal@example.invalid'),false);assert.equal(storage.has('pending'),false);pass('Portal entry receives the same failure recovery');

 let response,reads=0,renders=0,alerts=[],role='hr',env='real',tenant='tenant-a';
 const users=Array.from({length:9},(_,i)=>({id:'person-'+i,n:'虛構同名',email:'p'+i+'@example.invalid',active:true}));
 const h=install({S:{user:{id:'admin-a',email:'admin-a@example.invalid',authUserId:'uuid-a'},demoLogin:false},USERS:users,financeAuthIdentityEpoch:0,financeWorkspaceIdentityBlocked:false,ROLE_PERMISSIONS:{hr:{users:'write'}},CURRENT_PERMISSION_SNAPSHOT:{loaded:true},FINANCE_GOOGLE_LOGIN_HEALTH_SCOPE:'',FINANCE_GOOGLE_LOGIN_HEALTH:Object.create(null),FINANCE_GOOGLE_LOGIN_HEALTH_READS:Object.create(null),FINANCE_GOOGLE_LOGIN_HEALTH_BATCH:null,FINANCE_GOOGLE_LOGIN_HEALTH_RPC_AVAILABLE:null,FINANCE_GOOGLE_LOGIN_HEALTH_TIMEOUT_MS:20,
 currentFinanceAuthUserId:()=>h.S.user.authUserId,currentTenantId:()=>tenant,activeDataEnvironment:()=>env,currentRoleKey:()=>role,canManageUsers:()=>role==='hr',isCompanyGoogleLoginEmail:()=>true,visiblePersonnelUsers:()=>users,
 normalizeSettingValue:r=>r,orgGoogleLoginReady:()=>false,isRpcMissing:e=>e.code==='PGRST202',financeGoogleLoginStatusPresentation:x=>({label:x.status,detail:x.email}),getSb:()=>({rpc(name,args){assert.equal(name,'finance_admin_google_account_link_status_v2');reads++;return response(args);}}),renderUsers:()=>renders++,renderUsersHealth:()=>renders++,alert:s=>alerts.push(s),window:{},setTimeout,clearTimeout,console},['financeGoogleLoginStatusKey','normalizeFinanceGoogleLoginHealth','withOperationTimeout','financeGoogleLoginHealthIdentity','ensureFinanceGoogleLoginHealthScope','financeGoogleLoginHealthReadCurrent','rememberFinanceGoogleLoginHealth','financeGoogleLoginHealthForUser','fetchFinanceGoogleLoginHealth','window.checkGoogleLoginStatusForUser','window.refreshAllGoogleLoginHealth']);
 response=async()=>({data:{auth_user_id:'fictional-auth',status:'bound'}});await h.window.checkGoogleLoginStatusForUser(users[0].id,{alert:true});assert.equal(reads,1);assert.equal(renders,2);assert.equal(alerts.length,1);pass('authorized scoped health read still updates status and visible result');
 for(const change of [()=>{h.S.user={id:'admin-b',authUserId:'uuid-b',email:'b@example.invalid'};},()=>tenant='tenant-b',()=>env='test',()=>role='employee',()=>h.CURRENT_PERMISSION_SNAPSHOT={loaded:true,permissions:['changed']},()=>h.financeAuthIdentityEpoch++,()=>h.financeWorkspaceIdentityBlocked=true]){role='hr';h.financeWorkspaceIdentityBlocked=false;const d=deferred();response=()=>d.promise;const p=h.window.checkGoogleLoginStatusForUser(users[0].id,{alert:true});await tick();renders=0;alerts=[];change();d.resolve({data:{auth_user_id:'old-private-auth',status:'bound'}});assert.equal(await p,null);assert.equal(renders,0);assert.equal(alerts.length,0);assert.notEqual(h.financeGoogleLoginHealthForUser(users[0]).authUserId,'old-private-auth');}pass('UUID/Finance ID, tenant, environment, role, permissions, epoch and lock changes discard late health and UI');
 role='hr';h.financeWorkspaceIdentityBlocked=false;const batch=deferred();response=()=>batch.promise;reads=0;const bp=h.window.refreshAllGoogleLoginHealth({alert:true});await tick();assert.equal(reads,4);role='employee';batch.resolve({data:{auth_user_id:'old'}});await bp;assert.equal(reads,4);assert.equal(h.FINANCE_GOOGLE_LOGIN_HEALTH_BATCH,null);pass('identity/authority change stops remaining admin batches');
 role='hr';response=()=>new Promise(()=>{});reads=0;await Promise.all([h.fetchFinanceGoogleLoginHealth(users[1]),h.fetchFinanceGoogleLoginHealth(users[1])]);assert.equal(reads,1);assert.equal(h.financeGoogleLoginHealthForUser(users[1]).status,'failed');assert.equal(Object.keys(h.FINANCE_GOOGLE_LOGIN_HEALTH_READS).length,0);pass('health read singleflight and bounded timeout preserve failed state and retry');
 const old=deferred();response=()=>old.promise;const p=h.fetchFinanceGoogleLoginHealth(users[2]);await p;response=async()=>({data:{status:'bound',auth_user_id:'new-auth'}});await h.fetchFinanceGoogleLoginHealth(users[2]);old.resolve({data:{status:'failed'}});await tick();assert.equal(h.financeGoogleLoginHealthForUser(users[2]).authUserId,'new-auth');pass('late timed-out health result cannot replace newer successful retry');
 response=()=>{throw Error('transport throw');};assert.equal((await h.fetchFinanceGoogleLoginHealth(users[3])).health.status,'failed');role='employee';reads=0;await h.fetchFinanceGoogleLoginHealth(users[4]);assert.equal(reads,0);pass('thrown transport is retryable; unauthorized direct reader issues no RPC');
 role='hr';reads=0;response=async()=>({data:{status:'bound'}});const queued=h.fetchFinanceGoogleLoginHealth(users[5]);h.financeAuthIdentityEpoch++;assert.equal((await queued).stale,true);assert.equal(reads,0);pass('identity changed before queued read starts prevents any RPC');
 console.log(`${count} personnel OAuth/health behavior checks passed`);
})().catch(e=>{console.error(e);process.exitCode=1;});
