'use strict';
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const source=fs.readFileSync(path.join(__dirname,'../assets/engines/reporting-workspace.js'),'utf8'),anchor='  global.FinanceReportingWorkspace=api;';assert.equal(source.split(anchor).length,2);
const clone=x=>JSON.parse(JSON.stringify(x)),blank=()=>({schemaVersion:1,accountingFramework:null,tax:{},accountMappings:{},costCenters:[],budgets:[],allocations:[],eliminations:[],periodChecks:{},documents:{}}),response=(revision=1,label='')=>({data:{ok:true,revision,profile:{...blank(),accountingFramework:label||null},canEdit:true,canEditWorkpaper:true}});
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return{promise,resolve,reject};}
function fixture(){const dialog={dataset:{scopeIdentity:'tenant|test|manager|auth-manager|ceo|false|permission-v1',entity:'A',revision:'1',period:'2026-09'},open:true,innerHTML:'',showModal(){this.open=true;},close(){this.open=false;this.closed=(this.closed||0)+1;},setAttribute(){}};const elements={'rpt-ent':{value:'A'},'rpt-month':{value:'2026-09'},'finance-report-dialog':dialog,'finance-report-workspace':{innerHTML:''}},env={user:'manager',auth:'auth-manager',role:'ceo',blocked:false,permissions:'permission-v1',tenant:'tenant',environment:'test',calls:[],rpc:async()=>response()},lastModels=[];
const document={getElementById:id=>elements[id]||null,addEventListener(){},body:{appendChild(node){elements[node.id]=node;}},createElement(){return dialog;}};
const context={console,Map,Set,Intl,AbortController,setTimeout,clearTimeout,document,FormData:class{constructor(f){this.values=f.values||{};}forEach(fn){Object.entries(this.values).forEach(([k,v])=>fn(v,k));}}};context.FinanceManagementReportEngine=require('../assets/engines/management-report-engine.js');context.window=context;
vm.runInNewContext(source.replace(anchor,"  global.__boundary={openSettings,openManagementSettings,onSubmit,saveProfile,profileRecord,profileCopy,reportModel,renderReportBody,currentSheets,reportProfileIds,reportProfilesReady,onAction};\n"+anchor),context);
const runtime={tenant:()=>env.tenant,environment:()=>env.environment,user:()=>({id:env.user,authUserId:env.auth}),role:()=>env.role,identityBlocked:()=>env.blocked,permissionIdentity:()=>env.permissions,today:()=> '2026-09-10',state:()=>env.uiState||({page:'reports'}),entities:()=>[{id:'A',full:'Company A'},{id:'B',full:'Company B'}],departments:()=>[{c:'DA',eid:'A',n:'Dept A'},{c:'DB',eid:'B',n:'Dept B'}],accounts:()=>[],ledger:()=>env.ledger||[],invoices:()=>[],requests:()=>[],completeness:()=>env.completeness||({}),reportProfileEntityIds:()=>env.sourceEntityIds||['A','B'],exportSheets:()=>[{name:'測試報表',rows:[['項目','金額'],['合計',0]]}],statementModel:(e,p,o)=>{lastModels.push({e,p,o});return env.model||{};},rpc:async(n,a)=>{env.calls.push({n,a});return env.rpc(n,a);}};
context.FinanceReportingWorkspace.install(runtime);return{api:context.__boundary,workspace:context.FinanceReportingWorkspace,env,dialog,elements,lastModels,context};}
let total=0,failures=[];async function test(name,fn){try{await fn();console.log('PASS '+name);}catch(e){failures.push({name,message:e.message});console.error('FAIL '+name+': '+e.message);}total++;}
(async()=>{
await test('Changing report company resets stale department filter before computing amounts',async()=>{const f=fixture();await f.workspace.loadProfile('A');await f.workspace.loadProfile('B');f.workspace.state.tab='tax';f.workspace.renderReports();f.workspace.state.department='DA';f.elements['rpt-ent'].value='B';f.workspace.renderReports();assert.equal(f.workspace.state.department,'all');assert.equal(f.lastModels.length,0,'tax tab must not compute unrelated statements');f.api.reportModel({eid:'B',period:'2026-09'});assert.equal(f.lastModels.at(-1).e,'B');assert.equal(f.lastModels.at(-1).o.departmentCode,null);});
await test('complete all-company scope requires source companies including legacy IDs, not unrelated empty companies',async()=>{const f=fixture();f.env.completeness={tables:{ledger:{complete:true}}};f.env.sourceEntityIds=['A','LEGACY'];f.elements['rpt-ent'].value='all';await f.workspace.loadProfile('A');await f.workspace.loadProfile('LEGACY');assert.deepEqual(Array.from(f.api.reportProfileIds({eid:'all'})),['A','LEGACY']);assert.equal(f.api.reportProfilesReady({eid:'all'}),true);assert.equal(f.workspace.profileRecord('B'),null);f.env.rpc=async()=>({error:{message:'scope denied'}});await f.workspace.loadProfile('LEGACY',true);assert.equal(f.api.reportProfilesReady({eid:'all'}),false);assert.equal(f.api.reportProfilesReady({eid:'B'}),false);});
await test('management and full workbook retain a verified 500 budget for a company with no ledger',async()=>{const f=fixture();f.env.completeness={tables:{ledger:{complete:true}}};f.env.sourceEntityIds=['A'];f.elements['rpt-ent'].value='all';f.env.ledger=[{id:'a-dr',eid:'A',dc:'DA',ac:'1112',dr:100,cr:0,date:'2026-09-01'},{id:'a-cr',eid:'A',dc:'DA',ac:'4101',dr:0,cr:100,date:'2026-09-01'}];f.env.model=require('../assets/engines/financial-statements.js').buildModel({ledger:f.env.ledger,entityId:'all',period:'2026-09',completeness:{complete:true}});f.env.rpc=async(_,args)=>{const result=response();if(args.p_entity_id==='B'){result.data.profile.costCenters=[{departmentCode:'DB',kind:'cost'}];result.data.profile.budgets=[{id:'fixture-budget',period:'2026-09',departmentCode:'DB',accountCode:'6202',amount:500,status:'reviewed',reviewedBy:'fixture-reviewer',reviewedAt:'2026-09-01T00:00:00Z',effectiveFrom:'2026-09-01',effectiveTo:'2026-09-30'}];}return result;};await f.workspace.loadProfile('A');assert.equal(f.api.reportProfilesReady({eid:'all'}),true);assert.throws(()=>f.api.currentSheets(),/尚未完整讀取/);f.workspace.state.tab='management';assert.equal(f.api.reportProfilesReady({eid:'all'}),false);await f.workspace.loadProfile('B');assert.equal(f.api.reportProfilesReady({eid:'all'}),true);const workbook=f.api.currentSheets(),row=workbook.find(s=>s.name==='部門管理損益').rows.find(r=>r[0]==='Company B / Dept B');assert(row,'company with a budget but no ledger must remain in the management workbook');assert.deepEqual(Array.from(row.slice(1,7)),[0,0,0,0,0,500]);});
await test('incomplete ledger never runs statement model while rendering loading state',async()=>{const f=fixture();await f.workspace.loadProfile('A');f.env.completeness={tables:{ledger:{complete:false}}};f.workspace.renderReports();assert.equal(f.lastModels.length,0);assert.match(f.elements['finance-report-workspace'].innerHTML,/完整讀取正式分類帳/);});
for(const mode of ['success','failure','identity-change','department-change'])await test('Excel lazy dependency '+mode+' preserves export ordering and identity',async()=>{const f=fixture(),d=deferred();await f.workspace.loadProfile('A');f.env.model=require('../assets/engines/financial-statements.js').buildModel({ledger:[],entityId:'A',period:'2026-09',completeness:{complete:true}});let writes=0,loads=0;f.context.ensureFinanceDocumentLibrary=async name=>{assert.equal(name,'xlsx');loads++;await d.promise;if(mode==='failure')throw Error('Excel download failed');f.context.XLSX={utils:{book_new:()=>({}),aoa_to_sheet:()=>({}),book_append_sheet(){}},writeFile:()=>writes++};};const node={dataset:{rwAction:'export-xlsx'},closest:()=>null};const exporting=f.api.onAction({target:{closest:()=>node}});assert.equal(writes,0);assert.equal(loads,1);if(mode==='identity-change')f.env.auth='new-auth';if(mode==='department-change')f.workspace.state.department='DA';d.resolve();if(mode==='success'){await exporting;assert.equal(writes,1);}else{await assert.rejects(exporting,mode==='failure'?/download failed/:/範圍已變更/);assert.equal(writes,0);}});
for(const mode of ['success','failure','identity-change','department-change','query-change','bucket-change','entity-change','date-change'])await test('Receivable Excel cold-load '+mode+' never exports a changed scope',async()=>{
 const f=fixture(),d=deferred();f.env.uiState={page:'recv',recvEntity:'A'};f.env.rpc=async()=>({data:{complete:true,items:[{invoiceId:'fixture-invoice',invoiceNo:'FIXTURE-ONLY',buyer:'Fictional customer',entityId:'A',departmentCode:'DA',originalAmount:100,outstandingAmount:100}],summary:{},reconciliation:{bankVisible:false}}});
 await f.workspace.loadReceivables(false,{entity:'A',department:'all',asOf:'2026-09-10'});let writes=0,loads=0,exportedRows=[];
 f.context.ensureFinanceDocumentLibrary=async kind=>{assert.equal(kind,'xlsx');loads++;await d.promise;if(mode==='failure')throw Error('Pinned Excel download failed');f.context.XLSX={utils:{book_new:()=>({}),aoa_to_sheet:rows=>{exportedRows=clone(rows);return{}},book_append_sheet(){}},writeFile:()=>writes++};};
 const node={dataset:{rwAction:'export-receivables'},closest:()=>null},pending=f.api.onAction({target:{closest:()=>node}});assert.equal(loads,1);assert.equal(writes,0);
 if(mode==='identity-change')f.env.auth='different-auth';if(mode==='department-change')f.workspace.state.arDepartment='DA';if(mode==='query-change')f.workspace.state.arQuery='another';if(mode==='bucket-change')f.workspace.state.arBucket='open';if(mode==='entity-change')f.env.uiState.recvEntity='B';if(mode==='date-change')f.workspace.state.arAsOf='2026-08-31';
 d.resolve();if(mode==='success'){await pending;assert.equal(writes,1);assert(exportedRows.some(row=>row.includes('FIXTURE-ONLY')));}else{await assert.rejects(pending,mode==='failure'?/download failed/:/應收範圍或搜尋條件已變更/);assert.equal(writes,0);}
});
await test('CAS failure retains form values, keeps dialog open and preserves disabled controls',async()=>{const f=fixture();await f.workspace.loadProfile('A');f.env.rpc=async()=>({error:{message:'版本衝突'}});const status={textContent:''},buttons=[{disabled:true},{disabled:false}],form={dataset:{rwForm:'mapping'},values:{accountCode:'6202',statementClass:'expense',cashFlowClass:'',ociCategory:'',normalSide:'',reason:'keep me'},closest:()=>f.dialog,querySelectorAll:()=>buttons,querySelector:()=>status};await f.api.onSubmit({target:{closest:()=>form},preventDefault(){}});assert.equal(status.textContent,'版本衝突');assert.equal(f.dialog.open,true);assert.equal(f.dialog.closed,undefined);assert.deepEqual(buttons.map(b=>b.disabled),[true,false]);assert.equal(form.values.reason,'keep me');});
await test('Old dialog cannot write after a tenant/user boundary changes',async()=>{const f=fixture(),form={dataset:{},closest:()=>f.dialog};f.env.user='different-user';await assert.rejects(()=>f.api.onSubmit({target:{closest:()=>form},preventDefault(){}}),/登入身分/);assert.equal(f.env.calls.length,0);});
for(const [label,key,value]of [['Google auth UUID','auth','new-auth'],['lowered role','role','employee'],['revoked permission snapshot','permissions','permission-denied'],['identity lock','blocked',true]])await test('Same Finance ID cannot submit old dialog after '+label+' changes',async()=>{const f=fixture(),form={dataset:{},closest:()=>f.dialog};f.env[key]=value;await assert.rejects(()=>f.api.onSubmit({target:{closest:()=>form},preventDefault(){}}),/登入身分/);assert.equal(f.env.calls.length,0);});
await test('Read response cannot overwrite a profile revision saved while read was pending',async()=>{const f=fixture(),read=deferred();f.env.rpc=(n)=>n==='finance_reporting_profile_read_v1'?read.promise:Promise.resolve(response(3,'eas'));const pending=f.workspace.loadProfile('A');await f.api.saveProfile('A',blank(),'save',2);read.resolve(response(2,'ifrs'));await pending;assert.equal(f.api.profileRecord('A').revision,3);});
await test('Old identity response cannot populate the new identity cache',async()=>{const f=fixture(),read=deferred();f.env.rpc=()=>read.promise;const old=f.workspace.loadProfile('A');f.env.user='new-user';f.workspace.profileRecord('B');read.resolve(response(1,'eas'));await old;assert.equal(f.api.profileRecord('A'),null);});
await test('Most recent company settings action wins over a slower earlier action',async()=>{const f=fixture(),a=deferred(),b=deferred();f.env.rpc=(_n,args)=>args.p_entity_id==='A'?a.promise:b.promise;const old=f.api.openSettings('A'),latest=f.api.openSettings('B');b.resolve(response(1));await latest;a.resolve(response(1));await old;assert.equal(f.dialog.dataset.entity,'B');assert(f.dialog.innerHTML.includes('Company B'));});
await test('Delayed save response cannot roll back a newer refreshed cache revision',async()=>{const f=fixture(),save=deferred();f.env.rpc=(n)=>n==='finance_reporting_profile_save_v1'?save.promise:Promise.resolve(response(4,'ifrs'));const old=f.api.saveProfile('A',blank(),'save',2);await f.workspace.loadProfile('A',true);save.resolve(response(3,'eas'));await old;assert.equal(f.api.profileRecord('A').revision,4);assert.equal(f.api.profileRecord('A').profile.accountingFramework,'ifrs');});
await test('Delayed receivable metadata success cannot close a newer company dialog or start a stale refresh',async()=>{const f=fixture(),save=deferred();f.env.rpc=(name)=>name==='finance_update_receivable_terms_v1'?save.promise:Promise.resolve(response());const form={dataset:{rwForm:'receivable-terms',invoice:'invoice-A',version:'4',operationKey:'fixture-operation'},values:{dueDate:'2026-09-30',notes:'Keep original record',reason:'Verified contract'},closest:()=>f.dialog,querySelectorAll:()=>[],querySelector:()=>({textContent:''})};const pending=f.api.onSubmit({target:{closest:()=>form},preventDefault(){}});assert.equal(f.env.calls[0].n,'finance_update_receivable_terms_v1');await f.api.openSettings('B');save.resolve({data:{ok:true,invoiceId:'invoice-A',metadataVersion:5}});await pending;assert.equal(f.dialog.open,true);assert.equal(f.dialog.closed,undefined);assert.equal(f.dialog.dataset.entity,'B');assert(f.dialog.innerHTML.includes('Company B'));assert.equal(f.env.calls.filter(c=>c.n==='finance_receivables_v1').length,0);});
await test('Delayed profile save success cannot close or replace a newer company dialog',async()=>{const f=fixture(),save=deferred();await f.workspace.loadProfile('A');f.env.rpc=name=>name==='finance_reporting_profile_save_v1'?save.promise:Promise.resolve(response());const form={dataset:{rwForm:'mapping'},values:{accountCode:'6202',statementClass:'expense',cashFlowClass:'',ociCategory:'',normalSide:'',reason:'Mapping review'},closest:()=>f.dialog,querySelectorAll:()=>[],querySelector:()=>({textContent:''})};const pending=f.api.onSubmit({target:{closest:()=>form},preventDefault(){}});await f.api.openSettings('B');save.resolve(response(2));await pending;assert.equal(f.dialog.open,true);assert.equal(f.dialog.closed,undefined);assert.equal(f.dialog.dataset.entity,'B');assert(f.dialog.innerHTML.includes('Company B'));});
for(const domain of ['profile','receivables'])for(const order of ['old-first','new-first'])await test(domain+' forced read starts a fresh generation and preserves latest snapshot ('+order+')',async()=>{const f=fixture(),first=deferred(),second=deferred(),scope={entity:'A',department:'all',asOf:'2026-09-10'};let reads=0;const readName=domain==='profile'?'finance_reporting_profile_read_v1':'finance_receivables_v1',load=force=>domain==='profile'?f.workspace.loadProfile('A',force):f.workspace.loadReceivables(force,scope),get=()=>domain==='profile'?f.api.profileRecord('A'):f.workspace.receivablesForScope(scope),result=value=>domain==='profile'?response(value):{data:{complete:true,items:[{invoiceId:'A',outstandingAmount:value}],asOf:scope.asOf}};f.env.rpc=name=>{assert.equal(name,readName);reads++;return reads===1?first.promise:second.promise;};const old=load(false),latest=load(true);assert.equal(reads,2,'force must issue a new RPC instead of sharing the pre-mutation promise');if(order==='old-first'){first.resolve(result(1));await old;assert.equal(get(),null,'older read must not expose a stale snapshot while new generation is pending');const shared=load(false);assert.equal(reads,2,'older finally must not remove the newer pending promise');second.resolve(result(4));await Promise.all([latest,shared]);}else{second.resolve(result(4));await latest;first.resolve(result(1));await old;}if(domain==='profile')assert.equal(get().revision,4);else assert.equal(get().items[0].outstandingAmount,4);});
await test('Pre-mutation profile read cannot replace post-save forced read or lower its revision',async()=>{const f=fixture(),oldRead=deferred(),newRead=deferred();let reads=0;f.env.rpc=name=>name==='finance_reporting_profile_save_v1'?Promise.resolve(response(3,'eas')):++reads===1?oldRead.promise:newRead.promise;const pending=f.workspace.loadProfile('A');await f.api.saveProfile('A',blank(),'Audited change',2);const refreshed=f.workspace.loadProfile('A',true);assert.equal(reads,2);newRead.resolve(response(4,'ifrs'));await refreshed;oldRead.resolve(response(2,'eas'));await pending;assert.equal(f.api.profileRecord('A').revision,4);assert.equal(f.api.profileRecord('A').profile.accountingFramework,'ifrs');});
await test('Missing or denied company profiles prevent amount rendering and workbook construction',async()=>{const f=fixture(),scope={eid:'A',period:'2026-09'};for(const state of ['missing','denied']){if(state==='denied'){f.env.rpc=async()=>({error:{message:'scope denied'}});await f.workspace.loadProfile('A',true);}const html=f.api.renderReportBody(scope,{completeness:{complete:true},current:{bs:{assetTotal:987654321}}});assert.match(html,/正在讀取公司報表設定/);assert(!html.includes('987654321'));assert.throws(()=>f.api.currentSheets(),/尚未完整讀取/);}});
await test('Incomplete ledger with loaded profile prevents amount rendering and workbook construction',async()=>{const f=fixture();await f.workspace.loadProfile('A');const html=f.api.renderReportBody({eid:'A',period:'2026-09'},{completeness:{complete:false},current:{bs:{assetTotal:987654321}}});assert.match(html,/正式分類帳/);assert(!html.includes('987654321'));assert.throws(()=>f.api.currentSheets(),/尚未完整讀取/);});
console.log(JSON.stringify({ok:!failures.length,total,failures,productionHooksAdded:0}));if(failures.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
