'use strict';
// Exact shipped helpers and async callers, with the checked-in Edge schema.
// All transport/file boundaries are fictional; no OpenAI, Storage or DB writes.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'index.html'),'utf8');
const edge=fs.readFileSync(path.join(root,'supabase/functions/parse-invoice-openai/index.ts'),'utf8');
function declaration(name,window=false){let start=source.indexOf(window?'window.'+name+'=':'function '+name+'(');assert.ok(start>=0,name);if(!window&&source.slice(start-6,start)==='async ')start-=6;for(let i=source.indexOf('{',start);i<source.length;i++){if(source[i]!=='}')continue;const code=source.slice(start,i+1)+(window?';':'');try{new vm.Script(code);return code;}catch{}}throw Error(name);}
const schema=vm.runInNewContext(edge.slice(edge.indexOf('  const invoiceSchema ='),edge.indexOf('  const hrLaborSchema ='))+'\ninvoiceSchema');
let count=0;function check(label,fn){fn();count++;console.log('PASS '+label);}const plain=x=>JSON.parse(JSON.stringify(x));
function payload(net=210,tax=0,total=210,items=[]){const data=Object.fromEntries(Object.entries(schema.properties).map(([key,def])=>[key,def.type==='string'?'':def.type==='number'?0:[]]));Object.assign(data,{buyer_name:'虛構買受人',description:'九月服務合計',amount_excluding_tax:net,tax_amount:tax,total_amount:total,items,confidence:1,currency:'TWD'});return data;}
function item(name,gross){return Object.fromEntries(Object.entries(schema.properties.items.items.properties).map(([key,def])=>[key,key==='item_name'?name:key==='total_amount'?gross:key==='quantity'?1:def.type==='string'?'次':gross]));}
function fixture(){const dom=Object.fromEntries(['inv-no','inv-buyer','inv-taxid','inv-identifier-type','inv-date','inv-amt','inv-tax','inv-total','inv-desc','inv-item-type','batch-pw','batch-prog','batch-pl'].map(id=>[id,{value:'original',textContent:'',style:{}}]));
 const c={console,Number,Math,Array,JSON,String,Error,Promise,el:id=>dom[id],num:x=>Number(x||0),fmt:x=>String(x),invoiceItemTypeFromText:()=> 'other_income',updInvPrev(){},S:{bRows:[{buyer:'原資料',amt:50,total:50,tax:0}],bUploadFile:{name:'fictional.pdf',type:'application/pdf'},invOcrFile:{name:'fictional.pdf',type:'application/pdf'}},productModuleEnabled:()=>true,OPENAI_INVOICE_OCR_ENDPOINT:'https://example.invalid/ocr',SUPABASE_ANON_KEY:'fictional',fileToAttachment:async()=>({n:'fictional.pdf',mime:'application/pdf',url:'data:application/pdf;base64,UEZERklDVFVSRQ=='}),setInvOcrStatus:(text)=>{c.status=text;},ocrErrorMessage:e=>e.message,renderBatchTable:()=>{c.renderCount++;},defaultInvoiceBatchRow:()=>({}),renderCount:0,fetch:async()=>({ok:true,json:async()=>({invoice:c.response})}),alert:x=>{throw Error('Unexpected alert '+x);}};c.window=c;vm.createContext(c);
 for(const name of ['invoiceOcrReviewError','invoiceOcrNumber','invoiceOcrAmountParts','invoiceNumberValue','invoiceRateValue','invoiceAmountsFromTotal','applyInvoiceOcr','invoiceOcrDataToBatchRows'])vm.runInContext(declaration(name),c);
 for(const name of ['calcInvTax','analyzeSingleInvoiceFile','analyzeBatchInvoiceUpload'])vm.runInContext(declaration(name,true),c);return {c,dom};}
(async()=>{const {c,dom}=fixture();
 check('fixture is exact real Edge schema with item_name and no invented tax_rate',()=>{assert.equal(schema.properties.tax_rate,undefined);assert.ok(schema.properties.items.items.properties.item_name);assert.deepEqual(Object.keys(payload()).sort(),Array.from(schema.required).sort());});
 check('zero-tax batch preserves two source item names and all three amount totals',()=>{const rows=c.invoiceOcrDataToBatchRows({invoice:payload(210,0,210,[item('服務甲',100),item('服務乙',110)])});assert.deepEqual(plain(rows.map(r=>[r.desc,r.amt,r.tax,r.total,r.rate])),[['服務甲',100,0,100,0],['服務乙',110,0,110,0]]);});
 check('5% batch preserves document and row net/tax/gross',()=>{const rows=c.invoiceOcrDataToBatchRows({invoice:payload(300,15,315,[item('甲',105),item('乙',210)])});assert.deepEqual(plain(rows.map(r=>[r.amt,r.tax,r.total,r.rate])),[[100,5,105,.05],[200,10,210,.05]]);});
 for(const rate of [0,'0','0%'])check('explicit zero rate remains zero '+rate,()=>assert.equal(c.invoiceOcrDataToBatchRows({...payload(),tax_rate:rate})[0].tax,0));
 for(const rate of [.05,5,'5%'])check('explicit five percent agrees with source '+rate,()=>assert.equal(c.invoiceOcrAmountParts({...payload(200,10,210),tax_rate:rate}).tax,10));
 check('missing net derives only from explicit total and tax',()=>assert.deepEqual(plain(c.invoiceOcrAmountParts({tax_amount:0,total_amount:210})),{amount:210,tax:0,total:210,rate:0}));
 check('missing tax derives from explicit net and gross',()=>assert.equal(c.invoiceOcrAmountParts({amount_excluding_tax:200,total_amount:210}).tax,10));
 check('missing gross derives from explicit net and tax',()=>assert.equal(c.invoiceOcrAmountParts({amount_excluding_tax:200,tax_amount:10}).total,210));
 check('explicit rate allows a total-only source without defaulting unknown tax',()=>assert.equal(c.invoiceOcrAmountParts({total_amount:210,tax_rate:0}).amount,210));
 check('blank/null aliases are missing but primary zero is retained',()=>assert.equal(c.invoiceOcrAmountParts({amount_excluding_tax:0,subtotal:null,tax_amount:'',total_amount:0}).total,0));
 check('valid grouped numeric strings keep original amounts',()=>assert.equal(c.invoiceOcrAmountParts({amount_excluding_tax:'1,234',tax_amount:'0',total_amount:'1,234'}).total,1234));
 check('single source cents preserved when the actual form can represent them',()=>{c.applyInvoiceOcr(payload(100.5,5,105.5));assert.equal(Number(dom['inv-total'].value),105.5);});
 check('single zero replaces old input rather than resurrecting prior amount',()=>{c.applyInvoiceOcr(payload(0,0,0));assert.equal(Number(dom['inv-amt'].value),0);assert.equal(Number(dom['inv-total'].value),0);});
 check('single total plus explicit zero tax remains 210',()=>{c.applyInvoiceOcr({buyer_name:'新買受人',total_amount:210,tax_amount:0});assert.equal(Number(dom['inv-total'].value),210);assert.equal(dom['inv-tax'].value,'0');});
 const bad=[{}, {total_amount:210}, {amount_excluding_tax:0,tax_amount:0,total_amount:210}, {...payload(),tax_rate:5}, {...payload(),subtotal:200}, {...payload(),tax_amount:null,amount_excluding_tax:null}, {...payload(),total_amount:-1}, {...payload(),tax_amount:'not a number'}, {...payload(),tax_amount:true}, {...payload(),total_amount:Infinity}, {...payload(200,20,220),tax_rate:10}, {...payload(200,9,210)}, {...payload(),tax_rate:'NaN'}, {...payload(),total_amount:'2,10'}, {amount_excluding_tax:Number.MAX_SAFE_INTEGER,tax_amount:Math.round(Number.MAX_SAFE_INTEGER*.05)}];
 bad.forEach((input,i)=>check('ambiguous/invalid source '+i+' never partly changes any input',()=>{const before=plain(dom);assert.throws(()=>c.applyInvoiceOcr(input),e=>e.code==='INVOICE_OCR_REVIEW_REQUIRED'&&/人工核對/.test(e.message));assert.deepEqual(plain(dom),before);}));
 check('inconsistent item total rejects the complete result',()=>assert.throws(()=>c.invoiceOcrDataToBatchRows(payload(210,0,210,[item('甲',100)])),/合計/));
 check('document tax rounding cannot silently change after a two-row split',()=>assert.throws(()=>c.invoiceOcrDataToBatchRows(payload(19,1,20,[item('甲',10),item('乙',10)])),e=>e.code==='INVOICE_OCR_REVIEW_REQUIRED'&&/稅額/.test(e.message)));
 check('nonrepresentable batch decimal rejects rather than rounding source',()=>assert.throws(()=>c.invoiceOcrDataToBatchRows(payload(100.5,5,105.5)),/原樣/));
 c.response=payload(210,0,210,[item('甲',100),item('乙',110)]);await c.analyzeBatchInvoiceUpload();check('actual async batch caller applies valid schema rows only once',()=>{assert.equal(c.renderCount,1);assert.deepEqual(plain(c.S.bRows.map(r=>r.desc)),['甲','乙']);assert.match(dom['batch-pl'].textContent,/已填入 2 列/);});
 const previous=plain(c.S.bRows);c.response=payload(0,0,210);await c.analyzeBatchInvoiceUpload();check('actual async batch caller keeps previous rows and exposes actionable ambiguity',()=>{assert.deepEqual(plain(c.S.bRows),previous);assert.equal(c.renderCount,1);assert.match(dom['batch-pl'].textContent,/人工核對/);});
 const oldInputs=plain(dom);await c.analyzeSingleInvoiceFile();check('actual async single caller does not claim completion after rejection',()=>{assert.deepEqual(plain(dom),oldInputs);assert.match(c.status,/人工核對/);assert.doesNotMatch(c.status,/已回填/);});
 c.response=payload(200,10,210);await c.analyzeSingleInvoiceFile();check('actual async single caller preserves 5% control',()=>{assert.equal(Number(dom['inv-amt'].value),200);assert.equal(Number(dom['inv-total'].value),210);assert.equal(dom['inv-tax'].value,'5');assert.match(c.status,/已回填/);});
 console.log('Invoice OCR contract: '+count+' checks PASS');
})().catch(e=>{console.error(e);process.exitCode=1;});
