'use strict';
// Two immutable source variants over the same gzip server and controlled link.
// Anonymous only. Optional document tools are tested with generated local files.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),zlib=require('node:zlib'),{execFileSync}=require('node:child_process'),assert=require('node:assert/strict');
const {chromium}=require('playwright');const {applyBuildEnvironment}=require('./finance_build_environment');
const root=path.resolve(__dirname,'..'),base='5cf8751f7cdd1ec7ac745379a017c542aa3351a3',out=process.env.FINANCE_PERF_EVIDENCE_DIR||'/tmp/finance-three-second-browser-20260913';fs.mkdirSync(out,{recursive:true});
const cache=new Map();function bytes(version,file){const key=version+'/'+file;if(cache.has(key))return cache.get(key);let value=version==='before'?execFileSync('git',['show',base+':'+file],{cwd:root,maxBuffer:10*1024*1024}):fs.readFileSync(path.join(root,file));if(file==='index.html'){value=applyBuildEnvironment(value.toString(),{target:'local',supabaseUrl:'',supabaseAnonKey:''}).replace('bootAuthGate();\n\n})();',"window.__readLatencyQA={run:async function(code){return await eval(code)}};\nbootAuthGate();\n\n})();");}value=Buffer.from(value);cache.set(key,value);return value;}
const server=http.createServer((req,res)=>{try{const parts=new URL(req.url,'http://local').pathname.split('/').filter(Boolean),version=parts.shift();if(!['before','after'].includes(version))throw Error('route');const file=parts.join('/')||'index.html';if(file.includes('..')||(!file.startsWith('assets/')&&file!=='index.html'))throw Error('path');const content=bytes(version,file),type=file.endsWith('.html')?'text/html':file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'application/octet-stream',body=zlib.gzipSync(content);res.writeHead(200,{'Content-Type':type,'Content-Encoding':'gzip','Cache-Control':'no-store'});res.end(body);}catch(e){res.writeHead(404);res.end('Not found');}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;if(process.argv.includes('--serve')){console.log(origin+'/after/');return;}const browser=await chromium.launch({headless:true,channel:'chrome'}),runs=[];let passed=0;
 try{for(const version of ['before','after']){const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),page=await context.newPage(),errors=[],denied=[],documentRequests=[];
 page.on('pageerror',e=>errors.push(e.message));context.on('request',r=>{if(/\/npm\/(xlsx|pdf-lib|jspdf)@/.test(r.url()))documentRequests.push(r.url());});await context.route('**/*',route=>{const r=route.request();if(!['GET','HEAD'].includes(r.method())||/\/rest\/v1\//.test(r.url())){denied.push(r.method()+' '+new URL(r.url()).pathname);return route.abort();}return route.continue();});
 const cdp=await context.newCDPSession(page);await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:150,downloadThroughput:4*1024*1024/8,uploadThroughput:1024*1024/8,connectionType:'cellular4g'});await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});
 await page.goto(origin+'/'+version+'/',{waitUntil:'domcontentloaded',timeout:60000});await page.waitForFunction(()=>document.querySelector('#login-screen')?.getClientRects().length&&typeof window.googleLogin==='function');
 const timing=await page.evaluate(()=>({bootstrapReadyMs:performance.now(),firstPaintMs:performance.getEntriesByType('paint').find(x=>x.name==='first-contentful-paint')?.startTime,transferBytes:performance.getEntriesByType('navigation').concat(performance.getEntriesByType('resource')).reduce((n,x)=>n+(x.transferSize||0),0),width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));runs.push({version,...timing,documentRequestsAtLogin:[...documentRequests]});assert.equal(timing.width,timing.scrollWidth);assert.deepEqual(errors,[]);assert.deepEqual(denied,[]);passed++;
 await page.screenshot({path:path.join(out,version+'-login-390.png'),fullPage:true});
 if(version==='after'){
  assert.equal(documentRequests.length,0);passed++;
  await page.evaluate(()=>Promise.all([window.ensureFinanceDocumentLibrary('xlsx'),window.ensureFinanceDocumentLibrary('xlsx')]));assert.equal(documentRequests.filter(s=>s.includes('/xlsx@')).length,1);passed++;
  const rows=await page.evaluate(()=>window.__readLatencyQA.run("(async function(){var book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([['目的','金額'],['匿名測試',136]]),'Data');var file=new File([XLSX.write(book,{type:'array',bookType:'xlsx'})],'sample.xlsx');return await readSpreadsheetRows(file);})()"));assert.deepEqual(rows,[['目的','金額'],['匿名測試','136']]);passed++;
  const pdf=await page.evaluate(()=>window.__readLatencyQA.run("(async function(){await ensureFinanceDocumentLibrary('pdf');var files=[];for(var i=0;i<2;i++){var p=await PDFLib.PDFDocument.create();p.addPage([200+i,200]);var bytes=await p.save();files.push({n:'local-'+i+'.pdf',t:'pdf',url:'data:application/pdf;base64,'+btoa(String.fromCharCode.apply(null,bytes))});}var result=await receiptPdfAttachment(files,{no:'LOCAL'});var verified=await PDFLib.PDFDocument.load(result.url.split(',')[1]);return {sources:result.sourceCount,pages:verified.getPageCount()};})()"));assert.deepEqual(pdf,{sources:2,pages:2});assert.equal(documentRequests.filter(s=>s.includes('/pdf-lib@')).length,1);assert.equal(documentRequests.filter(s=>s.includes('/jspdf@')).length,0);passed++;
  assert.deepEqual(errors,[]);assert.deepEqual(denied,[]);
 }
 await context.close();}
 assert(runs[1].bootstrapReadyMs<runs[0].bootstrapReadyMs,'the same controlled link must improve');passed++;
 fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify({scope:'Anonymous offline-build bootstrap on loopback gzip, cold cache, 150ms RTT,4Mbps down,CPU4x. Not actual employee latency. Before is immutable Git source; after current source. Document functionality uses real pinned libraries and generated files.',base,passed,runs},null,2));console.log(JSON.stringify({passed,runs},null,2));
 }finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);server.close();process.exitCode=1});
