// Executable identity-race checks of the shipped readback/retry/outbox functions.
// Fictional source records and deferred transports; no network or DB writes.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
function fn(name){const start=source.search(new RegExp('^(?:async )?function '+name+'\\(','m'));assert.ok(start>=0,name);const rest=source.slice(start),next=rest.slice(1).search(/^(?:(?:async )?function |window\.|var )/m);return rest.slice(0,next<0?undefined:next+1);}
function windowAssignment(name,nextMarker){const start=source.indexOf('window.'+name+'=async function(){');const end=source.indexOf(nextMarker,start);assert.ok(start>=0&&end>start,name);return source.slice(start,end);}
function install(ctx,names){vm.createContext(ctx);for(const name of names)vm.runInContext(fn(name),ctx);return ctx;}
const base=['currentFinanceAuthUserId','expenseSubmissionOperationIdentity','expenseSubmissionOperationCurrent','expenseSubmissionIdentityChanged','expenseSubmissionStatementCanceled'];
const record=()=>({id:'r-a',no:'TEST-A',applicantId:'person-a',app:'匿名員工甲',eid:'E1',dc:'D1',type:'expense_reimbursement',amt:100,tenantId:'tenant-a',dataEnv:'production',files:[],formPayload:{submissionAttemptId:'attempt-a'}});
const user=()=>({id:'person-a',authUserId:'auth-a',email:'a@example.invalid',role:'employee',active:true});
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
const tick=()=>new Promise(resolve=>setImmediate(resolve));
let checks=0;const pass=n=>{checks++;console.log('PASS '+n);};
function fixture(names=[]){let tenant='tenant-a',env='production';const counts={reads:0,merged:0,writes:0,cleanup:0,clear:0,finalize:0};
 const pending={tenantId:tenant,dataEnv:env,applicantId:'person-a',requestId:'r-a',requestNo:'TEST-A',attemptId:'attempt-a',expected:record(),retryRecord:record()};
 const c=install({S:{user:user(),demoLogin:false,nrSubmissionConfirmationPending:pending},financeWorkspaceIdentityBlocked:false,currentTenantId:()=>tenant,activeDataEnvironment:()=>env,
  supabaseAuthErrorInfo:error=>({code:error&&error.code||'',message:error&&error.message||''}),
  num:v=>Number(v)||0,mapReq:r=>r,REQS:[],expenseRevisionContainsFilePaths:()=>true,withAbortableOperationTimeout:p=>p,withOperationTimeout:p=>p,
  mergeCommittedExpenseRequest:r=>{counts.merged++;return r;},clearExpenseSubmissionPending:()=>{counts.clear++;c.S.nrSubmissionConfirmationPending=null;},loadExpenseSubmissionPending:()=>pending,
  verifyPendingExpenseAttachmentPaths:async()=>({state:'present',missing:[]}),cleanupUnclaimedExpenseRepairUploads:async()=>0,
  finalizeRecoveredExpenseSubmission:async()=>{counts.finalize++;return {state:'committed'};},cleanupUploadedSupabaseAttachments:async()=>{counts.cleanup++;},recordOpsEvent(){},console,setTimeout:(f)=>setTimeout(f,0),clearTimeout,
 },[...base,...names]);
 return {c,counts,pending,env:value=>env=value,tenant:value=>tenant=value,switch:()=>{c.S.user={...user(),id:'person-b',authUserId:'auth-b',email:'b@example.invalid'};c.S.nrSubmissionConfirmationPending={requestId:'r-b',attemptId:'attempt-b'};}};
}
function readTransport(f){const d=deferred();f.c.getSb=()=>({from(){f.counts.reads++;return{select(){return this},eq(){return this},limit(){return d.promise}}}});return d;}
(async()=>{
 for(const change of ['auth','tenant','env','blocked']){
  const f=fixture(['expenseSubmissionRecordMatches','readExpenseSubmissionCommit']);const d=readTransport(f);const run=f.c.readExpenseSubmissionCommit(record());
  if(change==='auth')f.switch();if(change==='tenant')f.tenant('tenant-b');if(change==='env')f.env('test');if(change==='blocked')f.c.financeWorkspaceIdentityBlocked=true;
  d.resolve({data:[record()],error:null});const r=await run;assert.equal(r.identityChanged,true);assert.equal(f.counts.merged,0);assert.equal(r.record,undefined);pass('late committed read '+change+' change: no merge or returned old record');
 }
 {const f=fixture(['expenseSubmissionRecordMatches','readExpenseSubmissionCommit']);const d=readTransport(f),run=f.c.readExpenseSubmissionCommit(record());d.resolve({data:[record()],error:null});assert.equal((await run).state,'committed');assert.equal(f.counts.merged,1);pass('unchanged owner can read and merge exact committed attempt');}
 {const f=fixture(['expenseSubmissionRecordMatches','readExpenseSubmissionCommit']);readTransport(f);assert.equal((await f.c.readExpenseSubmissionCommit({...record(),applicantId:'person-b'})).identityChanged,true);assert.equal(f.counts.reads,0);pass('different applicant blocked before any read');}
 {const f=fixture(['readExpenseSubmissionCommitWithDelays']);let resolveTimer;f.c.setTimeout=resolve=>{resolveTimer=resolve};f.c.readExpenseSubmissionCommit=async()=>{f.counts.reads++;return{state:'absent'}};const run=f.c.readExpenseSubmissionCommitWithDelays(record(),[1]);f.switch();resolveTimer();assert.equal((await run).identityChanged,true);assert.equal(f.counts.reads,0);pass('identity switch while delay waits causes zero query');}
 for(const code of ['57014','CLIENT_TIMEOUT']){
  const f=fixture(['expenseApplicantRevisionRpcErrorIsAmbiguous','readExpenseSubmissionCommitWithDelays']);
  f.c.supabaseAuthErrorInfo=error=>({code:error.code,status:0,message:error.message});
  f.c.readExpenseSubmissionCommit=async()=>{f.counts.reads++;return f.counts.reads===1?{state:'unknown',error:{code,message:'statement timeout'}}:{state:'committed',record:record()}};
  const result=await f.c.readExpenseSubmissionCommitWithDelays(record(),[0,1]);
  assert.equal(result.state,'committed');assert.equal(f.counts.reads,2);
  assert.equal(f.counts.writes,0);assert.equal(f.counts.cleanup,0);assert.equal(f.counts.clear,0);
  pass('transient '+code+' readback retries exact request without write or cleanup');
 }
 {const f=fixture(['expenseApplicantRevisionRpcErrorIsAmbiguous','readExpenseSubmissionCommitWithDelays']);f.c.supabaseAuthErrorInfo=error=>({code:error.code,status:403,message:error.message});f.c.readExpenseSubmissionCommit=async()=>{f.counts.reads++;return{state:'unknown',error:{code:'42501',message:'permission denied'}}};const result=await f.c.readExpenseSubmissionCommitWithDelays(record(),[0,1]);assert.equal(result.state,'unknown');assert.equal(f.counts.reads,1);assert.equal(f.counts.clear,0);pass('authorization failure stops readback retries and keeps pending lock');}
 {const f=fixture(['expenseApplicantRevisionRpcErrorIsAmbiguous','readExpenseSubmissionCommitWithDelays']);f.c.supabaseAuthErrorInfo=error=>({code:error.code,status:500,message:error.message});f.c.readExpenseSubmissionCommit=async()=>{f.counts.reads++;return{state:'unknown',error:{code:'EXPENSE_SUBMISSION_ID_COLLISION',message:'network collision'}}};const result=await f.c.readExpenseSubmissionCommitWithDelays(record(),[0,1]);assert.equal(result.error.code,'EXPENSE_SUBMISSION_ID_COLLISION');assert.equal(f.counts.reads,1);assert.equal(f.counts.writes,0);pass('request identity collision never retries even if error looks transient');}
 {const f=fixture(['expenseSubmissionRecoveryPanelHtml','nrSubmitActionsHtml']);f.c.isExpenseApplicantRevisionMode=()=>false;f.c.escAttr=value=>String(value);const html=f.c.nrSubmitActionsHtml();assert.match(html,/前次送件待確認/);assert.match(html,/confirmPendingExpenseSubmission\(\)/);assert.match(html,/事件識別：attempt-a/);assert.doesNotMatch(html,/onclick="submitNR\(\)"/);assert.match(source,/id="nr-submission-recovery" hidden aria-live="polite"/);pass('durable pending replaces submit action with same-attempt confirmation on original request page');}
 {const f=fixture(['buildNR']);const originalFiles=[{name:'receipt.pdf'}],originalPassbook={name:'passbook.pdf'};f.c.S.nrType='expense_reimbursement';f.c.S.nrStep=3;f.c.S.nrFiles=originalFiles;f.c.S.nrPassbookFile=originalPassbook;let rendered=0,refreshed=0,childCount=1;f.c.el=()=>({childElementCount:childCount});f.c.renderNR=()=>{rendered++};f.c.refreshExpenseSubmissionRecoveryActions=()=>{refreshed++};f.c.buildNR();assert.equal(refreshed,1);assert.equal(rendered,0);assert.equal(f.c.S.nrType,'expense_reimbursement');assert.equal(f.c.S.nrStep,3);assert.equal(f.c.S.nrFiles,originalFiles);assert.equal(f.c.S.nrPassbookFile,originalPassbook);childCount=0;f.c.buildNR();assert.equal(rendered,1);assert.equal(f.c.S.nrFiles,originalFiles);pass('re-entering New Request preserves pending live form and only renders an empty recovery page after reload');}
 {const f=fixture(['expenseSubmissionPendingStorageKey','expenseSubmissionPendingInCurrentScope','loadExpenseSubmissionPending','reconcilePendingExpenseSubmission']);f.c.EXPENSE_SUBMISSION_PENDING_KEY_BASE='test_pending';const storage=new Map();f.c.sessionGetItem=key=>storage.get(key)||null;f.c.safeJsonGet=()=>null;storage.set(f.c.expenseSubmissionPendingStorageKey(),JSON.stringify(f.pending));f.c.S.user={...user(),id:'person-b',authUserId:'auth-b',email:'b@example.invalid'};assert.equal(f.c.loadExpenseSubmissionPending(),null);assert.equal(f.c.S.nrSubmissionConfirmationPending,null);f.c.readExpenseSubmissionCommitWithDelays=()=>{throw Error('old account must not read')};assert.equal((await f.c.reconcilePendingExpenseSubmission({allowRetry:true})).state,'none');f.c.S.user=user();assert.equal(f.c.loadExpenseSubmissionPending().requestId,f.pending.requestId);assert.match(source,/function clearFinanceLoginState\(\)[\s\S]*?S\.nrSubmissionConfirmationPending=null;[\s\S]*?S\.user=null;/);pass('account switch discards only old in-memory pointer and original owner reloads scoped pending');}
 {const f=fixture(['reconcilePendingExpenseSubmission']);let guarded=0;f.c.guardSubmissionIdentityDirectory=async()=>{guarded++;return false};f.c.readExpenseSubmissionCommitWithDelays=async()=>({state:'committed',record:record()});assert.equal((await f.c.reconcilePendingExpenseSubmission({allowRetry:true,requireDirectoryForRetry:true})).state,'committed');assert.equal(guarded,0);assert.equal(f.counts.finalize,1);pass('exact-ID committed readback completes before any slow directory sync');}
 {const f=fixture(['reconcilePendingExpenseSubmission']);let guarded=0,writes=0;f.c.guardSubmissionIdentityDirectory=async()=>{guarded++;return false};f.c.readExpenseSubmissionCommitWithDelays=async()=>({state:'absent'});f.c.submitExpenseRequestWithAmbiguousRecovery=async()=>{writes++;return{ok:true}};const result=await f.c.reconcilePendingExpenseSubmission({allowRetry:true,requireDirectoryForRetry:true});assert.equal(result.state,'unknown');assert.equal(result.reason,'directory_unavailable_retry_deferred');assert.equal(guarded,1);assert.equal(writes,0);assert.equal(f.counts.clear,0);pass('directory check only gates same-ID retry after confirmed-absent readback');}
 {const f=fixture(['reconcilePendingExpenseSubmission','expenseSubmissionRecoveryPanelHtml','nrSubmitActionsHtml']);const originalFiles=[{path:'test/original-receipt.pdf'}],originalPassbook={path:'test/original-passbook.pdf'};f.pending.retryRecord.files=originalFiles;f.pending.retryRecord.passbookFiles=[originalPassbook];f.c.S.nrFiles=originalFiles;f.c.S.nrPassbookFile=originalPassbook;f.c.readExpenseSubmissionCommitWithDelays=async()=>({state:'absent'});let retriedRecord,retryOptions;f.c.submitExpenseRequestWithAmbiguousRecovery=async(r,_label,options)=>{retriedRecord=r;retryOptions=options;return{ok:false,unknown:false,error:Error('rejected')}};const result=await f.c.reconcilePendingExpenseSubmission({allowRetry:true,retainAttachmentsOnFailure:true});assert.equal(result.state,'deterministic_failure');assert.equal(result.pending,f.pending);assert.equal(retriedRecord,f.pending.retryRecord);assert.equal(retryOptions.previouslyDispatched,true);assert.equal(retriedRecord.id,f.pending.requestId);assert.equal(retriedRecord.formPayload.submissionAttemptId,f.pending.attemptId);assert.equal(f.c.S.nrFiles,originalFiles);assert.equal(f.c.S.nrPassbookFile,originalPassbook);assert.equal(f.counts.writes,0);assert.equal(f.counts.cleanup,0);assert.equal(f.counts.clear,0);assert.equal(f.c.S.nrSubmissionConfirmationPending,f.pending);f.c.EXPENSE_SUBMISSION_PENDING_KEY_BASE='test_pending';f.c.sessionGetItem=()=>JSON.stringify(f.pending);f.c.safeJsonGet=()=>f.pending;f.c.escAttr=value=>String(value);f.c.isExpenseApplicantRevisionMode=()=>false;vm.runInContext(fn('expenseSubmissionPendingStorageKey')+fn('expenseSubmissionPendingInCurrentScope')+fn('loadExpenseSubmissionPending'),f.c);f.c.S.nrSubmissionConfirmationPending=null;f.c.S.nrFiles=[];f.c.S.nrPassbookFile=null;const afterReload=f.c.nrSubmitActionsHtml();assert.match(afterReload,/前次送件待確認/);assert.match(afterReload,/事件識別：attempt-a/);assert.match(afterReload,/confirmPendingExpenseSubmission\(\)/);assert.doesNotMatch(afterReload,/onclick="submitNR\(\)"/);assert.equal(f.c.S.nrSubmissionConfirmationPending.retryRecord.files[0].path,originalFiles[0].path);assert.equal(f.c.S.nrSubmissionConfirmationPending.retryRecord.passbookFiles[0].path,originalPassbook.path);pass('failed explicit confirmation keeps durable exact attempt and attachment paths recoverable after reload');}
 {const f=fixture(['expenseSubmissionRecoveryPanelHtml','nrSubmitActionsHtml']);f.c.window=f.c;f.c.isExpenseApplicantRevisionMode=()=>false;f.c.escAttr=value=>String(value);f.c.guardSubmissionIdentityDirectory=async()=>true;f.c.showActionFeedback=()=>{};f.c.failActionFeedback=()=>{};f.c.completeActionFeedback=()=>{};f.c.openApprovalTab=()=>{throw Error('unexpected navigation')};f.c.refreshExpenseSubmissionRecoveryActions=()=>{};const alerts=[];f.c.alert=message=>alerts.push(message);const d=deferred(),calls=[];f.c.reconcilePendingExpenseSubmission=opts=>{calls.push(opts);return d.promise};vm.runInContext(windowAssignment('confirmPendingExpenseSubmission','async function submitExpenseRequestWithAmbiguousRecovery'),f.c);const html=f.c.nrSubmitActionsHtml();const onclick=html.match(/onclick="([^"]*confirmPendingExpenseSubmission\(\)[^"]*)"/);assert.ok(onclick,'rendered recovery button has click handler');const click=()=>vm.runInContext(onclick[1],f.c);const run=click();await tick();assert.equal(f.c.S.nrSubmitting,true);await click();assert.equal(calls.length,1);d.resolve({state:'unknown'});await run;assert.equal(f.c.S.nrSubmitting,false);assert.equal(calls[0].allowRetry,true);assert.equal(calls[0].retainAttachmentsOnFailure,true);assert.equal(f.counts.cleanup,0);assert.equal(f.counts.clear,0);assert.equal(f.c.S.nrSubmissionConfirmationPending,f.pending);assert.match(alerts[0],/原帳號、原瀏覽器.*確認前次送件/);pass('rendered confirmation button click only reconciles original pending attempt and remains fail-closed on unknown');}
 {const f=fixture(['reconcilePendingExpenseSubmission']);const d=deferred();f.c.readExpenseSubmissionCommitWithDelays=()=>d.promise;const run=f.c.reconcilePendingExpenseSubmission({allowRetry:true});f.switch();const replacement=f.c.S.nrSubmissionConfirmationPending;d.resolve({state:'committed',record:record()});assert.equal((await run).identityChanged,true);assert.deepEqual(f.counts,{reads:0,merged:0,writes:0,cleanup:0,clear:0,finalize:0});assert.equal(f.c.S.nrSubmissionConfirmationPending,replacement);assert.equal(f.pending.requestId,'r-a');pass('reconciliation discards committed late response without finalize, cleanup or replacing another pending');}
 {const f=fixture(['reconcilePendingExpenseSubmission']);const d=deferred();f.c.readExpenseSubmissionCommitWithDelays=()=>d.promise;f.c.submitExpenseRequestWithAmbiguousRecovery=async()=>{f.counts.writes++;return{ok:false}};const run=f.c.reconcilePendingExpenseSubmission({allowRetry:true});f.switch();d.resolve({state:'absent'});assert.equal((await run).identityChanged,true);assert.equal(f.counts.writes,0);assert.equal(f.counts.cleanup,0);assert.equal(f.counts.clear,0);pass('absent late read never retries or deletes attachments under replacement identity');}
 {const f=fixture(['reconcilePendingExpenseSubmission']);f.c.readExpenseSubmissionCommitWithDelays=async()=>({state:'absent'});const d=deferred();f.c.submitExpenseRequestWithAmbiguousRecovery=()=>d.promise;const run=f.c.reconcilePendingExpenseSubmission({allowRetry:true});await tick();f.switch();const replacement=f.c.S.nrSubmissionConfirmationPending;d.resolve({ok:false,unknown:false,error:Error('denied')});assert.equal((await run).identityChanged,true);assert.equal(f.counts.cleanup,0);assert.equal(f.counts.clear,0);assert.equal(f.c.S.nrSubmissionConfirmationPending,replacement);pass('late deterministic retry failure preserves original staged files and both pending identities');}
 {const f=fixture(['submitExpenseRequestWithAmbiguousRecovery']);const d=deferred();f.c.callExpenseSubmissionOnce=()=>{f.counts.writes++;return d.promise};const run=f.c.submitExpenseRequestWithAmbiguousRecovery(record());f.switch();d.resolve({ok:true});assert.equal((await run).identityChanged,true);assert.equal(f.counts.writes,1);pass('late successful submission response is not confirmed under replacement identity');}
 {const f=fixture(['submitExpenseRequestWithAmbiguousRecovery']);f.c.callExpenseSubmissionOnce=async()=>{f.counts.writes++;return{ok:false,error:Error('timeout')}};f.c.expenseApplicantRevisionRpcErrorIsAmbiguous=()=>true;const d=deferred();f.c.readExpenseSubmissionCommitWithDelays=()=>d.promise;const run=f.c.submitExpenseRequestWithAmbiguousRecovery(record());await tick();f.switch();d.resolve({state:'absent'});assert.equal((await run).identityChanged,true);assert.equal(f.counts.writes,1);pass('ambiguous submission stops exact retry after identity changes during read');}
 {const f=fixture(['submitExpenseRequestWithAmbiguousRecovery']);f.c.callExpenseSubmissionOnce=async()=>{f.counts.writes++;return{ok:false,error:{code:'57014',message:'canceling statement due to statement timeout'}}};f.c.readExpenseSubmissionCommitWithDelays=async()=>{f.counts.reads++;return{state:'absent'}};const result=await f.c.submitExpenseRequestWithAmbiguousRecovery(record());assert.equal(result.confirmedRollback,true);assert.equal(result.error.code,'57014');assert.equal(f.counts.writes,1);assert.equal(f.counts.reads,0);assert.equal(f.counts.clear,0);pass('first explicit PostgreSQL 57014 rolls back without replaying the costly RPC');}
 {const f=fixture(['expenseApplicantRevisionRpcErrorIsAmbiguous','submitExpenseRequestWithAmbiguousRecovery']);const args=[];f.c.callExpenseSubmissionOnce=async r=>{args.push(r);return args.length===1?{ok:false,error:{code:'CLIENT_TIMEOUT',message:'network timeout'}}:{ok:true,data:{}}};f.c.readExpenseSubmissionCommitWithDelays=async()=>({state:'absent'});const r=record();assert.equal((await f.c.submitExpenseRequestWithAmbiguousRecovery(r)).ok,true);assert.equal(args.length,2);assert.equal(args[0],args[1]);pass('network timeout still replays only the exact request and attempt after absent readback');}
 {const f=fixture(['expenseApplicantRevisionRpcErrorIsAmbiguous','submitExpenseRequestWithAmbiguousRecovery','reconcilePendingExpenseSubmission']);f.c.readExpenseSubmissionCommitWithDelays=async()=>({state:'absent'});f.c.callExpenseSubmissionOnce=async()=>{f.counts.writes++;return{ok:false,error:{code:'57014',message:'canceling statement due to statement timeout'}}};const result=await f.c.reconcilePendingExpenseSubmission({allowRetry:true,retainAttachmentsOnFailure:true});assert.equal(result.state,'unknown');assert.equal(result.reason,'retry_ambiguous');assert.equal(f.counts.writes,2);assert.equal(f.counts.cleanup,0);assert.equal(f.counts.clear,0);assert.equal(f.c.S.nrSubmissionConfirmationPending,f.pending);pass('previously dispatched pending request stays locked on later 57014');}
 {const f=fixture(['finalizeRecoveredExpenseSubmission']);f.c.ensureExpensePostCommitOutbox=()=>({ok:true});const d=deferred();f.c.runExpensePostCommitOutbox=()=>d.promise;f.c.buildAll=()=>{f.counts.finalize++};f.c.pruneCompletedExpensePostCommitOutbox=()=>{f.counts.clear++};const run=f.c.finalizeRecoveredExpenseSubmission(f.pending,record());f.switch();const replacement=f.c.S.nrSubmissionConfirmationPending;d.resolve({ok:true,failed:[]});assert.equal((await run).identityChanged,true);assert.equal(f.counts.finalize,0);assert.equal(f.counts.clear,0);assert.equal(f.c.S.nrSubmissionConfirmationPending,replacement);pass('late outbox completion cannot clear pending or build old success screen');}
 {const f=fixture(['expensePostCommitTaskState','runExpensePostCommitOutbox']);const entry={id:'out-a',tenantId:'tenant-a',dataEnv:'production',record:record(),tasks:{},notification:{id:'n-a'}};f.c.EXPENSE_POST_COMMIT_OUTBOX_RUN_PROMISE=null;f.c.loadExpensePostCommitOutbox=()=>[entry];let saved=0;f.c.saveExpensePostCommitOutboxEntry=()=>{saved++;return true};const d=deferred();f.c.persistAccountingLinesRemote=()=>{f.counts.writes++;return d.promise};f.c.dbUpsert=()=>{f.counts.writes++;return{ok:true}};f.c.persistExpenseExternalNotificationSchedule=()=>{f.counts.writes++;return{ok:true}};f.c.formatStorageUploadError=e=>e.message;const run=f.c.runExpensePostCommitOutbox();await tick();assert.equal(saved,1);f.switch();d.resolve({ok:true});assert.equal((await run).identityChanged,true);assert.equal(f.counts.writes,1);assert.equal(saved,1);assert.equal(entry.tasks.accounting.status,'running');pass('outbox stops after in-flight response: no new writes, no cross-user cache save, original retry retained');}
 {const f=fixture(['expenseSubmissionAttachmentReferences','expenseSubmissionAttachmentPathInScope','verifyPendingExpenseAttachmentPaths']);
  const path='tenant-a/expense_requests/production/2026/10/E1/D1/TEST-A/request_files/receipt.pdf';
  const current=record();current.files=[{path,n:'receipt.pdf'}];f.c.reqDbRow=r=>({files:r.files,form_payload:r.formPayload});
  f.c.hasSupabase=()=>true;f.c.SUPABASE_ATTACHMENT_BUCKET='finance-attachments';f.c.withOperationTimeout=p=>p;
  let rows=[{id:'meta-a',storage_path:path,record_type:'expense_requests',record_no:'TEST-A',uploaded_by:'person-a',attachment_state:'staged'}],object={data:{exists:true},error:null},metadataError=null;
  f.c.getSb=()=>({from(){return{select(){return this},eq(){return this},in(){return Promise.resolve({data:rows,error:metadataError})}}},storage:{from(){return{exists(){return Promise.resolve(object)}}}}});
  const firstAttachmentCheck=await f.c.verifyPendingExpenseAttachmentPaths(f.pending,current,f.c.expenseSubmissionOperationIdentity());assert.equal(firstAttachmentCheck.state,'present',JSON.stringify(firstAttachmentCheck));
  rows=[];object={data:false,error:{status:404,message:'Object not found'}};const missing=await f.c.verifyPendingExpenseAttachmentPaths(f.pending,current,f.c.expenseSubmissionOperationIdentity());assert.equal(missing.state,'missing');assert.equal(missing.missing[0].path,path);
  metadataError={code:'57014'};assert.equal((await f.c.verifyPendingExpenseAttachmentPaths(f.pending,current,f.c.expenseSubmissionOperationIdentity())).state,'unknown');
  metadataError=null;rows=[{id:'meta-a',storage_path:path,record_type:'expense_requests',record_no:'TEST-A',uploaded_by:'person-a',attachment_state:'claimed'}];object={data:{exists:true},error:null};assert.equal((await f.c.verifyPendingExpenseAttachmentPaths(f.pending,current,f.c.expenseSubmissionOperationIdentity())).state,'unknown');
  rows=[{...rows[0],attachment_state:'staged'}];object={data:false,error:{status:403,code:'storage_denied'}};assert.equal((await f.c.verifyPendingExpenseAttachmentPaths(f.pending,current,f.c.expenseSubmissionOperationIdentity())).state,'unknown');
  assert.equal(f.counts.writes,0);assert.equal(f.counts.cleanup,0);pass('pending replay requires exact staged metadata and Storage proof; missing asks for file, errors and claimed rows remain locked');}
 {const f=fixture(['reconcilePendingExpenseSubmission']);f.c.readExpenseSubmissionCommitWithDelays=async()=>({state:'absent'});f.c.verifyPendingExpenseAttachmentPaths=async()=>({state:'missing',missing:[{path:'old',name:'receipt.pdf',kind:'request_files'}]});f.c.persistExpenseSubmissionPendingUpdate=(_old,next)=>{f.c.S.nrSubmissionConfirmationPending=next;return true};f.c.submitExpenseRequestWithAmbiguousRecovery=async()=>{f.counts.writes++;return{ok:true}};const result=await f.c.reconcilePendingExpenseSubmission({allowRetry:true});assert.equal(result.state,'attachment_missing');assert.equal(result.pending.requestId,'r-a');assert.equal(result.pending.repairMissing[0].name,'receipt.pdf');assert.equal(f.counts.writes,0);assert.equal(f.counts.clear,0);pass('stale pending with missing attachment exposes reselect state without RPC or unlocking request');}
 {const f=fixture(['reconcilePendingExpenseSubmission']);f.c.readExpenseSubmissionCommitWithDelays=async()=>({state:'absent'});f.c.verifyPendingExpenseAttachmentPaths=async()=>({state:'missing',missing:[{path:'old',name:'receipt.pdf'}]});f.c.persistExpenseSubmissionPendingUpdate=()=>false;f.c.submitExpenseRequestWithAmbiguousRecovery=async()=>{f.counts.writes++;return{ok:true}};const result=await f.c.reconcilePendingExpenseSubmission({allowRetry:true});assert.equal(result.state,'unknown');assert.equal(result.reason,'repair_state_not_durable');assert.equal(f.counts.writes,0);assert.equal(f.counts.clear,0);assert.equal(f.c.S.nrSubmissionConfirmationPending,f.pending);pass('repair-state persistence failure leaves original pending locked and sends zero RPCs');}
 {const f=fixture(['reconcilePendingExpenseSubmission']);const repaired=record();repaired.formPayload.submissionAttemptId='repair-a';f.pending.repairRecord=repaired;f.pending.retryRecord=repaired;f.pending.repairAttemptIds=['repair-a'];f.pending.repairUploadedPaths=['new-path'];let cleaned=0;f.c.cleanupUnclaimedExpenseRepairUploads=async()=>{cleaned++;return 1};f.c.readExpenseSubmissionCommitWithDelays=async()=>({state:'committed',record:record(),matchedExpected:f.pending.expected});f.c.submitExpenseRequestWithAmbiguousRecovery=async()=>{f.counts.writes++;return{ok:true}};const result=await f.c.reconcilePendingExpenseSubmission({allowRetry:true});assert.equal(result.state,'committed');assert.equal(cleaned,1);assert.equal(f.counts.writes,0);assert.equal(f.counts.finalize,1);pass('late original attempt wins same request ID: exact readback finalizes it, cleans only staged repair upload and never submits another row');}
 {const f=fixture(['expenseSubmissionRecoveryPanelHtml']);f.c.escAttr=v=>String(v);f.pending.repairMissing=[{path:'private/path',name:'receipt.pdf'}];const html=f.c.expenseSubmissionRecoveryPanelHtml(f.pending);assert.match(html,/expense-repair-file-0/);assert.match(html,/repairPendingExpenseSubmission\(\)/);assert.doesNotMatch(html,/private\/path/);pass('missing attachment UI requests real File bytes without leaking Storage path');}
 {const f=fixture(['expenseSubmissionPendingStorageKey','persistExpenseSubmissionPendingUpdate','replaceExpenseSubmissionAttachmentPath','expenseRepairSelectedFileCheck','retainExpenseRepairUploadsAfterIdentityChange']);const old='tenant-a/expense_requests/production/2026/10/E1/D1/TEST-A/request_files/old.pdf',fresh='tenant-a/expense_requests/production/2026/10/E1/D1/TEST-A/request_files/fresh.pdf';
  f.pending.expected.files=[{path:old,n:'receipt.pdf'}];f.pending.retryRecord.files=[{path:old,n:'receipt.pdf'}];f.pending.repairMissing=[{path:old,name:'receipt.pdf',kind:'request_files'}];
  const local=new Map(),session=new Map();f.c.EXPENSE_SUBMISSION_PENDING_KEY_BASE='test_pending';const key=f.c.expenseSubmissionPendingStorageKey();local.set(key,JSON.parse(JSON.stringify(f.pending)));session.set(key,JSON.stringify(f.pending));
  f.c.safeJsonGet=k=>local.get(k)||null;f.c.safeJsonSet=(k,v)=>{local.set(k,JSON.parse(JSON.stringify(v)));return true};f.c.safeRemoveItem=k=>local.delete(k);f.c.sessionGetItem=k=>session.get(k)||null;f.c.sessionSetItem=(k,v)=>{session.set(k,v);return true};f.c.sessionRemoveItem=k=>session.delete(k);
  let dispatches=0,cleaned=0;f.c.window=f.c;f.c.el=()=>({files:[{name:'receipt.pdf',size:5,type:'application/pdf'}]});f.c.confirm=()=>true;f.c.EXPENSE_REPAIR_FRESH_UPLOAD_PATHS={};f.c.showActionFeedback=()=>{};f.c.failActionFeedback=()=>{};f.c.completeActionFeedback=()=>{};f.c.refreshExpenseSubmissionRecoveryActions=()=>{};f.c.alert=()=>{};f.c.guardSubmissionIdentityDirectory=async()=>true;f.c.readExpenseSubmissionCommitWithDelays=async()=>({state:'absent'});f.c.verifyPendingExpenseAttachmentPaths=async()=>({state:'missing',missing:f.pending.repairMissing});f.c.fileToAttachment=async file=>({n:file.name,size:file.size,mime:file.type});f.c.uploadAttachmentsToSupabase=async()=>{const item={path:fresh,n:'receipt.pdf',kind:'request_files',url:''};Object.defineProperty(item,'__uploadCreatedThisAttempt',{value:true});return[item]};f.c.membershipOrgDraftUuid=()=> 'fresh-uuid';f.c.todayIso=()=> '2026-10-02';f.c.reconcilePendingExpenseSubmission=async()=>{dispatches++;return{state:'unknown'}};f.c.openApprovalTab=()=>{throw Error('unexpected navigation')};f.c.cleanupUnclaimedExpenseRepairUploads=async()=>{cleaned++;return 1};
  f.c.loadExpenseSubmissionPending=()=>f.c.S.nrSubmissionConfirmationPending;
  vm.runInContext(windowAssignment('repairPendingExpenseSubmission','async function submitExpenseRequestWithAmbiguousRecovery'),f.c);
  await f.c.repairPendingExpenseSubmission();const next=f.c.S.nrSubmissionConfirmationPending;
  assert.equal(next.requestId,'r-a');assert.equal(next.expected.files[0].path,old);assert.equal(next.retryRecord.files[0].path,fresh);assert.equal(next.repairRecord.files[0].path,fresh);assert.equal(next.retryRecord.formPayload.submissionAttemptId,'expense_submit_fresh-uuid');assert.equal(next.expected.formPayload.submissionAttemptId,'attempt-a');
  assert.equal(local.get(key).repairRecord,undefined);assert.equal(local.get(key).retryRecord.files[0].path,old);assert.deepEqual(local.get(key).repairAttemptIds,['expense_submit_fresh-uuid']);assert.equal(JSON.parse(session.get(key)).repairRecord.files[0].path,fresh);assert.equal(dispatches,1);pass('employee File reselect keeps request ID and immutable original/repaired snapshots in session; local copy gets only opaque attempt token');
  f.c.S.nrSubmissionConfirmationPending=f.pending;f.c.sessionSetItem=()=>false;await f.c.repairPendingExpenseSubmission();assert.equal(dispatches,1);assert.equal(cleaned,1);assert.equal(f.c.S.nrSubmissionConfirmationPending,f.pending);pass('failed session snapshot persistence cleans only fresh staged upload and never dispatches repaired RPC');
  f.c.sessionSetItem=(k,v)=>{session.set(k,v);return true};f.c.S.nrSubmissionConfirmationPending=f.pending;const lateUpload=deferred();f.c.uploadAttachmentsToSupabase=()=>lateUpload.promise;const run=f.c.repairPendingExpenseSubmission();await tick();f.switch();const replacement=f.c.S.nrSubmissionConfirmationPending;const lateMeta={path:fresh,n:'receipt.pdf',kind:'request_files',url:''};Object.defineProperty(lateMeta,'__uploadCreatedThisAttempt',{value:true});lateUpload.resolve([lateMeta]);await run;assert.equal(f.c.S.nrSubmissionConfirmationPending,replacement);assert.equal(dispatches,1);assert.deepEqual(JSON.parse(session.get(key)).unconfirmedRepairUploads,[fresh]);pass('identity switch just after upload records new staged path in original session and performs no cross-user delete or RPC');}
 {const f=fixture(['expenseRepairSelectedFileCheck']);assert.equal(f.c.expenseRepairSelectedFileCheck({name:'original.jpg',size:50,mime:'image/jpeg'},{name:'wrong.jpg',size:50,type:'image/jpeg'}).reason,'檔名');assert.equal(f.c.expenseRepairSelectedFileCheck({name:'original.jpg',size:50,mime:'image/jpeg'},{name:'original.jpg',size:51,type:'image/jpeg'}).reason,'檔案大小');assert.equal(f.c.expenseRepairSelectedFileCheck({name:'original.jpg',size:50,mime:'image/jpeg'},{name:'original.jpg',size:50,type:'image/png'}).reason,'檔案格式');assert.equal(f.c.expenseRepairSelectedFileCheck({name:'original.jpg',size:50,mime:'image/jpeg'},{name:'original.jpg',size:50,type:'image/jpeg'}).ok,true);assert.equal(f.c.expenseRepairSelectedFileCheck({name:'附件',size:0,mime:''},{name:'selected.pdf',size:50,type:'application/pdf'}).limited,true);pass('reselected evidence must match original name, bytes and MIME when known; missing metadata demands explicit confirmation');}
 {const f=fixture(['expenseSubmissionPendingStorageKey','expenseSubmissionPendingInCurrentScope','loadExpenseSubmissionPending']);f.c.EXPENSE_SUBMISSION_PENDING_KEY_BASE='test_pending';const local=JSON.parse(JSON.stringify(f.pending)),session=JSON.parse(JSON.stringify(f.pending));session.repairRecord=record();session.repairRecord.formPayload.submissionAttemptId='repair-only-in-session';session.retryRecord=session.repairRecord;f.c.safeJsonGet=()=>local;f.c.sessionGetItem=()=>JSON.stringify(session);assert.equal(f.c.loadExpenseSubmissionPending().retryRecord.formPayload.submissionAttemptId,'attempt-a');assert.equal(f.c.S.nrSubmissionConfirmationPending,local);pass('after a split storage write, reload rejects repaired session snapshot lacking the matching durable opaque token');}
 {const f=fixture(['expenseSubmissionRecordMatches','readExpenseSubmissionCommit']);const old=record(),repaired=record();repaired.formPayload.submissionAttemptId='expense_submit_repaired';const stored={...repaired,id:old.id,no:old.no};f.c.getSb=()=>({from(){return{select(){return this},eq(){return this},limit(){return Promise.resolve({data:[stored],error:null})}}}});const result=await f.c.readExpenseSubmissionCommit(old,[repaired],[]);assert.equal(result.state,'committed');assert.equal(result.matchedExpected,repaired);const byOpaqueToken=await f.c.readExpenseSubmissionCommit(old,[],['expense_submit_repaired']);assert.equal(byOpaqueToken.state,'committed');const unrecognized=await f.c.readExpenseSubmissionCommit(old,[],['another_attempt']);assert.equal(unrecognized.state,'unknown');assert.equal(unrecognized.error.code,'EXPENSE_SUBMISSION_ID_COLLISION');pass('same ID and number with a new attempt matches only the immutable repair snapshot or its saved opaque token');}
 {const f=fixture(['expenseSubmissionAttachmentReferences','expenseSubmissionAttachmentPathInScope','cleanupUnclaimedExpenseRepairUploads']);f.c.reqDbRow=r=>({files:r.files});f.c.hasSupabase=()=>true;f.c.SUPABASE_ATTACHMENT_BUCKET='finance-attachments';const path='tenant-a/expense_requests/production/2026/10/E1/D1/TEST-A/request_files/new.pdf';f.pending.repairUploadedPaths=[path];f.c.EXPENSE_REPAIR_FRESH_UPLOAD_PATHS={[path]:Date.now()};let deletes=0,removes=0,state='claimed',age=Date.now();f.c.getSb=()=>({from(){let deleting=false;return{select(){return deleting?Promise.resolve({data:[],error:null}):this},eq(){return this},limit(){return Promise.resolve({data:[{id:'meta-a',attachment_state:state,uploaded_by:'person-a',record_type:'expense_requests',record_no:'TEST-A'}],error:null})},delete(){deleting=true;deletes++;return this}}},storage:{from(){return{info(){return Promise.resolve({data:{createdAt:new Date(age).toISOString()},error:null})},remove(){removes++;return Promise.resolve({error:null})}}}}});assert.equal(await f.c.cleanupUnclaimedExpenseRepairUploads(f.pending,f.c.expenseSubmissionOperationIdentity()),0);assert.equal(deletes,0);assert.equal(removes,0);state='staged';age=Date.now()-31*60*1000;assert.equal(await f.c.cleanupUnclaimedExpenseRepairUploads(f.pending,f.c.expenseSubmissionOperationIdentity()),0);assert.equal(deletes,0);age=Date.now();assert.equal(await f.c.cleanupUnclaimedExpenseRepairUploads(f.pending,f.c.expenseSubmissionOperationIdentity()),0);assert.equal(deletes,1);assert.equal(removes,0);pass('cleanup skips claimed and over-30-minute files, and never removes Storage after a staged delete loses a claim race');}
 console.log(`${checks} submission identity behavior checks passed`);
})().catch(error=>{console.error(error);process.exitCode=1});
