'use strict';
// Actual offline history tab, pagination and retry controls at 1440/390px.
// Only the RPC transport and unrelated pending-task skeleton are simulated.
// Usage: node scripts/check_approval_history_browser.cjs /tmp/history-evidence
// Requires agent-browser. No real login, production data or network requests.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{execFile}=require('node:child_process'),{promisify}=require('node:util');
const run=promisify(execFile),root=path.resolve(__dirname,'..'),out=path.resolve(process.argv[2]||'/tmp/finance-history-browser-20260913'),session='history-'+process.pid,bin=process.env.AGENT_BROWSER_BIN||'agent-browser';
assert.ok(out!==root&&!out.startsWith(root+path.sep),'Browser evidence must be outside the source worktree');
const {applyBuildEnvironment}=require('./finance_build_environment');const source=fs.readFileSync(path.join(root,'index.html'),'utf8'),sourceHash=crypto.createHash('sha256').update(source).digest('hex');
let html=applyBuildEnvironment(source,{target:'local',supabaseUrl:'',supabaseAnonKey:''}),anchor='bootAuthGate();\n\n})();';assert.ok(html.includes(anchor));
html=html.replace(anchor,'window.__postingBrowser={run:async function(code){return await eval(code)}};\n'+anchor).replace(/<script\b[^>]*src=["']https?:[^>]*><\/script>/gi,'').replace('<head>','<head><meta http-equiv="Content-Security-Policy" content="connect-src \'self\'; form-action \'none\'; img-src \'self\' data: blob:">');
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(p!==root&&!p.startsWith(root+'/')){res.writeHead(403);return res.end();}if(p===root||p===path.join(root,'index.html')){res.setHeader('content-type','text/html; charset=utf-8');return res.end(html);}if(!fs.existsSync(p)||!fs.statSync(p).isFile()){res.writeHead(404);return res.end();}res.setHeader('content-type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.png')?'image/png':'application/octet-stream');res.end(fs.readFileSync(p));});
const b=async(...args)=>(await run(bin,['--session',session,...args],{maxBuffer:8e6,timeout:45000})).stdout;
async function scope(code){let v=JSON.parse(await b('eval','--base64',Buffer.from('(async()=>JSON.stringify(await window.__postingBrowser.run('+JSON.stringify(code)+')))()').toString('base64')));return typeof v==='string'?JSON.parse(v):v;}

const evidence={sourceHash,scope:'Local actual history tab and recovery handlers; fictional transport only; SQL authority/completeness verified separately',checks:[],screens:[]};
function check(name,ok){assert(ok,name);evidence.checks.push(name);console.log('PASS '+name);}
const setup=`(function(){USERS=[{id:'fixture-accountant',n:'許晴川',email:'accountant@example.invalid',role:'accountant',rL:'會計',eid:'F1',dc:'DAYCARE',active:true},{id:'fixture-employee',n:'林星河',email:'employee@example.invalid',role:'employee',rL:'組員',eid:'F1',dc:'DAYCARE',active:true}];ENTS=[{id:'F1',s:'星河照護',full:'星河照護股份有限公司',active:true}];DEPTS=[{c:'DAYCARE',n:'日間照顧課',eid:'F1',entityCodes:['F1'],newFormEntityCodes:['F1'],lv:4,active:true,isPostingUnit:true}];REQS=[];INVS=[];BILLS=[];NOTIFS=[];VOUCHERS=[];LEDGER=[];ORG_CHART=[];quickLogin('accountant');S.user.authUserId='10000000-0000-0000-0000-000000000001';S.user.tenantId=currentTenantId();

window.__historyMode='57014';window.__historyCalls=[];window.__historyDeferred=[];window.__historyAborts=0;
var timeout=withOperationTimeout;withOperationTimeout=function(p,label,ms){return timeout(p,label,label==='個人簽核歷史'&&window.__historyMode==='hang'?80:ms)};
approvalFastShouldHoldSkeleton=function(){return false;};
window.__historyPayload=function(args,prefix){var total=123;return {ok:true,identity:{tenant_id:currentTenantId(),finance_user_id:S.user.id,auth_user_id:S.user.authUserId,data_environment:activeDataEnvironment()},total:total,all_total:total,page:{limit:50,offset:args.p_offset,has_more:args.p_offset+50<total},items:Array.from({length:Math.min(50,total-args.p_offset)},function(_,n){var id=(prefix||'HISTORY-')+String(args.p_offset+n+1).padStart(3,'0');return {history_key:'expense_requests:'+id,record_type:'expense_requests',kind:'req',record_id:id,personally_acted:true,participation_label:'本人已處理',last_participated_at:'2026-09-12T00:00:00Z',source_rows:[{id:id,no:id,tenant_id:currentTenantId(),data_environment:activeDataEnvironment(),entity_id:'F1',department_code:'DAYCARE',applicant:'林星河',applicant_id:'fixture-employee',type:'payment_request',status:'completed',amount:1250,request_date:'2026-09-12',description:'離線歷史驗證資料',files:[],steps:[{rk:'accountant',uid:S.user.id,a:'approved',at:'2026-09-12T00:00:00Z'}],form_payload:{}}]};})};};
getSb=function(){return {rpc:function(name,args){if(name!=='finance_approval_participant_history_for_current_user')throw Error('Unexpected RPC '+name);window.__historyCalls.push(JSON.parse(JSON.stringify(args)));var mode=window.__historyMode;return {abortSignal:function(signal){signal.addEventListener('abort',function(){window.__historyAborts++});return this;},then:function(resolve,reject){if(mode==='57014')return Promise.resolve({data:null,error:{code:'57014',message:'canceling statement due to statement timeout'}}).then(resolve,reject);if(mode==='hang')return new Promise(function(){});if(mode==='deferred')return new Promise(function(r){window.__historyDeferred.push({args:args,resolve:r,payload:window.__historyPayload(args,'LATE-')});}).then(resolve,reject);return Promise.resolve({data:window.__historyPayload(args)}).then(resolve,reject);}};}}};
S.demoLogin=false;openApprovalTab('h');return true;})()`;
(async()=>{fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));await b('open','http://127.0.0.1:'+server.address().port);await b('set','viewport','1440','1000');await scope(setup);
await scope('(async function(){await APPROVAL_HISTORY_RUNTIME.promise;return true;})()');
let state=await scope('({status:APPROVAL_HISTORY_RUNTIME.status,text:el("appr-list").innerText,retry:typeof window.loadApprovalHistoryPage})');check('actual 57014 becomes error with callable retry, not permanent loading',state.status==='error'&&state.retry==='function'&&state.text.includes('重新載入'));await b('screenshot',path.join(out,'history-57014-1440.png'));
await scope('(function(){window.__historyMode="ok";return true;})()');await b('click','#appr-list button[onclick*="loadApprovalHistoryPage"]');await scope('(async function(){await APPROVAL_HISTORY_RUNTIME.promise;return true;})()');
state=await scope('({status:APPROVAL_HISTORY_RUNTIME.status,total:APPROVAL_HISTORY_RUNTIME.total,items:APPROVAL_HISTORY_RUNTIME.items.length,text:el("appr-list").innerText})');check('real retry click recovers first 50 of 123 authorized records',state.status==='ready'&&state.total===123&&state.items===50&&state.text.includes('HISTORY-001'));
await b('screenshot',path.join(out,'history-ready-1440.png'));await scope('(async function(){window.apprPage(3);await APPROVAL_HISTORY_RUNTIME.promise;return true;})()');state=await scope('({page:S.apprPage,items:APPROVAL_HISTORY_RUNTIME.items.length,text:el("appr-list").innerText})');check('real pager reaches final 23 records without resetting to first page',state.page===3&&state.items===23&&state.text.includes('HISTORY-123'));
await b('set','viewport','390','844');await b('screenshot',path.join(out,'history-page3-390.png'));check('mobile history has no horizontal page overflow',!(await scope('document.documentElement.scrollWidth>innerWidth+1')));
await scope('(async function(){window.__historyMode="hang";await window.loadApprovalHistoryPage({force:true});return true;})()');state=await scope('({status:APPROVAL_HISTORY_RUNTIME.status,count:APPROVAL_HISTORY_RUNTIME.items.length,aborts:window.__historyAborts,text:el("approval-manager-summary").innerText})');check('never-settling transport ends visibly while retaining verified history',state.status==='error'&&state.count===23&&state.aborts>=1&&state.text.includes('重新載入'));
const size=await scope('(function(){var button=document.querySelector("#approval-manager-summary button[onclick*=loadApprovalHistoryPage]"),r=button.getBoundingClientRect();return {w:r.width,h:r.height};})()');check('mobile actual retry control meets 44px target',size.w>=44&&size.h>=44);await b('screenshot',path.join(out,'history-timeout-390.png'));
for(const width of [1440,390]){
 await b('set','viewport',String(width),width===1440?'1000':'844');
 await scope('(async function(){window.__historyMode="ok";S.apprQuery="";await loadApprovalHistoryPage({force:true,page:1,query:""});window.__historyMode="deferred";window.__searchStart=window.__historyCalls.length;var input=el("appr-q");input.value="舊查詢";input.dispatchEvent(new InputEvent("input",{bubbles:true}));await new Promise(function(r){setTimeout(r,280)});window.__searchOld=window.__historyDeferred[window.__historyDeferred.length-1];return true;})()');
 state=await scope('(async function(){var input=el("appr-q"),aborts=window.__historyAborts;input.value="自費";input.dispatchEvent(new InputEvent("input",{bubbles:true}));window.__searchOld.resolve({data:window.__searchOld.payload});await new Promise(function(r){setTimeout(r,0)});return {aborts:window.__historyAborts-aborts,query:APPROVAL_HISTORY_RUNTIME.query,status:APPROVAL_HISTORY_RUNTIME.status,items:APPROVAL_HISTORY_RUNTIME.items.length,late:REQS.some(function(x){return x.id.startsWith("LATE-")})};})()');
 check(width+' actual search input immediately aborts old query; its late response cannot enter the cache',state.aborts===1&&state.query==='自費'&&state.status==='loading'&&state.items===0&&!state.late);
 await scope('(async function(){await new Promise(function(r){setTimeout(r,300)});return true;})()');
 state=await scope('(function(){var before=window.__historyCalls.length,aborts=window.__historyAborts;window.__searchCurrent=window.__historyDeferred[window.__historyDeferred.length-1];window.__retryOne=window.loadApprovalHistoryPage({force:true});window.__retryTwo=window.loadApprovalHistoryPage({force:true});return {calls:before-window.__searchStart,query:window.__historyCalls[before-1].p_search,same:window.__retryOne===window.__retryTwo,aborts:window.__historyAborts-aborts};})()');
 check(width+' repeated retry joins one final typed query without aborting it',state.calls===2&&state.query==='自費'&&state.same&&state.aborts===0);
 await scope('(async function(){window.__searchCurrent.resolve({data:window.__historyPayload(window.__searchCurrent.args,"SEARCH-")});await window.__retryOne;return true;})()');
 check(width+' searched authoritative results retain all 123 records and complete pagination',await scope('APPROVAL_HISTORY_RUNTIME.status==="ready"&&APPROVAL_HISTORY_RUNTIME.total===123&&APPROVAL_HISTORY_RUNTIME.items.length===50&&el("appr-list").innerText.includes("SEARCH-001")'));
 state=await scope('(async function(){window.__historyMode="ok";var start=window.__historyCalls.length,input=el("appr-q");input.dispatchEvent(new CompositionEvent("compositionstart",{bubbles:true}));input.value="zi";input.dispatchEvent(new InputEvent("input",{bubbles:true,isComposing:true,data:"zi"}));await new Promise(function(r){setTimeout(r,300)});var unfinished=window.__historyCalls.length-start;input.value="自费輸入完成";input.dispatchEvent(new InputEvent("input",{bubbles:true,isComposing:true}));input.value="自費輸入完成";input.dispatchEvent(new CompositionEvent("compositionend",{bubbles:true,data:"自費輸入完成"}));input.dispatchEvent(new InputEvent("input",{bubbles:true,isComposing:false}));await new Promise(function(r){setTimeout(r,300)});return {unfinished:unfinished,calls:window.__historyCalls.length-start,query:window.__historyCalls[window.__historyCalls.length-1].p_search,status:APPROVAL_HISTORY_RUNTIME.status};})()');
 check(width+' real composition events send only the final Chinese text once',state.unfinished===0&&state.calls===1&&state.query==='自費輸入完成'&&state.status==='ready');
 state=await scope('(async function(){S.user.email="fixture-history-token@suiyuecare.com";supabaseAuthSubscription=null;bindSupabaseAuthState({auth:{onAuthStateChange:function(fn){window.__historyAuthListener=fn;return {data:{subscription:{}}};}}});window.__historyMode="deferred";S.apprQuery="自費憑證更新";window.__beforeAuthHistory=loadApprovalHistoryPage({force:true,page:1});await new Promise(function(r){setTimeout(r,0)});window.__beforeAuthEntry=window.__historyDeferred[window.__historyDeferred.length-1];var start=window.__historyCalls.length,session={access_token:"fictional-local-token",expires_in:3600,user:{id:S.user.authUserId,email:S.user.email,email_confirmed_at:"2026-09-14T00:00:00Z",app_metadata:{provider:"google",providers:["google"]}}};window.__historyAuthListener("TOKEN_REFRESHED",session);window.__historyAuthListener("TOKEN_REFRESHED",session);await new Promise(function(r){setTimeout(r,0)});return {added:window.__historyCalls.length-start,query:window.__historyCalls[window.__historyCalls.length-1].p_search,blocked:financeWorkspaceIdentityBlocked,pending:!!APPROVAL_HISTORY_RUNTIME.promise};})()');
 check(width+' actual auth listener immediately resumes one current search after same-person token refresh',state.added===1&&state.query==='自費憑證更新'&&!state.blocked&&state.pending);
 state=await scope('(async function(){var current=APPROVAL_HISTORY_RUNTIME.promise;window.__beforeAuthEntry.resolve({data:window.__beforeAuthEntry.payload});var stale=await window.__beforeAuthHistory;var kept=APPROVAL_HISTORY_RUNTIME.promise===current,entry=window.__historyDeferred[window.__historyDeferred.length-1];entry.resolve({data:window.__historyPayload(entry.args,"REFRESH-")});await current;return {stale:stale.stale,kept:kept,status:APPROVAL_HISTORY_RUNTIME.status,text:el("appr-list").innerText,late:REQS.some(function(r){return r.id.startsWith("LATE-")})};})()');
 check(width+' old auth response cleanup preserves the replacement and paints verified results',state.stale&&state.kept&&state.status==='ready'&&state.text.includes('REFRESH-001')&&!state.late);
 await b('screenshot',path.join(out,'history-search-'+width+'.png'));
 check(width+' typed search has no horizontal page overflow',!(await scope('document.documentElement.scrollWidth>innerWidth+1')));
}
await scope('(function(){window.__historyDeferred=[];return true;})()');
await scope('(function(){window.__historyMode="deferred";window.__oldHistory=loadApprovalHistoryPage({force:true,query:"old",page:1});return true;})()');await scope('(async function(){window.__historyMode="ok";await loadApprovalHistoryPage({force:true,query:"new",page:1});window.__historyDeferred[0].resolve({data:window.__historyDeferred[0].payload});await window.__oldHistory;return true;})()');check('late old search response cannot repaint or overwrite current results',(await scope('APPROVAL_HISTORY_RUNTIME.query==="new"&&APPROVAL_HISTORY_RUNTIME.items[0].raw.id==="HISTORY-001"')));
await scope('(function(){window.__historyMode="deferred";window.__oldHistory=loadApprovalHistoryPage({force:true,query:"identity",page:1});return true;})()');await scope('(async function(){S.user=Object.assign({},S.user,{id:"OTHER",authUserId:"OTHER-AUTH"});financeWorkspaceIdentityBlocked=true;window.__historyDeferred[1].resolve({data:window.__historyDeferred[1].payload});await window.__oldHistory;return true;})()');check('late old-user history cannot enter new identity cache',!(await scope('REQS.some(function(x){return x.id.startsWith("LATE-")})')));
const errors=(await b('errors')).trim();assert.equal(errors,'');evidence.errors=errors;fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify(evidence,null,2));console.log('PASS actual history browser: '+out);
})().catch(e=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:e.message,evidence},null,2));console.error(e);process.exitCode=1}).finally(async()=>{await b('close').catch(()=>{});server.close()});
