#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),engine=require('../assets/engines/tax-report-engine.js');
const source=fs.readFileSync(path.join(__dirname,'../assets/engines/reporting-workspace.js'),'utf8');
const marker='  global.FinanceReportingWorkspace=api;';assert.equal(source.split(marker).length,2);
const context={console,Map,Set,Intl,FormData:class {constructor(form){this.values=form.values||{};}forEach(fn){Object.entries(this.values).forEach(([k,v])=>fn(v,k));}},document:{getElementById:id=>elements[id]||null,addEventListener(){}},FinanceTaxReportEngine:engine};context.window=context;
// Expose private functions only in this in-memory test copy. No production hook.
vm.runInNewContext(source.replace(marker,"  global.__taxAdapterTest={taxScope,taxDocuments,taxWorkpaper,profileCopy,submitProfileForm,taxRawSources,taxCanonical,ensureTaxData,taxReadState,requireTaxData,openTaxDocument,onAction};\n"+marker),context);
const clone=x=>JSON.parse(JSON.stringify(x)),elements={'rpt-ent':{value:'A'},'rpt-month':{value:'2026-08'},'finance-report-dialog':{dataset:{entity:'A',revision:'0'},open:false,showModal(){this.open=true;},close(){this.open=false;}}};
const profile={schemaVersion:1,accountingFramework:null,tax:{formType:'401',taxId:'12345675',legalName:'Fixture',taxRegistrationNo:'registration',responsiblePerson:'Reviewer',address:'address',filingMode:'individual',filingFrequency:'bimonthly',periods:{'2026-07-01/2026-08-31':{priorCarryforwardTax:0,refundLimitConfirmedTax:0}}},accountMappings:{},costCenters:[],budgets:[],allocations:[],eliminations:[],periodChecks:{},documents:{}};
let invoices=[],requests=[],saved=clone(profile),posted=[],lastSave=null,complete=true,tests=0;
const rt={tenant:()=> 'fixture',environment:()=> 'test',user:()=>({id:'accountant'}),role:()=> 'accountant',today:()=> '2026-09-10',invoices:()=>invoices,requests:()=>requests,postedAccountingLines:()=>posted,postedAccountingRequired:()=>true,ensurePostedAccountingLines:async()=>({status:posted?'ready':'error',lines:posted}),completeness:()=>({tables:{invoices:{complete},expense_requests:{complete}}}),state:()=>({page:'reports'}),rpc:async(name,args)=>{if(name==='finance_reporting_tax_sources_v1'){const raw=api.taxRawSources({eid:args.p_entity_id}),sources={};for(const d of args.p_documents){const row=raw.find(r=>r.key===d.key);sources[d.key]=row?{available:true,snapshot:clone(row.snapshot),binding:fixtureBinding(row.snapshot)}:{available:false};}return{data:{ok:true,entityId:args.p_entity_id,dataEnvironment:args.p_data_environment,sources}};}if(name==='finance_reporting_profile_save_v1'){lastSave=clone(args);saved=clone(args.p_profile);return{data:{ok:true,profile:saved,revision:1,canEdit:false,canEditWorkpaper:true}};}return {data:{ok:true,profile:clone(saved),revision:0,canEdit:false,canEditWorkpaper:true}};}};
context.FinanceReportingWorkspace.install(rt);const api=context.__taxAdapterTest;
function fixtureBinding(snapshot){return{version:1,fingerprint:require('node:crypto').createHash('sha256').update(api.taxCanonical(snapshot)).digest('hex')};}
async function load(p){saved=clone(p);for(const row of api.taxRawSources({eid:'A'})){if(saved.documents[row.key])saved.documents[row.key].sourceBinding=fixtureBinding(row.snapshot);}await context.FinanceReportingWorkspace.loadProfile('A',true);await api.ensureTaxData({eid:'A'},true);}
async function test(name,fn){await fn();tests++;console.log('PASS '+name);}
function classification(type,id,extra={}){return {sourceType:type,sourceId:id,formatCode:type==='invoice'?'35':'25',taxClass:'taxable',deduction:'eligible',assetKind:'expense',sellerTaxId:'87654321',buyerTaxId:'12345675',number:'AA00000001',date:'2026-08-10',originalNetAmount:100,originalTaxAmount:5,grossAmount:105,evidenceReference:'fixture-original',classificationReason:'Verified original',...extra};}

const scope={eid:'A',period:'2026-08'},key='expense_request:r1:0';
let ensured=0,sourceCalls=0,originalRpc=rt.rpc,accountingGate=null,sourceGate=null,identityUser='accountant',sourceOverride=null;
rt.user=()=>({id:identityUser});rt.entities=()=>[{id:'A'},{id:'B'}];
rt.ensurePostedAccountingLines=async r=>{ensured++;if(accountingGate)return accountingGate(r);return{status:'ready',lines:clone(posted)};};
rt.rpc=async(name,args)=>{if(name==='finance_reporting_tax_sources_v1'){sourceCalls++;if(sourceGate)return sourceGate(name,args);const out=await originalRpc(name,args);if(sourceOverride)sourceOverride(out);return out;}return originalRpc(name,args);};
const flush=()=>new Promise(r=>setImmediate(r));
function sourceRow(){return{id:'r1',eid:'A',amt:210,ver:1,desc:'Anonymous test expense',formPayload:{lazyRows:[{no:'BB00000002',item:'Stationery',date:'2026-08-11',grossAmount:210}]}};}
async function exactLoad(p){saved=clone(p);await context.FinanceReportingWorkspace.loadProfile('A',true);}
function classified(){let p=clone(profile);p.documents[key]=classification('expense_request','r1',{sourceLineId:'0',number:'BB00000002',date:'2026-08-11',originalNetAmount:200,originalTaxAmount:10,grossAmount:210});p.documents[key].sourceBinding=fixtureBinding(api.taxRawSources(scope)[0].snapshot);return p;}
async function reset(){invoices=[];requests=[sourceRow()];posted=[{id:'canonical-line',description:'Stationery',grossAmount:210,taxAmount:10}];accountingGate=sourceGate=sourceOverride=null;identityUser='accountant';ensured=sourceCalls=0;rt.postedAccountingRequired=()=>true;context.FinanceReportingWorkspace.invalidate();await exactLoad(classified());}
(async()=>{
await test('Fresh report blocks full export until it autonomously loads verified book lines',async()=>{await reset();assert.throws(()=>api.requireTaxData(scope));assert.notEqual(api.taxWorkpaper(scope).status,'ready_for_review');await api.ensureTaxData(scope);assert.equal(ensured,1);let w=api.taxWorkpaper(scope);assert.equal(w.status,'ready_for_review');assert.equal(w.documents[0].bookTaxAmount,10);assert.equal(engine.workbookSheets(w).find(s=>s.name==='進項扣抵明細').rows[1][8],10);assert.equal(api.requireTaxData(scope).status,'ready');});
await test('Repeated report reads use matching source cache without opening any detail',async()=>{await api.ensureTaxData(scope);await api.ensureTaxData(scope);assert.equal(ensured,1);assert.equal(sourceCalls,1);assert.equal(api.taxWorkpaper(scope).documents[0].bookTaxAmount,10);});
await test('Legacy fully classified document is not silently given a verified binding',async()=>{await reset();let p=clone(saved);delete p.documents[key].sourceBinding;await exactLoad(p);await api.ensureTaxData(scope);let w=api.taxWorkpaper(scope);assert.equal(w.documents[0].sourceBindingStatus,'unverified');assert.equal(w.documents[0].included,false);assert(w.checks.some(c=>c.code==='SOURCE_BINDING_REVIEW'));assert.equal(saved.documents[key].sourceBinding,undefined);});
await test('Replacement at the same legacy index invalidates saved original amounts',async()=>{await reset();await api.ensureTaxData(scope);let old=clone(saved);requests[0].formPayload.lazyRows[0]={no:'CC00000003',item:'Replacement repair',date:'2026-08-12',grossAmount:315};requests[0].amt=315;posted=[{description:'Replacement repair',grossAmount:315,taxAmount:15}];assert.throws(()=>api.requireTaxData(scope));await api.ensureTaxData(scope);let w=api.taxWorkpaper(scope);assert.equal(w.documents[0].sourceBindingStatus,'changed');assert.equal(w.documents[0].included,false);assert.equal(w.status,'needs_review');assert.deepEqual(saved,old);});
await test('Changed source date cannot hide stale classification from its new reporting period',async()=>{await reset();requests[0].formPayload.lazyRows[0].date='2026-10-11';await api.ensureTaxData({eid:'A',period:'2026-10'});let w=api.taxWorkpaper({eid:'A',period:'2026-10'});assert.equal(w.documents.length,1);assert(w.checks.some(c=>c.code==='SOURCE_BINDING_REVIEW'));});
await test('Server evidence change invalidates binding even if visible fields are unchanged',async()=>{await reset();sourceOverride=out=>out.data.sources[key].binding.fingerprint='9'.repeat(64);await api.ensureTaxData(scope);assert.equal(api.taxWorkpaper(scope).documents[0].sourceBindingStatus,'changed');});
await test('Missing or cross-company batch response never becomes a complete source cache',async()=>{for(const mutate of [o=>delete o.data.sources[key],o=>o.data.entityId='B',o=>o.data.dataEnvironment='production']){await reset();sourceOverride=mutate;await api.ensureTaxData(scope);assert.equal(api.taxReadState(scope).status,'error');assert.throws(()=>api.requireTaxData(scope));}});
await test('Wrong source snapshot stays blocked even when saved fingerprint matches',async()=>{await reset();sourceOverride=out=>out.data.sources[key].snapshot.line.no='FOREIGN';await api.ensureTaxData(scope);assert.equal(api.taxWorkpaper(scope).documents[0].sourceBindingStatus,'changed');});
await test('Book-source error cannot produce a ready workbook and explicit retry recovers',async()=>{await reset();accountingGate=async()=>({status:'error',message:'fixture denied'});await api.ensureTaxData(scope);assert.equal(api.taxReadState(scope).status,'error');assert.throws(()=>api.requireTaxData(scope));assert.notEqual(api.taxWorkpaper(scope).status,'ready_for_review');accountingGate=null;await api.ensureTaxData(scope,true);assert.equal(api.taxWorkpaper(scope).documents[0].bookTaxAmount,10);assert.equal(api.requireTaxData(scope).status,'ready');});
await test('Ready voucher without matched lines is an explicitly unresolved workpaper, never ready',async()=>{await reset();accountingGate=async()=>({status:'ready',lines:null});await api.ensureTaxData(scope);assert.equal(api.taxReadState(scope).status,'ready');assert.equal(api.taxWorkpaper(scope).status,'needs_review');assert(api.taxWorkpaper(scope).checks.some(c=>c.code==='BOOK_TAX_UNRESOLVED'));assert.equal(api.taxWorkpaper(scope).documents[0].bookTaxAmount,null);});
await test('Unposted sources are explicit and never fetch or substitute draft accounting tax',async()=>{await reset();rt.postedAccountingRequired=()=>false;await api.ensureTaxData(scope);let w=api.taxWorkpaper(scope);assert.equal(ensured,0);assert.equal(w.documents[0].bookTaxStatus,'not_posted');assert.equal(w.documents[0].bookTaxAmount,null);assert.equal(w.documents[0].originalTaxAmount,10);});
await test('Company-scoped report never requests another company accounting rows',async()=>{await reset();requests.push({...sourceRow(),id:'other',eid:'B'});await api.ensureTaxData(scope);assert.equal(ensured,1);assert.equal(Object.keys(api.taxReadState(scope).accounting).length,1);});
await test('Unrelated prior-period advances do not block current-period book reads',async()=>{await reset();requests.push({...sourceRow(),id:'prior',type:'advance_request',formPayload:{lazyRows:[{date:'2025-01-01',grossAmount:100}]}});accountingGate=async r=>{assert.equal(r.id,'r1');return{status:'ready',lines:clone(posted)};};await api.ensureTaxData(scope);assert.equal(ensured,1);assert.equal(api.taxWorkpaper(scope).status,'ready_for_review');});
await test('Late source result cannot overwrite a newer source version',async()=>{await reset();let resolve,first=true;sourceGate=async(name,args)=>{if(first){first=false;const out=await originalRpc(name,args);return new Promise(r=>resolve=()=>r(out));}return originalRpc(name,args);};let pending=api.ensureTaxData(scope);await flush();requests[0].ver=2;await exactLoad(classified());await api.ensureTaxData(scope);let latest=api.taxReadState(scope);resolve();assert.equal(await pending,null);assert.equal(api.taxReadState(scope),latest);assert.equal(api.taxWorkpaper(scope).documents[0].sourceBindingStatus,'verified');});
await test('Late accounting result cannot overwrite a replaced request/version',async()=>{await reset();let resolve;accountingGate=()=>new Promise(r=>resolve=r);let pending=api.ensureTaxData(scope);await flush();requests[0]={...sourceRow(),ver:2};await exactLoad(classified());accountingGate=null;await api.ensureTaxData(scope);let latest=api.taxReadState(scope);resolve({status:'ready',lines:[{description:'Stationery',grossAmount:210,taxAmount:99}]});assert.equal(await pending,null);assert.equal(api.taxReadState(scope),latest);assert.equal(api.taxWorkpaper(scope).documents[0].bookTaxAmount,10);});
await test('Identity change discards in-flight source and book data',async()=>{await reset();let resolve;sourceGate=async(name,args)=>{const out=await originalRpc(name,args);return new Promise(r=>resolve=()=>r(out));};let pending=api.ensureTaxData(scope);await flush();identityUser='another-accountant';context.FinanceReportingWorkspace.invalidate();resolve();assert.equal(await pending,null);assert.equal(api.taxReadState(scope),null);assert.throws(()=>api.requireTaxData(scope));});
await test('More than 100 source selectors are completely paged without silent truncation',async()=>{await reset();requests=[];invoices=Array.from({length:201},(_,i)=>({id:'inv'+i,eid:'A',date:'2026-08-10',no:'AA'+String(i).padStart(8,'0'),amt:100,tax:5,total:105}));await api.ensureTaxData(scope);assert.equal(sourceCalls,3);assert.equal(Object.keys(api.requireTaxData(scope).sources).length,201);});
await test('Actual dialog captures server binding, replacing stale displayed amounts with current source',async()=>{await reset();delete saved.documents[key].sourceBinding;await exactLoad(saved);await api.openTaxDocument(key);const html=elements['finance-report-dialog'].innerHTML;assert(html.includes('data-source-binding='));assert(html.includes('來源版本未綁定或已變更'));assert(html.includes('name="originalTaxAmount" type="number" value=""'));assert(html.includes('name="number" type="text" value="BB00000002"'));});
await test('Submit refuses local source change after review, without issuing profile save',async()=>{await reset();const raw=api.taxRawSources(scope)[0],form={dataset:{rwForm:'document',document:key,sourceSnapshot:api.taxCanonical(raw.snapshot),sourceBinding:JSON.stringify(fixtureBinding(raw.snapshot))},values:{...classification('expense_request','r1'),reason:'Review original',isReturn:'no'}};lastSave=null;requests[0].formPayload.lazyRows[0].no='REPLACED';await assert.rejects(()=>api.submitProfileForm(form),/憑證已變更/);assert.equal(lastSave,null);});

await test('PDF click opens synchronously before asynchronous source verification, then writes only ready data',async()=>{await reset();context.FinanceReportingWorkspace.state.tab='tax';let opened=0,writes=0,closed=0,resolve;const popup={opener:{},document:{body:{textContent:''},open(){},write(){writes++;},close(){},getElementById(){return{addEventListener(){}};}},close(){closed++;}};context.open=()=>{opened++;return popup;};sourceGate=async(name,args)=>{const out=await originalRpc(name,args);return new Promise(r=>resolve=()=>r(out));};const node={dataset:{rwAction:'export-pdf'},closest(){return null;}},pending=api.onAction({target:{closest(){return node;}}});assert.equal(opened,1);assert.equal(writes,0);await flush();resolve();await pending;assert.equal(opened,1);assert.equal(writes,1);assert.equal(closed,0);assert.equal(popup.opener,null);});
await test('PDF verification failure or changed company closes the reserved window without report content',async()=>{for(const mode of ['error','company','identity']){await reset();context.FinanceReportingWorkspace.state.tab='tax';let writes=0,closed=0,resolve;context.open=()=>({document:{body:{textContent:''},write(){writes++;}},close(){closed++;}});sourceGate=async(name,args)=>{const out=await originalRpc(name,args);return new Promise(r=>resolve=()=>r(out));};const node={dataset:{rwAction:'export-pdf'},closest(){return null;}},pending=api.onAction({target:{closest(){return node;}}});await flush();if(mode==='error')accountingGate=async()=>({status:'error',message:'denied'});if(mode==='company')elements['rpt-ent'].value='B';if(mode==='identity')identityUser='changed';resolve();await assert.rejects(()=>pending);assert.equal(writes,0);assert.equal(closed,1);elements['rpt-ent'].value='A';}});
console.log(JSON.stringify({ok:true,tests,detailPagesOpened:0,productionWrites:0}));
})().catch(e=>{console.error(e);process.exitCode=1;});
