'use strict';
// Actual source/read coordination functions, with anonymous local transports only.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),engine=require('../assets/engines/financial-statements.js');
function extract(name){let start=source.indexOf('function '+name+'(');assert(start>=0,name);if(source.slice(start-6,start)==='async ')start-=6;const end=source.indexOf('\n',start);return source.slice(start,end).endsWith('}')?source.slice(start,end):source.slice(start,source.indexOf('\n}',end)+2);}
const pause=ms=>new Promise(r=>setTimeout(r,ms)),clone=x=>JSON.parse(JSON.stringify(x));let passed=0;
function check(label){passed++;console.log('PASS '+label);}
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return{promise,resolve,reject};}
function fixture(options={}){
 const c={Date,Promise,Number,Object,String,Array,Math,Error,AbortController,setTimeout,clearTimeout,console:{warn(){}},window:{FinanceFinancialStatements:engine},S:{user:{id:'finance-a',authUserId:'auth-a',role:'accountant'},page:'dashboard',approvalRuntimeTasks:[]},financeWorkspaceIdentityBlocked:false,CURRENT_PERMISSION_SNAPSHOT:{loaded:true,permissions:['read']},FINANCE_DRAFT_IDENTITY_EPOCH:0,FINANCE_DRAFT_READ_TIMEOUT_MS:12000,FINANCE_DRAFT_READ_RUNTIME:{identity:'',status:'idle',complete:false,total:null,loadedCount:0,rows:[],updatedAt:'',error:'',generation:0,promise:null,controller:null},remoteLoadPromise:null,STATEMENT_SOURCE_STATE:{ledger:{complete:false,status:'not_loaded'},invoices:{complete:false,status:'not_loaded'},expense_requests:{complete:false,status:'not_loaded'}},FINANCE_BOOTSTRAP_READ_QUEUE:{active:0,wide:0,waiting:[]},DASHBOARD_FINANCIAL_SOURCE_RUNTIME:{identity:'',generation:0,promise:null,status:'not_loaded',result:null},LEDGER:[{id:'old'}],USERS:[],REQS:[],INVS:[],BILLS:[],VOUCHERS:[],DRAFTS:[],SYSTEM_SETTINGS:{version:'old'},SYSTEM_SETTINGS_RUNTIME_KEYS:['accounts'],REMOTE_BOOTSTRAP_LIMITS:{vouchers:2500,bills:2500,optional:1200,requests:2500,invoices:2500},REMOTE_BOOTSTRAP_CONCURRENCY:2,REMOTE_AUDIT_BOOTSTRAP_LIMIT:50,lastSyncAt:'',remoteDataAuthUserId:'',APPROVAL_FAST_BOOTSTRAP:{hydrated:false},approvalFastBootstrapRunPromise:null,approvalFastBootstrapRunIdentity:'',remoteRefreshApprovalDirty:false,remoteRefreshApprovalInFlight:false,remoteRefreshPromise:null,queries:[],paints:[],issues:[],invalidations:0,applied:[],active:0,wide:0,max:0,maxWide:0};
 const wideTables=new Set(['ledger_entries','expense_requests','vouchers','bills','invoices','period_closes','compliance_archives','annual_reviews','compliance_audit_logs','backup_restore_events','system_setting_versions','payee_bank_accounts','invoice_lifecycle_events','bank_statement_imports','bank_transactions','bank_reconciliation_matches']);
 const client={from(table){const q={table,filters:[],start:0,end:999,select(){return q},eq(k,v){q.filters.push([k,v]);return q},in(){return q},or(filter){q.ownerFilter=filter;return q},order(){return q},limit(){return q},range(a,b){q.start=a;q.end=b;return q},abortSignal(signal){q.signal=signal;return q},then(resolve,reject){c.queries.push(q);if(table!=='draft_requests')c.active++;if(wideTables.has(table))c.wide++;c.max=Math.max(c.max,c.active);c.maxWide=Math.max(c.maxWide,c.wide);const finish=()=>{if(table!=='draft_requests')c.active--;if(wideTables.has(table))c.wide--;};let p;try{p=options.transport?options.transport(q,c):null;}catch(e){p=Promise.reject(e)}if(!p){const rows=table==='ledger_entries'?[{id:'new',entry_date:'2026-09-13',dataEnv:'production'}]:table==='system_settings'?[{key:'version',value:'fresh'}]:[];p=Promise.resolve({data:rows,count:rows.length,error:null});}return Promise.resolve(p).then(v=>{finish();return resolve(v)},e=>{finish();return reject(e)});}};return q;}};
 Object.assign(c,{hasSupabase:()=>!options.noClient,currentFinanceAuthUserId:()=>c.S.user&&c.S.user.authUserId||'',getSb:()=>options.noClient?null:client,approvalFastBootstrapIdentity:()=>c.S.user&&c.S.user.authUserId||'',currentTenantId:()=>c.tenant||'tenant-a',activeDataEnvironment:()=>c.environment||'production',normalizedRoleKey:u=>u.role,inActiveDataEnvironment:r=>(r.dataEnv||r.data_environment||'production')===(c.environment||'production'),mapLedger:r=>{if(options.mapFailure)throw Error('invalid ledger row');return Object.assign({},r,{mappedWith:c.SYSTEM_SETTINGS.version})},applySystemSettings:rows=>{c.applied.push(clone(rows));c.SYSTEM_SETTINGS={version:rows[0]&&rows[0].value}},invalidateDashboardFinancialCache:()=>c.invalidations++,invalidateDashboardFinancialModel:()=>{c.modelInvalidations=(c.modelInvalidations||0)+1},buildDash:()=>c.paints.push({complete:c.statementDataCompleteness().tables.ledger.complete,ledger:clone(c.LEDGER),settings:clone(c.SYSTEM_SETTINGS)}),recordRemoteReadIssue:(label,error)=>c.issues.push({label,error:error.message}),remoteTableMissing:e=>e.code==='MISSING',isTransientRemoteReadError:e=>e.code==='CLIENT_TIMEOUT'||/timeout/i.test(e.message),financeDataEngine:()=>null,
 syncRemoteFinanceUsersDirectory:async()=>({users:[c.S.user]}),resetApprovalSourceCompleteness:()=>{},setApprovalSourceCompleteness:()=>{},approvalRemoteSourceResultComplete:r=>!!r&&!r.error,loadFinanceNotifications:async()=>({data:[],error:null}),loadRemoteApprovalFallbackData:async(_,rows)=>options.fallback?options.fallback(rows):rows,remoteReadResultTimedOut:r=>!!(r&&r.error&&r.error.code==='CLIENT_TIMEOUT'),refreshOrgChartRowsFromRuntime:async()=>({ok:true}),normalizeRequestFlows:()=>{},scheduleRemoteRecovery:()=>{},approvalMutationRuntimeReady:()=>true,clearRemoteRecovery:()=>{},scheduleDeferredFinanceRuntimeRefresh:()=>{},uniqueRemoteStrings:x=>[...new Set(x)],draftBelongsToCurrentUser:()=>true,
 mapUser:x=>x,mapReq:x=>x,mapBill:x=>x,mapInv:x=>x,mapVoucher:x=>x,mapRemoteDraft:x=>x,mapPeriodClose:x=>x,mapComplianceArchive:x=>x,mapAnnualReview:x=>x,mapComplianceAudit:x=>x,mapBackupEvent:x=>x,mapSettingVersion:x=>x,mapPayeeBankAccount:x=>x,mapPortalRole:x=>x,mapInvoiceLifecycleEvent:x=>x,mapBankAccount:x=>x,mapBankStatementImport:x=>x,mapBankTransaction:x=>x,mapBankReconciliationMatch:x=>x});
 vm.createContext(c);const names=['statementDataIdentity','statementDataCompleteness','queueFinanceBootstrapRead','drainFinanceBootstrapReads','financeBootstrapRead','loadFinanceBootstrapOptionalTable','statementSourceResultCurrent','commitStatementSourceResult','paintDashboardFinancialSources','dashboardFinancialSourceIdentity','loadDashboardFinancialSources','loadFinanceDocumentSourcePage','loadStatementSourcePages','applyRemoteLimit','runRemoteJobsWithConcurrency','runFinanceBootstrapReadJobs','withOperationTimeout','financeDraftReadIdentity','draftReadinessForCurrentUser','paintCurrentUserDrafts','financeDraftOwnerFilter','loadCurrentUserDrafts','approvalDraftsCompleteForCurrentUser','remoteRowKey','mergeRemoteRowsByKey','financeReadSourceSnapshot','mergeFinanceReadSourceRows','performRemoteDataLoad'];vm.runInContext(names.map(extract).join('\n'),c);
 if(options.timeout){const original=c.withOperationTimeout;c.withOperationTimeout=(p,label,ms)=>original(p,label,ms===120000?options.timeout*10:options.timeout);}
 return c;
}
async function run(){
 {
 const settings=deferred(),c=fixture({transport:q=>q.table==='system_settings'?settings.promise:null});const loading=c.loadDashboardFinancialSources(true);await pause(0);assert.equal(c.STATEMENT_SOURCE_STATE.ledger.complete,false);assert.deepEqual(c.LEDGER,[{id:'old'}]);assert.equal(c.loadDashboardFinancialSources(true),loading);settings.resolve({data:[{key:'version',value:'new-settings'}]});assert((await loading).ok);assert.equal(c.LEDGER[0].mappedWith,'new-settings');assert(c.STATEMENT_SOURCE_STATE.ledger.complete);assert(c.paints.some(p=>p.complete&&p.ledger[0].id==='new'));assert.equal(c.max,2);assert.equal(c.maxWide,1);check('ledger and settings commit together; no completed state for old rows, settings precede mapping, force shares pending core');
 assert((await c.loadDashboardFinancialSources(false)).ok);assert.equal(c.queries.length,2);check('successful current source snapshot is reusable without another read');
 assert.equal(c.invalidations,0);assert.equal(c.modelInvalidations,1);check('verified core publication invalidates only the local model, preserving independent in-flight AR');
 }
 {
 const c=fixture();Object.assign(c,{APPROVAL_BOOTSTRAP_COORDINATOR:{identity:'',generation:0,promise:null},approvalBootstrapGeneration:0,loadApprovalFastBootstrap:async()=>{c.APPROVAL_FAST_BOOTSTRAP.hydrated=true;return{ok:true,hydrated:true}}});
 vm.runInContext(['loadRemoteData','approvalBootstrapCoordinatorForCurrentUser','approvalFastThenRemoteBootstrap'].map(extract).join('\n'),c);
 const result=await c.approvalFastThenRemoteBootstrap('login');assert(result.ok);assert(c.STATEMENT_SOURCE_STATE.ledger.complete);assert(c.queries.length>10,'actual broad coordinator must perform source reads');assert.equal(c.invalidations,0);assert(c.modelInvalidations>0);check('real cold coordinator uses the default remote loader without revoking the independent AR read');
 await c.loadRemoteData();assert.equal(c.invalidations,1);assert(c.STATEMENT_SOURCE_STATE.ledger.complete);check('explicit remote reload fully invalidates AR once before a fresh source read');
 }
 {
 const waiting=deferred(),c=fixture({transport:q=>q.table==='ledger_entries'?waiting.promise:null});vm.runInContext(extract('loadRemoteData'),c);const cold=c.loadRemoteData({preserveDashboardAggregate:true});await pause(0);assert.equal(c.invalidations,0);const explicit=c.loadRemoteData();assert.equal(c.invalidations,1,'a requested resync must invalidate even while joining an existing source read');waiting.resolve({data:[{id:'joined'}],count:1});assert.equal(await cold,true);assert.equal(await explicit,true);assert.equal(c.queries.filter(q=>q.table==='ledger_entries').length,1);check('explicit resync during cold broad read invalidates AR while sharing the existing source transport');
 }
 {
 const c=fixture(),oldFast=deferred(),newFast=deferred();let refreshed=0;Object.assign(c,{remoteRefreshApprovalRevision:0,approvalFastBootstrapRunIdentity:c.approvalFastBootstrapIdentity(),approvalFastBootstrapRunPromise:oldFast.promise,setTopSyncStatus:()=>{},syncStatusText:()=>'',requestApprovalFastBootstrap:async(reason,options)=>{assert.equal(reason,'committed-fixture');assert(options.force);refreshed++;return newFast.promise;}});vm.runInContext(extract('refreshApprovalAfterCommittedAction'),c);const committed=c.refreshApprovalAfterCommittedAction('committed-fixture','invoices',['fictional-id']);assert.equal(c.invalidations,1,'committed mutation invalidates AR before any slow readback');assert.equal(refreshed,0);oldFast.resolve();await pause(0);assert.equal(refreshed,1);newFast.resolve({hydrated:true});assert.equal(await committed,true);assert.equal(c.invalidations,1);check('committed approval invalidates AR immediately and still waits for a new authority readback');
 }
 {
 const c=fixture({mapFailure:true});assert.equal((await c.loadDashboardFinancialSources(true)).ok,false);assert.equal(c.STATEMENT_SOURCE_STATE.ledger.complete,false);assert.equal(c.STATEMENT_SOURCE_STATE.ledger.status,'error');assert.equal(c.LEDGER[0].id,'old');check('mapping failure cannot certify or replace existing ledger');
 }
 for(const mutation of [c=>c.S.user.authUserId='auth-b',c=>c.S.user.id='finance-b',c=>c.S.user.role='employee',c=>c.tenant='tenant-b',c=>c.environment='test',c=>c.financeWorkspaceIdentityBlocked=true,c=>c.CURRENT_PERMISSION_SNAPSHOT.permissions=['changed']]){
 const d=deferred(),c=fixture({transport:q=>q.table==='ledger_entries'?d.promise:null});const loading=c.loadDashboardFinancialSources(true);await pause(0);mutation(c);d.resolve({data:[{id:'stale'}],count:1});assert.equal((await loading).stale,true);assert.equal(c.LEDGER[0].id,'old');assert.equal(c.statementDataCompleteness().tables.ledger.complete,false);check('identity/scope/role/lock change rejects late core without promoting old data');
 }
 {
 const c=fixture();await c.loadDashboardFinancialSources(true);c.S.user.n='refreshed label';c.S.user.jobTitle='updated title';assert.equal(c.statementDataCompleteness().tables.ledger.complete,true);check('same auth person metadata refresh does not invalidate successful financial data');
 }
 {
 const old=deferred();let fail=true;const c=fixture({timeout:10,transport:q=>q.table==='system_settings'&&fail?old.promise:null});assert.equal((await c.loadDashboardFinancialSources(true)).ok,false);assert.equal(c.STATEMENT_SOURCE_STATE.ledger.status,'error');const timed=c.queries.find(q=>q.table==='system_settings');assert(timed.signal.aborted);fail=false;assert((await c.loadDashboardFinancialSources(true)).ok);const current=clone(c.LEDGER);old.resolve({data:[{key:'version',value:'late-old'}]});await pause(0);assert.deepEqual(clone(c.LEDGER),current);assert.equal(c.SYSTEM_SETTINGS.version,'fresh');assert.equal(c.STATEMENT_SOURCE_STATE.ledger.complete,true);check('failed settings deadline aborts; explicit retry succeeds and late old settings cannot overwrite it');
 }
 {
 const c=fixture({noClient:true});assert.equal((await c.loadDashboardFinancialSources(true)).ok,false);assert.equal(c.STATEMENT_SOURCE_STATE.ledger.status,'error');assert(c.paints.length);check('missing client is a visible retryable error, never an endless not-loaded state');
 }
 {
 const c=fixture();c.S.user.role='employee';assert.equal((await c.loadDashboardFinancialSources(true)).forbidden,true);assert.equal(c.queries.length,0);check('employee cannot start a privileged financial read');
 }
 {
 const blocked=deferred();let hit=false;const c=fixture({timeout:20,transport:q=>{if(q.table==='vouchers'){hit=true;return blocked.promise}return null}});const broad=c.performRemoteDataLoad();await pause(5);assert(hit);assert.equal(c.LEDGER[0].id,'new');assert.equal(c.STATEMENT_SOURCE_STATE.ledger.complete,true);assert(c.paints.some(p=>p.complete));assert(c.queries.findIndex(q=>q.table==='ledger_entries')<c.queries.findIndex(q=>q.table==='vouchers'));await assert.rejects(broad,e=>e.code==='CLIENT_TIMEOUT');assert(c.queries.find(q=>q.table==='vouchers').signal.aborted);assert.equal(c.LEDGER[0].id,'new');blocked.resolve({data:[]});await pause(0);check('true broad loader displays verified core before hanging vouchers and stops waiting on its deadline');
 }
 {
 const tail=deferred();let generation=0,reached=false;const c=fixture({transport:q=>q.table==='ledger_entries'?Promise.resolve({data:[{id:'generation-'+(++generation)}],count:1}):null,fallback:rows=>{reached=true;return tail.promise.then(()=>rows)}});const broad=c.performRemoteDataLoad();for(let i=0;!reached&&i<50;i++)await pause(1);assert(reached);assert.equal(c.LEDGER[0].id,'generation-1');assert((await c.loadDashboardFinancialSources(true)).ok);assert.equal(c.LEDGER[0].id,'generation-2');tail.resolve();assert.equal(await broad,true);assert.equal(c.LEDGER[0].id,'generation-2');assert.equal(c.STATEMENT_SOURCE_STATE.ledger.complete,true);assert(c.STATEMENT_SOURCE_STATE.invoices.complete);assert(c.STATEMENT_SOURCE_STATE.expense_requests.complete);assert(c.max<=2);assert(c.maxWide<=1);check('late broad merge cannot overwrite a newer core generation; requests/invoices certify only after real array commit');
 }
 {
 const c=fixture(),d=deferred(),starts=[];const wide=c.queueFinanceBootstrapRead(()=>{starts.push('old-wide');return d.promise},true,false);await pause(0);const next=c.loadDashboardFinancialSources(true);await pause(0);assert(!c.queries.some(q=>q.table==='ledger_entries'));assert(c.queries.some(q=>q.table==='system_settings'));d.resolve();await wide;assert((await next).ok);check('manual core retry shares the existing one-wide/two-total read scheduler');
 }

 {
 const c=fixture({transport:q=>q.table==='ledger_entries'?Promise.resolve({data:[],count:0}):null});assert((await c.loadDashboardFinancialSources(true)).ok);assert.equal(c.LEDGER.length,0);assert.equal(c.STATEMENT_SOURCE_STATE.ledger.total,0);assert.equal(c.STATEMENT_SOURCE_STATE.ledger.complete,true);check('verified empty ledger is a real zero-row result; no fabricated rows or stale totals');
 }
 {
 const c=fixture({transport:q=>q.table==='ledger_entries'?Promise.resolve(q.start===0?{data:Array.from({length:1000},(_,i)=>({id:'p'+i})),count:1001}:{error:Error('second page rejected')}):null});assert.equal((await c.loadDashboardFinancialSources(true)).ok,false);assert.equal(c.LEDGER[0].id,'old');assert.equal(c.STATEMENT_SOURCE_STATE.ledger.complete,false);assert.equal(c.STATEMENT_SOURCE_STATE.ledger.status,'error');check('failed later page never commits a partial ledger or uses old rows as verified');
 }
 {
 const d=deferred();const c=fixture({timeout:10,transport:q=>q.table==='bank_transactions'?d.promise:null});assert.equal(await c.performRemoteDataLoad(),true);assert.equal(c.STATEMENT_SOURCE_STATE.ledger.complete,true);assert.equal(c.LEDGER[0].id,'new');assert(c.issues.some(e=>e.label==='bank_transactions'));assert(c.queries.find(q=>q.table==='bank_transactions').signal.aborted);d.resolve({data:[{id:'late-bank-row'}]});await pause(0);assert.equal(c.BANK_TRANSACTIONS.length,0);check('optional bank timeout is recorded and aborts; broad completes without replacing verified finance or late optional data');
 }
 {
 const c=fixture({transport:q=>q.table==='system_settings'?Promise.resolve({error:Error('settings denied')}):null});await assert.rejects(c.performRemoteDataLoad(),/settings denied/);assert.equal(c.STATEMENT_SOURCE_STATE.ledger.complete,false);assert.equal(c.lastSyncAt,'');check('mandatory configuration denial cannot be relabeled as successful broad bootstrap');
 }

 for(const change of [c=>{c.financeWorkspaceIdentityBlocked=true;return()=>{c.financeWorkspaceIdentityBlocked=false}},c=>{c.S.user.authUserId='auth-b';return()=>{c.S.user.authUserId='auth-a'}}]){
 const d=deferred();let pending=true;const c=fixture({transport:q=>q.table==='ledger_entries'&&pending?d.promise:null});const old=c.loadDashboardFinancialSources(true);await pause(0);const restore=change(c);d.resolve({data:[{id:'old-inflight'}],count:1});assert((await old).stale);assert.equal(c.DASHBOARD_FINANCIAL_SOURCE_RUNTIME.promise,null);restore();pending=false;assert((await c.loadDashboardFinancialSources(true)).ok);assert.equal(c.queries.length,4);assert.equal(c.LEDGER[0].id,'new');assert(c.STATEMENT_SOURCE_STATE.ledger.complete);check('stale core settles its own promise; original identity can explicitly retry after reauthentication/switch-back');
 }
 {
 const oldLedger=deferred(),newSettings=deferred();let settingsCalls=0,ledgerCalls=0;const c=fixture({transport:q=>q.table==='ledger_entries'&&++ledgerCalls===1?oldLedger.promise:q.table==='system_settings'&&++settingsCalls===2?newSettings.promise:null});const old=c.loadDashboardFinancialSources(true);await pause(0);c.S.user.authUserId='auth-b';const newer=c.loadDashboardFinancialSources(true);await pause(0);oldLedger.resolve({data:[{id:'old'}],count:1});assert((await old).stale);assert.equal(c.DASHBOARD_FINANCIAL_SOURCE_RUNTIME.promise,newer);newSettings.resolve({data:[{key:'version',value:'new'}]});assert((await newer).ok);assert(c.STATEMENT_SOURCE_STATE.ledger.complete);check('old identity cleanup cannot clear a newer core generation promise');
 }
 console.log('OK: '+passed+' actual dashboard financial source checks');
}
module.exports={fixture};
if(require.main===module)run().catch(e=>{console.error(e);process.exitCode=1});
