// Local actual-DOM verification. Requires agent-browser on PATH (or AGENT_BROWSER_BIN).
// The shipped index is unchanged on disk; only the localhost HTTP response exposes
// a closure test hook. Fictional fixture, external scripts removed, outbound fetch
// and form submission blocked. No real login, credentials, or production API.
// Usage: node scripts/check_employee_auth_notifications_browser.cjs [evidence-dir]
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict'),cp=require('node:child_process'),util=require('node:util'),crypto=require('node:crypto');
const run=util.promisify(cp.execFile),root=path.resolve(__dirname,'..'),out=path.resolve(process.argv[2]||'/tmp/finance-employee-auth-after-20260912');
const session='employee-auth-'+process.pid,bin=process.env.AGENT_BROWSER_BIN||'agent-browser';
const {applyBuildEnvironment}=require('./finance_build_environment');
const source=fs.readFileSync(path.join(root,'index.html'),'utf8'),sourceHash=crypto.createHash('sha256').update(source).digest('hex');
let html=applyBuildEnvironment(source,{target:'local',supabaseUrl:'',supabaseAnonKey:''});
const hook='window.__employeeAudit={run:async function(code){return await eval(code);}};\n';
assert.ok(html.includes('bootAuthGate();\n\n})();'),'exact local-only closure anchor');
html=html.replace('bootAuthGate();\n\n})();',hook+'bootAuthGate();\n\n})();').replace(/<script\b[^>]*src=["']https?:[^>]*><\/script>/gi,'').replace('<head>','<head><meta http-equiv="Content-Security-Policy" content="connect-src \'self\'; form-action \'none\'">');
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(p!==root&&!p.startsWith(root+'/')){res.writeHead(403);return res.end();}if(p===root||p===path.join(root,'index.html')){res.setHeader('content-type','text/html; charset=utf-8');return res.end(html);}if(!fs.existsSync(p)||!fs.statSync(p).isFile()){res.writeHead(404);return res.end();}res.setHeader('content-type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.png')?'image/png':'application/octet-stream');res.end(fs.readFileSync(p));});
const b=async(...args)=>(await run(bin,['--session',session,...args],{maxBuffer:8e6,timeout:45000})).stdout;
async function scoped(code){let v=JSON.parse(await b('eval','--base64',Buffer.from('(async()=>JSON.stringify(await window.__employeeAudit.run('+JSON.stringify(code)+')))()').toString('base64')));return typeof v==='string'?JSON.parse(v):v;}
const evidence={scope:'actual index and engines, localhost response hook, fictional fixture; not real-account E2E',sourceHash,browser:[],network:'No remote API; CSP connect-src self, no external scripts'};
const fixture=`USERS=[{id:'fixture-employee',n:'林星河',email:'fixture.employee@example.invalid',role:'employee',rL:'一般組員',dc:'T1101',eid:'E1',init:'林',active:true},{id:'fixture-other',n:'林星河',email:'fixture.other@example.invalid',role:'employee',rL:'一般組員',dc:'T1101',eid:'E1',init:'林',active:true}];ENTS=[{id:'E1',s:'星河測試公司',full:'星河測試公司',active:true}];DEPTS=[{c:'T1101',n:'測試行政組',eid:'E1',entityCodes:['E1'],lv:3,active:true,isPostingUnit:true}];DEPARTMENT_HISTORY_ALIASES=[];ORG_CHART=[];REQS=[];INVS=[];BILLS=[];VOUCHERS=[];LEDGER=[];NOTIFS=[];DRAFTS=[];quickLogin('employee');S.user.authUserId='10000000-0000-0000-0000-000000000001';S.user.tenantId=currentTenantId();
REQS=[mapReq({id:'fixture-own',no:'UX-OWN-001',entity_id:'E1',department_code:'T1101',applicant:'林星河舊名',applicant_id:'fixture-employee',applicant_email:'fixture.employee@example.invalid',type:'expense_reimbursement',type_label:'費用報銷',amount:1250,status:'pending_ceo',step:2,ver:1,request_date:'2026-09-12',description:'本人更名前送出的測試申請',steps:[],files:[],data_environment:'test',tenant_id:currentTenantId()}),mapReq({id:'fixture-other-request',no:'UX-OTHER-002',entity_id:'E1',department_code:'T1101',applicant:'林星河',applicant_id:'fixture-other',applicant_email:'fixture.other@example.invalid',type:'expense_reimbursement',type_label:'費用報銷',amount:777,status:'pending_ceo',step:2,ver:1,request_date:'2026-09-12',description:'同名另一人的測試申請，不得顯示在本人工作台',steps:[],files:[],data_environment:'test',tenant_id:currentTenantId()})];buildDash();`;
(async()=>{
  fs.mkdirSync(out,{recursive:true});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));evidence.url='http://127.0.0.1:'+server.address().port;
  await b('open',evidence.url);await scoped(`(function(){${fixture}return true;})()`);await b('wait','150');
  for(const width of [1440,390]){
    await b('set','viewport',String(width),width===390?'844':'1000');
    const home=await scoped(`({text:el('dash-tbl').innerText,guide:el('dash-employee-guide').innerText,overflow:document.documentElement.scrollWidth>innerWidth+1})`);
    assert.match(home.text,/UX-OWN-001/);assert.doesNotMatch(home.text,/UX-OTHER-002/);assert.equal(home.overflow,false);
    await b('screenshot',path.join(out,'home-'+width+'.png'));
    await scoped(`(function(){el('dash-employee-guide').querySelector('button').focus();window.__returnFocus=document.activeElement;showFinanceAuthRecovery({reason:'auth_session_expired',message:'離線測試：登入到期，內容仍保留。'},'送出申請');return true;})()`);
    assert.equal(await scoped(`el('finance-auth-recovery').contains(document.activeElement)`),true);
    await scoped(`(function(){el('dash-employee-guide').querySelector('button').focus();return true;})()`);
    assert.equal(await scoped(`el('finance-auth-recovery').contains(document.activeElement)`),true,'background cannot steal focus');
    for(const key of ['Tab','Tab','Shift+Tab']){await b('press',key);assert.equal(await scoped(`el('finance-auth-recovery').contains(document.activeElement)`),true,'modal contains keyboard focus');}
    await b('press','Escape');assert.equal(await scoped(`!el('finance-auth-recovery').open&&document.activeElement===window.__returnFocus`),true,'escape and return focus for unlocked workspace');
    const recovery=await scoped(`(async function(){setFinanceWorkspaceIdentityBlocked(true);showFinanceAuthRecovery({reason:'auth_identity_mismatch',message:'離線測試：工作區已鎖定，需要本人重新驗證。'},'繼續使用');window.__oldHost=ensureOfficialHostBeforeOAuth;window.__oldSb=getSb;window.__oldTimeout=FINANCE_REAUTH_TIMEOUT_MS;ensureOfficialHostBeforeOAuth=function(){return true};FINANCE_REAUTH_TIMEOUT_MS=30;window.__attempts=0;getSb=function(){return{auth:{signInWithOAuth:function(options){window.__attempts++;if(!options.options.skipBrowserRedirect)throw new Error('unsafe SDK redirect');return Promise.reject(new Error('Fixture offline'));}}}};await startFinanceReauthentication();return{retry:!!el('finance-auth-recovery').querySelector('[data-finance-auth-retry]:not(:disabled)'),locked:financeWorkspaceIdentityBlocked,inert:el('main-wrap').inert,hidden:el('main-wrap').style.visibility,focus:el('finance-auth-recovery').contains(document.activeElement),attempts:window.__attempts};})()`);
    assert.deepEqual(recovery,{retry:true,locked:true,inert:true,hidden:'hidden',focus:true,attempts:1});
    await b('press','Escape');assert.equal(await scoped(`el('finance-auth-recovery').open`),true);
    await b('click','[data-finance-auth-retry]');assert.equal(await scoped(`window.__attempts`),2,'real retry button invokes handler');
    const timeout=await scoped(`(async function(){window.__attempts=0;getSb=function(){return{auth:{signInWithOAuth:function(){window.__attempts++;return new Promise(function(resolve){window.__lateOAuth=resolve});}}}};var first=startFinanceReauthentication(),second=startFinanceReauthentication();await Promise.all([first,second]);return{attempts:window.__attempts,text:el('finance-auth-recovery').innerText,retry:!!el('finance-auth-recovery').querySelector('[data-finance-auth-retry]:not(:disabled)'),overflow:document.documentElement.scrollWidth>innerWidth+1,controls:Array.from(el('finance-auth-recovery').querySelectorAll('button')).map(function(x){var r=x.getBoundingClientRect();return{h:r.height,w:r.width}})};})()`);
    assert.equal(timeout.attempts,1);assert.equal(timeout.retry,true);assert.match(timeout.text,/逾時/);assert.equal(timeout.overflow,false);assert.ok(timeout.controls.every(x=>x.h>=44&&x.w>=44),JSON.stringify(timeout));
    await b('screenshot',path.join(out,'recovery-timeout-'+width+'.png'));
    await scoped(`(function(){getSb=window.__oldSb;ensureOfficialHostBeforeOAuth=window.__oldHost;FINANCE_REAUTH_TIMEOUT_MS=window.__oldTimeout;setFinanceWorkspaceIdentityBlocked(false);hideFinanceAuthRecovery();return true;})()`);
    evidence.browser.push({width,home,recovery,timeout});
  }
  // Keep real rendering and real loader. Only the table transport is stubbed;
  // neither the fixture nor the runtime can reach Supabase.
  await scoped(`(function(){S.demoLogin=false;FINANCE_NOTIFICATION_STATE=null;FINANCE_NOTIFICATION_TIMEOUT_MS=30;window.__noticeReads=0;window.__noticeMode='timeout';getSb=function(){return{from:function(table){if(table!=='notifications')throw new Error('Unexpected table '+table);return{select:function(cols,opts){if(opts.count!=='exact')throw new Error('Missing exact count');return this},eq:function(){return this},order:function(){return this},limit:function(){return this},abortSignal:function(){return this},then:function(resolve,reject){window.__noticeReads++;return(window.__noticeMode==='timeout'?new Promise(function(){}):window.__noticeMode==='error'?Promise.resolve({data:null,error:{code:'CLIENT_TIMEOUT'}}):Promise.resolve({data:window.__noticeMode==='empty'?[]:[{id:'fixture-notice',type:'system',title:'測試通知：請確認自己的申請',body:'虛構資料，沒有正式發送',read:false,data_environment:activeDataEnvironment(),tenant_id:currentTenantId()}],count:window.__noticeMode==='empty'?0:1,error:null})).then(resolve,reject)}}}}};lastSyncAt=new Date().toISOString();nav('notif',null);return true;})()`);
  await scoped(`(async function(){if(FINANCE_NOTIFICATION_STATE.promise)await FINANCE_NOTIFICATION_STATE.promise;return true;})()`);
  const fail=await scoped(`({pending:!!FINANCE_NOTIFICATION_STATE.promise,timeout:FINANCE_NOTIFICATION_TIMEOUT_MS,identityCurrent:FINANCE_NOTIFICATION_STATE.identity===financeNotificationIdentity(),status:financeNotificationView().status,unread:financeNotificationView().unread,text:el('pg-notif').innerText,badge:el('notif-cnt').innerText,markAllDisabled:el('notif-mark-all').disabled})`);
  assert.equal(fail.status,'error',JSON.stringify(fail)+' '+await b('errors'));assert.equal(fail.unread,null);assert.equal(fail.badge,'—');assert.equal(fail.markAllDisabled,true);assert.doesNotMatch(fail.text,/0 則未讀|沒有通知/);
  for(const width of [1440,390]){await b('set','viewport',String(width),width===390?'844':'1000');await b('screenshot',path.join(out,'notification-first-failure-'+width+'.png'));}
  await scoped(`(function(){window.__noticeMode='one';return true;})()`);await b('click','#notif-load-status [data-finance-notification-retry]');await scoped(`(async function(){if(FINANCE_NOTIFICATION_STATE.promise)await FINANCE_NOTIFICATION_STATE.promise;return true;})()`);
  assert.equal(await scoped(`financeNotificationView().unread`),1);const stamp=await scoped(`financeNotificationView().lastSuccessAt`);assert.ok(stamp);
  await scoped(`(async function(){window.__noticeMode='error';await retryFinanceNotifications();return true;})()`);
  const stale=await scoped(`({unread:financeNotificationView().unread,stamp:financeNotificationView().lastSuccessAt,text:el('pg-notif').innerText})`);
  assert.equal(stale.unread,1);assert.equal(stale.stamp,stamp);assert.match(stale.text,/上次成功更新/);assert.match(stale.text,/測試通知/);
  for(const width of [1440,390]){await b('set','viewport',String(width),width===390?'844':'1000');assert.equal(await scoped(`document.documentElement.scrollWidth>innerWidth+1`),false);await b('screenshot',path.join(out,'notification-last-success-'+width+'.png'));}
  await scoped(`(function(){window.__noticeMode='empty';return true;})()`);await b('click','#notif-load-status [data-finance-notification-retry]');await scoped(`(async function(){if(FINANCE_NOTIFICATION_STATE.promise)await FINANCE_NOTIFICATION_STATE.promise;return true;})()`);
  assert.equal(await scoped(`financeNotificationView().unread`),0);assert.match(await scoped(`el('notif-list').innerText`),/沒有通知/);
  evidence.notifications={fail,stale,final:await scoped(`({status:financeNotificationView().status,unread:financeNotificationView().unread,reads:window.__noticeReads,overflow:document.documentElement.scrollWidth>innerWidth+1})`)};
  evidence.errors=(await b('errors')).trim();assert.ok(!evidence.errors||/No (?:page )?errors/i.test(evidence.errors),evidence.errors);
  assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'index.html'))).digest('hex'),sourceHash,'on-disk source unchanged by browser harness');
  fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify(evidence,null,2));console.log('PASS actual DOM: desktop/mobile owner identity, recovery retry/focus/lock, notification timeout and successful retry. '+out);
})().catch(error=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({message:error.message,evidence},null,2));console.error(error);process.exitCode=1;}).finally(async()=>{try{await b('close');}catch(_){}server.close();});
