'use strict';
// Actual shipped DOM, event handlers and OCR adapter. Fictional local identities
// and a fake OCR response only; no database, Storage or external network writes.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),out=process.env.FINANCE_FORMS_EVIDENCE||'/tmp/finance-forms-fixes-browser-20260914';
const {applyBuildEnvironment}=require('./finance_build_environment');const source=fs.readFileSync(path.join(root,'index.html'),'utf8'),anchor='bootAuthGate();\n\n})();';assert(source.includes(anchor));
let html=applyBuildEnvironment(source,{target:'local',supabaseUrl:'',supabaseAnonKey:''}).replace(anchor,'window.__formsFix={run:async function(code){return await eval(code)}};\n'+anchor).replace(/<script\b[^>]*src=["']https?:[^>]*><\/script>/gi,'');
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://local').pathname,p=path.resolve(root,'.'+pathname);if(p!==root&&!p.startsWith(root+'/')){res.writeHead(403);return res.end();}res.setHeader('Content-Security-Policy',"connect-src 'none'; form-action 'none'; img-src 'self' data: blob:; font-src 'self' data:");if(p===root||p===root+'/index.html'){res.setHeader('Content-Type','text/html');return res.end(html);}if(!fs.existsSync(p)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(p));});
const setup=`(function(){window.__writes=[];window.__alerts=[];window.__identityGuards=[];var nativeAlert=window.alert;window.alert=x=>{window.__alerts.push(String(x));return nativeAlert(x);};window.fetch=()=>{throw Error('Network forbidden')};getSb=()=>{window.__writes.push('database');throw Error('Database forbidden')};USERS=[{id:'fictional-accountant',n:'虛構會計',role:'accountant',rL:'會計',email:'accountant@example.invalid',eid:'F1',dc:'D1',active:true},{id:'fictional-ceo',n:'虛構主管',role:'ceo',email:'ceo@example.invalid',eid:'F1',dc:'D1',active:true}];ENTS=[{id:'F1',full:'虛構甲法人',s:'虛構甲法人',active:true},{id:'F2',full:'虛構乙法人',s:'虛構乙法人',active:true}];DEPTS=[{c:'D1',n:'虛構部門',eid:'F1',entityCodes:['F1'],newFormEntityCodes:['F1'],lv:3,active:true,isPostingUnit:true}];REQS=[];INVS=[];BILLS=[];VOUCHERS=[];LEDGER=[];NOTIFS=[];ORG_CHART=[];quickLogin('accountant');guardSubmissionIdentityDirectory=async function(label){window.__identityGuards.push(label);return false;};nav('shareholder');return true})()`;
function invoice(net,tax,total,items){return {invoice_number:'FICT-001',invoice_date:'2026-09-14',seller_name:'虛構開立人',seller_tax_id:'',buyer_name:'虛構買受人',buyer_tax_id:'',description:'九月服務合計',amount_excluding_tax:net,tax_amount:tax,total_amount:total,currency:'TWD',confidence:1,accounting_subject_suggestion:'收入',usage_context_suggestion:'測試',tax_treatment_suggestion:'需會計確認',assetization_suggestion:'不需資產化',items:items||[],warnings:[]};}
function item(name,total){return {item_name:name,quantity:1,unit:'次',unit_price:total,total_amount:total};}
(async()=>{fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;if(process.argv.includes('--serve')){console.log(JSON.stringify({origin,setup}));return;}
const {chromium}=require('playwright'),browser=await chromium.launch({headless:true,channel:process.env.FINANCE_BROWSER_CHANNEL||'chrome'}),evidence={scope:'Fictional local fixtures, actual DOM/handlers, no business writes or external fetch',sourceHash:crypto.createHash('sha256').update(source).digest('hex'),runs:[]};let checks=0;function eq(a,b,label){assert.deepEqual(a,b,label);checks++;console.log('PASS '+label);}function ok(v,label){assert.ok(v,label);checks++;console.log('PASS '+label);}try{
for(const width of [1440,390]){const ctx=await browser.newContext({viewport:{width,height:width===390?844:1000}}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',dialog=>dialog.dismiss());await ctx.route('**/*',route=>new URL(route.request().url()).origin===origin&&route.request().method()==='GET'?route.continue():route.abort());await page.goto(origin,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__formsFix);const run=code=>page.evaluate(code=>window.__formsFix.run(code),code);await run(setup);
 eq(await page.evaluate(()=>['syncShareholderTxnOptions','syncShareholderDirection','submitShareholderTxn'].map(n=>typeof window[n])),['function','function','function'],'public event entrypoints '+width);
 if(width===390)await page.getByRole('button',{name:'下一步',exact:true}).click();
 const categories={shareholder_funds:'shareholder_loan_in',intercompany_funds:'company_loan_out',investment_equity:'equity_acquisition',interest_fee:'interest_expense'};
 for(const [category,first] of Object.entries(categories)){await page.locator('#sh-category').selectOption(category);eq(await page.locator('#sh-type option').first().getAttribute('value'),first,'category actual change '+category+' '+width);}
 await page.locator('#sh-category').selectOption('intercompany_funds');await page.locator('#sh-type').selectOption('company_loan_repay');eq(await page.locator('#sh-cash-direction').inputValue(),'transfer','repayment direction updates '+width);eq(await page.locator('#sh-offset-required').inputValue(),'yes','repayment offset updates '+width);
 await page.locator('#sh-amt').fill('1000');if(width===390)await page.getByRole('button',{name:'下一步',exact:true}).click();await page.locator('#sh-submit-btn').click();eq(await run('window.__identityGuards'),['公司往來簽核單'],'real submit reaches unchanged identity gate '+width);await page.waitForFunction(()=>window.__formsFix.run('ACTION_FEEDBACK_ACTIVE===0'));eq(await page.locator('#action-feedback').evaluate(n=>n.classList.contains('show')),false,'rejected identity gate never announces submission success '+width);
 await run(`window.__identityGuards=[];window.__alerts=[];guardSubmissionIdentityDirectory=async function(label){window.__identityGuards.push(label);return await new Promise(resolve=>{window.__releaseSubmit=()=>resolve(false);});};`);
 await page.locator('#sh-submit-btn').click();ok(await page.locator('#action-feedback.show').isVisible(),'processing overlay protects actual button '+width);await run('window.submitShareholderTxn()');eq(await run('window.__identityGuards.length'),1,'reentrant public submit shares first async identity gate '+width);ok((await run('window.__alerts.join(" ")')).includes('正在送出'),'reentrant submit has explicit processing feedback '+width);await run('window.__releaseSubmit();true');await page.waitForFunction(()=>window.__formsFix.run('!POSTING_IN_FLIGHT.shareholderSubmit'));await page.waitForFunction(()=>!document.getElementById('action-feedback').classList.contains('show'));
 // Invoke the same public entry under an unauthorized fictional role: the true
 // product access guard, rather than the test identity boundary, must reject it.
 await run(`(async function(){window.__alerts=[];window.__identityGuards=[];guardSubmissionIdentityDirectory=async label=>{window.__identityGuards.push(label);return false;};S.user.role='employee';await window.submitShareholderTxn();S.user.role='accountant';})()`);
 eq(await run('window.__identityGuards.length'),0,'permission refusal precedes identity/transaction '+width);ok((await run('window.__alerts.join(" ")')).includes('只有執行長'),'permission guard retained '+width);
 await page.screenshot({path:path.join(out,'shareholder-'+width+'.png'),fullPage:true});
 await run(`nav('invoices');productModuleEnabled=()=>true;OPENAI_INVOICE_OCR_ENDPOINT='https://example.invalid/fictional-ocr';SUPABASE_ANON_KEY='fictional';window.__ocrRequests=[];window.fetch=async function(url,options){if(url!==OPENAI_INVOICE_OCR_ENDPOINT)throw Error('Unexpected external fetch');window.__ocrRequests.push(JSON.parse(options.body));return {ok:true,json:async()=>({invoice:window.__ocrResponse})};};`);
 await page.locator('#bfile').setInputFiles({name:'虛構憑據.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nFICTIONAL ONLY')});
 await run('window.__ocrResponse='+JSON.stringify(invoice(210,0,210,[item('虛構服務甲',100),item('虛構服務乙',110)]))+';true');await page.locator('#inv-batch-ai-button').click();await page.waitForFunction(()=>document.getElementById('batch-pl').textContent.includes('已填入 2 列'));
 eq(await run('S.bRows.map(r=>[r.desc,r.amt,r.tax,r.total,r.rate])'),[['虛構服務甲',100,0,100,0],['虛構服務乙',110,0,110,0]],'actual OCR caller preserves schema item names and zero tax '+width);
 eq(await page.locator('#btbody [data-b-field="desc"]').evaluateAll(nodes=>nodes.map(n=>n.value)),['虛構服務甲','虛構服務乙'],'actual batch DOM labels '+width);eq(await page.locator('#btbody [data-b-field="rate"]').evaluateAll(nodes=>nodes.map(n=>n.value)),['0','0'],'actual batch DOM zero rates '+width);
 const saved=await run('JSON.stringify(S.bRows)');await run('window.__ocrResponse='+JSON.stringify(invoice(0,0,210))+';true');await page.locator('#inv-batch-ai-button').click();await page.waitForFunction(()=>document.getElementById('batch-pl').textContent.includes('人工核對'));eq(await run('JSON.stringify(S.bRows)'),saved,'invalid OCR preserves previous rows '+width);await page.waitForFunction(()=>window.__formsFix.run('ACTION_FEEDBACK_ACTIVE===0'));eq(await page.locator('#action-feedback').evaluate(n=>n.classList.contains('show')),false,'invalid OCR never announces analysis complete '+width);
 await run('window.__ocrResponse='+JSON.stringify(invoice(300,15,315,[item('虛構服務甲',105),item('虛構服務乙',210)]))+';true');await page.locator('#inv-batch-ai-button').click();await page.waitForFunction(()=>document.getElementById('batch-pl').textContent.includes('已填入 2 列'));eq(await run('S.bRows.map(r=>[r.amt,r.tax,r.total])'),[[100,5,105],[200,10,210]],'actual 5% OCR caller and renderer stay consistent '+width);
 eq(await run('window.__ocrRequests.every(r=>r.mode==="invoice_batch"&&r.dataUrl.startsWith("data:application/pdf"))'),true,'real FileReader to exact OCR request contract '+width);
 // The unified UI exposes batch mode. Exercise the retained single adapter on
 // its real DOM without claiming the hidden legacy button is a user entry.
 await run('applyInvoiceOcr('+JSON.stringify(invoice(210,0,210))+');true');eq(await page.locator('#inv-amt').inputValue(),'210','retained single actual DOM net '+width);eq(await page.locator('#inv-tax').inputValue(),'0','retained single actual DOM zero tax '+width);
 ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no page overflow '+width);eq(errors,[],'zero unhandled page errors '+width);eq(await run('window.__writes'),[],'zero business mutation attempts '+width);await page.locator('#action-feedback.show').waitFor({state:'hidden'});await page.locator('#invoice-batch-sheet').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'invoice-ocr-'+width+'.png'),fullPage:true});evidence.runs.push({width,errors,shareholderCategories:Object.keys(categories),ocr:{zeroTax:true,fivePercent:true,itemNames:true,invalidPreservesInputs:true},businessWrites:0});await ctx.close();}
 eq(fs.readFileSync(path.join(root,'index.html'),'utf8'),source,'exact tested source unchanged');evidence.checks=checks;fs.writeFileSync(path.join(out,'browser-report.json'),JSON.stringify(evidence,null,2));console.log('Shareholder/OCR actual browser: '+checks+' checks PASS; '+out);
}finally{await browser.close();server.close();}})().catch(error=>{console.error(error);server.close();process.exitCode=1});
