// Executable identity-race checks of the shipped readback/retry/outbox functions.
// Fictional source records and deferred transports; no network or DB writes.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
function fn(name){const start=source.search(new RegExp('^(?:async )?function '+name+'\\(','m'));assert.ok(start>=0,name);const rest=source.slice(start),next=rest.slice(1).search(/^(?:(?:async )?function |window\.|var )/m);return rest.slice(0,next<0?undefined:next+1);}
function install(ctx,names){vm.createContext(ctx);for(const name of names)vm.runInContext(fn(name),ctx);return ctx;}
const base=['currentFinanceAuthUserId','expenseSubmissionOperationIdentity','expenseSubmissionOperationCurrent','expenseSubmissionIdentityChanged'];
const record=()=>({id:'r-a',no:'TEST-A',applicantId:'person-a',app:'匿名員工甲',eid:'E1',dc:'D1',type:'expense_reimbursement',amt:100,tenantId:'tenant-a',dataEnv:'production',files:[],formPayload:{submissionAttemptId:'attempt-a'}});
const user=()=>({id:'person-a',authUserId:'auth-a',email:'a@example.invalid',role:'employee',active:true});
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
const tick=()=>new Promise(resolve=>setImmediate(resolve));
let checks=0;const pass=n=>{checks++;console.log('PASS '+n);};
function fixture(names=[]){let tenant='tenant-a',env='production';const counts={reads:0,merged:0,writes:0,cleanup:0,clear:0,finalize:0};
 const pending={tenantId:tenant,dataEnv:env,applicantId:'person-a',requestId:'r-a',attemptId:'attempt-a',expected:record(),retryRecord:record()};
 const c=install({S:{user:user(),demoLogin:false,nrSubmissionConfirmationPending:pending},financeWorkspaceIdentityBlocked:false,currentTenantId:()=>tenant,activeDataEnvironment:()=>env,
  num:v=>Number(v)||0,mapReq:r=>r,REQS:[],expenseRevisionContainsFilePaths:()=>true,withAbortableOperationTimeout:p=>p,withOperationTimeout:p=>p,
  mergeCommittedExpenseRequest:r=>{counts.merged++;return r;},clearExpenseSubmissionPending:()=>{counts.clear++;c.S.nrSubmissionConfirmationPending=null;},loadExpenseSubmissionPending:()=>pending,
  finalizeRecoveredExpenseSubmission:async()=>{counts.finalize++;return {state:'committed'};},cleanupUploadedSupabaseAttachments:async()=>{counts.cleanup++;},recordOpsEvent(){},console,setTimeout:(f)=>setTimeout(f,0),clearTimeout,
 },[...base,...names]);
 return {c,counts,pending,env:value=>env=value,tenant:value=>tenant=value,switch:()=>{c.S.user={...user(),id:'person-b',authUserId:'auth-b',email:'b@example.invalid'};c.S.nrSubmissionConfirmationPending={requestId:'r-b',attemptId:'attempt-b'};}};
}
function readTransport(f){const d=deferred();f.c.getSb=()=>({from(){f.counts.reads++;return{select(){return this},eq(){return this},limit(){return d.promise}}}});return d;}
(async()=>{
 for(const change of ['auth','tenant','env','blocked']){
  const f=fixture(['expenseSubmissionRecordMatches','readExpenseSubmissionCommit']);const d=readTransport(f);const run=f.c.readExpenseSubmissionCommit(record());
  if(change==='auth')f.switch();if(change==='tenant')f.tenant('tenant-b');if(change==='env')f.env('test');if(change==='blocked')f.c.financeWorkspaceIdentityBlocked=true;
  d.resolve({data:[record()],error:null});const r=await run;assert.equal(r.identityChanged,true);assert.equal(f.counts.merged,0);assert.equal(r.record,undefined);pass('late committed read '+change+' change: no merge or returned old record');
 }
 {const f=fixture(['expenseSubmissionRecordMatches','readExpenseSubmissionCommit']);const d=readTransport(f),run=f.c.readExpenseSubmissionCommit(record());d.resolve({data:[record()],error:null});assert.equal((await run).state,'committed');assert.equal(f.counts.merged,1);pass('unchanged owner can read and merge exact committed attempt');}
 {const f=fixture(['expenseSubmissionRecordMatches','readExpenseSubmissionCommit']);readTransport(f);assert.equal((await f.c.readExpenseSubmissionCommit({...record(),applicantId:'person-b'})).identityChanged,true);assert.equal(f.counts.reads,0);pass('different applicant blocked before any read');}
 {const f=fixture(['readExpenseSubmissionCommitWithDelays']);let resolveTimer;f.c.setTimeout=resolve=>{resolveTimer=resolve};f.c.readExpenseSubmissionCommit=async()=>{f.counts.reads++;return{state:'absent'}};const run=f.c.readExpenseSubmissionCommitWithDelays(record(),[1]);f.switch();resolveTimer();assert.equal((await run).identityChanged,true);assert.equal(f.counts.reads,0);pass('identity switch while delay waits causes zero query');}
 {const f=fixture(['reconcilePendingExpenseSubmission']);const d=deferred();f.c.readExpenseSubmissionCommitWithDelays=()=>d.promise;const run=f.c.reconcilePendingExpenseSubmission({allowRetry:true});f.switch();const replacement=f.c.S.nrSubmissionConfirmationPending;d.resolve({state:'committed',record:record()});assert.equal((await run).identityChanged,true);assert.deepEqual(f.counts,{reads:0,merged:0,writes:0,cleanup:0,clear:0,finalize:0});assert.equal(f.c.S.nrSubmissionConfirmationPending,replacement);assert.equal(f.pending.requestId,'r-a');pass('reconciliation discards committed late response without finalize, cleanup or replacing another pending');}
 {const f=fixture(['reconcilePendingExpenseSubmission']);const d=deferred();f.c.readExpenseSubmissionCommitWithDelays=()=>d.promise;f.c.submitExpenseRequestWithAmbiguousRecovery=async()=>{f.counts.writes++;return{ok:false}};const run=f.c.reconcilePendingExpenseSubmission({allowRetry:true});f.switch();d.resolve({state:'absent'});assert.equal((await run).identityChanged,true);assert.equal(f.counts.writes,0);assert.equal(f.counts.cleanup,0);assert.equal(f.counts.clear,0);pass('absent late read never retries or deletes attachments under replacement identity');}
 {const f=fixture(['reconcilePendingExpenseSubmission']);f.c.readExpenseSubmissionCommitWithDelays=async()=>({state:'absent'});const d=deferred();f.c.submitExpenseRequestWithAmbiguousRecovery=()=>d.promise;const run=f.c.reconcilePendingExpenseSubmission({allowRetry:true});await tick();f.switch();const replacement=f.c.S.nrSubmissionConfirmationPending;d.resolve({ok:false,unknown:false,error:Error('denied')});assert.equal((await run).identityChanged,true);assert.equal(f.counts.cleanup,0);assert.equal(f.counts.clear,0);assert.equal(f.c.S.nrSubmissionConfirmationPending,replacement);pass('late deterministic retry failure preserves original staged files and both pending identities');}
 {const f=fixture(['submitExpenseRequestWithAmbiguousRecovery']);const d=deferred();f.c.callExpenseSubmissionOnce=()=>{f.counts.writes++;return d.promise};const run=f.c.submitExpenseRequestWithAmbiguousRecovery(record());f.switch();d.resolve({ok:true});assert.equal((await run).identityChanged,true);assert.equal(f.counts.writes,1);pass('late successful submission response is not confirmed under replacement identity');}
 {const f=fixture(['submitExpenseRequestWithAmbiguousRecovery']);f.c.callExpenseSubmissionOnce=async()=>{f.counts.writes++;return{ok:false,error:Error('timeout')}};f.c.expenseApplicantRevisionRpcErrorIsAmbiguous=()=>true;const d=deferred();f.c.readExpenseSubmissionCommitWithDelays=()=>d.promise;const run=f.c.submitExpenseRequestWithAmbiguousRecovery(record());await tick();f.switch();d.resolve({state:'absent'});assert.equal((await run).identityChanged,true);assert.equal(f.counts.writes,1);pass('ambiguous submission stops exact retry after identity changes during read');}
 {const f=fixture(['submitExpenseRequestWithAmbiguousRecovery']);const args=[];f.c.callExpenseSubmissionOnce=async r=>{args.push(r);return args.length===1?{ok:false,error:Error('timeout')}:{ok:true,data:{}}};f.c.expenseApplicantRevisionRpcErrorIsAmbiguous=()=>true;f.c.readExpenseSubmissionCommitWithDelays=async()=>({state:'absent'});const r=record();assert.equal((await f.c.submitExpenseRequestWithAmbiguousRecovery(r)).ok,true);assert.equal(args.length,2);assert.equal(args[0],args[1]);pass('same owner keeps exact request/attempt identity on legitimate retry');}
 {const f=fixture(['finalizeRecoveredExpenseSubmission']);f.c.ensureExpensePostCommitOutbox=()=>({ok:true});const d=deferred();f.c.runExpensePostCommitOutbox=()=>d.promise;f.c.buildAll=()=>{f.counts.finalize++};f.c.pruneCompletedExpensePostCommitOutbox=()=>{f.counts.clear++};const run=f.c.finalizeRecoveredExpenseSubmission(f.pending,record());f.switch();const replacement=f.c.S.nrSubmissionConfirmationPending;d.resolve({ok:true,failed:[]});assert.equal((await run).identityChanged,true);assert.equal(f.counts.finalize,0);assert.equal(f.counts.clear,0);assert.equal(f.c.S.nrSubmissionConfirmationPending,replacement);pass('late outbox completion cannot clear pending or build old success screen');}
 {const f=fixture(['expensePostCommitTaskState','runExpensePostCommitOutbox']);const entry={id:'out-a',tenantId:'tenant-a',dataEnv:'production',record:record(),tasks:{},notification:{id:'n-a'}};f.c.EXPENSE_POST_COMMIT_OUTBOX_RUN_PROMISE=null;f.c.loadExpensePostCommitOutbox=()=>[entry];let saved=0;f.c.saveExpensePostCommitOutboxEntry=()=>{saved++;return true};const d=deferred();f.c.persistAccountingLinesRemote=()=>{f.counts.writes++;return d.promise};f.c.dbUpsert=()=>{f.counts.writes++;return{ok:true}};f.c.persistExpenseExternalNotificationSchedule=()=>{f.counts.writes++;return{ok:true}};f.c.formatStorageUploadError=e=>e.message;const run=f.c.runExpensePostCommitOutbox();await tick();assert.equal(saved,1);f.switch();d.resolve({ok:true});assert.equal((await run).identityChanged,true);assert.equal(f.counts.writes,1);assert.equal(saved,1);assert.equal(entry.tasks.accounting.status,'running');pass('outbox stops after in-flight response: no new writes, no cross-user cache save, original retry retained');}
 console.log(`${checks} submission identity behavior checks passed`);
})().catch(error=>{console.error(error);process.exitCode=1});
