#!/usr/bin/env node
'use strict';
// Real captured v2 -> unchanged v3/canonical SQL. All actors and monetary rows
// are synthetic in PGlite; no network, real-user claims, or production writes.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {PGlite}=require('@electric-sql/pglite'),{createArMappingFixture}=require('./check_ar_mapping_performance.cjs');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
const migrationFile='supabase/migrations/20260914001246_finance_dashboard_scope_integrity_v1.sql',migration=read(migrationFile),oldFile='scripts/fixtures/finance_dashboard_v2_pre_scope_20260914.sql';
const sig='public.finance_executive_dashboard_v2(date,date,date,date,date,text,text)';
async function createDashboardScopeFixture(db,options={}){
 const f=await createArMappingFixture(db,{seed:false});await f.admin(db,'select 1');
 await db.exec(`alter table public.finance_users add column department_code text;
 alter table public.expense_requests add column actual_amount numeric,add column estimated_amount numeric,add column amount numeric,add column voucher_id text,add column request_date date,add column no text,add column status text,add column voided_at timestamptz,add column entity_id text,add column department_code text,add column applicant text,add column form_payload jsonb default '{}',add column steps jsonb default '[]',add column type text;
 alter table public.invoices add column applicant text;
 alter table public.ledger_entries add column created_at timestamptz default now();
 create function public.current_finance_user() returns public.finance_users language sql stable security definer as $$select * from public.finance_users where auth_user_id=auth.uid() and active$$;
 -- Synthetic verified Google transport, not a bypass of the real read predicates.
 create function public.finance_current_verified_google_email_v2() returns text language sql stable security definer as $$select lower(email) from public.finance_users where auth_user_id=auth.uid() and active and google_link_status in ('bound','pending_rebind') and coalesce(current_setting('audit.google_unverified',true),'false')<>'true'$$;
 drop function public.finance_executive_dashboard_v2(date,date,date,date,date,text,text);`);
 await db.exec(read('scripts/fixtures/finance_dashboard_step_authority_20260914.sql')+'\n'+read('scripts/fixtures/finance_dashboard_read_authority_20260914.sql')+'\n'+read(oldFile)+';');
 await db.exec(`alter function ${sig} owner to postgres;revoke all on function ${sig} from public,anon;grant execute on function ${sig} to authenticated,service_role;
 alter table public.expense_requests enable row level security;alter table public.expense_requests force row level security;
 create policy fixture_expense_read on public.expense_requests for select to authenticated using(public.can_read_expense_request(expense_requests));
 grant select on public.expense_requests to authenticated;`);
 for(const [name,uid]of[['external_audit','00000000-0000-0000-0000-000000000015'],['board','00000000-0000-0000-0000-000000000016']])await db.query('insert into public.finance_users(id,tenant_id,auth_user_id,name,email,role,active,google_link_status) values($1,$2,$3,$1,$4,$1,true,\'bound\')',[name,f.tenant,uid,name+'@example.invalid']);
 f.asActor=async name=>{await f.admin(db,'select 1');const uid=name?(await db.query('select auth_user_id from public.finance_users where id=$1',[name])).rows[0]?.auth_user_id:'';await db.query("select set_config('audit.uid',$1,false)",[uid||'']);await db.exec('set session authorization authenticated');};
 f.dashboard=async(opts={})=>{await f.asActor(opts.actor||'accountant');return(await db.query('select public.finance_executive_dashboard_v3($1,$2,$3,$4,$5,$6,$7) x',[opts.start||'2026-09-01',opts.end||'2026-09-30',opts.prevStart||'2026-08-01',opts.prevEnd||'2026-08-31',opts.trendStart||'2026-08-01',Object.hasOwn(opts,'entity')?opts.entity:'FICT-CO',opts.env||'test'])).rows[0].x;};
 if(options.install!==false)await db.exec('begin;'+migration+'\ncommit;');return f;
}
async function run(){let checks=0;const check=(name,value)=>{assert.ok(value,name);checks++;console.log('PASS '+name);};const db=new PGlite();try{
 const f=await createDashboardScopeFixture(db,{install:false});
 async function invoice(id,amount,opts={}){return f.make(db,id,amount,{invoice_date:'2026-09-02',approval_status:'delivered',...opts});}
 async function expense(id,amount,opts={}){await f.admin(db,'select 1');const r={id,no:id,tenant_id:f.tenant,data_environment:'test',entity_id:'FICT-CO',department_code:'FICT-D',request_date:'2026-09-02',status:'completed',amount,actual_amount:amount,estimated_amount:amount,voucher_id:id,applicant:'accountant',form_payload:{},steps:[],...opts};await db.query('insert into public.expense_requests select * from jsonb_populate_record(null::public.expense_requests,$1)',[JSON.stringify(r)]);await journal(id,amount,{tenant:r.tenant_id,env:r.data_environment,entity:r.entity_id,date:r.request_date,kind:'expense_request',expense:true});}
 async function journal(id,amount,opts={}){await f.admin(db,'select 1');const tenant=Object.hasOwn(opts,'tenant')?opts.tenant:f.tenant;for(const [ac,dr,cr]of(opts.expense?[['6202',amount,0],['1112',0,amount]]:[['1112',amount,0],['4111',0,amount]]))await db.query(`insert into public.ledger_entries(tenant_id,data_environment,entry_date,entity_id,department_code,account_code,debit,credit,source_type,source_id,source_no,reference_no,posting_key,voucher_no,voided_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11,$12,$10,$13)`,[tenant,opts.env||'test',opts.date||'2026-09-02',opts.entity||'FICT-CO',opts.department||'FICT-D',ac,dr,cr,opts.kind||'invoice',id,opts.no||id,id+':'+ac,opts.voided?'2026-09-03':null]);}
 await invoice('OWN',100);await invoice('FOREIGN',900,{tenant_id:f.other});await journal('NULL',700,{tenant:null});await expense('OWN-EX',30);await expense('FOREIGN-EX',300,{tenant_id:f.other});await journal('NULL-EX',200,{tenant:null,expense:true,kind:'expense_request'});
 let old=await f.dashboard();check('real deployed v2 dependency reproduces cross-tenant revenue and expense',old.summary.revenue===100&&old.reconciliation.revenue.officialAmount===1700&&old.reconciliation.expense.officialAmount===530);
 await f.admin(db,'select 1');const baseline=await f.fingerprint(db);await db.exec('begin;'+migration+'\nrollback;');check('rehearsal restores exact original v2 hash',(await db.query('select md5(prosrc) h from pg_proc where oid=$1::regprocedure',[sig])).rows[0].h==='8de3ece274d222fdf7d7a02949d6475b');
 await db.exec('begin;'+migration+'\ncommit;');let x=await f.dashboard();check('v3 summary and source reconciliation now use identical tenant facts',x.summary.revenue===100&&x.reconciliation.revenue.officialAmount===100&&x.summary.expense===30&&x.reconciliation.expense.officialAmount===30);check('all source counts exclude foreign and NULL tenants',x.rowCounts.ledger_rows===4&&x.rowCounts.invoice_rows===1&&x.rowCounts.expense_rows===1);check('no foreign identifiers survive any returned JSON field',!JSON.stringify(x).includes('FOREIGN')&&!JSON.stringify(x).includes('NULL-'));
 await f.admin(db,'select 1');check('migration and reads do not alter monetary data',await f.fingerprint(db)===baseline);
 await invoice('PRIOR',40,{invoice_date:'2026-08-02'});await invoice('FOREIGN-PRIOR',400,{invoice_date:'2026-08-02',tenant_id:f.other});await invoice('OTHER-COMPANY',60,{entity_id:'FICT-OTHER'});await invoice('PRODUCTION',80,{data_environment:'production'});await journal('VOID',500,{voided:true});await journal('FUTURE',600,{date:'2026-10-02'});
 x=await f.dashboard();check('previous summary and trend remain isolated',x.previousSummary.revenue===40&&x.trend.find(r=>r.month==='2026-08').revenue===40&&x.trend.find(r=>r.month==='2026-09').revenue===100);check('selected company and date/environment/void filters remain exact',x.summary.revenue===100&&x.companies.length===1&&x.companies[0].entityId==='FICT-CO');check('authorized all-company scope keeps both company totals',(await f.dashboard({entity:null})).summary.revenue===160);check('explicit production environment is independent',(await f.dashboard({env:'production'})).summary.revenue===80);check('authorized empty company returns true zero',(await f.dashboard({entity:'EMPTY'})).summary.ledgerRows===0);
 // Same reference in another company must not create a source bridge.
 await invoice('SAME-NO-OTHER',0,{entity_id:'FICT-OTHER',no:'COLLISION',revenue_posted:false});await journal('UNLINKED',50,{no:'COLLISION'});await journal('UNLINKED-NEGATIVE',-50,{no:'COLLISION'});x=await f.dashboard();check('cross-company same-number references remain unlinked',x.reconciliation.revenue.unlinkedSourceCount===2&&x.reconciliation.revenue.officialUnlinked===0&&x.reconciliation.revenue.unlinkedSourceAbsoluteAmount===100);
 async function deny(name,fn,code='42501'){let err;try{await fn();}catch(e){err=e;}check(name,err?.code===code);}
 await deny('employee cannot call full company dashboard',()=>f.dashboard({actor:'employee'}));await deny('unknown company cannot turn into trusted zero',()=>f.dashboard({entity:'NOT-IN-CATALOG'}));await deny('invalid environment is refused',()=>f.dashboard({env:'foreign'}),'22023');
 await f.asActor(null);await deny('absent identity is refused',()=>db.query(`select ${sig.replace(/\([^]*$/,'')}(current_date,current_date,current_date,current_date,current_date,null,'test')`));
 await f.admin(db,"set audit.google_unverified='true'");await deny('unverified Google identity is refused',()=>f.dashboard());await f.admin(db,"set audit.google_unverified='false';update public.finance_users set active=false where id='accountant'");await deny('inactive Finance identity is refused',()=>f.dashboard());await f.admin(db,"update public.finance_users set active=true where id='accountant';update public.system_settings set value=jsonb_set(value,'{accountant,reports}','\"none\"') where key='role_permissions'");await deny('saved reports deny is enforced',()=>f.dashboard());await f.admin(db,"update public.system_settings set value=jsonb_set(value,'{accountant,reports}','\"edit\"') where key='role_permissions'");
 await deny('external audit cannot read sources absent from its row scope',()=>f.dashboard({actor:'external_audit'}));await deny('board cannot read sources absent from its row scope',()=>f.dashboard({actor:'board'}));
 await f.admin(db,`update public.invoices set applicant_id='external_audit';update public.expense_requests set form_payload='{"applicantProfile":{"id":"external_audit"}}';`);check('external audit retains read access when every source is actually shared',(await f.dashboard({actor:'external_audit'})).summary.revenue===100);
 // The production optional-control-plane function stays real; only the isolated
 // Membership service and its synthetic denies/grants are supplied here.
 await f.admin(db,`create table public.membership_users(id uuid,tenant_id uuid,legacy_finance_user_id text,auth_user_id uuid,status text);
 insert into public.membership_users select auth_user_id,tenant_id,id,auth_user_id,'active' from public.finance_users;
 create function public.membership_current_user_id() returns uuid language sql stable as $$select auth.uid()$$;
 create function public.membership_has_explicit_deny(uuid,text,jsonb) returns boolean language sql stable as $$select coalesce(current_setting('audit.denied_entity',true),'')=$3->>'entity_id' or coalesce(current_setting('audit.denied_department',true),'')=$3->>'department_code'$$;
 create function public.membership_can(uuid,text,jsonb) returns boolean language sql stable as $$select coalesce(current_setting('audit.membership_allowed',true),'true')='true'$$;
 set audit.denied_entity='FICT-CO';`);
 await deny('explicit company deny blocks complete totals',()=>f.dashboard());await f.admin(db,"set audit.denied_entity='';set audit.denied_department='FICT-D'");await deny('explicit department deny blocks complete totals',()=>f.dashboard());await f.admin(db,"set audit.denied_department='';set audit.membership_allowed='false'");await deny('missing membership grant blocks complete totals',()=>f.dashboard());await f.admin(db,"set audit.membership_allowed='true'");check('allowed membership retains exact totals',(await f.dashboard()).summary.revenue===100);
 await f.admin(db,"set audit.uid=''");for(const file of ['scripts/finance_dashboard_scope_postflight.sql','scripts/finance_ar_mapping_postflight.sql','scripts/finance_ar_reconciliation_postflight.sql','scripts/finance_canonical_receivables_postflight.sql']){await db.exec(read(file).replace(/^\\set ON_ERROR_STOP on\r?\n/,''));check('read-only postflight remains compatible '+path.basename(file),true);}
 await db.exec('begin;grant execute on function '+sig+' to anon;');await deny('postflight detects accidental anonymous execute grant',()=>db.exec(read('scripts/finance_dashboard_scope_postflight.sql').replace(/^\\set ON_ERROR_STOP on\r?\n/,'')),'P0001');await db.exec('rollback;');
 check('v3 body is unchanged',(await db.query("select md5(prosrc) h from pg_proc where oid='public.finance_executive_dashboard_v3(date,date,date,date,date,text,text)'::regprocedure")).rows[0].h==='36e536eb3ccfc071a8541719022597f1');
 const beforeCanary=await f.fingerprint(db),proof=await db.exec(read('scripts/finance_dashboard_scope_canary.sql'));check('full read-only canary checks real aggregate without employee claims',proof.some(x=>x.rows?.some(r=>r.dashboard_scope_canary_result?.scope_preserved)));check('read-only proof leaves all monetary facts unchanged',await f.fingerprint(db)===beforeCanary);
 await f.admin(db,`drop function public.membership_can(uuid,text,jsonb);drop function public.membership_has_explicit_deny(uuid,text,jsonb);drop function public.membership_current_user_id();drop table public.membership_users;delete from public.ledger_entries;delete from public.invoices;delete from public.expense_requests;`);
 const observedRoles=JSON.parse(read('scripts/fixtures/finance_dashboard_role_permissions_20260914.json')).roles;
 await db.query("update public.system_settings set value=$1 where key='role_permissions'",[JSON.stringify(observedRoles)]);
 for(const role of [...Object.keys(observedRoles),'unknown_role']){await f.admin(db,'update public.finance_users set role=$1 where id=\'accountant\'',[role]);if(['ceo','admin_director','accountant','external_audit','board'].includes(role))check('observed saved permissions preserve authorized role '+role,(await f.dashboard()).summary.ledgerRows===0);else await deny('observed saved permissions keep nonfinancial role denied '+role,()=>f.dashboard());}
 await f.admin(db,"update public.finance_users set role='accountant' where id='accountant'");
 const companies=Array.from({length:11},(_,i)=>({id:'SCALE-'+(i+1)}));await db.query("update public.system_settings set value=$1 where key='entities'",[JSON.stringify(companies)]);
 await db.query("insert into public.invoices(id,no,tenant_id,data_environment,entity_id,department_code,invoice_date,total,amount,tax,status,approval_status,steps) select 'SCALE-I-'||n,'SCALE-I-'||n,$1,'test','SCALE-'||(1+n%11),'D-'||(1+n%12),'2026-09-02',0,0,0,'unpaid','draft','[]' from generate_series(1,1003)n",[f.tenant]);
 await db.query("insert into public.expense_requests(id,no,tenant_id,data_environment,entity_id,department_code,request_date,amount,status,steps,form_payload) select 'SCALE-R-'||n,'SCALE-R-'||n,$1,'test','SCALE-'||(1+n%11),'D-'||(1+n%40),'2026-09-02',0,'pending_accountant','[]','{}' from generate_series(1,565)n",[f.tenant]);
 await db.query("insert into public.ledger_entries(tenant_id,data_environment,entry_date,entity_id,department_code,account_code,debit,credit,source_type,source_id,posting_key) select $1,'test','2026-09-02','SCALE-'||(1+((n-1)/2)%11),'D-'||(1+((n-1)/2)%37),case when n%2=1 then '1112' else '4111' end,case when n%2=1 then 1 else 0 end,case when n%2=0 then 1 else 0 end,'accounting_adjustment','SCALE-J-'||((n-1)/2),'SCALE-J-'||n from generate_series(1,4034)n",[f.tenant]);
 for(const actor of ['accountant','ceo']){const value=await f.dashboard({actor,entity:null});check('11-company production-scale synthetic '+actor+' read succeeds with actual permission structure',value.summary.revenue===2017&&value.rowCounts.ledger_rows===4034&&value.rowCounts.invoice_rows===1003&&value.rowCounts.expense_rows===565);}
 console.log(JSON.stringify({ok:true,checks,productionWrites:0,fixture:'real v2/v3/canonical and read-authority functions; synthetic auth and Membership transport'}));
 }finally{await db.close();}}
module.exports={createDashboardScopeFixture,migrationFile};if(require.main===module)run().catch(e=>{console.error(e.message,e.code,e.where);process.exitCode=1;});
