'use strict';
// Local source UI with fictional records and RPC-boundary fixtures only.
// No real Google accounts, production reads or writes are used by this test.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {applyBuildEnvironment}=require('./finance_build_environment');
const args=process.argv.slice(2),arg=(k,f)=>args.includes(k)?args[args.indexOf(k)+1]:f;
const root=path.resolve(arg('--root',path.join(__dirname,'..'))),output=path.resolve(arg('--output','/tmp/finance-audit-workspace-browser-20260911'));
const baseline=args.includes('--before'),original=fs.readFileSync(path.join(root,'index.html'),'utf8');
const anchor='bootAuthGate();\n\n})();';assert.ok(original.includes(anchor));
let html=applyBuildEnvironment(original,{target:'local',supabaseUrl:'',supabaseAnonKey:''});
html=html.replace(anchor,'window.__reportTest={run:async function(code){return await eval(code);}};\n'+anchor).replace(/<script\b[^>]*src=["']https?:[^>]*><\/script>/gi,'');
html=html.replace('</head>','<script src="/fixture-xlsx.js"></script></head>');
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname==='/fixture-xlsx.js'){res.setHeader('content-type','application/javascript');return res.end(fs.readFileSync('/tmp/finance-report-xlsx-0.18.5.js'));}const file=path.resolve(root,'.'+url.pathname);if(file!==root&&!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}if(file===root||file===path.join(root,'index.html')){res.setHeader('content-type','text/html');return res.end(html);}if(!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}res.setHeader('content-type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(file));});
const ledger=[];function pair(id,date,dc,dr,cr,amount,description){ledger.push({id:id+'-dr',eid:'F1',dc,ac:dr,an:dr,dr:amount,cr:0,date,desc:description,ref:id,sourceId:id,sourceNo:id,voucherNo:id,dataEnv:'test'},{id:id+'-cr',eid:'F1',dc,ac:cr,an:cr,dr:0,cr:amount,date,desc:description,ref:id,sourceId:id,sourceNo:id,voucherNo:id,dataEnv:'test'});}
pair('opening','2026/08/01','ADMIN','1112','3111',1000,'期初');pair('aug-sale','2026/08/31','CARE','1123','4101',100,'八月服務');pair('sep-sale','2026/09/30','CARE','1123','4101',100,'九月服務');pair('sep-allowance','2026/09/30','CARE','4101','1123',20,'折讓');pair('sep-receipt','2026/09/30','CARE','1112','1123',40,'實際收款');pair('repair','2026/09/30','CARE','6204','1112',50,'設備維修費');pair('shared','2026/09/30','ADMIN','6202','1112',100.01,'共同費用');pair('bank-transfer','2026/09/30','ADMIN','111201','111202',100,'銀行互轉');
const profile={schemaVersion:1,accountingFramework:'eas',tax:{formType:'401',taxId:'12345675',legalName:'星河照護股份有限公司',taxRegistrationNo:'123456789',responsiblePerson:'林星河',address:'虛構測試地址',filingFrequency:'bimonthly',filingMode:'individual',periods:{}},accountMappings:{},costCenters:[{departmentCode:'ADMIN',kind:'shared',name:'行政中心'},{departmentCode:'CARE',kind:'profit',name:'照護服務'}],budgets:[],allocations:[{id:'fixture-allocation',name:'依人數分攤',sourceDepartmentCode:'ADMIN',accountCodes:['6202'],basis:'headcount',targets:[{departmentCode:'CARE',weight:0.5},{departmentCode:'HOME',weight:0.5}],status:'reviewed',effectiveFrom:'2026-09-01',effectiveTo:null,reviewedBy:'fixture-ceo',reviewedAt:'2026-09-01T00:00:00Z',reviewedRevision:1,reviewReason:'核對人數'}],eliminations:[],periodChecks:{},documents:{}};
const items=[{invoiceId:'inv-aug',invoiceNo:'FA00000001',entityId:'F1',departmentCode:'CARE',buyer:'林星河',invoiceDate:'2026-08-31',dueDate:null,originalAmount:100,recognizedAmount:100,allowanceAmount:0,arAllowanceAmount:0,receivedAmount:0,outstandingAmount:100,pendingReceiptAmount:0,balanceStatus:'unpaid',status:'unpaid',rowVersion:1,metadataVersion:0,agingBucket:'unknown',ownerName:'',refundPayable:0,refundedAmount:0},{invoiceId:'inv-sep',invoiceNo:'FA00000002',entityId:'F1',departmentCode:'CARE',buyer:'陳晴川',invoiceDate:'2026-09-01',dueDate:'2026-09-05',originalAmount:100,recognizedAmount:100,allowanceAmount:20,arAllowanceAmount:20,receivedAmount:40,outstandingAmount:40,pendingReceiptAmount:0,balanceStatus:'partial',status:'partial',rowVersion:2,metadataVersion:0,agingBucket:'d1',overdueDays:25,ownerName:'林星河',ownerId:'fixture-accountant',nextActionDate:'2026-10-01',refundPayable:0,refundedAmount:0}];
let browser;
(async()=>{fs.mkdirSync(output,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port+'/';const{chromium}=require('playwright');browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'chrome'});const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const blocked=[];await context.route('**/*',route=>{if(new URL(route.request().url()).origin===new URL(url).origin||/^(blob|data):/.test(route.request().url()))return route.continue();blocked.push(route.request().url());return route.abort();});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.dismiss());await page.goto(url);await page.waitForFunction(()=>window.__reportTest);const scope=code=>page.evaluate(code=>window.__reportTest.run(code),code);
await scope(`(async()=>{
 USERS=[{id:'fixture-ceo',n:'許晴川',email:'ceo@example.invalid',role:'ceo',rL:'執行長',eid:'F1',dc:'ADMIN',active:true},{id:'fixture-accountant',n:'林星河',email:'accountant@example.invalid',role:'accountant',rL:'會計',eid:'F1',dc:'ADMIN',active:true}];
 ENTS=[{id:'F1',n:'星河照護股份有限公司',full:'星河照護股份有限公司',s:'星河照護',active:true,color:'#286448'},{id:'F2',n:'晴川居護有限公司',full:'晴川居護有限公司',s:'晴川居護',active:true,color:'#5673a0'}];
 DEPTS=[{c:'ADMIN',n:'行政中心',eid:'F1',lv:2,active:true},{c:'CARE',n:'日間照顧',eid:'F1',lv:3,active:true},{c:'HOME',n:'居家服務',eid:'F1',lv:3,active:true}];
 ORG_CHART=[];REQS=[];INVS=[];BILLS=[];VOUCHERS=[];NOTIFS=[];quickLogin('ceo');
 LEDGER=${JSON.stringify(ledger)};INVS=${JSON.stringify(items)}.map(function(i){return mapInv({id:i.invoiceId,no:i.invoiceNo,entity_id:i.entityId,entity_name:'星河照護',department_code:i.departmentCode,buyer:i.buyer,amount:i.originalAmount,tax:0,total:i.originalAmount,invoice_date:i.invoiceDate,status:i.status,row_version:i.rowVersion,revenue_posted:true,approval_status:'completed',data_environment:'test',tenant_id:currentTenantId()});});
 todayIso=function(){return'2026-09-30';};todayMonth=function(){return'2026-09';};
 window.__rwWrites=[];window.__rwProfile=${JSON.stringify(profile)};window.__rwItems=${JSON.stringify(items)};window.__rwRevision=1;
 if(typeof statementDataCompleteness==='function')statementDataCompleteness=function(){return{complete:true,status:'complete',rowCount:LEDGER.length,tables:{ledger:{complete:true,status:'complete',rowCount:LEDGER.length,total:LEDGER.length},invoices:{complete:true,status:'complete',rowCount:INVS.length,total:INVS.length},expense_requests:{complete:true,status:'complete',rowCount:0,total:0}}};};
 hasSupabase=function(){return true;};ensureRemoteDashboardAggregate=function(){};
 getSb=function(){return{rpc:async function(name,args){
 if(name==='finance_reporting_tax_sources_v1'){var sources={};args.p_documents.forEach(function(d){var i=INVS.find(function(i){return i.id===d.sourceId;});if(d.sourceType!=='invoice'||!i)throw new Error('Unexpected tax source fixture');sources[d.key]={available:true,binding:{version:1,fingerprint:'a'.repeat(64)},snapshot:{sourceType:'invoice',sourceId:i.id,entityId:i.eid,revision:Number(i.rowVersion)||0,number:i.no||'',date:String(i.date||'').split('/').join('-').slice(0,10),netAmount:i.amt==null?null:Number(i.amt),taxAmount:i.tax==null?null:Number(i.tax),grossAmount:i.total==null?null:Number(i.total),description:i.desc||'',buyerTaxId:i.taxId||''}};});return{data:{entityId:args.p_entity_id,dataEnvironment:args.p_data_environment,sources:sources}};}
 if(name==='finance_reporting_profile_read_v1')return{data:{ok:true,profile:args.p_entity_id==='F1'?window.__rwProfile:{schemaVersion:1,tax:{},accountMappings:{},costCenters:[],budgets:[],allocations:[],eliminations:[],periodChecks:{},documents:{}},revision:window.__rwRevision,canEdit:true,canEditWorkpaper:true}};
 if(name==='finance_reporting_profile_save_v1'){window.__rwWrites.push({name,args});if(args.p_expected_revision!==window.__rwRevision)return{error:{message:'版本衝突'}};window.__rwProfile=args.p_profile;return{data:{ok:true,profile:args.p_profile,revision:++window.__rwRevision,canEdit:true,canEditWorkpaper:true}};}
 if(name==='finance_receivables_v1')return{data:{version:1,asOf:args.p_as_of,complete:true,totalCount:window.__rwItems.length,items:window.__rwItems,summary:{outstandingAmount:140,receivedAmount:40,allowanceAmount:20,overdueAmount:40,unrecognizedAmount:0,creditAmount:0,refundPayable:0},buckets:[],reconciliation:{bankVisible:true,bankScope:'company',unmatchedBankItems:[{id:'bank-fixture',date:'2026-09-30',description:'部分核銷款',amount:100,matchedAmount:40,remainingAmount:60}],unmatchedBankAmount:60}}};
 if(name==='finance_update_receivable_terms_v1'){window.__rwWrites.push({name,args});var item=window.__rwItems.find(function(x){return x.invoiceId===args.p_invoice_id;});Object.assign(item,args.p_patch,{metadataVersion:item.metadataVersion+1});return{data:{ok:true,invoiceId:item.invoiceId,metadataVersion:item.metadataVersion}};}
 return{data:null,error:{message:'Unexpected fixture RPC '+name}};
 }};};
 loadRemoteData=async function(){return true;};
 if(window.FinanceReportingWorkspace){await window.FinanceReportingWorkspace.loadProfile('F1',true);await window.FinanceReportingWorkspace.loadProfile('F2',true);}
 await nav('reports');refreshEntitySelectors();el('rpt-ent').value='F1';el('rpt-ent').dispatchEvent(new Event('change',{bubbles:true}));syncReportPeriodOptions('2026-09');el('rpt-month').value='2026-09';buildReports();
})()`);
if(!baseline)await page.waitForFunction(()=>window.FinanceReportingWorkspace.profileFor('F1'));
await page.evaluate(()=>{window.__capturedReports=[];const write=XLSX.writeFile;XLSX.writeFile=function(wb,name){window.__capturedReports.push({name,sheets:wb.SheetNames.map(name=>({name,rows:XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,defval:null})}))});return write.apply(this,arguments);};});
const checks=[];
async function capture(name,width){await page.setViewportSize({width,height:width<600?844:1000});await page.locator('#finance-report-workspace').scrollIntoViewIfNeeded();await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const size=await page.evaluate(()=>({w:innerWidth,scroll:document.documentElement.scrollWidth}));assert(size.scroll<=width,'no document overflow '+name+': '+JSON.stringify(size));await page.screenshot({path:path.join(output,(baseline?'before-':'after-')+name+'-'+width+'.png'),fullPage:false});checks.push({name,width,size});}
if(baseline){for(const width of [1440,390])await capture('reports',width);}
else{
await scope(`(function(){
 window.__awCase={schemaVersion:1,engagementType:'both',legalForm:'股份有限公司',auditorName:'虛構會計師事務所',engagementReference:'委任範圍草稿 v1',items:{}};
 window.FinanceAuditReadinessEngine.templates().forEach(function(t){window.__awCase.items[t.id]={ownerId:'fixture-accountant',dueDate:'2026-10-05',evidenceReference:'',notes:'',sourceLinks:[],applicability:'unknown',status:'pending'};});
 Object.assign(window.__awCase.items.A02,{applicability:'applicable',status:'provided',evidenceReference:'分類帳及總帳核對 v1',preparedBy:'fixture-accountant',preparedAt:'2026-09-30T00:00:00Z'});
 Object.assign(window.__awCase.items.A03,{applicability:'applicable',status:'reviewed',evidenceReference:'憑證索引 v1',preparedBy:'fixture-accountant',preparedAt:'2026-09-29T00:00:00Z',reviewedBy:'fixture-ceo',reviewedAt:'2026-09-29T01:00:00Z',reviewedFingerprint:'b'.repeat(64)});
 window.__awRevision=1;window.__awCanEdit=true;window.__awWrites=[];window.__awFailure=false;
 var previous=getSb;getSb=function(){var client=previous();return{rpc:async function(name,args){
   if(name==='finance_audit_case_history_v1')return{data:{ok:true,rows:[{revision:window.__awRevision,actorId:'fixture-ceo',createdAt:'2026-09-30T00:00:00Z',reason:'匿名測試：提供查帳資料'}]}};
   if(name==='finance_audit_case_save_v1'){
     if(window.__awFailure||args.p_expected_revision!==window.__awRevision)return{error:{code:'40001',message:'版本衝突：請重新核對'}};
     if(!window.__awCanEdit)return{error:{code:'42501',message:'沒有編輯權限'}};
     window.__awWrites.push({name,args:JSON.parse(JSON.stringify(args))});window.__awCase=JSON.parse(JSON.stringify(args.p_case_data));window.__awRevision++;
     Object.values(window.__awCase.items).forEach(function(i){if(i.status==='provided'&&!i.preparedBy){i.preparedBy='fixture-ceo';i.preparedAt='2026-09-30T01:00:00Z';}if(i.status==='reviewed'&&i.reviewedFingerprint==='a'.repeat(64)){i.reviewedBy='fixture-ceo';i.reviewedAt='2026-09-30T02:00:00Z';}});
   }
   if(name==='finance_audit_case_read_v1'||name==='finance_audit_case_save_v1')return{data:{ok:true,entityId:args.p_entity_id,period:args.p_period,revision:window.__awRevision,caseData:JSON.parse(JSON.stringify(window.__awCase)),sourceFingerprint:'a'.repeat(64),sourceCounts:{ledger:LEDGER.length,invoices:INVS.length,expense_requests:REQS.length},canEdit:window.__awCanEdit,actorId:'fixture-ceo'}};
   return client.rpc(name,args);
 }};};
})()`);
await page.getByRole('tab',{name:'會計師查帳',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#finance-audit-workspace')?.textContent.includes('資料清單'));
assert.equal(await page.locator('.aw-item').count(),12);assert((await page.locator('#finance-audit-workspace').innerText()).includes('來源已變更'));
for(const width of [1440,390])await capture('audit-checklist',width);
await page.setViewportSize({width:1440,height:1000});await page.locator('[data-aw-action=item][data-item=A01]').click();await page.locator('#finance-audit-dialog [name=evidenceReference]').fill('公司登記與委任範圍 v2');await page.locator('#finance-audit-dialog [name=applicability]').selectOption('applicable');await page.locator('#finance-audit-dialog [name=status]').selectOption('provided');await page.locator('#finance-audit-dialog [name=reason]').fill('已提供公司及委任範圍資料');await page.locator('#finance-audit-dialog button[type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#finance-audit-dialog').open);assert.equal(await scope('window.__awWrites.length'),1);assert.equal(await scope('window.__awWrites[0].args.p_expected_revision'),1);assert.equal(await scope('window.__awWrites[0].args.p_expected_source_fingerprint'),'a'.repeat(64));
await page.locator('[data-aw-action=item][data-item=A02]').click();await page.locator('#finance-audit-dialog [name=status]').selectOption('reviewed');await page.locator('#finance-audit-dialog [name=reason]').fill('由另一位授權同仁核對來源母體');await page.locator('#finance-audit-dialog button[type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#finance-audit-dialog').open);assert.equal(await scope('window.__awWrites[1].args.p_case_data.items.A02.reviewedFingerprint'),'a'.repeat(64));
await scope('window.__awFailure=true');await page.locator('[data-aw-action=item][data-item=A01]').click();await page.locator('#finance-audit-dialog [name=reason]').fill('模擬版本衝突');await page.locator('#finance-audit-dialog button[type=submit]').click();await page.waitForFunction(()=>document.querySelector('#finance-audit-dialog [role=status]').textContent.includes('版本衝突'));assert.equal(await page.locator('#finance-audit-dialog [name=evidenceReference]').inputValue(),'公司登記與委任範圍 v2');assert.equal(await scope('window.__awWrites.length'),2);await page.locator('#finance-audit-dialog [data-aw-action=close]').click();await scope('window.__awFailure=false');
await page.locator('[data-aw-action=section][data-section=controls]').click();assert.equal(await page.locator('.aw-control').count(),10);for(const width of [1440,390])await capture('audit-controls',width);await page.setViewportSize({width:1440,height:1000});
await page.locator('[data-aw-action=control-sources][data-control=C09]').click();assert((await page.locator('#finance-audit-dialog').innerText()).includes('FA00000001'));assert.equal(await page.locator('#finance-audit-dialog [data-aw-action=invoice]').count(),1);await page.locator('#finance-audit-dialog [data-aw-action=close]').click();
await page.locator('[data-aw-action=section][data-section=equity]').click();assert((await page.locator('#finance-audit-workspace').innerText()).includes('其他權益變動（待分類）'));for(const width of [1440,390])await capture('audit-equity',width);await page.setViewportSize({width:1440,height:1000});
await page.locator('[data-aw-action=section][data-section=sources]').click();assert.equal(await page.locator('#finance-audit-workspace tbody tr').count(),ledger.length);await page.locator('[name=aw-source-query]').fill('1000');await page.locator('[name=aw-source-query]').press('Tab');assert.equal(await page.locator('#finance-audit-workspace tbody tr').count(),2);
const xlsxDownload=page.waitForEvent('download');await page.locator('[data-aw-action=export-xlsx]').click();await (await xlsxDownload).saveAs(path.join(output,'audit-preparation.xlsx'));const book=await page.evaluate(()=>window.__capturedReports.at(-1));assert(book.sheets.some(s=>s.name==='科目試算表'));assert(book.sheets.some(s=>s.name==='權益調節底稿'));assert(book.sheets.some(s=>s.name==='資產負債表'));assert(book.sheets.find(s=>s.name==='分類帳來源索引').rows.length>ledger.length,'export retains complete source population with introductions');
const jsonDownload=page.waitForEvent('download');await page.locator('[data-aw-action=export-json]').click();const jsonPath=path.join(output,'audit-source-index.json');await (await jsonDownload).saveAs(jsonPath);const json=JSON.parse(fs.readFileSync(jsonPath,'utf8'));assert.equal(json.payload.ledger.length,ledger.length,'screen search never shrinks audit export');assert.equal(json.payload.sourceCounts.ledger,ledger.length);assert.equal(require('node:crypto').createHash('sha256').update(JSON.stringify(json.payload)).digest('hex'),json.payloadSha256);
await scope('window.__awOriginalAmount=LEDGER[0].dr;LEDGER[0].dr=null');const invalidDownload=page.waitForEvent('download');await page.locator('[data-aw-action=export-xlsx]').click();await (await invalidDownload).saveAs(path.join(output,'invalid-source-workpaper.xlsx'));const invalidBook=await page.evaluate(()=>window.__capturedReports.at(-1));assert(invalidBook.sheets.some(s=>s.name==='財報待核對'));assert(!invalidBook.sheets.some(s=>s.name==='資產負債表'),'invalid raw amounts cannot become numeric financial exports');await scope('LEDGER[0].dr=window.__awOriginalAmount');
await page.locator('[data-aw-action=history]').click();assert((await page.locator('#finance-audit-dialog').innerText()).includes('匿名測試'));await page.locator('#finance-audit-dialog [data-aw-action=close]').click();
await scope(`window.__awCanEdit=false;window.FinanceAuditWorkspace.invalidate();window.FinanceAuditWorkspace.state.section='items';buildReports();`);await page.waitForFunction(()=>document.querySelector('#finance-audit-workspace')?.textContent.includes('查帳資料清單'));await page.locator('[data-aw-action=item][data-item=A01]').click();assert.equal(await page.locator('#finance-audit-dialog button[type=submit]').count(),0);assert(await page.locator('#finance-audit-dialog [name=evidenceReference]').isDisabled());await page.locator('#finance-audit-dialog [data-aw-action=close]').click();
// Navigation to all legal entities must show a scope requirement and no totals.
await scope(`el('rpt-ent').value='all';buildReports();`);assert((await page.locator('#finance-audit-workspace').innerText()).includes('選擇一間'));assert.equal(await page.locator('.aw-kpis').count(),0);
checks.push({xlsxSheets:book.sheets.map(s=>s.name),jsonRows:json.payload.ledger.length,hashVerified:true,successfulFixtureWrites:2,readOnlyForm:true,staleSourceVisible:true,versionConflictPreservesForm:true});
}
assert.deepEqual(errors,[],'no browser runtime errors');fs.writeFileSync(path.join(output,(baseline?'before':'after')+'-result.json'),JSON.stringify({ok:true,root,baseline,fixture:'Fictional users/entities/documents and RPC transport; no production data or real user logins',checks,errors,blocked},null,2));console.log(JSON.stringify({ok:true,output,baseline,checks,errors}));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();await new Promise(r=>server.close(r));});
