'use strict';
// Real index closure + shipped readers/renderers. Only localhost configuration,
// fictional Supabase transport and the clock are replaced; no product test hook.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{execFile}=require('node:child_process'),{promisify}=require('node:util');
const run=promisify(execFile),root=path.resolve(__dirname,'..'),out=path.resolve(process.argv[2]||'/tmp/finance-dashboard-readiness-browser-20260913'),session='dashboard-readiness-'+process.pid,bin=process.env.AGENT_BROWSER_BIN||'agent-browser';
assert(out!==root&&!out.startsWith(root+path.sep));const sourcePath=process.env.FINANCE_DASHBOARD_SOURCE||path.join(root,'index.html'),source=fs.readFileSync(sourcePath,'utf8'),engineSource=fs.readFileSync(path.join(root,'assets/engines/reporting-workspace.js'),'utf8'),{applyBuildEnvironment}=require('./finance_build_environment');
const anchor='bootAuthGate();\n\n})();';assert(source.includes(anchor));let html=applyBuildEnvironment(source,{target:'local',supabaseUrl:'',supabaseAnonKey:''}).replace(anchor,'window.__dashboardQA={run:async function(code){return await eval(code)}};\n'+anchor).replace(/<script\b[^>]*src=["']https?:[^>]*><\/script>/gi,'').replace('<head>','<head><meta http-equiv="Content-Security-Policy" content="connect-src \'self\'; form-action \'none\'; img-src \'self\' data: blob:">');
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(p!==root&&!p.startsWith(root+path.sep)){res.writeHead(403);return res.end();}if(p===root||p===path.join(root,'index.html')){res.setHeader('content-type','text/html; charset=utf-8');return res.end(html);}if(!fs.existsSync(p)||!fs.statSync(p).isFile()){res.writeHead(404);return res.end();}res.setHeader('content-type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(p));});
const b=async(...args)=>(await run(bin,['--session',session,...args],{maxBuffer:12e6,timeout:45000})).stdout;
async function scope(code){let v=JSON.parse(await b('eval','--base64',Buffer.from('(async()=>JSON.stringify(await window.__dashboardQA.run('+JSON.stringify(code)+')))()').toString('base64')));return typeof v==='string'?JSON.parse(v):v;}
async function until(code){return scope('(async function(){for(var i=0;i<150;i++){if('+code+')return true;await new Promise(r=>setTimeout(r,20));}return false;})()');}
const evidence={scope:'Local actual dashboard/statement/core/profile/AR loaders and DOM. Fictional read transport, no real employee login or production access. Deadlines accelerated only by the fixture clock.',sourceHash:crypto.createHash('sha256').update(source).digest('hex'),engineHash:crypto.createHash('sha256').update(engineSource).digest('hex'),checks:[],screens:[]};
function check(label,ok){assert(ok,label);evidence.checks.push(label);console.log('PASS '+label);}
const setup=`(function(mode){
USERS=[{id:'qa-accountant',n:'許晴川',email:'accountant@example.invalid',authUserId:'10000000-0000-0000-0000-000000000001',role:'accountant',rL:'會計',eid:'F1',dc:'D1',active:true}];ENTS=[{id:'F1',s:'星河照護',full:'星河照護股份有限公司',active:true}];DEPTS=[{c:'D1',n:'行政課',eid:'F1',entityCodes:['F1'],newFormEntityCodes:['F1'],lv:3,active:true,isPostingUnit:true}];REQS=[];INVS=[];BILLS=[];NOTIFS=[];VOUCHERS=[];LEDGER=[];DRAFTS=[];ORG_CHART=[];quickLogin('accountant');S.user.authUserId=USERS[0].authUserId;S.demoLogin=false;S.dashEntity='F1';S.dashMonth='2026-09';S.dashMonthFrom='2026-09';S.dashMonthTo='2026-09';S.dashPeriodMode='month';
window.__mode=mode;window.__reads=[];window.__blockedWrites=[];window.__late=[];window.__aborts=[];window.__broadDone=false;window.__broadError="";window.__started=performance.now();
var nativeTimer=window.setTimeout;window.setTimeout=function(fn,ms){return nativeTimer(fn,ms===12000?150:ms===15000?(mode==='ar-controlled'?10000:180):ms===20000?900:ms)};window.fetch=function(){throw Error('External network is disabled in the offline fixture')};window.alert=function(){};
var tenant=currentTenantId(),environment=activeDataEnvironment();var data={finance_users:[{id:'qa-accountant',name:'許晴川',email:'accountant@example.invalid',auth_user_id:S.user.authUserId,tenant_id:tenant,role:'accountant',department_code:'D1',entity_id:'F1',active:true}],system_settings:[],expense_requests:[],invoices:[],bills:[],ledger_entries:[{id:'fixture-ledger-1',tenant_id:tenant,data_environment:environment,entity_id:'F1',department_code:'D1',source_id:'fixture-expense',source_type:'expense',entry_date:'2026-09-13',account_code:'6207',account_name:'文具用品',debit:1050,credit:0},{id:'fixture-ledger-2',tenant_id:tenant,data_environment:environment,entity_id:'F1',department_code:'D1',source_id:'fixture-expense',source_type:'expense',entry_date:'2026-09-13',account_code:'1112',account_name:'銀行存款',debit:0,credit:1050}],notifications:[],vouchers:[]};
if(mode==='ar-controlled'){
 ENTS=Array.from({length:10},function(_,i){return{id:'F'+(i+1),s:'虛構法人'+(i+1),full:'虛構照護法人'+(i+1),active:true}});
 DEPTS=ENTS.map(function(e,i){return{c:'D'+(i+1),n:'虛構部門'+(i+1),eid:e.id,entityCodes:[e.id],newFormEntityCodes:[e.id],lv:3,active:true,isPostingUnit:true}});S.dashEntity='all';
 data.ledger_entries=Array.from({length:4034},function(_,i){var company=1+Math.floor(i/2)%10;return{id:'fictional-ledger-'+String(i).padStart(5,'0'),tenant_id:tenant,data_environment:environment,entity_id:'F'+company,department_code:'D'+company,source_id:'fictional-source-'+Math.floor(i/2),source_type:'expense',entry_date:'2026-09-13',account_code:i%2?'1112':'6207',account_name:i%2?'銀行存款':'文具用品',debit:i%2?0:1,credit:i%2?1:0}});
}
function aggregate(args,amount){amount=amount||120;return{version:3,environment:args.p_data_environment,entityId:args.p_entity_id||'all',period:{start:args.p_start,end:args.p_end,previousStart:args.p_previous_start,previousEnd:args.p_previous_end,trendStart:args.p_trend_start},generatedAt:'2026-09-13T02:00:00Z',summary:{balanceDiff:0,missingSourceCount:0},receivables:{complete:true,total:amount+50,count:2,overdueTotal:amount,over90Total:0,unknownDue:1,items:[{invoiceId:'fixture-invoice',invoiceNo:'FIXTURE-INV-001',entityId:args.p_entity_id||'F1',balance:amount,overdueDays:12,buyer:'虛構買方',due:'2026-09-01'},{invoiceId:'fixture-unknown-due',invoiceNo:'FIXTURE-INV-002',entityId:args.p_entity_id||'F1',balance:50,overdueDays:null,buyer:'虛構缺付款日買方',due:null,agingBucket:'unknown'}],buckets:['unknown','not_due','d1','d31','d61','d90'].map(key=>({key:key,label:key,count:key==='d1'||key==='unknown'?1:0,total:key==='d1'?amount:key==='unknown'?50:0}))},previousReceivables:{total:20,count:1},reconciliation:{revenue:{},expense:{}},rowCounts:{ledger_rows:2,expense_rows:0,invoice_rows:1}};}
function transport(name,args,payload){var entry={name:name,args:args,started:performance.now()-window.__started};window.__reads.push(entry);var mode=window.__mode,signal;return{abortSignal:function(s){signal=s;s.addEventListener('abort',function(){window.__aborts.push(name)});return this;},then:function(resolve,reject){var result;if(mode==='optional-hang'&&name==='vouchers'||mode==='profile-hang'&&name==='finance_reporting_profile_read_v1')result=new Promise(function(){});else if(mode==='ar-controlled'&&name==='finance_executive_dashboard_v3'||mode==='late'&&(name==='finance_executive_dashboard_v3'||name==='finance_reporting_profile_read_v1'))result=new Promise(function(r){window.__late.push({name:name,args:args,payload:payload,resolve:r})});else result=new Promise(function(r){nativeTimer(function(){r(mode==='ar-error'&&name==='finance_executive_dashboard_v3'?{error:{code:'57014',message:'虛構測試：應收核對逾時'}}:payload)},10)});return result.then(function(value){entry.ended=performance.now()-window.__started;return value;}).then(resolve,reject);}};}
getSb=function(){return{from:function(table){var from=0,to=999;var q={select:function(){return this},eq:function(){return this},in:function(){return this},order:function(){return this},limit:function(n){to=n-1;return this},range:function(a,b){from=a;to=b;return this},abortSignal:function(signal){q.signal=signal;return this},then:function(resolve,reject){var rows=data[table]||[],operation=transport(table,{}, {data:rows.slice(from,to+1),count:rows.length,error:null});if(q.signal)operation.abortSignal(q.signal);return operation.then(resolve,reject)}};['insert','upsert','update','delete'].forEach(function(method){q[method]=function(){window.__blockedWrites.push({table:table,method:method});return Promise.resolve({error:{code:'42501',message:'Offline fixture refuses writes'}})}});return q;},rpc:function(name,args){args=args||{};var payload;if(name==='finance_reporting_profile_read_v1')payload={data:{ok:true,entityId:args.p_entity_id,dataEnvironment:args.p_data_environment,revision:1,profile:{schemaVersion:1,tax:{},accountMappings:{},costCenters:[],budgets:[],allocations:[],eliminations:[],periodChecks:{},documents:{}},canEdit:false,canEditWorkpaper:false}};else if(name==='finance_executive_dashboard_v3')payload=window.__aggregateError?{error:window.__aggregateError}:{data:aggregate(args)};else if(name==='finance_statement_source_page_v1'){var rows=(data[args.p_source]||[]).filter(r=>r.tenant_id===tenant&&r.data_environment===args.p_data_environment).slice().sort((a,b)=>String(a.id).localeCompare(String(b.id))),offset=args.p_offset,limit=args.p_limit;payload={data:{ok:true,source:args.p_source,tenantId:tenant,dataEnvironment:args.p_data_environment,rows:rows.slice(offset,offset+limit),total:rows.length,limit:limit,offset:offset,hasMore:offset+limit<rows.length},error:null};}else payload={error:{code:'42501',message:'Offline fixture only authorizes dashboard read APIs: '+name}};return transport(name,args,payload);},auth:{getSession:async function(){return{data:{session:null},error:null}}}}};hasSupabase=function(){return true};
return true;})`;
async function open(mode){await b('open','http://127.0.0.1:'+server.address().port);await b('set','viewport','1440','1000');await scope(setup+'('+JSON.stringify(mode)+')');}
async function screenshot(label,width){await b('set','viewport',String(width),width===390?'844':'1000');check(label+' '+width+' has no document overflow',!(await scope('document.documentElement.scrollWidth>innerWidth+1')));await b('screenshot',path.join(out,label+'-'+width+'.png'));evidence.screens.push(label+'-'+width+'.png');}
(async()=>{fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));
await open('ar-controlled');await scope('(function(){window.__core=loadDashboardFinancialSources(true);return true})()');
check('ten company profiles and all 4034 ledger rows finish while canonical AR remains in flight',await until('dashboardFinancialReadState(dashboardScope()).ready&&statementDataCompleteness().tables.ledger.rowCount===4034&&dashboardFinancialReadState(dashboardScope()).records.length===10&&window.__late.length>0'));
check('source-page progress and core completion keep exactly one current/previous-period aggregate query',await scope('window.__reads.filter(x=>x.name==="finance_executive_dashboard_v3").length===1&&window.__late.length===1&&window.__aborts.indexOf("finance_executive_dashboard_v3")<0&&window.__late[0].args.p_entity_id===null&&window.__late[0].args.p_end==="2026-09-30"&&window.__late[0].args.p_previous_end==="2026-08-31"'));
await scope('(function(){var request=DASH_REMOTE_PENDING[dashboardRemoteKey(dashboardScope())];window.__retryOriginalRequest=request;window.__retryOriginalTimer=request.timer;return true})()');
await b('click','#dash-load-status button');
check('retry button joins an existing AR request without aborting or resetting its deadline',await scope('!!DASH_RETRY_PROMISE&&DASH_REMOTE_PENDING[dashboardRemoteKey(dashboardScope())]===window.__retryOriginalRequest&&DASH_REMOTE_PENDING[dashboardRemoteKey(dashboardScope())].timer===window.__retryOriginalTimer&&window.__reads.filter(x=>x.name==="finance_executive_dashboard_v3").length===1&&window.__aborts.indexOf("finance_executive_dashboard_v3")<0&&el("dash-load-status").querySelector("button").disabled&&el("dash-load-status").querySelector("button").innerText.includes("正在重試")'));
await scope('(async function(){for(var i=0;i<5;i++){invalidateDashboardFinancialModel();buildDash();await Promise.resolve();}return true})()');
check('multiple local source publications preserve the same pending AR request',await scope('window.__reads.filter(x=>x.name==="finance_executive_dashboard_v3").length===1&&Object.keys(DASH_REMOTE_PENDING).length===1'));
check('joined retry remains processing through local redraws until the original response arrives',await scope('!!DASH_RETRY_PROMISE&&el("dash-load-status").querySelector("button").disabled&&el("dash-load-status").querySelector("button").innerText.includes("正在重試")&&DASH_REMOTE_PENDING[dashboardRemoteKey(dashboardScope())].timer===window.__retryOriginalTimer'));
evidence.multiCompanyPending=await scope('({rows:statementDataCompleteness().tables.ledger.rowCount,profiles:dashboardFinancialReadState(dashboardScope()).records,reads:window.__reads,aborts:window.__aborts})');
await scope('(function(){window.__late.splice(0).forEach(function(x){x.resolve(x.payload)});return true})()');
check('original pending AR response becomes usable without a second query and settles the joined retry',await until('!DASH_RETRY_PROMISE&&dashboardFinancialBundle(dashboardScope()).officialSource==="remote_full"&&window.__reads.filter(x=>x.name==="finance_executive_dashboard_v3").length===1'));
await scope('invalidateDashboardFinancialModel();buildDash();true');check('confirmed AR survives a later local model update',await scope('dashboardFinancialBundle(dashboardScope()).receivables.total===170&&window.__reads.filter(x=>x.name==="finance_executive_dashboard_v3").length===1'));
await screenshot('multi-company-ready',1440);await screenshot('multi-company-ready',390);
await scope('(function(){window.__mode="ok";invalidateDashboardFinancialCache();buildDash();return true})()');check('full business-data invalidation still obtains a fresh aggregate',await until('dashboardFinancialBundle(dashboardScope()).officialSource==="remote_full"&&window.__reads.filter(x=>x.name==="finance_executive_dashboard_v3").length===2'));
await open('optional-hang');await scope('(function(){window.__broad=performRemoteDataLoad().then(function(r){window.__broadDone=true;return r},function(error){window.__broadDone=true;window.__broadError=error.message;return null});return true})()');check('cold financial core becomes ready while optional vouchers still hang',await until("DASHBOARD_FINANCIAL_SOURCE_RUNTIME.status==='ready'&&dashboardFinancialReadState(dashboardScope()).ready&&!window.__broadDone&&window.__reads.some(x=>x.name==='vouchers'&&!x.ended)"));
evidence.cold=await scope('({readyMs:performance.now()-window.__started,coreStatus:DASHBOARD_FINANCIAL_SOURCE_RUNTIME.status,complete:statementDataCompleteness().tables.ledger,profile:FinanceReportingWorkspace.profileRecord("F1"),broadDone:window.__broadDone,reads:window.__reads})');check('actual financial renderer shows verified net -1050 before optional work',await scope('dashboardFinancialBundle(dashboardScope()).summary.net===-1050&&el("dash-kpis").innerText.includes("1,050")'));check('missing due date stays unknown in validated actual AR data',await until('DASH_REMOTE_AGGREGATES[dashboardRemoteKey(dashboardScope())]&&DASH_REMOTE_AGGREGATES[dashboardRemoteKey(dashboardScope())].receivables.unknownDue===1&&dashboardFinancialBundle(dashboardScope()).receivables.items.some(x=>x.overdueDays===null)'));await screenshot('cold-ready',1440);await screenshot('cold-ready',390);check('optional timeout settles broad without revoking ready financial data',await until('window.__broadDone&&dashboardFinancialReadState(dashboardScope()).ready'));
check('completed source uses the exact-count RPC; a timed-out mandatory voucher does not fabricate later source reads',await scope('window.__reads.some(r=>r.name==="finance_statement_source_page_v1"&&r.args.p_source==="expense_requests"&&r.ended)&&!window.__reads.some(r=>["expense_requests","bills","invoices"].includes(r.name))&&!!window.__broadError'));
check('successful independent AR remains verified after early source publication and optional timeout',await scope('!!DASH_REMOTE_AGGREGATES[dashboardRemoteKey(dashboardScope())]&&dashboardFinancialBundle(dashboardScope()).officialSource==="remote_full"&&dashboardFinancialBundle(dashboardScope()).receivables.unknownDue===1'));
check('cold bootstrap has no unhandled browser errors',(await b('errors')).trim()==='');
await open('profile-hang');await scope('(function(){window.__core=loadDashboardFinancialSources(true);return true})()');check('profile timeout ends as an explicit failed state, not indefinite loading',await until('FinanceReportingWorkspace.profileRecord("F1")&&FinanceReportingWorkspace.profileRecord("F1").status==="error"&&el("dash-load-status").innerText.includes("讀取失敗")'));await screenshot('profile-failed',1440);await screenshot('profile-failed',390);const size=await scope('(function(){var r=document.querySelector("#dash-load-status button").getBoundingClientRect();return{w:r.width,h:r.height}})()');check('mobile dashboard retry is a visible 44px target',size.w>=44&&size.h>=44);await scope('window.__mode="ok"');await b('click','#dash-load-status button');check('actual retry button restores profile and financial readiness',await until('!DASH_RETRY_PROMISE&&dashboardFinancialReadState(dashboardScope()).ready'));await screenshot('profile-recovered',390);
check('profile timeout/recovery has no unhandled browser errors',(await b('errors')).trim()==='');
await open('ar-error');await scope('(function(){window.__core=loadDashboardFinancialSources(true);return true})()');check('AR error leaves independently verified financial amounts visible',await until('dashboardFinancialReadState(dashboardScope()).ready&&Object.keys(DASH_REMOTE_ERRORS).length>0'));const ar=await scope('({kpis:el("dash-kpis").innerText,ar:el("dash-ar-summary").innerText,verdict:el("dash-verdict-points").innerText,ready:dashboardFinancialBundle(dashboardScope()).financialReady,source:dashboardFinancialBundle(dashboardScope()).officialSource})');check('failed AR is shown as failed/unknown instead of a successful zero',ar.ready&&ar.source!=='remote_full'&&ar.kpis.includes('讀取失敗')&&ar.ar.includes('讀取失敗'));check('AR failure never claims there are no overdue receivables',!ar.verdict.includes('目前沒有逾期應收'));await screenshot('ar-failed',1440);await screenshot('ar-failed',390);
const failedArReads=await scope('window.__reads.filter(x=>x.name==="finance_executive_dashboard_v3").length');
await scope('(async function(){for(var i=0;i<4;i++){invalidateDashboardFinancialModel();buildDash();await Promise.resolve();}return true})()');
check('local source refresh preserves the AR error and does not automatically retry',await scope('window.__reads.filter(x=>x.name==="finance_executive_dashboard_v3").length==='+failedArReads+'&&!!DASH_REMOTE_ERRORS[dashboardRemoteKey(dashboardScope())]&&el("dash-ar-summary").innerText.includes("讀取失敗")'));
await scope('window.__mode="ok";true');await b('click','#dash-load-status button');
check('real failed-AR retry button restores independently verified AR',await until('!DASH_RETRY_PROMISE&&dashboardFinancialBundle(dashboardScope()).officialSource==="remote_full"&&!DASH_REMOTE_ERRORS[dashboardRemoteKey(dashboardScope())]'));
check('failed-AR retry performs exactly one new query',await scope('window.__reads.filter(x=>x.name==="finance_executive_dashboard_v3").length==='+String(failedArReads+1)));
await scope('(async function(){window.__mode="ar-error";await ensureRemoteDashboardAggregate(dashboardScope(),{force:true});return true})()');
check('failed refresh retains old verified AR while exposing a visible retryable error',await scope('dashboardFinancialBundle(dashboardScope()).receivables.total===170&&!!DASH_REMOTE_ERRORS[dashboardRemoteKey(dashboardScope())]&&!el("dash-load-status").hidden&&el("dash-load-status").innerText.includes("失敗")&&!!el("dash-load-status").querySelector("button")'));
await screenshot('verified-ar-refresh-failed',390);
const refreshReads=await scope('window.__reads.filter(x=>x.name==="finance_executive_dashboard_v3").length');
await scope('window.__mode="ok";true');await b('click','#dash-load-status button');
check('retry with an existing AR cache still clears the failed-refresh state',await until('!DASH_RETRY_PROMISE&&!DASH_REMOTE_ERRORS[dashboardRemoteKey(dashboardScope())]&&window.__reads.filter(x=>x.name==="finance_executive_dashboard_v3").length==='+String(refreshReads+1)));
for(const failure of [
 {code:'57014',message:'query canceled PRIVATE_FIXTURE_DETAIL',expected:'查詢逾時'},
 {code:'PGRST301',message:'invalid token PRIVATE_FIXTURE_DETAIL',expected:'本人登入資料'},
 {code:'42501',message:'not authorized PRIVATE_FIXTURE_DETAIL',expected:'本人帳號權限'},
 {code:'DASHBOARD_INVALID_RESPONSE',message:'bad shape PRIVATE_FIXTURE_DETAIL',expected:'回應不完整或範圍不符'},
 {code:'FETCH_FAILED',message:'network disconnected PRIVATE_FIXTURE_DETAIL',expected:'確認網路後重試'},
 {code:'UNEXPECTED_FIXTURE',message:'PRIVATE_FIXTURE_DETAIL',expected:'暫時無法完成'}
]){
 await scope('(async function(){window.__aggregateError='+JSON.stringify({code:failure.code,message:failure.message})+';await ensureRemoteDashboardAggregate(dashboardScope(),{force:true});return true})()');
 check('real '+failure.code+' failure has actionable bounded copy without exposing raw diagnostic text',await scope('el("dash-data-freshness").innerText.includes('+JSON.stringify(failure.expected)+')&&!el("dash-load-status").hidden&&el("dash-load-status").innerText.includes("保留上次核對結果")&&!el("dash-load-status").innerText.includes("PRIVATE_FIXTURE_DETAIL")&&!el("dash-data-freshness").innerText.includes("PRIVATE_FIXTURE_DETAIL")'));
}
await scope('window.__aggregateError=null;true');await b('click','#dash-load-status button');check('classified failure retries normally without clearing verified source data',await until('!DASH_RETRY_PROMISE&&!DASH_REMOTE_ERRORS[dashboardRemoteKey(dashboardScope())]&&dashboardFinancialReadState(dashboardScope()).ready'));
await scope('(function(){window.__mode="late";window.__oldProfile=FinanceReportingWorkspace.retryProfiles(["F1"]);window.__oldAggregate=ensureRemoteDashboardAggregate(dashboardScope(),{force:true});return true})()');check('old identity requests are in flight for the race fixture',await until('window.__late.length===2'));await scope('(async function(){S.user=Object.assign({},S.user,{id:"qa-other",authUserId:"10000000-0000-0000-0000-000000000009"});financeWorkspaceIdentityBlocked=true;FinanceReportingWorkspace.profileRecord("F1");clearDashboardRemoteReads();window.__late.forEach(function(x){x.resolve(x.payload)});await Promise.all([window.__oldProfile,window.__oldAggregate]);return true})()');check('late prior identity cannot repopulate profile or aggregate caches',await scope('FinanceReportingWorkspace.profileRecord("F1")===null&&Object.keys(DASH_REMOTE_AGGREGATES).length===0'));
const errors=(await b('errors')).trim();assert.equal(errors,'');evidence.errors=errors;evidence.ok=true;assert.equal(fs.readFileSync(sourcePath,'utf8'),source,'index changed during evidence run; repeat exact source');assert.equal(fs.readFileSync(path.join(root,'assets/engines/reporting-workspace.js'),'utf8'),engineSource,'engine changed during evidence run');fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify(evidence,null,2));if(fs.existsSync(path.join(out,'failure.json')))fs.unlinkSync(path.join(out,'failure.json'));console.log('PASS dashboard readiness browser: '+out);
})().catch(async e=>{console.error(e);fs.mkdirSync(out,{recursive:true});let debug;try{debug=await scope('({mode:window.__mode,reads:window.__reads,core:typeof DASHBOARD_FINANCIAL_SOURCE_RUNTIME!=="undefined"?DASHBOARD_FINANCIAL_SOURCE_RUNTIME:null,profile:FinanceReportingWorkspace.profileRecord("F1"),ledger:statementDataCompleteness(),remoteKeys:Object.keys(DASH_REMOTE_AGGREGATES),remoteKey:dashboardRemoteKey(dashboardScope()),remoteErrors:DASH_REMOTE_ERRORS,remotePending:Object.keys(DASH_REMOTE_PENDING),broadDone:window.__broadDone,broadError:window.__broadError,text:document.body.innerText})');}catch(_){}fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:e.message,evidence,debug},null,2));process.exitCode=1;}).finally(async()=>{await b('close').catch(()=>{});server.close();});
