'use strict';
// Anonymous, local-only fixtures around actual shipped form handlers. No production
// login or network writes. Use --serve for agent-browser exploratory verification.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const args=process.argv.slice(2),arg=(k,f)=>args.includes(k)?args[args.indexOf(k)+1]:f;
const root=path.resolve(arg('--root',path.join(__dirname,'..'))),label=arg('--label','after'),output=path.resolve(arg('--output','/tmp/finance-employee-form-evidence-20260912'));
const setup=`(async function(){
 window.__employeeWrites=[];window.__employeeDialogs=[];
 window.alert=function(m){window.__employeeDialogs.push(String(m));};
 window.fetch=function(){throw Error('Offline employee fixture forbids network');};
 getSb=function(){window.__employeeWrites.push('database');throw Error('Offline employee fixture forbids database');};
 USERS=[{id:'fixture-employee',n:'林星河',email:'employee@example.invalid',role:'employee',rL:'一般組員',eid:'F1',dc:'DAYCARE',active:true},{id:'fixture-ceo',n:'許晴川',email:'ceo@example.invalid',role:'ceo',rL:'執行長',eid:'F1',dc:'DAYCARE',active:true},{id:'fixture-cashier',n:'葉青禾',email:'cashier@example.invalid',role:'cashier',rL:'出納',eid:'F1',dc:'DAYCARE',active:true}];
 ENTS=[{id:'F1',n:'星河照護股份有限公司',s:'星河照護'}];
 DEPTS=[{c:'DAYCARE',n:'日間照顧課',eid:'F1',entityCodes:['F1'],newFormEntityCodes:['F1'],lv:4,active:true,isPostingUnit:true}];
 MEMBERSHIP_ORG_RUNTIME={available:false,graph:null};ORG_CHART=[];REQS=[];INVS=[];BILLS=[];VOUCHERS=[];NOTIFS=[];
 quickLogin('employee');await nav('newreq');window.__employeeReady=true;
})()`;
const {applyBuildEnvironment}=require(path.join(root,'scripts/finance_build_environment'));
let html=applyBuildEnvironment(fs.readFileSync(path.join(root,'index.html'),'utf8'),{target:'local',supabaseUrl:'',supabaseAnonKey:''});
assert.ok(html.includes('bootAuthGate();\n\n})();'));
html=html.replace('bootAuthGate();\n\n})();','window.__employeeFormTest={run:async function(code){return await eval(code);}};\nbootAuthGate();\nwindow.addEventListener("load",function(){'+setup+'});\n\n})();').replace(/<script\b[^>]*src=["']https?:[^>]*><\/script>/gi,'');
const server=http.createServer((req,res)=>{
 const pathname=new URL(req.url,'http://localhost').pathname;const file=path.resolve(root,'.'+pathname);
 if(file!==root&&!file.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}
 res.setHeader('Content-Security-Policy',"connect-src 'none'; img-src 'self' data: blob:; font-src 'self' data:; frame-src blob:");
 if(file===root||file===path.join(root,'index.html')){res.setHeader('content-type','text/html');res.end(html);return;}
 if(!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end();return;}
 res.setHeader('content-type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(file));
});
async function metrics(page){return page.evaluate(()=>{const root=document.querySelector('#pg-newreq');return{viewport:innerWidth,documentWidth:document.documentElement.scrollWidth,contentHeight:document.querySelector('.content').scrollHeight,visibleFields:[...root.querySelectorAll('input,select,textarea')].filter(n=>n.checkVisibility()).length,sections:root.querySelectorAll('.efux-section').length,openSections:root.querySelectorAll('.efux-section[open]').length,smallControls:[...root.querySelectorAll('button,[role=button],summary')].filter(n=>n.checkVisibility()).filter(n=>{const r=n.getBoundingClientRect();return r.height<43.9||r.width<43.9}).map(n=>({text:n.textContent.trim().slice(0,35),width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height}))};});}
function pdf(){const objs=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 400 300] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];let stream='BT /F1 20 Tf 30 240 Td (LOCAL RECEIPT 123) Tj ET';objs.push('<< /Length '+stream.length+' >>\nstream\n'+stream+'\nendstream');let s='%PDF-1.4\n',off=[0];objs.forEach((o,i)=>{off.push(s.length);s+=(i+1)+' 0 obj\n'+o+'\nendobj\n'});let x=s.length;s+='xref\n0 '+off.length+'\n0000000000 65535 f \n';off.slice(1).forEach(o=>s+=String(o).padStart(10,'0')+' 00000 n \n');s+='trailer\n<< /Size '+off.length+' /Root 1 0 R >>\nstartxref\n'+x+'\n%%EOF';return Buffer.from(s);}
let browser;
(async()=>{
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url='http://127.0.0.1:'+server.address().port+'/';
 if(args.includes('--serve')){console.log(JSON.stringify({url,root}));return;}
 fs.mkdirSync(output,{recursive:true});const {chromium}=require('playwright');browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'chrome'});
 const context=await browser.newContext({viewport:{width:1440,height:900}});await context.route('**/*',r=>{const u=new URL(r.request().url());return u.origin===new URL(url).origin||['blob:','data:'].includes(u.protocol)?r.continue():r.abort();});
 const page=await context.newPage();page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.dismiss());await page.goto(url);await page.waitForFunction(()=>window.__employeeReady);
 const run=code=>page.evaluate(code=>window.__employeeFormTest.run(code),code);let checks=0;const eq=(a,b,label)=>{assert.deepEqual(a,b,label);checks++;};const ok=(v,label)=>{assert.ok(v,label);checks++;};
 const report={label,forms:[],checks:0};
 for(const type of ['expense_reimbursement','petty_cash_request','travel_request','purchase_request']){
  for(const width of [1440,390]){
   await page.setViewportSize({width,height:900});await run(`markNRClean();buildNR();nrT(${JSON.stringify(type)});document.querySelector('.content').scrollTop=0;`);await page.waitForTimeout(100);
   const m=await metrics(page);report.forms.push({type,...m});await page.screenshot({path:path.join(output,label+'-'+type+'-'+width+'.png')});
   if(label==='after'){ok(m.documentWidth<=width,'no page overflow '+type+' '+width);eq(m.smallControls,[],'44px controls '+type+' '+width);eq(await run('S.nrStep'),3,'form visible means fill/send stage');if(width===390){ok(m.sections>=3,'mobile has sections');ok(m.openSections<m.sections,'mobile starts with condensed sections');}}
  }
 }
 if(label==='before'){fs.writeFileSync(path.join(output,label+'-report.json'),JSON.stringify(report,null,2));return;}
 await page.setViewportSize({width:1440,height:900});await run(`markNRClean();buildNR();nrT('petty_cash_request');el('nr-desc-purpose').value='交通用品採買';el('nr-desc').value='原備註保持不變';el('nr-amt').value='3000';el('nr-payee').value='匿名收款測試';el('nr-bank-name').value='017 兆豐銀行';el('nr-bank-branch').value='測試分行';el('nr-bank-no').value='000012340000';el('nr-paydate').value='2026-09-30';S.lazyRows=[{item:'文具',qty:1,netAmount:123,taxAmount:0,grossAmount:123,total:123}];S.nrFiles=[new File(['fixture'],'保留附件.pdf',{type:'application/pdf'})];renderNRFList();`);
 const before=await run('collectNRFormState()');await page.locator('#petty-mode').selectOption('initial');const initial=await run('collectNRFormState()');
 const withoutMode=x=>Object.fromEntries(Object.entries(x).filter(([k])=>k!=='petty-mode'));
 eq(withoutMode(initial.fields),withoutMode(before.fields),'petty change keeps unrelated fields');eq(initial.pettyMode,'initial','mode updated');eq(initial.lazyRows,[],'initial has no expense accounting rows');eq(await run('S.nrFiles.length'),1,'file retained');
 await page.locator('#petty-mode').selectOption('general');const restored=await run('collectNRFormState()');eq(withoutMode(restored.fields),withoutMode(before.fields),'switch back fields intact');eq(restored.lazyRows,before.lazyRows,'expense rows restored only for reimbursement');eq(await run('S.nrRec'),'receipt','receipt routing restored');await run("S.nrRec='invoice';");await page.locator('#petty-mode').selectOption('initial');eq(await run('S.nrRec'),'form','initial funding uses form receipt type');await page.locator('#petty-mode').selectOption('general');eq(await run('S.nrRec'),'invoice','selected invoice receipt type restored');report.petty={fieldsPreserved:true,rowsRestored:true,receiptTypeRestored:true};
 // Choose and drop batches; actual onchange and drop handlers keep valid files.
 await run(`markNRClean();buildNR();nrT('expense_reimbursement');`);
 await page.locator('#nr-file').setInputFiles([{name:'2026出差住宿憑證-第一張正本-完整檔名.pdf',mimeType:'application/pdf',buffer:pdf()},{name:'2026出差住宿憑證-第二張作廢-完整檔名.pdf',mimeType:'application/pdf',buffer:pdf()}]);
 eq(await page.locator('.efux-file-row').count(),2,'two local files shown');ok(await page.locator('.efux-file-info strong').first().evaluate(e=>getComputedStyle(e).whiteSpace!=='nowrap'&&e.scrollWidth<=e.clientWidth),'full file name wraps');ok((await page.locator('.efux-file-info').first().innerText()).includes('591 B'),'file size shown');
 const chooser=page.waitForEvent('filechooser');await page.locator('#nr-dz').press('Enter');await chooser;checks++;
 await run(`(function(){var dt=new DataTransfer();dt.items.add(new File(['valid'],'合法.csv',{type:'text/csv'}));dt.items.add(new File([new Uint8Array(50*1024*1024+1)],'超過上限.pdf',{type:'application/pdf'}));el('nr-dz').dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:dt}));})()`);
 eq(await run('S.nrFiles.length'),3,'drop keeps valid files and rejects huge file');ok((await page.locator('#nr-file-issues').innerText()).includes('超過上限.pdf'),'rejection shown inline');eq(await run('S.nrFiles.some(f=>f.name===\'超過上限.pdf\')'),false,'no invalid file in form payload');
 // Real raster preview and close; object URLs are tracked and revoked.
 await run(`window.__efuxUrls=[];window.__efuxRevoked=[];var createURL=URL.createObjectURL.bind(URL),revokeURL=URL.revokeObjectURL.bind(URL);URL.createObjectURL=function(b){var u=createURL(b);window.__efuxUrls.push(u);return u;};URL.revokeObjectURL=function(u){window.__efuxRevoked.push(u);return revokeURL(u);};`);
 await page.locator('#nr-file').setInputFiles({name:'匿名收據.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jXioAAAAASUVORK5CYII=','base64')});
 await page.getByRole('button',{name:'預覽 匿名收據.png',exact:true}).click();await page.locator('.efux-preview img').waitFor();ok(await page.locator('.efux-preview img').evaluate(e=>e.complete&&e.naturalWidth>0),'local image rendered');await page.keyboard.press('Escape');eq(await page.locator('.efux-preview').count(),0,'Escape closes preview');eq(await run('window.__efuxUrls.length'),await run('window.__efuxRevoked.length'),'preview object URL revoked');
 await page.getByRole('button',{name:'開啟／下載 2026出差住宿憑證-第一張正本-完整檔名.pdf',exact:true}).click();const pdfLink=page.getByRole('link',{name:'另開 PDF 原檔',exact:true});eq(await pdfLink.getAttribute('rel'),'noopener noreferrer','PDF native viewer cannot access opener');ok((await page.locator('.efux-preview').innerText()).includes('PDF 不在此頁嵌入預覽'),'PDF capabilities stated accurately');const downloadPromise=page.waitForEvent('download');await page.getByRole('link',{name:'下載本機原檔',exact:true}).click();const download=await downloadPromise;eq(download.suggestedFilename(),'2026出差住宿憑證-第一張正本-完整檔名.pdf','download preserves complete filename');eq(fs.readFileSync(await download.path()),pdf(),'download preserves exact PDF bytes');await page.screenshot({path:path.join(output,'after-pdf-original-file.png')});const popupPromise=page.waitForEvent('popup');await pdfLink.click();const pdfPage=await popupPromise;await pdfPage.waitForLoadState();eq(await pdfPage.evaluate(()=>window.opener),null,'native PDF popup opener actually absent');await pdfPage.close();await page.getByRole('button',{name:'關閉檢查',exact:true}).click();eq(await run('window.__efuxUrls.length'),await run('window.__efuxRevoked.length'),'PDF URL revoked on close');
 await page.getByRole('button',{name:'移除 2026出差住宿憑證-第二張作廢-完整檔名.pdf',exact:true}).click();eq(await run('S.nrFiles.some(f=>f.name.includes(\'第二張\'))'),false,'named removal removes correct file');
 await page.setViewportSize({width:390,height:900});await page.locator('#nr-flist').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'after-attachments-390.png')});
 // Real submit stops before any route, number allocation, upload or persistence.
 await run(`markNRClean();buildNR();nrT('expense_reimbursement');verifyProductionReleaseContractForSubmission=async()=>({ok:true});guardSubmissionIdentityDirectory=async()=>true;window.__employeeDialogs=[];window.__routeCalls=[];prepareApprovalRouteForSubmit=async function(user,type,dc,opts,steps){window.__routeCalls.push({user:user.id,type:type,dc:dc,opts:opts});return {ok:false};};`);
 await run(`submitNR()`);const issueText=await page.locator('#nr-validation-summary').innerText();for(const t of ['申請原因','總金額','收款人','分行','帳號'])ok(issueText.includes(t),'all missing fields listed '+t);eq(await run('window.__employeeDialogs'),[],'no serial alerts');eq(await run('S.nrSubmitting'),false,'invalid submission releases existing lock');eq(await run('window.__routeCalls.length'),0,'invalid fields never reach route');
 await page.locator('#nr-validation-summary button').filter({hasText:'收款人'}).click();eq(await page.evaluate(()=>document.activeElement.id),'nr-payee','error link opens section and focuses exact field');ok(await page.locator('#nr-payee').isVisible(),'field becomes visible');await page.locator('#nr-payee').fill('匿名收款測試');
 await page.locator('#nr-validation-summary button').filter({hasText:'申請原因'}).click();eq(await page.evaluate(()=>document.activeElement.id),'nr-desc-purpose','purpose focus');await page.locator('#nr-desc-purpose').fill('部門文具採買用途');await page.locator('#nr-amt').fill('123');await page.locator('#nr-bank-branch').fill('測試分行');await page.locator('#nr-bank-no').fill('000012340000');
 await run(`submitNR()`);eq(await page.locator('#nr-validation-summary').count(),0,'fixed errors cleared');eq(await run('window.__routeCalls.length'),1,'valid form reaches unchanged route boundary once');eq(await run('window.__routeCalls[0].opts.amount'),123,'same amount to route');eq(await run('window.__routeCalls[0].dc'),'DAYCARE','same department to route');
 // Long travel form sections retain actual fields, companion choices and amounts.
 await run(`markNRClean();buildNR();nrT('travel_request');`);await page.locator('.efux-section summary').filter({hasText:'差旅申請資料'}).click();
 await page.locator('#tr-reason').fill('到外地參加訓練');await page.locator('#tr-outcome').fill('完成實作課程');await page.locator('#tr-from').fill('臺北');await page.locator('#tr-to').fill('臺中');const travelState=await run('collectNRFormState().fields');
 await page.locator('.efux-section summary').filter({hasText:'差旅申請資料'}).click();await page.locator('.efux-section summary').filter({hasText:'差旅申請資料'}).click();eq(await run('collectNRFormState().fields'),travelState,'collapse preserves travel inputs');await page.setViewportSize({width:1440,height:900});await page.setViewportSize({width:390,height:900});eq(await run('collectNRFormState().fields'),travelState,'viewport changes preserve travel inputs');
 await run(`submitNR()`);ok((await page.locator('#nr-validation-summary').innerText()).includes('出發時間'),'travel required fields precise');await page.locator('#nr-validation-summary button').filter({hasText:'出發時間'}).click();eq(await page.evaluate(()=>document.activeElement.id),'tr-start','travel link focuses date field');await page.screenshot({path:path.join(output,'after-validation-travel-390.png')});
 eq(await run('window.__employeeWrites'),[],'no database reads or writes');eq(errors,[],'no page JS errors');report.checks=checks;report.errors=errors;report.writes=[];fs.writeFileSync(path.join(output,label+'-report.json'),JSON.stringify(report,null,2));console.log('Employee form browser: '+checks+' checks PASS; '+output);
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(!args.includes('--serve'))server.close();});
