'use strict';
// Actual local index/engines. Only local response exposes closure access;
// fictional transport verifies UI failure handling, SQL tested separately.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict'),{execFile}=require('child_process'),{promisify}=require('util');
const {applyBuildEnvironment}=require('./finance_build_environment');
const run=promisify(execFile),root=path.resolve(__dirname,'..'),out=process.env.EMPLOYEE_CONCERN_EVIDENCE||'/tmp/finance-employee-concerns-20260912',session='employee-concerns-'+process.pid;
let html=applyBuildEnvironment(fs.readFileSync(path.join(root,'index.html'),'utf8'),{target:'local',supabaseUrl:'',supabaseAnonKey:''});
const anchor='bootAuthGate();\n\n})();';assert(html.includes(anchor));html=html.replace(anchor,'window.__employeeRoot={run:async function(code){return await eval(code)}};\n'+anchor).replace(/<script\b[^>]*src=["']https?:[^>]*><\/script>/gi,'').replace('<head>','<head><meta http-equiv="Content-Security-Policy" content="connect-src \'self\'; form-action \'none\'">');
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(p!==root&&!p.startsWith(root+'/')){res.writeHead(403);return res.end();}if(p===root||p===path.join(root,'index.html')){res.setHeader('content-type','text/html');return res.end(html);}if(!fs.existsSync(p)||!fs.statSync(p).isFile()){res.writeHead(404);return res.end();}res.setHeader('content-type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(p));});
const b=async(...a)=>(await run('agent-browser',['--session',session,...a],{maxBuffer:8e6,timeout:45000})).stdout;
async function scope(code){let v=JSON.parse(await b('eval','--base64',Buffer.from('(async()=>JSON.stringify(await window.__employeeRoot.run('+JSON.stringify(code)+')))()').toString('base64')));return typeof v==='string'?JSON.parse(v):v;}
(async()=>{fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));await b('open','http://127.0.0.1:'+server.address().port);
 await scope(`(function(){USERS=[{id:'employee',n:'匿名員工',email:'login@example.invalid',contactEmail:'work@example.invalid',role:'employee',rL:'組員',eid:'E1',dc:'D1',active:true},{id:'manager',n:'現任主管',role:'dept_manager',eid:'E1',dc:'D1',active:true}];ENTS=[{id:'E1',s:'匿名公司',full:'匿名公司',active:true}];DEPTS=[{c:'D1',n:'行政部門',eid:'E1',lv:3,active:true}];REQS=[];INVS=[];BILLS=[];NOTIFS=[];VOUCHERS=[];ORG_CHART=[];quickLogin('employee');S.aT='mine';window.__req=mapReq({id:'test-progress',no:'UX-001',applicant_id:'employee',applicant:'匿名員工',entity_id:'E1',department_code:'D1',type:'payment_request',amount:1250,description:'測試差旅費',data_environment:activeDataEnvironment(),tenant_id:currentTenantId(),status:'pending_dept_manager',step:1,ver:1,steps:[{rk:'applicant_submit',uid:'employee',a:'approved'},{rk:'dept_manager',uid:'manager',r:'部門主管',a:'',status:'pending_dept_manager'}]});REQS=[window.__req];nav('approvals',null);S.aT='mine';renderApprList([{kind:'req',raw:window.__req}]);return true;})()`);
 const evidence=[];
 for(const width of [1440,390]){await b('set','viewport',String(width),'1000');await b('wait','100');const state=await scope(`({text:el('appr-list').innerText,overflow:document.documentElement.scrollWidth>innerWidth+1})`);assert.match(state.text,/待處理：現任主管/);assert.equal(state.overflow,false);await b('screenshot',path.join(out,'progress-'+width+'.png'));evidence.push({width,progress:state});}
 await scope(`(function(){window.__sourceSnapshot=JSON.stringify(REQS);window.__concernIdentity='employee';window.__concernMode='lost';window.__concernCalls=[];window.__concernRow=null;window.__oldRuntime=window.FinanceApprovalRuntime;window.FinanceApprovalRuntime={S:{user:{id:'employee',authUserId:'test-auth'},demoLogin:false},currentTenantId:function(){return'test-tenant'},activeDataEnvironment:function(){return'test'},permissionIdentity:function(){return window.__concernIdentity},hasSupabase:function(){return true},isIdentityBlocked:function(){return false},ensureSupabaseWriteReady:async function(){return{ok:true}},getSb:function(){return{rpc:async function(name,args){if(name==='finance_payment_concern_read_v1'){if(window.__concernMode==='delayed-read')return await new Promise(function(resolve){window.__resolveConcernRead=resolve});if(window.__concernMode==='read-error')return{error:{message:'測試：讀取失敗'}};return{data:{ok:true,rows:window.__concernRow?[window.__concernRow]:[],canReport:!window.__concernRow,limit:100}};}window.__concernCalls.push(JSON.parse(JSON.stringify(args)));window.__concernRow={requestId:'test-progress',requestNo:'UX-001',version:1,status:'open',reason:args.p_message,response:'',canReport:false,canRespond:false,canResolve:false,history:[{action:'report',actorName:'匿名員工',message:args.p_message,at:'2026-09-12T00:00:00Z'}]};if(window.__concernMode==='lost')return{error:{message:'測試：回應中斷，請確認原結果'}};return{data:{ok:true,version:1,status:'open'}};}}}};return true;})()`);
 await scope(`(async function(){await FinancePaymentConcerns.open('test-progress');return true;})()`);
 await b('fill','#payment-concern-message','尚未收到 1,250 元，請協助查核。');
 await scope(`(function(){window.__concernMode='delayed-read';return true;})()`);await b('click','[data-reload]');await b('fill','#payment-concern-message','讀取期間繼續填寫的說明');await scope(`(function(){window.__resolveConcernRead({data:{ok:true,rows:[],canReport:true,limit:100}});return true;})()`);await b('wait','50');assert.equal(await scope(`document.querySelector('#payment-concern-message').value`),'讀取期間繼續填寫的說明','Late read preserves the latest typed draft');await b('fill','#payment-concern-message','尚未收到 1,250 元，請協助查核。');
 await scope(`(function(){window.__concernMode='read-error';return true;})()`);await b('click','[data-reload]');await b('wait','50');assert.equal(await scope(`document.querySelector('#payment-concern-message').value`),'尚未收到 1,250 元，請協助查核。','Read failure preserves employee draft');
 await scope(`(function(){window.__concernMode='lost';return true;})()`);await b('click','[data-action="report"]');await b('wait','50');assert.equal(await scope(`document.querySelector('#payment-concern-message').disabled`),true);
 await scope(`(function(){window.__concernMode='success';return true;})()`);await b('click','[data-action="report"]');await b('wait','100');
 const calls=await scope(`window.__concernCalls`);assert.equal(calls.length,2);assert.deepEqual(calls[0],calls[1],'Lost response retries exact original payload and operation UUID');
 assert.match(await scope(`document.querySelector('.payment-concern-dialog').innerText`),/待出納／會計查核/);
 for(const width of [1440,390]){await b('set','viewport',String(width),'1000');assert.equal(await scope(`document.documentElement.scrollWidth>innerWidth+1`),false);assert.equal(await scope(`Array.from(document.querySelectorAll('.payment-concern-dialog button')).every(function(b){return b.getBoundingClientRect().height>=44})`),true);await b('screenshot',path.join(out,'concern-'+width+'.png'));}
 await b('click','[data-close]');assert.match(await scope(`el('payment-concern-queue').innerText`),/UX-001/);
 await scope(`(function(){window.__concernRow.canRespond=true;window.__concernRow.canResolve=false;return true;})()`);await scope(`(async function(){await FinancePaymentConcerns.open('test-progress');return true;})()`);assert.equal(await scope(`!!document.querySelector('[data-action="respond"]')`),true);
 await b('fill','#payment-concern-message','查核回覆草稿');await scope(`(function(){window.__concernIdentity='different';return true;})()`);await b('click','[data-action="respond"]');assert.equal((await scope(`window.__concernCalls`)).length,2,'Identity change cannot send old draft');
 assert.equal(await scope(`JSON.stringify(REQS)===window.__sourceSnapshot`),true,'UI concern actions never mutate source request');
 await b('click','[data-close]');await scope(`(function(){window.FinanceApprovalRuntime=window.__oldRuntime;nav('orgchart',null);renderOrgPersonnelRows(orgSupervisorOverviewStats(USERS).rows);return true;})()`);
 for(const width of [1440,390]){await b('set','viewport',String(width),'1000');await scope(`(function(){window.mobileOrgTab('chart');document.querySelector('[data-org-person-id="employee"]').scrollIntoView({block:'center',inline:'center'});return true;})()`);const contact=await scope(`({text:document.querySelector('[data-org-person-id="employee"]').innerText,visible:document.querySelector('[data-org-person-id="employee"] .org-person-contact').checkVisibility(),overflow:document.documentElement.scrollWidth>innerWidth+1})`);assert.equal(contact.visible,true);assert.match(contact.text,/聯絡信箱：work@example.invalid/);assert.doesNotMatch(contact.text,/登入信箱：|login@example.invalid/);assert.equal(contact.overflow,false);await b('screenshot',path.join(out,'contacts-'+width+'.png'));}
 await scope(`(function(){var host=document.createElement('div');host.id='fixture-preview-host';host.style.cssText='position:fixed;top:10px;left:10px;background:white;z-index:99999';document.body.append(host);var bytes=Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg=='),function(c){return c.charCodeAt(0)});FinanceEmployeeFormUX.renderFiles(host,[new File([bytes],'身分隔離測試.png',{type:'image/png'})]);return true;})()`);await b('click','#fixture-preview-host button');await b('wait','80');assert.equal(await scope(`!!document.querySelector('.efux-preview[open]')`),true);await scope(`(function(){setFinanceWorkspaceIdentityBlocked(true);return true;})()`);assert.equal(await scope(`!!document.querySelector('.efux-preview')`),false,'Identity lock removes local attachment preview');await scope(`(function(){setFinanceWorkspaceIdentityBlocked(false);document.getElementById('fixture-preview-host').remove();return true;})()`);
 const errors=(await b('errors')).trim();assert.equal(errors,'');fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify({ok:true,evidence,lostResponseSameKey:true,readFailurePreservesDraft:true,identityGuard:true,sourceUnchanged:true,scope:'Actual local UI, fictional transport. SQL authorization tested separately; no real login or production writes.'},null,2));console.log('PASS actual desktop/mobile progress + concern draft/retry/identity: '+out);
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{await b('close').catch(()=>{});server.close();});
