// Actual local index + engines. Only localhost HTTP responses expose a test
// closure; synthetic OAuth/read transports never contact Google or production.
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {chromium}=require('playwright');const {applyBuildEnvironment}=require('./finance_build_environment');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.argv[2]||'/tmp/finance-personnel-login-browser-20260914');
const source=fs.readFileSync(path.join(root,'index.html'),'utf8'),hash=crypto.createHash('sha256').update(source).digest('hex');
const anchor='bootAuthGate();\n\n})();';assert.ok(source.includes(anchor));
let html=applyBuildEnvironment(source,{target:'local',supabaseUrl:'',supabaseAnonKey:''}).replace(anchor,"window.__personnelQA={run:async function(code){return await eval(code);}};\n"+anchor).replace(/<!-- DEMO_LOGIN_START -->[\s\S]*?<!-- DEMO_LOGIN_END -->/g,'').replace(/<script\b[^>]*src=["']https?:[^>]*><\/script>/gi,'').replace('<head>',`<head><meta http-equiv="Content-Security-Policy" content="connect-src 'self'; form-action 'none'">`);
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname==='/auth/v1/authorize'){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end('<h1>匿名範例：本機 OAuth 導頁已驗證，未登入。</h1>');}const file=path.resolve(root,'.'+url.pathname);if(file!==root&&!file.startsWith(root+'/')){res.writeHead(403);return res.end();}if(file===root||file===path.join(root,'index.html')){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(html);}if(!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(file));});
const evidence={scope:'Actual local UI; fictional identities and fake OAuth/read transport only. No real-account E2E.',sourceHash:hash,checks:[],screenshots:[]};let browser;
function check(name,actual,expected){assert.deepEqual(actual,expected,name);evidence.checks.push(name);}
(async()=>{fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({channel:process.env.FINANCE_BROWSER_CHANNEL||'chrome',headless:true});
 for(const width of [1440,390]){const page=await browser.newPage({viewport:{width,height:width===390?844:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());const run=code=>page.evaluate(code=>window.__personnelQA.run(code.includes('await ')?'(async function(){'+code+'})()':code),code);await page.goto(origin,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__personnelQA);
 await run(`isFinanceProductionBuild=function(){return true};ensureOfficialHostBeforeOAuth=function(){return true};FINANCE_INITIAL_OAUTH_TIMEOUT_MS=60;SUPABASE_URL=location.origin;window.__oauthCalls=0;window.__oauthMode='reject';getSb=function(){return{auth:{signInWithOAuth:function(args){window.__oauthCalls++;if(!args.options.skipBrowserRedirect)throw Error('SDK redirect was not disabled');return window.__oauthMode==='timeout'?new Promise(function(resolve){window.__lateOAuth=resolve}):window.__oauthMode==='success'?Promise.resolve({data:{url:location.origin+'/auth/v1/authorize'}}):Promise.reject(Error('Fictional network failure'));},getSession:async function(){return{data:{session:null}}}}}};el('login-screen').style.display='flex';el('auth-loading').style.display='none';document.querySelector('.google-btn').disabled=false;`);
 await page.locator('.google-btn').click();await page.waitForFunction(()=>document.querySelector('#login-err').style.display!=='none'&&!document.querySelector('.google-btn').disabled,{},{timeout:5000}).catch(async error=>{console.error({url:page.url(),errors,body:await page.locator('#login-screen').innerText(),state:await run('({calls:window.__oauthCalls,attempt:!!financeInitialOAuthAttempt,switching:financeGoogleAccountSwitchInProgress})')});throw error;});check('first error retry enabled '+width,await page.locator('.google-btn').isEnabled(),true);check('first error visible '+width,/Google 登入沒有完成/.test(await page.locator('#login-err').innerText()),true);
 await run(`window.__oauthMode='timeout';window.__oauthCalls=0;window.__pendingA=googleLogin();window.__pendingB=googleLogin();`);await run(`await Promise.all([window.__pendingA,window.__pendingB]);`);check('double click single OAuth '+width,await run('window.__oauthCalls'),1);check('timeout visible '+width,/逾時/.test(await page.locator('#login-err').innerText()),true);check('timeout retry enabled '+width,await page.locator('.google-btn').isEnabled(),true);await run(`window.__lateOAuth({data:{url:location.origin+'/auth/v1/authorize'}})`);await page.waitForTimeout(20);check('late OAuth never redirects '+width,page.url(),origin+'/');check('login no overflow '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);const shot=path.join(out,'oauth-timeout-'+width+'.png');await page.screenshot({path:shot,fullPage:true});evidence.screenshots.push(shot);
 await run(`window.__oauthMode='success'`);await page.locator('.google-btn').click();await page.waitForURL('**/auth/v1/authorize');check('successful retry reaches local validated destination '+width,await page.locator('h1').innerText(),'匿名範例：本機 OAuth 導頁已驗證，未登入。');check('no page errors '+width,errors,[]);
 await page.goto(origin,{waitUntil:'networkidle'});
 await run(`USERS=[{id:'fixture-hr',n:'星河人資',email:'fixture.hr@example.invalid',role:'hr',active:true,authUserId:'10000000-0000-0000-0000-000000000001'},{id:'fixture-employee',n:'虛構員工',email:'fixture.person@example.invalid',role:'employee',active:true}];ENTS=[{id:'E1',s:'星河虛構公司',active:true}];DEPTS=[];ORG_CHART=[];REQS=[];INVS=[];BILLS=[];VOUCHERS=[];LEDGER=[];NOTIFS=[];DRAFTS=[];quickLogin('hr');S.user.authUserId='10000000-0000-0000-0000-000000000001';S.demoLogin=false;FINANCE_GOOGLE_LOGIN_HEALTH_TIMEOUT_MS=500;window.__healthCalls=0;window.__qaAlerts=[];window.alert=function(s){window.__qaAlerts.push(s)};getSb=function(){return{rpc:function(name,args){if(name!=='finance_admin_google_account_link_status_v2')return Promise.resolve({data:null,error:{code:'PGRST202'}});window.__healthCalls++;return new Promise(function(resolve){window.__lateHealth=resolve})}}};window.__healthPending=checkGoogleLoginStatusForUser('fixture-employee',{alert:true});true;`);
 check('real authorized health read '+width,await run('window.__healthCalls'),1);
 await run(`S.user={id:'fixture-other',n:'另一位虛構員工',email:'other@example.invalid',role:'employee',authUserId:'10000000-0000-0000-0000-000000000002'};financeAuthIdentityEpoch++;setFinanceWorkspaceIdentityBlocked(true);showFinanceAuthRecovery({reason:'auth_identity_mismatch',message:'匿名測試：已切換登入身分，工作區保持鎖定。'});window.__lateHealth({data:{status:'bound',auth_user_id:'old-private-auth',current_login_email:'private-old@example.invalid'}});await window.__healthPending;`);
 check('late admin response has no alert '+width,await run('window.__qaAlerts.length'),0);check('late admin response excluded from new scope cache '+width,await run(`financeGoogleLoginHealthForUser(USERS[1]).authUserId==='old-private-auth'`),false);check('identity lock retained '+width,await run('financeWorkspaceIdentityBlocked'),true);check('no private response in DOM '+width,await page.locator('body').innerText().then(t=>t.includes('private-old@example.invalid')),false);check('locked screen no overflow '+width,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);const locked=path.join(out,'late-health-locked-'+width+'.png');await page.screenshot({path:locked,fullPage:true});evidence.screenshots.push(locked);check('no page errors after health '+width,errors,[]);await page.close();
 }
 check('source unchanged during browser',crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'index.html'))).digest('hex'),hash);evidence.ok=true;fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify(evidence,null,2));console.log(`PASS ${evidence.checks.length} actual browser checks; ${out}`);
})().catch(e=>{fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({message:e.message,evidence},null,2));console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.close();});
