// Real SQL, fictional tenants only. No production connection or employee data.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();let checks=0;
const T='11111111-1111-4111-8111-111111111111',OTHER='22222222-2222-4222-8222-222222222222',UID='33333333-3333-4333-8333-333333333333',ARCH='44444444-4444-4444-8444-444444444444';
const eq=(a,b,label)=>{assert.deepEqual(a,b,label);checks++;};
const rejects=async(fn,re)=>{await assert.rejects(fn,re);checks++;};
async function actor(id='A',role='accountant',tenant=T){await db.exec('reset role');await db.query("select set_config('fixture.actor',$1,false),set_config('fixture.role',$2,false),set_config('fixture.tenant',$3,false),set_config('fixture.auth',$4,false)",[id,role,tenant,UID]);await db.exec('set role authenticated');}
const fixture=`
create role anon;create role authenticated;create role service_role;
create schema auth;create schema private;create schema storage;
grant usage on schema auth,storage to authenticated,anon;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('fixture.auth',true),'')::uuid$$;
create function public.current_tenant_id() returns uuid language sql stable as $$select nullif(current_setting('fixture.tenant',true),'')::uuid$$;
create function public.current_finance_role() returns text language sql stable as $$select current_setting('fixture.role',true)$$;
create function public.is_finance_accounting() returns boolean language sql stable as $$select public.current_finance_role() in ('accountant','ceo','admin_director')$$;
create function private.finance_reporting_actor_v1(e text,env text) returns jsonb language plpgsql stable security definer set search_path='' as $$begin if auth.uid() is null or e<>'F1' or env not in('production','test') or public.current_finance_role() not in('accountant','ceo','admin_director','external_audit') then raise exception 'scope denied' using errcode='42501';end if;return jsonb_build_object('tenantId',public.current_tenant_id(),'actorId',current_setting('fixture.actor',true),'canEditWorkpaper',public.is_finance_accounting(),'canEdit',public.current_finance_role() in('ceo','admin_director'));end$$;
create table public.tenants(id uuid primary key);insert into public.tenants values('${T}'),('${OTHER}');
create table public.finance_users(id text primary key,tenant_id uuid);insert into public.finance_users values('A','${T}'),('B','${T}'),('C','${OTHER}');
create table public.finance_portal_roles(id text primary key,tenant_id uuid);insert into public.finance_portal_roles values('RA','${T}'),('RB','${OTHER}');
create table public.finance_identity_links(id uuid primary key,tenant_id uuid,finance_user_id text,logging_role_id text);
insert into public.finance_identity_links values('55555555-5555-4555-8555-555555555555','${T}','A','RA'),('66666666-6666-4666-8666-666666666666','${OTHER}','C','RB');
alter table public.finance_portal_roles enable row level security;alter table public.finance_identity_links enable row level security;
create policy finance_portal_roles_select_authenticated on public.finance_portal_roles for all to authenticated using(true) with check(true);
create policy finance_identity_links_manage_people_admin_20260610 on public.finance_identity_links for all to authenticated using(true) with check(true);
grant select,insert,update,delete on public.finance_portal_roles,public.finance_identity_links to authenticated;
create table public.ledger_entries(id text primary key,tenant_id uuid,entity_id text,data_environment text,entry_date date,debit numeric,credit numeric);
create table public.period_closes(id text primary key,tenant_id uuid,entity_id text,data_environment text,period text,status text);
alter table public.period_closes enable row level security;create policy legacy_finance on public.period_closes for all to authenticated using(public.is_finance_accounting()) with check(public.is_finance_accounting());
grant select,insert,update,delete on public.period_closes,public.ledger_entries to authenticated;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint);
create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,metadata jsonb,unique(bucket_id,name));
alter table storage.objects enable row level security;
create policy legacy_storage_all on storage.objects for all to authenticated,anon using(true) with check(true);
grant select,insert,update,delete on storage.objects to authenticated,anon;
create table public.expense_requests(id text primary key,tenant_id uuid,entity_id text,data_environment text,request_date date,created_at timestamptz);
create table public.invoices(id text primary key,tenant_id uuid,entity_id text,data_environment text,invoice_date date,created_at timestamptz);
create table public.bills(id text primary key,tenant_id uuid,entity_id text,data_environment text,due_date date,created_at timestamptz);
insert into public.expense_requests values('REQ','${T}','F1','production','2026-08-01',null);
create table public.finance_reporting_profiles(tenant_id uuid,data_environment text,entity_id text,revision bigint,profile jsonb,updated_by text,primary key(tenant_id,data_environment,entity_id));
create table private.finance_reporting_profile_revisions_v1(tenant_id uuid,data_environment text,entity_id text,revision bigint,profile jsonb,actor_id text);
create function private.finance_reporting_default_v1() returns jsonb language sql as $$select '{"budgets":[],"allocations":[],"eliminations":[]}'::jsonb$$;
create function public.finance_reporting_profile_save_v1(p_entity_id text,p_expected_revision bigint,p_profile jsonb,p_reason text,p_data_environment text default 'production') returns jsonb language plpgsql security definer set search_path='' as $$declare t uuid:=public.current_tenant_id();rev bigint;actor text:=current_setting('fixture.actor',true);begin
select revision into rev from public.finance_reporting_profiles where tenant_id=t and entity_id=p_entity_id and data_environment=p_data_environment;
if coalesce(rev,0)<>p_expected_revision then raise exception 'revision conflict' using errcode='40001';end if;
insert into public.finance_reporting_profiles values(t,p_data_environment,p_entity_id,p_expected_revision+1,p_profile,actor) on conflict(tenant_id,data_environment,entity_id) do update set revision=excluded.revision,profile=excluded.profile,updated_by=excluded.updated_by;
insert into private.finance_reporting_profile_revisions_v1 values(t,p_data_environment,p_entity_id,p_expected_revision+1,p_profile,actor);
return jsonb_build_object('ok',true,'revision',p_expected_revision+1,'profile',p_profile);end$$;
`;
try{
 await db.exec(fixture);
 await db.exec('alter table public.period_closes add column note text');
 await db.exec(await fs.readFile(new URL('../supabase/migrations/20260927152432_finance_audit_controls_v1.sql',import.meta.url),'utf8'));
 eq((await db.query("select has_schema_privilege('anon','private','USAGE') allowed")).rows[0].allowed,false,'anonymous cannot resolve the HR directory private namespace');
 eq((await db.query("select has_schema_privilege('authenticated','private','USAGE') allowed")).rows[0].allowed,false,'authenticated cannot resolve the HR directory private namespace');
 await actor('A','ceo');
 await rejects(()=>db.query("select private.finance_archive_path_allowed_v1('fixture')"),/permission denied for schema private/);
 eq((await db.query('select count(*)::int n from public.finance_identity_links')).rows[0].n,1,'permissive ALL cannot widen tenant');
 eq((await db.query('select count(*)::int n from public.finance_portal_roles')).rows[0].n,1,'portal role tenant');
 eq((await db.query("update public.finance_identity_links set finance_user_id='A' where tenant_id=$1 returning id",[OTHER])).rows.length,0,'foreign tenant update invisible');
 await rejects(()=>db.query("insert into public.finance_identity_links values(gen_random_uuid(),$1,'C','RA')",[T]),/不屬於目前租戶/);
 await rejects(()=>db.query("insert into public.finance_identity_links values(gen_random_uuid(),$1,'A','RB')",[T]),/不屬於目前租戶/);
 await rejects(()=>db.query("insert into public.finance_portal_roles values('BAD',$1)",[OTHER]),/row-level security/);
 await db.exec('reset role');
 await rejects(()=>db.query("update public.finance_users set tenant_id=$1 where id='A'",[OTHER]),/foreign key constraint/);
 await actor('A','ceo');
 await db.query("insert into public.ledger_entries values('DR',$1,'F1','production','2026-08-01',100,0),('CR',$1,'F1','production','2026-08-01',0,99.90)",[T]);
 await rejects(()=>db.query("insert into public.period_closes(id,tenant_id,entity_id,data_environment,period,status) values('close',$1,'F1','production','2026-08','closed')",[T]),/借貸不平/);
 await db.query("update public.ledger_entries set credit=99.99 where id='CR'");
 await rejects(()=>db.query("insert into public.period_closes(id,tenant_id,entity_id,data_environment,period,status) values('close',$1,'F1','production','2026-08','closed')",[T]),/借貸不平/);
 await db.query("insert into public.ledger_entries values('TAIL',$1,'F1','production','2026-08-01',0,0.01)",[T]);
 await db.query("insert into public.period_closes(id,tenant_id,entity_id,data_environment,period,status) values('close',$1,'F1','production','2026-08','closed')",[T]);checks++;
 await rejects(()=>db.query("delete from public.period_closes where id='close'"),/關帳紀錄不可刪除/);
await rejects(()=>db.query("insert into public.ledger_entries values('LATE',$1,'F1','production','2026-08-02',1,1)",[T]),/期間已關閉/);
 await rejects(()=>db.query("update public.period_closes set status='open' where id='close'"),/填寫新的原因/);
 await actor('B','accountant');await rejects(()=>db.query("update public.period_closes set status='open',note='Source correction' where id='close'"),/填寫新的原因/);
 await actor('A','ceo');await db.query("update public.period_closes set status='open',note='Source correction' where id='close'");checks++;
 await db.query("insert into public.ledger_entries values('REOPENED',$1,'F1','production','2026-08-02',1,1)",[T]);checks++;
 await db.query("update public.period_closes set status='closed' where id='close'");
 await rejects(()=>db.query("update public.period_closes set status='open' where id='close'"),/填寫新的原因/);
 await rejects(()=>db.query("insert into public.period_closes(id,tenant_id,entity_id,data_environment,period,status) values('foreign',$1,'F1','production','2026-07','closed')",[OTHER]),/未授權/);
 await actor('A',null);await rejects(()=>db.query("insert into public.period_closes(id,tenant_id,entity_id,data_environment,period,status) values('null-role',$1,'F1','production','2026-07','closed')",[T]),/未授權/);
 await actor('A','staff');await rejects(()=>db.query("insert into public.period_closes(id,tenant_id,entity_id,data_environment,period,status) values('staff',$1,'F1','production','2026-07','closed')",[T]),/未授權|row-level security/);
 await actor();
 const prefix=`${T}/F1/2026-08/${ARCH}/`,object=prefix+'original.pdf';
 await db.query("insert into storage.objects(bucket_id,name,metadata) values('finance-audit-archives',$1,'{\"size\":3}')",[object]);checks++;
 await rejects(()=>db.query("insert into storage.objects(bucket_id,name,metadata) values('finance-audit-archives',$1,'{\"size\":3}')",[object.replace(T,OTHER)]),/row-level security/);
 eq((await db.query("update storage.objects set metadata='{\"size\":4}' where name=$1 returning name",[object])).rows.length,0,'archive bytes cannot overwrite');
 eq((await db.query("delete from storage.objects where name=$1 returning name",[object])).rows.length,0,'archive cannot delete');
 let manifest={version:1,archiveId:ARCH,tenantId:T,dataEnvironment:'production',scope:{entityId:'F1',period:'2026-08'},files:[{path:object,name:'original.pdf',size:3,sha256:'a'.repeat(64),sourceType:'expense_requests',sourceId:'REQ'}]};
 const seal=m=>db.query('select public.finance_seal_document_archive_v1($1,$2,$3) r',['F1','2026-08',m]);
 await rejects(()=>seal({...manifest,files:[{...manifest.files[0],size:4}]}),/大小不符/);
 await rejects(()=>seal({...manifest,files:[{...manifest.files[0],sha256:null}]}),/檔案或來源無效/);
 await rejects(()=>seal({...manifest,files:[{...manifest.files[0],sourceId:'OTHER-REQ'}]}),/來源不屬於/);
 eq((await seal(manifest)).rows[0].r.ok,true,'seal after upload');eq((await seal(manifest)).rows[0].r.replayed,true,'same manifest retry');
 await rejects(()=>seal({...manifest,createdAt:'different'}),/重試內容不一致/);
 await rejects(()=>db.query("insert into storage.objects(bucket_id,name,metadata) values('finance-audit-archives',$1,'{\"size\":3}')",[prefix+'extra.pdf']),/row-level security/);
 eq((await db.query("select public.finance_document_archives_v1('F1','2026-08') r")).rows[0].r.archives.length,1,'archive listed');
 await rejects(()=>db.query('select public.finance_verify_document_archive_v1($1,0)',[ARCH]),/件數不符/);
 eq((await db.query('select public.finance_verify_document_archive_v1($1,1) r',[ARCH])).rows[0].r.ok,true,'full readback recorded');
 await actor('B','external_audit');eq((await db.query("select count(*)::int n from storage.objects where bucket_id='finance-audit-archives'")).rows[0].n,1,'auditor reads authorised archive');
 await rejects(()=>db.query("insert into storage.objects(bucket_id,name,metadata) values('finance-audit-archives',$1,'{\"size\":3}')",[prefix.replace(ARCH,'77777777-7777-4777-8777-777777777777')+'extra.pdf']),/row-level security/);
 await actor('A','ceo');
 let p={budgets:[{id:'BUDGET',status:'draft',amount:100}],allocations:[],eliminations:[]};
 const save=(profile,rev)=>db.query("select public.finance_reporting_profile_save_v1('F1',$1,$2,'Verified source','production') r",[rev,profile]);
 eq((await save(p,0)).rows[0].r.revision,1,'draft prepared');
 let reviewed={...p,budgets:[{...p.budgets[0],status:'reviewed',reviewReason:'Checked'}]};
 await rejects(()=>save(reviewed,1),/不得覆核自己的/);
 await actor('B','admin_director');eq((await save(reviewed,1)).rows[0].r.revision,2,'second actor reviews');
 await rejects(()=>save({...p,budgets:[{...p.budgets[0],id:'NEW',status:'reviewed'}]},2),/先保存草稿/);
 await rejects(()=>db.query("select public.finance_reporting_profile_save_pre_review_v1('F1',2,$1,'bypass','production')",[p]),/permission denied/);
 await db.exec('reset role');await db.query("select set_config('fixture.auth','',false)");await db.exec('set role anon');
 eq((await db.query("select count(*)::int n from storage.objects where bucket_id='finance-audit-archives'")).rows[0].n,0,'anonymous archive read blocked');
 await rejects(()=>db.query("select public.finance_document_archives_v1('F1','2026-08')"),/permission denied/);
 console.log(`PASS ${checks} real SQL controls: tenant isolation, exact close, archive immutability/readback and second-person review`);
}finally{await db.close();}
