'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const engine=require('../assets/engines/document-search.js'),html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
let checks=0;function check(name,fn){fn();checks++;console.log('PASS '+name);}
const row={texts:['測試水費','REQ-AB/001','林會計'],amounts:[1250,12.5,-65.75]};
for(const query of ['1250','1,250','NT$1,250','NT$ 1,250','TWD 1,250','NTD1,250','新臺幣1,250元','新台幣 1,250 元','ＮＴ＄１，２５０','1250.00','1,250.00','12.50','-65.75','−65.75','水費 1,250','125'])check('supported amount query '+query,()=>assert.equal(engine.matches(query,row),true));
for(const query of ['12.00','1.25','65.70','1,25','missing 1,250','%','[','.*'])check('unmatched literal/amount query '+query,()=>assert.equal(engine.matches(query,row),false));
check('Decimal and sign never disappear',()=>{assert.equal(engine.matches('12.50',{amounts:[1250]}),false);assert.equal(engine.matches('-65.75',{amounts:[65.75]}),false);assert.equal(engine.matches('12.00',{amounts:[1250]}),false);assert.equal(engine.matches('12.00',{texts:['amount 12.001']}),false);});
check('Known zero differs from missing values',()=>{assert.equal(engine.matches('0',{amounts:[null,undefined,'',false,NaN,Infinity,{}]}),false);assert.equal(engine.matches('0.00',{amounts:[0]}),true);});
check('Integer partial amount and existing document number search',()=>{assert.equal(engine.matches('1250',{amounts:[12500]}),true);assert.equal(engine.matches('ab/001',row),true);assert.equal(engine.matches('ab001',{...row,compactText:true}),true);assert.equal(engine.matches('12.50',{texts:['1250'],compactText:true}),false);});
check('Monetary formatting does not erase invalid grouping',()=>{assert.equal(engine.amountText('1,25'),null);assert.equal(engine.amountText('1,234,567.50'),'1234567.5');assert.equal(engine.amountText('-0.00'),'0');});
check('Text cannot bypass decimal precision or negative sign',()=>{assert.equal(engine.matches('12.50',{texts:['金額 -12.50'],amounts:[-12.5]}),false);assert.equal(engine.matches('12.50',{texts:['NT$112.50']}),false);});
check('Batch sums ignore binary noise without rounding genuine fractions',()=>{assert.equal(engine.matches('0.30',{amounts:[0.1+0.2]}),true);assert.equal(engine.matches('12.00',{amounts:[12.001]}),false);});
function fn(name){const start=html.indexOf('function '+name+'(');assert.ok(start>=0,name);const end=html.indexOf('\n}',start);assert.ok(end>start,name);return html.slice(start,end+2);}
const context={window:{FinanceDocumentSearch:engine},console,S:{aT:'p',apprQuery:'1,250'},requestReviewAmount:r=>r.actualAmt||r.amt||0,billGroupApprovalRows:i=>i.rows||[i.raw],invoiceGroupApprovalRows:i=>i.rows||[i.raw],approvalRowAmount:i=>i.amount,approvalSearchText:i=>i.label||'',approvalSortState:()=>({field:'amount',dir:'asc'}),approvalSortValue:i=>i.amount,approvalRowFormNo:i=>i.raw.no,gD:()=>({n:'照護部'}),gE:()=>({s:'甲公司',full:'甲公司'}),entityOfDept:()=> 'E1',ledgerSourceRef:r=>r.ref,sourceByLedgerRef:()=>({no:'SOURCE-A',label:'來源單據'})};
vm.createContext(context);
for(const name of ['financeDocumentMatchesQuery','requestSearchAmounts','approvalMatchesQuery','approvalApplySearchSort','ledgerRowMatchesQuery'])vm.runInContext(fn(name),context);
const approval={kind:'inv',raw:{no:'A',total:700},rows:[{no:'A',total:700},{no:'B',total:550}],amount:1250,label:'林會計 水費'};
check('Actual approval filter searches batch aggregate and constituent money',()=>{assert.equal(context.approvalMatchesQuery(approval,'NT$1,250'),true);assert.equal(context.approvalMatchesQuery(approval,'550.00'),true);assert.equal(context.approvalMatchesQuery(approval,'林會計 700'),true);assert.equal(context.approvalApplySearchSort([approval,{...approval,amount:400,rows:[{total:400}]}]).length,1);});
check('Actual request amounts include estimated and final amounts',()=>{const r={amt:1000,actualAmt:1250,estimatedAmt:1300};assert.equal(engine.matches('1,300.00',{amounts:context.requestSearchAmounts(r)}),true);});
check('Actual request missing money does not invent zero',()=>assert.equal(engine.matches('0',{amounts:context.requestSearchAmounts({})}),false));
check('History remains globally searched and paged by scoped server RPC',()=>{context.S.aT='h';context.S.apprQuery='not a local match';assert.equal(context.approvalApplySearchSort([approval]).length,1);assert.match(html,/p_search:query\|\|null/);});
check('Actual ledger filter finds either debit or credit and source',()=>{const r={dc:'CARE',dr:1250.5,cr:0,ref:'SOURCE-A',desc:'測試水費'};assert.equal(context.ledgerRowMatchesQuery(r,'水費 1,250.50'),true);assert.equal(context.ledgerRowMatchesQuery({...r,dr:0,cr:1250.5},'1250.50'),true);assert.equal(context.ledgerRowMatchesQuery(r,'12.50'),false);assert.equal(context.ledgerRowMatchesQuery(r,'SOURCE-A'),true);});
// Exercise the real request amount selector and full expense text/payload index,
// because testing the shared engine alone would miss rounded text and default 0.
const expenseContext={window:{FinanceDocumentSearch:engine},EXPENSE_SEARCH_CACHE:new WeakMap(),num:v=>Number(v)||0,fmt:v=>Math.round(Number(v)||0).toLocaleString('zh-TW'),gE:()=>({}),gD:()=>({}),expenseStatusKey:()=>'',requestTypeLabel:()=>'',requestPurposeText:r=>r.purpose||'',requestNoteText:r=>r.note||'',requestFeeBearer:()=>'',requestDateText:()=>'',requestExpectedPayText:()=>'',expenseCompletedDate:()=>'',SL:{}};
vm.createContext(expenseContext);
for(const name of ['requestReviewAmount','expenseSearchNormalize','expenseSearchCompact','financeDocumentMatchesQuery','requestSearchAmounts','expensePayloadSearchValues','expenseAttachmentSearchValues','expenseSearchIndex','expenseMatchesQuery'])vm.runInContext(fn(name),expenseContext);
check('Actual expense search never invents the rounded amount 1250 from 1249.75',()=>{const r={type:'expense_request',amt:1249.75};assert.equal(expenseContext.expenseMatchesQuery(r,'1250'),false);assert.equal(expenseContext.expenseMatchesQuery(r,'1,250'),false);assert.equal(expenseContext.expenseMatchesQuery(r,'1249.75'),true);});
check('Actual expense search does not convert a missing amount into searchable zero',()=>{const r={type:'expense_request'};assert.equal(expenseContext.expenseMatchesQuery(r,'0'),false);assert.equal(expenseContext.expenseMatchesQuery(r,'0.00'),false);});
check('Actual expense search retains an explicitly known zero',()=>{const r={type:'expense_request',amt:0};assert.equal(expenseContext.expenseMatchesQuery(r,'0'),true);assert.equal(expenseContext.expenseMatchesQuery(r,'0.00'),true);});
check('Actual expense payload text cannot bypass the sign of a decimal amount',()=>{const r={type:'expense_request',amt:-12.5,formPayload:{accountingLines:[{description:'更正金額 -12.50',grossAmount:-12.5}]}};assert.equal(expenseContext.expenseMatchesQuery(r,'12.50'),false);assert.equal(expenseContext.expenseMatchesQuery(r,'−12.50'),true);});
check('Actual expense nested currency text cannot match a smaller decimal substring',()=>{const r={type:'expense_request',amt:112.5,formPayload:{accountingLines:[{description:'憑證 NT$112.50',grossAmount:112.5}]}};assert.equal(expenseContext.expenseMatchesQuery(r,'12.50'),false);assert.equal(expenseContext.expenseMatchesQuery(r,'112.50'),true);});
check('Actual expense typed amount still supports currency NFKC and combined text',()=>{const r={type:'expense_request',amt:1250,purpose:'測試水費'};assert.equal(expenseContext.expenseMatchesQuery(r,'水費 ＮＴ＄１，２５０'),true);assert.equal(expenseContext.expenseMatchesQuery(r,'水費 12.50'),false);});
check('Actual advance request retains both estimated and settled searchable amounts',()=>{const r={type:'advance_request',actualAmt:1249.75,estimatedAmt:1300};assert.equal(expenseContext.expenseMatchesQuery(r,'1,300.00'),true);assert.equal(expenseContext.expenseMatchesQuery(r,'1249.75'),true);assert.equal(expenseContext.expenseMatchesQuery(r,'1250'),false);});
check('Shared engine loads before every reporting consumer',()=>{assert.ok(html.indexOf('src="assets/engines/document-search.js')<html.indexOf('src="assets/engines/reporting-workspace.js'));});
console.log(JSON.stringify({ok:true,checks}));
