'use strict';
const assert=require('node:assert/strict');
const ar=require('../assets/engines/receivables-engine.js');
let checks=0;function check(name,fn){fn();checks++;console.log('PASS '+name);}
function item(id,overrides={}){return Object.assign({invoiceId:id,batchId:'B1',entityId:'E1',departmentCode:'D1',originalAmount:100,recognizedAmount:100,allowanceAmount:0,arAllowanceAmount:0,receivedAmount:0,outstandingAmount:100,pendingReceiptAmount:0,refundPayable:0,refundedAmount:0,dueDate:null,overdueDays:null,balanceStatus:'unpaid',status:'unpaid'},overrides);}
check('mixed paid100 plus unpaid200 batch retains actual received100 and outstanding200',()=>{const r=ar.summarize([item('I1',{receivedAmount:100,outstandingAmount:0,status:'paid',balanceStatus:'settled'}),item('I2',{originalAmount:200,recognizedAmount:200,outstandingAmount:200})]);assert.equal(r.receivedAmount,100);assert.equal(r.outstandingAmount,200);assert.equal(r.settledCount,1);});
check('full allowance after partial receipt preserves separate AR allowance and refundable cash',()=>{const r=ar.summarize([item('I1',{receivedAmount:40,allowanceAmount:100,arAllowanceAmount:60,outstandingAmount:0,refundPayable:40})]);assert.equal(r.outstandingAmount,0);assert.equal(r.allowanceAmount,100);assert.equal(r.arAllowanceAmount,60);assert.equal(r.refundPayable,40);});
check('workflow paid cannot invent a receipt',()=>assert.equal(ar.summarize([item('I1',{status:'paid'})]).receivedAmount,0));
check('positive receivables and credits stay separate',()=>{const r=ar.summarize([item('I1'),item('I2',{outstandingAmount:-20})]);assert.equal(r.outstandingAmount,100);assert.equal(r.creditAmount,20);assert.equal(r.signedOutstandingAmount,80);});
check('unknown dates and genuine overdue amounts remain distinct',()=>{const r=ar.summarize([item('I1'),item('I2',{dueDate:'2026-01-01',overdueDays:50})]);assert.equal(r.unknownDueAmount,100);assert.equal(r.overdueAmount,100);});
check('partial refunds do not reduce actual received cash or recreate AR',()=>{const r=ar.summarize([item('I1',{receivedAmount:100,outstandingAmount:0,refundPayable:60,refundedAmount:40})]);assert.equal(r.receivedAmount,100);assert.equal(r.refundedAmount,40);assert.equal(r.refundPayable,60);assert.equal(r.outstandingAmount,0);});
check('decimal cents sum exactly',()=>assert.equal(ar.summarize([item('I1',{outstandingAmount:.1}),item('I2',{outstandingAmount:.2})]).outstandingAmount,.3));
check('missing canonical rows expose unavailable instead of fake zero',()=>{const r=ar.summarizeInvoices([{id:'I1'},{id:'I2'}],[item('I1')]);assert.equal(r.ready,false);assert.equal(r.receivedAmount,null);assert.deepEqual(r.missingIds,['I2']);});
check('explicit worklist scope excludes unrelated canonical rows',()=>{const r=ar.summarizeInvoices([{id:'I1'}],[item('I1'),item('OTHER')]);assert.equal(r.count,1);assert.equal(r.outstandingAmount,100);});
check('duplicate ids never double count',()=>{assert.equal(ar.summarize([item('I1'),item('I1')]).ready,false);assert.equal(ar.summarizeInvoices(['I1'],[item('I1'),item('I1')]).ready,false);assert.equal(ar.summarizeInvoices(['I1','I1'],[item('I1')]).ready,false);});
check('null missing numeric strings excess precision and unsafe values remain unavailable',()=>{for(const value of [null,undefined,'100',NaN,Infinity,1.001,1e18])assert.equal(ar.summarize([item('I1',{receivedAmount:value})]).ready,false);});
check('groups use every invoice and do not mutate rows',()=>{const rows=[item('I1'),item('I2',{departmentCode:'D2'})],before=JSON.stringify(rows),groups=ar.group(rows,'departmentCode');assert.equal(groups.length,2);assert.equal(groups[1].summary.outstandingAmount,100);assert.equal(JSON.stringify(rows),before);});
check('valid empty results are zero while absent results are unavailable',()=>{assert.equal(ar.summarize([]).outstandingAmount,0);assert.equal(ar.summarize(null).outstandingAmount,null);});
// Exercise the real legacy adapter/build function so status-based sums cannot return.
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const adapter=source.slice(source.indexOf('function recvCanonicalSnapshot(){'),source.indexOf('\n\tfunction bankRowsForSelectedEntity(){',source.indexOf('function recvCanonicalSnapshot(){')));
const inputs=[{id:'I1',eid:'E1',en:'虛構公司',total:100,status:'paid'},{id:'I2',eid:'E1',en:'虛構公司',total:200,status:'partial'}];
let payload={complete:true,asOf:'2026-09-10',items:[item('I1',{receivedAmount:100,outstandingAmount:0,status:'paid',invoiceDate:'2026-07-01'}),item('I2',{originalAmount:200,recognizedAmount:200,outstandingAmount:200,invoiceDate:'2026-08-01'})]},requested=[];
const nodes={},ctx={window:{FinanceReceivablesEngine:ar,FinanceReportingWorkspace:{receivablesForScope(scope){assert.deepEqual(JSON.parse(JSON.stringify(scope)),{entity:'E1',department:'all',asOf:'2026-09-10'});return payload;},loadReceivables(force,scope){requested.push(scope);}}},S:{recvEntity:'E1'},todayIso:()=> '2026-09-10',fmt:v=>String(v),escAttr:String,el:id=>nodes[id]||(nodes[id]={}),recvBaseInvoices:()=>inputs,normalizeRecvEntity:()=>{},recvInvoicesForMonthRange:x=>x,renderRecvEntitySelects:()=>{},renderRecvMonthRangeControls:()=>{},recvInvoicesForSelectedEntity:x=>x,uniqueInvoiceGroups:x=>x,recvCounts:()=>({notPaid:1,unpaid:0,partial:1,pending_receipt_review:0}),updateRecvSidebarBadge:()=>{},recvEntityLabel:()=> '虛構公司',recvMonthRangeLabel:()=> '全部月份',renderBankReconciliationPanel:()=>{},renderRecvRateSummary:()=>{},gE:()=>({s:'虛構公司'}),renderRecvDetail:()=>{}};
vm.createContext(ctx);vm.runInContext(adapter,ctx);
check('real legacy build uses canonical totals not whole unpaid batch',()=>{ctx.window.buildRecv();assert.match(nodes['recv-kpis'].innerHTML,/正式實收[\s\S]*?>100</);assert.match(nodes['recv-kpis'].innerHTML,/未收餘額[\s\S]*?>200</);assert.match(nodes['recv-etbl'].innerHTML,/>33%</);});
check('real legacy adapter fixes current scope independently of historical department worklist',()=>{const summary=ctx.recvCanonicalSummary(inputs,ctx.recvCanonicalSnapshot());assert.equal(summary.outstandingAmount,200);});
check('real legacy monthly cards use issue cohorts and never last paid date',()=>{assert.match(nodes['recv-trend'].innerHTML,/不是各月銀行收款流量/);assert.match(nodes['recv-trend'].innerHTML,/2026年07月開票/);assert.match(nodes['recv-trend'].innerHTML,/2026年08月開票/);});
check('real legacy missing response renders unavailable with no fake zero',()=>{payload=null;ctx.window.buildRecv();assert.match(nodes['recv-kpis'].innerHTML,/未核對/);assert.match(nodes['recv-trend'].innerHTML,/月別金額尚未核對/);assert.equal(requested.length,1);assert.equal(ctx.recvCanonicalRate({ready:false,originalAmount:100,receivedAmount:0}),null);});
check('real legacy missing issue dates are separate from known months',()=>{payload={complete:true,items:[item('I1'),item('I2')]};const groups=ctx.recvCanonicalMonthGroups(inputs,payload);assert.equal(groups[0].key,'unknown');});
const rowSource=source.slice(source.indexOf('function recvInvoiceRowHtml(i,RECV){'),source.indexOf('\n\tfunction singleInvoiceDetailHtml',source.indexOf('function recvInvoiceRowHtml(i,RECV){')));
const partial={id:'P1',eid:'E1',status:'partial',total:100},paid={id:'P0',eid:'E1',status:'paid',total:100};
Object.assign(ctx,{S:{user:{id:'FICT'},recvEntity:'E1'},invoiceGroupRows:()=>[paid,partial],invoiceGroupTotal:()=>200,invoiceGroupLeader:()=>paid,receiptFilesForInvoiceRows:()=>[],invoiceGroupReceiptCounts:()=>({paid:1,unpaid:0,partial:1,total:2}),invoiceGroupNo:()=> 'FICT-BATCH',recvGroupStatusKey:()=> 'partial',recvStatusKey:i=>i.status,recvStatusShortLabel:()=> '部分已收',invoiceIdentifierType:()=>'',captureReceiptReviewVersions:()=>{},canActReceipt:i=>i.status==='partial',currentRoleKey:()=> 'accountant'});
vm.runInContext(rowSource,ctx);
check('real partial group upload targets actionable invoice even when leader already paid',()=>{const html=ctx.recvInvoiceRowHtml(paid,{});assert.match(html,/submitReceiptReview\('P1',this\)/);assert.match(html,/上傳證明/);});
const bankHealth=source.slice(source.indexOf('function bankReconciliationHealthForEntity('),source.indexOf('\n\tfunction bankTxShort',source.indexOf('function bankReconciliationHealthForEntity(')));
const bankPanel=source.slice(source.indexOf('function renderBankReconciliationPanel('),source.indexOf('\n\twindow.recvTab=',source.indexOf('function renderBankReconciliationPanel(')));
Object.assign(ctx,{productModuleEnabled:()=>true,isFinance:()=>true});vm.runInContext(bankHealth+'\n'+bankPanel,ctx);
check('real bank panel retains all partial matched remainders beyond six rows',()=>{payload={complete:true,asOf:'2026-09-10',items:[],reconciliation:{bankVisible:true,unmatchedBankAmount:480,unmatchedBankCount:8,unmatchedBankItems:Array.from({length:8},(_,i)=>({id:'BANK-'+i,date:'2026-09-01',amount:100,matchedAmount:40,remainingAmount:60,matchStatus:'matched'}))}};ctx.renderBankReconciliationPanel();assert.match(nodes['bank-recon-panel'].innerHTML,/BANK-7/);assert.match(nodes['bank-recon-panel'].innerHTML,/>480</);assert.equal((nodes['bank-recon-panel'].innerHTML.match(/data-bank-remainder=/g)||[]).length,8);assert.doesNotMatch(nodes['bank-recon-panel'].innerHTML,/目前無風險/);});
check('real bank panel missing or unauthorized data cannot claim zero or no risk',()=>{payload=null;ctx.renderBankReconciliationPanel();assert.match(nodes['bank-recon-panel'].innerHTML,/尚未核對/);payload={complete:true,items:[],reconciliation:{bankVisible:false}};ctx.renderBankReconciliationPanel();assert.match(nodes['bank-recon-panel'].innerHTML,/無銀行核銷明細讀取權限/);ctx.isFinance=()=>false;ctx.renderBankReconciliationPanel();assert.equal(nodes['bank-recon-panel'].innerHTML,'');});
async function finalRuntimeChecks(){
  const currentSource=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
  const facadeSource=currentSource.slice(currentSource.indexOf('function createFinanceReportingRuntime(){'),currentSource.indexOf('\nif(window.FinanceReportingWorkspace){',currentSource.indexOf('function createFinanceReportingRuntime(){')));
  let role='accountant',allowed=true,who='UUID1',calls=[],uploadCalls=[],attachments=[{name:'fiction.pdf',path:'private/fiction.pdf'}];
  const fctx={window:{},S:{user:{id:'FICT-ACCOUNTANT'},page:'recv'},INVS:[{id:'P1',no:'FICTION-1',eid:'E1',dc:'D1',status:'partial'}],currentRoleKey:()=>role,canActReceipt:()=>allowed,approvalFastBootstrapIdentity:()=>who,activeDataEnvironment:()=> 'test',approvalRecordsActionAvailability:()=>({ok:allowed}),fileToAttachment:async x=>({name:x.name}),uploadAttachmentsToSupabase:async(files,scope)=>{uploadCalls.push({files,scope});return attachments;},financeReceiptAction:async(...args)=>{calls.push(args);return{ok:true};}};
  vm.createContext(fctx);vm.runInContext(facadeSource,fctx);const runtime=fctx.createFinanceReportingRuntime(),opts={amount:40,receivedDate:'2026-09-09',note:'虛構部分實收',files:[{name:'fiction.pdf'}]};
  await runtime.submitReceipt('P1',7,opts);
  check('real reporting facade submits partial amount date private proof and reviewed version',()=>{assert.equal(calls[0][0][0].id,'P1');assert.equal(calls[0][1],'submit');assert.deepEqual(calls[0][3],attachments);assert.equal(calls[0][4].P1,7);assert.equal(calls[0][5].amounts.P1,40);assert.equal(calls[0][5].receivedDate,'2026-09-09');assert.equal(uploadCalls[0].scope.kind,'receipt_proof');assert.equal(uploadCalls[0].scope.recordNo,'FICTION-1');});
  await runtime.submitReceipt('P1',7,opts);check('real facade retry reuses uploaded proof metadata',()=>assert.equal(uploadCalls.length,1));
  role='employee';await assert.rejects(runtime.submitReceipt('P1',7,opts));role='accountant';allowed=false;await assert.rejects(runtime.submitReceipt('P1',7,opts));check('real facade rejects unauthorized role or canActReceipt before uploads',()=>{assert.equal(calls.length,2);assert.equal(uploadCalls.length,1);});
  allowed=true;role='ceo';await runtime.receiptAction('P1','approve','虛構覆核',9);check('real CEO facade passes reviewed version and cannot replace submitted amount/date',()=>{assert.equal(calls[2][1],'approve');assert.equal(calls[2][4].P1,9);assert.equal(calls[2][5],undefined);});
  role='accountant';fctx.uploadAttachmentsToSupabase=async()=>{who='UUID2';return attachments;};await assert.rejects(runtime.submitReceipt('P1',10,{amount:30,receivedDate:'2026-09-09',files:[{name:'new.pdf'}]}));check('real facade rejects identity change during proof upload before receipt RPC',()=>assert.equal(calls.length,3));
  // Actual old modal refund handler: rejection resets CAS; uncertain replies preserve key.
  const start=currentSource.indexOf('var FINANCE_REFUND_PENDING_OPERATIONS='),refundSource=currentSource.slice(start,currentSource.indexOf('\n\tfunction recvInvoiceLedgerRows',start));
  let response={error:{code:'40001',message:'stale refund amount'}},requests=[],refreshFail=false,refundRefreshes=0,uuid=0;
  const event={id:'EV1',invoiceId:'I1',total:100,refundPayableAmount:100,refundAmount:0};
  const rctx={window:{FinanceReportingWorkspace:{invalidate(){}}},INVOICE_LIFECYCLE_EVENTS:[event],canManageInvoiceLifecycle:()=>true,approvalFastBootstrapIdentity:()=> 'UUID-FICT',activeDataEnvironment:()=> 'test',num:Number,fmt:String,invoiceNumberValue:Number,prompt:label=>label.includes('金額')?'10':'虛構退款',alert:()=>{},todayIso:()=> '2026-09-10',crypto:{randomUUID:()=> 'operation-'+(++uuid)},getSb:()=>({rpc:async(name,args)=>{requests.push(JSON.parse(JSON.stringify(args)));return response;}}),expenseApplicantRevisionRpcErrorIsAmbiguous:e=>e.code==='57014'||/network/.test(e.message||''),refreshAfterInvoiceLifecycle:async()=>{refundRefreshes++;if(refreshFail)throw new Error('network readback');event.refundAmount=20;}};
  vm.createContext(rctx);vm.runInContext(refundSource,rctx);await rctx.window.refundInvoiceLifecycleEvent('EV1');
  check('real old refund definitive CAS rejection discards stale operation and reloads',()=>{assert.equal(Object.keys(rctx.FINANCE_REFUND_PENDING_OPERATIONS).length,0);assert.equal(refundRefreshes,1);});
  response={data:{ok:true}};await rctx.window.refundInvoiceLifecycleEvent('EV1');check('real old refund next input uses fresh CAS and new operation key',()=>{assert.equal(requests[1].p_expected_refund_amount,20);assert.notEqual(requests[1].p_idempotency_key,requests[0].p_idempotency_key);});
  response={error:{message:'network failed'}};await rctx.window.refundInvoiceLifecycleEvent('EV1');await rctx.window.refundInvoiceLifecycleEvent('EV1');check('real old refund ambiguous failure retains identical key and payload',()=>assert.deepEqual(requests[2],requests[3]));
  response={data:{ok:true}};refreshFail=true;await rctx.window.refundInvoiceLifecycleEvent('EV1');await rctx.window.refundInvoiceLifecycleEvent('EV1');check('real old refund successful commit with failed readback also keeps same idempotency key',()=>{assert.equal(requests[4].p_idempotency_key,requests[2].p_idempotency_key);assert.equal(requests[5].p_idempotency_key,requests[2].p_idempotency_key);});
  console.log('PASS canonical receivables, bank, runtime facade and refund cache: '+checks+' checks');
}
finalRuntimeChecks().catch(e=>{console.error(e);process.exitCode=1;});
