#!/usr/bin/env node
'use strict';

/**
 * Generates and verifies a deterministic manifest for the exact www artifact.
 * The manifest excludes itself from the artifact digest to avoid self-hashing.
 */

const childProcess = require('node:child_process');
const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const {
  applyBuildEnvironment,
  resolveBuildConfig
} = require('./finance_build_environment');

const ROOT = path.resolve(__dirname, '..');
const OUTPUT = path.join(ROOT, 'www');
const MANIFEST_PATH = path.join(OUTPUT, 'release-manifest.json');
const CHECKER_PATH = 'scripts/check_root_cause_regressions.js';
const MIGRATION_CHECKER_PATH = 'scripts/check_migration_lineage_contract.js';
const args = new Set(process.argv.slice(2));
let buildConfig = null;

function fail(message) {
  process.stderr.write(`FAIL ${message}\n`);
  process.exit(1);
}

try {
  buildConfig = resolveBuildConfig(process.env);
} catch (error) {
  fail(`invalid Finance build environment: ${error.message}`);
}

function sha256(buffer) {
  return crypto.createHash('sha256').update(buffer).digest('hex');
}

function gitHead() {
  try {
    return childProcess.execFileSync('git', ['rev-parse', 'HEAD'], {
      cwd: ROOT,
      encoding: 'utf8',
      timeout: 10000,
      stdio: ['ignore', 'pipe', 'pipe']
    }).trim();
  } catch (error) {
    const vercelSha = String(process.env.VERCEL_GIT_COMMIT_SHA || '').trim();
    if (/^[0-9a-f]{40}$/.test(vercelSha)) return vercelSha;
    fail(`source commit is unavailable: ${error.message}`);
  }
}

function relative(file) {
  return path.relative(ROOT, file).split(path.sep).join('/');
}

function removeGeneratedOsMetadata(directory) {
  if (!fs.existsSync(directory)) return;
  const stack = [directory];
  while (stack.length) {
    const current = stack.pop();
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const full = path.join(current, entry.name);
      if (entry.isDirectory()) {
        stack.push(full);
      } else if (entry.name === '.DS_Store' || entry.name === 'Thumbs.db') {
        // These files are generated by the workstation, not the Finance build.
        // Remove them from the generated output before hashing or upload.
        fs.unlinkSync(full);
      }
    }
  }
}

function walk(directory, excluded = new Set()) {
  if (!fs.existsSync(directory)) return [];
  const files = [];
  const stack = [directory];
  while (stack.length) {
    const current = stack.pop();
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const full = path.join(current, entry.name);
      const rel = relative(full);
      if (excluded.has(rel)) continue;
      if (entry.isSymbolicLink()) fail(`artifact contains symlink: ${rel}`);
      if (entry.isDirectory()) stack.push(full);
      else if (entry.isFile()) files.push(full);
    }
  }
  return files.sort((a, b) => relative(a).localeCompare(relative(b)));
}

function fileRecords(files) {
  return files.map((file) => {
    const body = fs.readFileSync(file);
    return { path: relative(file), bytes: body.length, sha256: sha256(body) };
  });
}

function recordDigest(records) {
  const canonical = records.map((item) => `${item.path}\0${item.bytes}\0${item.sha256}\n`).join('');
  return sha256(Buffer.from(canonical));
}

function releaseSourceFiles() {
  const exact = [
    'scripts/check_financial_statements.cjs',
    'scripts/check_financial_statement_runtime.cjs',
    'scripts/check_management_report_engine.cjs',
    'scripts/check_tax_report_engine.js',
  'scripts/check_tax_workpaper_adapter.js',
  'scripts/check_reporting_workspace_boundaries.cjs',
    'scripts/check_finance_reporting_profiles.js',
    'scripts/check_canonical_receivables.js',
    'scripts/check_receivables_engine.cjs',
    'scripts/test_reports_release_batch.mjs',
    'scripts/check_document_amount_search.cjs',
    'scripts/check_document_amount_search_browser.cjs',
    'scripts/check_reporting_workspace_amount_search.cjs',
    'scripts/check_history_amount_search.cjs',
    'scripts/test_amount_search_release_batch.mjs',
    'scripts/finance_amount_search_fingerprint.sql',
    'scripts/finance_amount_search_postflight.sql',
    'scripts/finance_amount_search_canary.sql',
    'scripts/check_reporting_workspace_browser.cjs',
    'scripts/finance_reports_20260910_fingerprint.sql',
    'scripts/finance_canonical_receivables_postflight.sql',
    'scripts/finance_canonical_receivables_canary.sql',
    'scripts/finance_reporting_profiles_postflight.sql',
    'scripts/finance_reporting_profiles_canary.sql',
    'scripts/fixtures/finance_receivables_schema_20260910.sql',
    'assets/engines/financial-statements.js',
    'assets/engines/document-search.js',
    'assets/engines/receivables-engine.js',
    'assets/engines/management-report-engine.js',
    'assets/engines/reporting-workspace.js',
    'assets/engines/tax-report-engine.js',
    'assets/styles/reporting-workspace.css',
    'docs/FINANCIAL_STATEMENT_MODEL.md',
    'docs/finance-receivables-contract.md',
    'docs/finance-reporting-contract.md',
    'docs/finance-reporting-implementation.md',
    'docs/reference/taiwan-vat-401-403-404-official-20230831.pdf',

    '.github/workflows/finance-production-release.yml',
    '.github/workflows/stability-gate.yml',
    '.gitignore',
    '.vercelignore',
    'assets/suiyue-logo-transparent.png',
    'assets/templates/hr_expense_template.xlsx',
    'assets/templates/labor_service_fee.docx',
    'docs/FINANCE_PRODUCTION_RELEASE.md',
    'docs/RELEASE_GATES.md',
    'docs/歲悅會計系統_V4修訂重點.html',
    'docs/歲悅會計系統教育訓練手冊_橘色版.docx',
    'docs/歲悅財務管理系統V4_使用教學.pptx',
    'index.html',
    'package.json',
    'pnpm-lock.yaml',
    'privacy.html',
    'scripts/build_www.js',
    'scripts/finance_build_environment.js',
    'scripts/check_environment_isolation_contract.js',
    'scripts/check_finance_production_release_contract.js',
    'scripts/check_release_source_integrity.js',
    'scripts/check_migration_lineage_contract.js',
    'scripts/check_root_cause_regressions.js',
    'scripts/check_release_artifact.js',
    'scripts/check_submission_identity_directory_contract.js',
    'scripts/check_notification_staff_access_reconciliation_contract.js',
    'scripts/check_finance_login_account_switch_contract.js',
    'scripts/check_receipt_attachment_dedup_and_labor_tax.js',
    'scripts/check_membership_org_expense_submission_contract.js',
    'scripts/check_submission_applicant_identity_contract.js',
    'scripts/check_submission_persona_routes.js',
    'scripts/test_expense_route_authority_v2.js',
    'scripts/check_incident_account_org_repair.js',
    'scripts/finance_production_db_fingerprint.sql',
    'scripts/finance_production_db_postflight.sql',
    'scripts/finance_production_db_preflight.sql',
    'scripts/finance_production_authenticated_canary.sql',
    'scripts/finance_production_human_accounting_canary.sql',
    'scripts/finance_production_release_guard.js',
    'scripts/check_approval_postflight.js',
    'scripts/check_procurement_payment_handler.js',
    'scripts/fixtures/finance_procurement_payment_helpers_20260908.sql',
    'scripts/fixtures/finance_finalize_expense_baseline_20260908.sql',
    'scripts/fixtures/finance_finalize_dependencies_20260908.sql',
    'scripts/test_cases_release_batch.mjs',
    'scripts/check_utility_bill_input_tax.js',
    'scripts/check_utility_gross_expense_guard.js',
    'scripts/check_utility_bill_browser.cjs',
    'scripts/check_utility_bill_posting.cjs',
    'scripts/test_utility_release_batch.mjs',
    'scripts/finance_utility_tax_postflight.sql',
    'scripts/finance_utility_tax_canary.sql',
    'scripts/finance_cases_20260908_fingerprint.sql',
    'scripts/finance_finalize_accounting_lines_postflight.sql',
    'scripts/finance_finalize_accounting_lines_canary.sql',
    'scripts/check_finalize_accounting_lines_atomic.js',
    'scripts/test_posted_accounting_view.cjs',
    'scripts/check_attachment_download_names.cjs',
    'scripts/check_attachment_download_browser.cjs',
    'scripts/check_finance_auth_recovery_regressions.js',
    'scripts/check_finance_auth_recovery_browser.cjs',
    'scripts/check_finance_approval_runtime_browser.cjs',
    'scripts/test_current_identity_runtime_sql.mjs',
    'scripts/check_finance_org_regressions.js',
    'scripts/check_procurement_human_event_contract.js',
    'scripts/check_expense_accounting_corrections.js',
    'scripts/check_receipt_atomic_workflow.js',
    'scripts/check_receipt_revenue_compatibility.js',
    'scripts/check_receipt_notification_ui.js',
    'scripts/test_hris_attendance_identity_boundary.mjs',
    'scripts/test_html_render_security.cjs',
    'scripts/test_diagnostic_outbox.cjs',
    'scripts/test_audit_release_batch.mjs',
    'scripts/finance_audit_20260907_fingerprint.sql',
    'scripts/finance_audit_20260907_postflight.sql',
    'scripts/finance_org_integrity_postflight.sql',
    'scripts/finance_approval_audit_postflight.sql',
    'scripts/fixtures/hris_attendance_live_baseline_20260907.sql',
    'scripts/fixtures/finance_procurement_guard_20260907.sql',
    'scripts/fixtures/finance_invoice_revenue_posting_20260908.sql',
    'scripts/fixtures/finance_correction_dependencies_20260907.sql',
    'supabase/config.toml',
    'vercel.json'
  ].map((item) => path.join(ROOT, item));
  const recursive = ['assets/engines', 'assets/styles', 'assets/templates', 'supabase/migrations']
    .flatMap((item) => walk(path.join(ROOT, item)));
  return [...new Set(exact.concat(recursive))].sort((a, b) => relative(a).localeCompare(relative(b)));
}

function expectedBuiltIndex() {
  let html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  const engineDirectory = path.join(ROOT, 'assets/engines');
  const styleDirectory = path.join(ROOT, 'assets/styles');
  const versionedAssets = fs.readdirSync(engineDirectory)
    .filter((file) => file.endsWith('.js'))
    .map((file) => ({ key: `engines/${file}`, file: path.join(engineDirectory, file) }))
    .concat(
      fs.readdirSync(styleDirectory)
        .filter((file) => file.endsWith('.css'))
        .map((file) => ({ key: `styles/${file}`, file: path.join(styleDirectory, file) }))
    )
    .sort((a, b) => a.key.localeCompare(b.key));
  const hash = crypto.createHash('sha256');
  for (const asset of versionedAssets) hash.update(asset.key).update(fs.readFileSync(asset.file));
  html = html.replace(/__FINANCE_ASSET_VERSION__/g, hash.digest('hex').slice(0, 16));
  return applyBuildEnvironment(html, buildConfig);
}

if (!fs.existsSync(OUTPUT) || !fs.statSync(OUTPUT).isDirectory()) fail('www does not exist; build first');
removeGeneratedOsMetadata(OUTPUT);
const builtIndexPath = path.join(OUTPUT, 'index.html');
if (!fs.existsSync(builtIndexPath)) fail('www/index.html is missing');
const builtIndex = fs.readFileSync(builtIndexPath, 'utf8');
if (builtIndex !== expectedBuiltIndex()) fail('www/index.html is not the deterministic build of index.html for the selected build target');
if (/__(?:FINANCE_BUILD_TARGET|FINANCE_SUPABASE_URL|FINANCE_SUPABASE_ANON_KEY)__/.test(builtIndex)) {
  fail('www/index.html still contains a Finance runtime configuration placeholder');
}
if (buildConfig.target !== 'production' && /https:\/\/[a-z0-9-]+\.supabase\.co/i.test(builtIndex)) {
  fail(`${buildConfig.target} artifact contains a Supabase project URL`);
}
if (buildConfig.target !== 'production' && /var\s+SUPABASE_(?:ANON|PUBLISHABLE)_KEY\s*=\s*['"](?:eyJ|sb_)/i.test(builtIndex)) {
  fail(`${buildConfig.target} artifact contains a Supabase browser key`);
}
if (/sb_secret_|service[_-]?role[^\n]{0,80}(?:eyJ|sb_)/i.test(builtIndex)) {
  fail('artifact contains a forbidden Supabase elevated key');
}

const requiredReportArtifacts=["assets/engines/document-search.js","assets/engines/receivables-engine.js","assets/engines/financial-statements.js", "assets/engines/management-report-engine.js", "assets/engines/reporting-workspace.js", "assets/engines/tax-report-engine.js", "assets/styles/reporting-workspace.css", "docs/reference/taiwan-vat-401-403-404-official-20230831.pdf"];
for(const item of requiredReportArtifacts){
  const built=path.join(OUTPUT,item),source=path.join(ROOT,item);
  if(!fs.existsSync(built)||!fs.readFileSync(built).equals(fs.readFileSync(source)))fail('report artifact is missing or differs from its exact source: '+item);
}

const sourceRecords = fileRecords(releaseSourceFiles());
const artifactRecords = fileRecords(walk(OUTPUT, new Set(['www/release-manifest.json'])));
if (!artifactRecords.length) fail('artifact is empty');

const expectedManifest = {
  schema_version: 2,
  contract: 'finance-release-artifact-v2',
  build_target: buildConfig.target,
  runtime_mode: buildConfig.runtimeMode,
  source_commit: gitHead(),
  source_manifest_sha256: recordDigest(sourceRecords),
  artifact_manifest_sha256: recordDigest(artifactRecords),
  root_cause_contract_sha256: sha256(fs.readFileSync(path.join(ROOT, CHECKER_PATH))),
  migration_lineage_contract_sha256: sha256(fs.readFileSync(path.join(ROOT, MIGRATION_CHECKER_PATH))),
  artifact_files: artifactRecords
};

if (args.has('--write-manifest')) {
  fs.writeFileSync(MANIFEST_PATH, `${JSON.stringify(expectedManifest, null, 2)}\n`, { flag: 'w', mode: 0o644 });
  process.stdout.write(`WROTE ${relative(MANIFEST_PATH)}\n`);
}

if (args.has('--verify-manifest')) {
  if (!fs.existsSync(MANIFEST_PATH)) fail('release-manifest.json is missing');
  let actual;
  try { actual = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf8')); }
  catch (error) { fail(`release-manifest.json is invalid: ${error.message}`); }
  if (JSON.stringify(actual) !== JSON.stringify(expectedManifest)) fail('artifact/source/health hashes do not match release-manifest.json');
  if (process.env.VERCEL_ENV === 'production') {
    const vercelSha = String(process.env.VERCEL_GIT_COMMIT_SHA || '');
    if (!/^[0-9a-f]{40}$/.test(vercelSha) || vercelSha !== expectedManifest.source_commit) {
      fail('production artifact is not bound to VERCEL_GIT_COMMIT_SHA');
    }
  }
  process.stdout.write('PASS deterministic source, artifact, and root-cause health hashes\n');
}

if (!args.has('--write-manifest') && !args.has('--verify-manifest')) {
  fail('use --write-manifest or --verify-manifest');
}

process.stdout.write(`FINANCE_RELEASE_ARTIFACT ${JSON.stringify({
  build_target: expectedManifest.build_target,
  runtime_mode: expectedManifest.runtime_mode,
  source_commit: expectedManifest.source_commit,
  source_manifest_sha256: expectedManifest.source_manifest_sha256,
  artifact_manifest_sha256: expectedManifest.artifact_manifest_sha256,
  root_cause_contract_sha256: expectedManifest.root_cause_contract_sha256,
  migration_lineage_contract_sha256: expectedManifest.migration_lineage_contract_sha256,
  artifact_file_count: expectedManifest.artifact_files.length
})}\n`);
