'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),{chromium}=require('playwright');
let browser,context,page;
const root=path.resolve(__dirname,'..'),out=path.resolve(process.argv[2]||'/tmp/finance-admin-action-browser'),session='handler-click-audit-'+process.pid;
fs.mkdirSync(out,{recursive:true});const {applyBuildEnvironment}=require(root+'/scripts/finance_build_environment');const source=fs.readFileSync(root+'/index.html','utf8'),anchor='bootAuthGate();\n\n})();';if(!source.includes(anchor))throw Error('anchor');
const html=applyBuildEnvironment(source,{target:'local',supabaseUrl:'',supabaseAnonKey:''}).replace(anchor,'window.__qa={run:async function(code){return await eval(code)}};\n'+anchor).replace(/<script\b[^>]*src=["']https?:[^>]*><\/script>/gi,'').replace('<head>','<head><meta http-equiv="Content-Security-Policy" content="connect-src \'self\'; form-action \'none\'; img-src \'self\' data: blob:">');
const server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+new URL(req.url,'http://local').pathname);if(file!==root&&!file.startsWith(root+path.sep)){res.writeHead(403);return res.end();}if(file===root||file===root+'/index.html'){res.setHeader('content-type','text/html; charset=utf-8');return res.end(html);}if(!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);return res.end();}res.setHeader('content-type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(file));});
const b=async(command,...args)=>{
 if(command==='open')return page.goto(args[0],{waitUntil:'load'});
 if(command==='set')return page.setViewportSize({width:Number(args[1]),height:Number(args[2])});
 if(command==='click')return page.locator(args[0]).click();
 if(command==='screenshot')return page.screenshot({path:args[0],fullPage:true});
 if(command==='close')return browser.close();
 throw Error('Unknown browser command');
};
async function scope(code){return page.evaluate(code=>window.__qa.run(code),code);}
const roles=['employee','section_chief','dept_manager','ceo','admin_director','accountant','cashier','hr','general_affairs'];const results={scope:'Real shipped local index and engines. Fictional users/documents. Default role configuration; no actual employee login or formal API. Page navigation and handler binding checks, not every mutation.',sourceSha:crypto.createHash('sha256').update(source).digest('hex'),roles,pages:[],runs:[],settings:[]};
const setup=role=>`(function(){USERS=${JSON.stringify(roles.map((r,i)=>({id:'qa-'+r,n:'Fixture '+r,email:r+'@example.invalid',authUserId:'11111111-1111-1111-1111-'+String(i+1).padStart(12,'0'),role:r,rL:r,dc:'D1',eid:'E1',active:true})))};ENTS=[{id:'E1',s:'Fixture Entity',full:'Fixture Entity',active:true}];DEPTS=[{c:'D1',n:'Fixture Dept',eid:'E1',entityCodes:['E1'],newFormEntityCodes:['E1'],isPostingUnit:true,lv:3,active:true}];REQS=[];INVS=[];BILLS=[];NOTIFS=[];VOUCHERS=[];LEDGER=[];DRAFTS=[];ORG_CHART=[];window.__dialogs=[];window.alert=function(x){window.__dialogs.push(String(x))};window.confirm=function(){return false};window.prompt=function(){return null};window.fetch=function(){throw Error('network forbidden by fixture')};quickLogin(${JSON.stringify(role)});return {user:S.user.role,pages:Object.keys(PT)}})()`;
(async()=>{browser=await chromium.launch({headless:true,channel:process.env.FINANCE_BROWSER_CHANNEL||'chrome'});context=await browser.newContext();page=await context.newPage();await context.route('**/*',r=>{const u=new URL(r.request().url());return u.hostname==='127.0.0.1'&&['GET','HEAD'].includes(r.request().method())?r.continue():r.abort();});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,proof={scope:results.scope,sourceSha:results.sourceSha,cases:[]};
try{for(const width of [1440,390]){await b('open',origin);await b('set','viewport',String(width),'1000');await scope(setup('ceo'));await scope(`(function(){window.__clickErrors=[];window.addEventListener('error',function(e){window.__clickErrors.push(e.message)});return true})()`);
for(const [page,tab,fn] of [['orgchart','','financeAdminAction("org")'],['users','','financeAdminAction("permissions")'],['users','health','nav("orgchart")'],['compliance','','financeAdminAction(\'compliance\')'],['health','','financeAdminAction(\'health\')'],['settings','workflows','financeAdminAction(\'workflows\')']]){
await scope('(async function(){await nav('+JSON.stringify(page)+',null);'+(tab?(page==='users'?'mobileUsersTab("health");':'settingsTab('+JSON.stringify(tab)+',null);'):'')+'return true})()');
const state=await scope(`(function(){var candidates=Array.from(el('pg-'+S.page).querySelectorAll('[onclick]')).filter(e=>(e.getAttribute('onclick')||'').startsWith(${JSON.stringify(fn)}));var e=candidates.find(e=>e.getClientRects().length);window.__clickErrors=[];window.__dialogs=[];if(!e)return {found:candidates.length,visible:false};e.setAttribute('data-audit-click','target');return {found:candidates.length,visible:true,label:e.textContent.trim(),handler:e.getAttribute('onclick'),globalType:typeof window[${JSON.stringify(fn.split('(')[0])}]}})()`);
let clickError='';if(state.visible){try{await b('click','[data-audit-click="target"]')}catch(e){clickError=e.message}await scope(`new Promise(r=>setTimeout(()=>r(true),50))`);}const after=await scope(`({errors:window.__clickErrors,dialogs:window.__dialogs,page:S.page})`);await scope(`(function(){document.querySelectorAll('[data-audit-click]').forEach(e=>e.removeAttribute('data-audit-click'));return true})()`);const row={width,page,tab,fn,...state,...after,clickError};proof.cases.push(row);if(state.visible&&(after.errors.length||clickError||state.globalType!=='function'))throw Error('Admin action failed: '+JSON.stringify(row));if(!state.visible&&!(width===390&&fn.includes('permissions')))throw Error('Expected visible admin action '+JSON.stringify(row));fs.writeFileSync(out+'/evidence.json',JSON.stringify(proof,null,2));console.log(JSON.stringify(row));
}
await b('screenshot',out+'/last-'+width+'.png');}
await scope(setup('employee'));const denied=await scope('(async function(){S.user=USERS.find(u=>u.role==="employee");CURRENT_PERMISSION_SNAPSHOT={loaded:true,permissions:[{permission_code:"member.role.manage",effect:"deny"}]};var calls=0;syncFrontOfficePermissionRuntime=async function(){calls++;};var r=await financeAdminAction("permissions");return {denied:r.denied,calls:calls}})()');if(!denied.denied||denied.calls)throw Error('Employee permission sync was not denied');proof.denied=denied;proof.done=true;fs.writeFileSync(out+'/evidence.json',JSON.stringify(proof,null,2));
}finally{await b('close').catch(()=>{});server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
