#!/usr/bin/env node
'use strict';
// Real inline history loader and input/pager handlers with a deterministic clock.
// Only transport/render dependencies are fictional; no live identity or data.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(process.env.FINANCE_HISTORY_SOURCE||path.resolve(__dirname,'../index.html'),'utf8');
const block=html.slice(html.indexOf('function approvalHistoryIdentity(){'),html.indexOf('function financeReadSourceSnapshot('));
const fn=name=>{const start=html.indexOf('function '+name+'(');assert(start>=0,name);return html.slice(start,html.indexOf('\n}',start)+2);};
const handler=name=>{const start=html.indexOf('window.'+name+'=function(');assert(start>=0,name);return html.slice(start,html.indexOf('\n};',start)+3);};
const flush=async()=>{for(let i=0;i<4;i++)await new Promise(resolve=>setImmediate(resolve));};
let checks=0,failures=[];
async function test(name,run){try{await run();checks++;console.log('PASS '+name);}catch(error){failures.push(name+': '+error.message);console.error('FAIL '+name+': '+error.message);}}
function fixture(){
 let now=0,next=0;const timers=new Map();
 const c={window:{},Promise,Date,Number,String,Object,Array,Math,JSON,Error,AbortController,console:{warn(){},error(){}},
  setTimeout(fn,delay){const id=++next;timers.set(id,{fn,at:now+delay});return id;},clearTimeout(id){timers.delete(id);},
  S:{user:{id:'FICTION',authUserId:'AUTH'},page:'approvals',aT:'h',apprPage:1,apprQuery:'',demoLogin:false},REQS:[],BILLS:[],INVS:[],calls:[],paint:[],env:'test',tenant:'T',financeWorkspaceIdentityBlocked:false,financeAuthIdentityEpoch:1,approvalHistorySearchTimer:null,
  APPROVAL_HISTORY_RUNTIME:{identity:'',status:'idle',items:[],total:0,allTotal:0,page:1,limit:50,query:'',error:'',updatedAt:'',promise:null,requestSeq:0}};
 Object.assign(c,{approvalFastBootstrapIdentity:()=>c.tenant+'|auth:'+c.S.user?.authUserId,currentTenantId:()=>c.tenant,activeDataEnvironment:()=>c.env,DEFAULT_TENANT_ID:'T',
  getSb:()=>({rpc:(name,args)=>{assert.equal(name,'finance_approval_participant_history_for_current_user');let resolve;const result=new Promise(r=>resolve=r),call={args:JSON.parse(JSON.stringify(args)),resolve,aborts:0};c.calls.push(call);return{abortSignal(signal){call.signal=signal;signal.addEventListener('abort',()=>call.aborts++);return this;},then(ok,bad){return result.then(ok,bad);}};}}),
  updateApprovalTodoBadge:()=>{},buildApprovals:()=>c.paint.push(c.APPROVAL_HISTORY_RUNTIME.status),remoteReadIssueText:e=>e.message,recordRemoteReadIssue:()=>{},escAttr:x=>String(x),el:()=>null,mapReq:x=>({...x}),mapBill:x=>({...x}),mapInv:x=>({...x}),mergeRemoteRowsByKey:(a,b)=>[...a,...b.filter(x=>!a.some(y=>x.id===y.id))]});
 vm.createContext(c);vm.runInContext(fn('withOperationTimeout')+'\n'+block+'\n'+handler('apprSearch')+'\n'+handler('apprPage'),c);
 c.advance=async ms=>{const end=now+ms;for(;;){const due=[...timers].filter(([,t])=>t.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!due)break;now=due[1].at;timers.delete(due[0]);due[1].fn();await flush();}now=end;await flush();};
 c.respond=async(index,options={})=>{const call=c.calls[index];assert(call,'dispatched request '+index);call.resolve(options.error?{error:options.error}:{data:payload(c,call.args,options)});await flush();};
 return c;
}
function payload(c,args,{id='R',total=1,all=total}={}){const offset=args.p_offset;return{ok:true,identity:{finance_user_id:c.S.user.id,auth_user_id:c.S.user.authUserId,tenant_id:c.tenant,data_environment:c.env},total,all_total:all,page:{limit:50,offset,has_more:offset+50<total},items:Array.from({length:Math.min(50,Math.max(0,total-offset))},(_,n)=>({record_type:'expense_requests',kind:'req',record_id:id+(offset+n),history_key:'expense_requests:'+id+(offset+n),source_rows:[{id:id+(offset+n),tenant_id:c.tenant,data_environment:c.env}],personally_acted:true}))};}
async function seed(c,query=''){c.S.apprQuery=query;const p=c.loadApprovalHistoryPage({query});await flush();await c.respond(c.calls.length-1,{id:'VERIFIED',total:123});assert((await p).ok);}
(async()=>{
 await test('same-signature forced retries join the original request and deadline',async()=>{const c=fixture(),first=c.loadApprovalHistoryPage();await flush();const second=c.window.loadApprovalHistoryPage({force:true}),third=c.window.loadApprovalHistoryPage({force:true});await flush();assert.equal(c.calls.length,1);assert.equal(c.calls[0].aborts,0);assert.equal(first,second);assert.equal(second,third);await c.respond(0);assert((await first).ok);});
 await test('retry at 11 seconds cannot extend the original 12 second deadline',async()=>{const c=fixture(),first=c.loadApprovalHistoryPage();await flush();await c.advance(11000);const retry=c.window.loadApprovalHistoryPage({force:true});await c.advance(1000);assert.equal(c.calls.length,1);assert.equal(first,retry);assert.equal(c.APPROVAL_HISTORY_RUNTIME.status,'error');assert.equal(c.calls[0].aborts,1);assert(!(await first).ok);});
 await test('typing aborts/invalidate old search before the debounce timer fires',async()=>{const c=fixture();c.S.apprQuery='舊';const old=c.loadApprovalHistoryPage({query:'舊'});await flush();c.window.apprSearch('自費');assert.equal(c.calls[0].aborts,1);await c.respond(0,{id:'LATE'});assert((await old).stale);assert.equal(c.REQS.length,0);assert.equal(c.APPROVAL_HISTORY_RUNTIME.query,'自費');});
 await test('rapid text changes dispatch only the final query after 250ms quiet',async()=>{const c=fixture();c.window.apprSearch('自');await c.advance(100);c.window.apprSearch('自費');await c.advance(249);assert.equal(c.calls.length,0);await c.advance(1);assert.equal(c.calls.length,1);assert.equal(c.calls[0].args.p_search,'自費');await c.respond(0,{id:'MATCH',total:2,all:123});assert.equal(c.APPROVAL_HISTORY_RUNTIME.total,2);assert.equal(c.APPROVAL_HISTORY_RUNTIME.allTotal,123);});
 await test('a cold search sets pending state before render can bootstrap an empty query',async()=>{const c=fixture();c.buildApprovals=()=>{if(c.APPROVAL_HISTORY_RUNTIME.status==='idle')c.loadApprovalHistoryPage({query:''});};c.window.apprSearch('自費');await flush();assert.equal(c.calls.length,0);assert.equal(c.APPROVAL_HISTORY_RUNTIME.status,'loading');await c.advance(250);assert.equal(c.calls.length,1);assert.equal(c.calls[0].args.p_search,'自費');});
 await test('Chinese IME composition never dispatches unfinished text',async()=>{const c=fixture();c.window.apprSearch('自',{isComposing:true});await c.advance(400);assert.equal(c.calls.length,0);c.window.apprSearch('自費',{isComposing:true});await c.advance(400);assert.equal(c.calls.length,0);c.window.apprSearch('自費');await c.advance(250);assert.equal(c.calls.length,1);assert.equal(c.calls[0].args.p_search,'自費');});
 await test('IME input DOM is actually wired to input/composition events',async()=>{const tag=html.match(/<input\b[^>]*id="appr-q"[^>]*>/)[0];assert(tag.includes('apprSearch(this.value,event)'));assert(tag.includes('oncompositionstart='));assert(tag.includes('oncompositionend='));});
 await test('repeating equivalent input reuses the complete verified result',async()=>{const c=fixture();await seed(c,'自費');c.window.apprSearch('  自費  ');await c.advance(500);assert.equal(c.calls.length,1);assert.equal(c.APPROVAL_HISTORY_RUNTIME.status,'ready');assert.equal(c.APPROVAL_HISTORY_RUNTIME.total,123);});
 await test('repeating input after error does not create an automatic retry loop',async()=>{const c=fixture();c.S.apprQuery='自費';c.loadApprovalHistoryPage({query:'自費'});await flush();await c.respond(0,{error:{code:'57014',message:'canceling statement due to statement timeout'}});c.window.apprSearch('自費');await c.advance(500);assert.equal(c.calls.length,1);assert.equal(c.APPROVAL_HISTORY_RUNTIME.status,'error');});
 await test('explicit retry before debounce takes ownership without a duplicate request',async()=>{const c=fixture();c.window.apprSearch('自費');const pending=c.window.loadApprovalHistoryPage({force:true});await flush();await c.advance(250);assert.equal(c.calls.length,1);assert.equal(c.calls[0].aborts,0);await c.respond(0);assert((await pending).ok);});
 for(const change of ['tab','page','user','auth','tenant','environment','lock','epoch'])await test('queued input cannot query after '+change+' changed',async()=>{const c=fixture();c.window.apprSearch('自費');if(change==='tab')c.S.aT='p';if(change==='page')c.S.page='dashboard';if(change==='user')c.S.user.id='OTHER';if(change==='auth')c.S.user.authUserId='OTHER';if(change==='tenant')c.tenant='OTHER';if(change==='environment')c.env='production';if(change==='lock')c.financeWorkspaceIdentityBlocked=true;if(change==='epoch')c.financeAuthIdentityEpoch++;await c.advance(500);assert.equal(c.calls.length,0);});
 await test('leaving and returning to history safely starts its current query',async()=>{const c=fixture();c.window.apprSearch('自費');c.S.aT='p';await c.advance(300);c.S.aT='h';const p=c.ensureApprovalHistoryCurrent({page:1});await flush();assert.equal(c.calls.length,1);assert.equal(c.calls[0].args.p_search,'自費');await c.respond(0);assert((await p).ok);});
 await test('pager double click shares exactly one page request',async()=>{const c=fixture();await seed(c);c.window.apprPage(2);await flush();c.window.apprPage(2);await flush();assert.equal(c.calls.length,2);assert.equal(c.calls[1].aborts,0);await c.respond(1,{total:123});assert.equal(c.APPROVAL_HISTORY_RUNTIME.page,2);assert.equal(c.APPROVAL_HISTORY_RUNTIME.items.length,50);});
 await test('pager cannot be overwritten by a previously queued search',async()=>{const c=fixture();await seed(c);c.window.apprSearch('自費');c.window.apprPage(2);await flush();await c.advance(250);assert.equal(c.calls.length,2);assert.equal(c.calls[1].args.p_offset,50);await c.respond(1,{total:123});assert.equal(c.APPROVAL_HISTORY_RUNTIME.page,2);});
 await test('same-query refresh failure keeps verified rows/count and requires explicit retry',async()=>{const c=fixture();await seed(c,'自費');c.loadApprovalHistoryPage({force:true});await flush();await c.respond(1,{error:{code:'57014',message:'timeout'}});assert.equal(c.APPROVAL_HISTORY_RUNTIME.items.length,50);assert.equal(c.APPROVAL_HISTORY_RUNTIME.total,123);assert.equal(c.APPROVAL_HISTORY_RUNTIME.status,'error');assert(c.approvalHistoryStatusHtml().includes('重新載入'));});
 await test('new-query failure does not claim old results are current or report successful empty',async()=>{const c=fixture();await seed(c,'舊');c.window.apprSearch('自費');await c.advance(250);await c.respond(1,{error:{code:'57014',message:'timeout'}});assert.equal(c.APPROVAL_HISTORY_RUNTIME.items.length,0);assert.equal(c.APPROVAL_HISTORY_RUNTIME.status,'error');assert.equal(c.APPROVAL_HISTORY_RUNTIME.query,'自費');});
 await test('verified zero matches remains distinct from failure and preserves all-history count',async()=>{const c=fixture();c.window.apprSearch('不存在');await c.advance(250);await c.respond(0,{total:0,all:123});assert.equal(c.APPROVAL_HISTORY_RUNTIME.status,'ready');assert.equal(c.APPROVAL_HISTORY_RUNTIME.total,0);assert.equal(c.APPROVAL_HISTORY_RUNTIME.allTotal,123);assert(c.APPROVAL_HISTORY_RUNTIME.updatedAt);});
 await test('literal text/amount query stays unchanged and is never filtered on the current page',async()=>{const c=fixture();const query='自費 NT$ 1,250.00';c.window.apprSearch(query);await c.advance(250);assert.equal(c.calls[0].args.p_search,query);await c.respond(0,{total:51,all:123});assert.equal(c.APPROVAL_HISTORY_RUNTIME.items.length,50);assert.equal(c.APPROVAL_HISTORY_RUNTIME.total,51);assert.equal(c.calls[0].args.p_data_environment,'test');});
 await test('late same-person response after reauthentication cannot enter source cache',async()=>{const c=fixture(),old=c.loadApprovalHistoryPage();await flush();c.financeAuthIdentityEpoch++;await c.respond(0,{id:'OLD'});assert((await old).stale);assert.equal(c.REQS.length,0);});
 console.log('History search: '+checks+' passed, '+failures.length+' failed.');if(failures.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
