'use strict';
// Local actual loader / page / runtime diagnostics with fictional read transport.
// Usage: node scripts/check_startup_read_coordination_browser.cjs /tmp/evidence [baseline-index.html]
// agent-browser is required. A baseline is optional; no production calls/login.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{execFile}=require('node:child_process'),{promisify}=require('node:util');
const run=promisify(execFile),root=path.resolve(__dirname,'..'),out=path.resolve(process.argv[2]||'/tmp/finance-startup-evidence-20260913'),source=fs.readFileSync(path.join(root,'index.html'),'utf8'),baseline=process.argv[3]?fs.readFileSync(process.argv[3],'utf8'):null,session='finance-startup-'+process.pid;
assert(!out.startsWith(root+path.sep));const {applyBuildEnvironment}=require('./finance_build_environment');
let activeSource=source;function html(){let h=applyBuildEnvironment(activeSource,{target:'local',supabaseUrl:'',supabaseAnonKey:''}),anchor='bootAuthGate();\n\n})();';assert(h.includes(anchor));return h.replace(anchor,'window.__startupQA={run:async function(code){return await eval(code)}};\n'+anchor).replace(/<script\b[^>]*src=["']https?:[^>]*><\/script>/gi,'').replace('<head>','<head><meta http-equiv="Content-Security-Policy" content="connect-src \'self\'; form-action \'none\'">');}
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(p!==root&&!p.startsWith(root+path.sep)){res.writeHead(403);return res.end();}if(p===root||p===path.join(root,'index.html')){res.setHeader('content-type','text/html; charset=utf-8');return res.end(html());}if(!fs.existsSync(p)||!fs.statSync(p).isFile()){res.writeHead(404);return res.end();}res.setHeader('content-type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(p));});
const b=async(...args)=>(await run(process.env.AGENT_BROWSER_BIN||'agent-browser',['--session',session,...args],{maxBuffer:12e6,timeout:45000})).stdout;
async function scope(code){let v=JSON.parse(await b('eval','--base64',Buffer.from('(async()=>JSON.stringify(await window.__startupQA.run('+JSON.stringify(code)+')))()').toString('base64')));return typeof v==='string'?JSON.parse(v):v;}
const setup=`(function(){
USERS=[{id:'qa-accountant',n:'許晴川',email:'qa@example.invalid',authUserId:'10000000-0000-0000-0000-000000000001',role:'accountant',rL:'會計',eid:'F1',dc:'D1',active:true},{id:'qa-chief',n:'林星河',role:'ceo',eid:'F1',dc:'D1',active:true}];ENTS=[{id:'F1',s:'星河照護',full:'星河照護股份有限公司',active:true}];DEPTS=[{c:'D1',n:'行政課',eid:'F1',entityCodes:['F1'],newFormEntityCodes:['F1'],lv:3,active:true,isPostingUnit:true}];REQS=[];INVS=[];BILLS=[];NOTIFS=[];VOUCHERS=[];LEDGER=[];DRAFTS=[];ORG_CHART=[];quickLogin('accountant');S.user.authUserId=USERS[0].authUserId;S.demoLogin=false;
window.__trace=[];window.__active=0;window.__maxActive=0;window.__wide=0;window.__maxWide=0;window.__repaired=0;window.__now=performance.now();window.__deferred=null;window.__mode='ok';window.__notificationCount=0;
window.fetch=function(){throw Error('No network in fixture')};window.alert=function(){};
var data={expense_requests:[{id:'fixture-r1',no:'FIXTURE-001',tenant_id:currentTenantId(),data_environment:activeDataEnvironment(),entity_id:'F1',department_code:'D1',applicant_id:'qa-accountant',applicant:'許晴川',type:'payment_request',amount:1050,status:'completed',description:'虛構採購付款',steps:[],request_date:'2026-09-13'}],invoices:[],bills:[],ledger_entries:[{id:'fixture-l1',tenant_id:currentTenantId(),data_environment:activeDataEnvironment(),entity_id:'F1',department_code:'D1',source_id:'fixture-r1',source_type:'expense',entry_date:'2026-09-13',account_code:'6207',account_name:'文具用品',debit:1050,credit:0},{id:'fixture-l2',tenant_id:currentTenantId(),data_environment:activeDataEnvironment(),entity_id:'F1',department_code:'D1',source_id:'fixture-r1',source_type:'expense',entry_date:'2026-09-13',account_code:'1112',account_name:'銀行存款',debit:0,credit:1050}],notifications:[],vouchers:[]};
var small=['finance_users','notifications','system_settings','draft_requests','finance_portal_roles','bank_accounts'];
async function read(name,payload){var wide=small.indexOf(name)<0&&name.indexOf('finance_org_')!==0&&name.indexOf('runtime_health')<0;var entry={name:name,started:performance.now()-window.__now};window.__trace.push(entry);window.__active++;if(wide)window.__wide++;window.__maxActive=Math.max(window.__maxActive,window.__active);window.__maxWide=Math.max(window.__maxWide,window.__wide);try{await new Promise(function(resolve){setTimeout(resolve,60)});if(window.__mode==='error'&&name==='finance_org_department_list')return{data:null,error:{code:'42501',message:'虛構測試：診斷暫時無法讀取'}};return payload;}finally{window.__active--;if(wide)window.__wide--;entry.ended=performance.now()-window.__now;}}
getSb=function(){return{from:function(table){var from=0,to=999;return{select:function(){return this},eq:function(){return this},in:function(){return this},order:function(){return this},limit:function(n){to=n-1;return this},range:function(a,b){from=a;to=b;return this},abortSignal:function(){return this},then:function(resolve,reject){if(table==='notifications')window.__notificationCount++;var rows=data[table]||[];return read(table,{data:rows.slice(from,to+1),count:rows.length,error:null}).then(resolve,reject)}}},rpc:function(name){var payload={ok:true};if(name==='finance_org_employee_role_list')payload=[{finance_user_id:'qa-accountant',role_key:'accountant',department_code:'D1',role_type:'primary',is_primary:true,active:true}];else if(name==='finance_org_department_list'||name==='finance_org_position_list')payload=[];else if(name==='finance_org_chart_editor_state_v2')payload={revision:'fixture-revision',rows:[]};else if(name==='finance_payment_concern_read_v1')payload={ok:true,rows:[],limit:100,canReport:false};return read(name,{data:payload,error:null});}}};
hasSupabase=function(){return true};syncRemoteFinanceUsersDirectory=async function(){return{ok:true,cached:true,users:USERS}};
financeUsersDirectoryAuthUserId=S.user.authUserId;financeUsersDirectoryReadyAt=new Date().toISOString();financeUsersDirectoryLastError='';
// The production permission and organization RPCs are separate SQL suites. Only
// their fixture responses are fixed; no read cache authorizes a test mutation.
financeUserRuntimeReadiness=function(){return{ok:true,warnings:[]}};repairCurrentFinanceIdentityRuntime=async function(){window.__repaired++;throw Error('A ready fixture must never auto-repair')};
refreshMembershipOrgGraph=async function(){return true};refreshCurrentPermissionSnapshotRuntime=async function(){return true};refreshWorkflowAdminHealth=async function(){return true};
recordOpsEvent=function(){};recordOpsEventDedup=function(){};ensureRemoteDashboardAggregate=function(){return false};scheduleRemoteRecovery=function(){};
applySystemSettings=function(){};normalizeRequestFlows=function(){};startRealtime=function(){};restoreFinanceAuthRecoveryDraft=async function(){return false};
APPROVAL_FAST_BOOTSTRAP={identity:approvalFastBootstrapIdentity(),hydrated:false,verified:false,tasksVerified:false,summaryItems:[],summaryFingerprint:'',verifiedSummaryFingerprint:''};S.approvalRuntimeTasks=[];ORG_ADMIN_RUNTIME.available=null;
window.__originalDeferred=scheduleDeferredFinanceRuntimeRefresh;scheduleDeferredFinanceRuntimeRefresh=function(id){window.__deferred=id};
window.__originalTimeout=withOperationTimeout;withOperationTimeout=function(p,label,ms){return window.__originalTimeout(p,label,window.__mode==='timeout'&&/診斷|登入組織資料/.test(label)?80:ms)};
return true;})()`;
const evidence={scope:'Local actual broad loader and diagnostics; fixed 60ms fictional read latency; no real login or production API. These are controlled pipeline timings, not production user timing.',runs:[]};
async function scenario(label,src){activeSource=src;await b('open','http://127.0.0.1:'+server.address().port);await b('set','viewport','1440','1000');await scope(setup);
 const result=await scope(`(async function(){await loadFinanceNotifications();var started=performance.now();var broad=await performRemoteDataLoad();var broadMs=performance.now()-started;buildAll({pageOnly:true});var firstRender=performance.now()-started;var broadTrace=window.__trace.slice(),broadMaxActive=window.__maxActive,broadMaxWide=window.__maxWide;window.__originalDeferred(window.__deferred);await runCurrentUserRuntimeAssurance({silent:true});await new Promise(function(resolve){setTimeout(resolve,350)});buildAll({pageOnly:true});return{ok:broad,broadMs:broadMs,firstRenderMs:firstRender,fullMs:performance.now()-started,notificationReads:window.__notificationCount,orgReads:window.__trace.filter(function(x){return /^finance_org_(department_list|position_list|employee_role_list|admin_health)$|^finance_(front_office_permission_runtime_health|department_runtime_health)$/.test(x.name)}).length,maxActive:window.__maxActive,maxWide:window.__maxWide,broadMaxActive:broadMaxActive,broadMaxWide:broadMaxWide,broadTrace:broadTrace,trace:window.__trace,sourceCompleteness:statementDataCompleteness(),requests:REQS.length,ledger:LEDGER.length,repairs:window.__repaired,notification:financeNotificationView().summary,assurance:ACCOUNT_RUNTIME_ASSURANCE_STATE.ok};})()`);
 result.label=label;result.sourceHash=crypto.createHash('sha256').update(src).digest('hex');evidence.runs.push(result);assert(result.ok&&result.requests===1&&result.ledger===2&&result.sourceCompleteness.complete&&result.assurance);assert.equal(result.repairs,0);for(const width of [1440,390]){await b('set','viewport',String(width),width===390?'844':'1000');assert.equal(await scope('document.documentElement.scrollWidth>innerWidth+1'),false);await b('screenshot',path.join(out,label+'-'+width+'.png'));}assert.equal((await b('errors')).trim(),'');console.log('PASS '+label+' broad '+Math.round(result.broadMs)+'ms, first render '+Math.round(result.firstRenderMs)+'ms, full '+Math.round(result.fullMs)+'ms, org RPCs '+result.orgReads+', notifications '+result.notificationReads);return result;}
(async()=>{fs.mkdirSync(out,{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));if(baseline)await scenario('before',baseline);const after=await scenario('after',source);assert.equal(after.orgReads,6);assert.equal(after.notificationReads,1);assert(after.broadMaxWide<=1);assert(after.broadMaxActive<=2);if(baseline){const before=evidence.runs[0];assert(after.broadMs<before.broadMs*0.9,'small reads overlap without two wide financial reads');assert(after.orgReads<before.orgReads);assert.deepEqual(after.broadTrace.filter(x=>x.name!=='notifications').map(x=>x.name).sort(),before.broadTrace.filter(x=>x.name!=='notifications').map(x=>x.name).sort(),'same complete source reads');}
 // A failed queue remains visibly unverified; hidden page builds do not start it.
 await scope(`(function(){FinancePaymentConcerns.suspend();S.page='dashboard';window.__queueReads=0;var old=getSb;getSb=function(){return{rpc:async function(){window.__queueReads++;return{error:{message:'虛構測試：待辦連線中斷'}};}}};window.__queueOld=old;return true;})()`);await scope('(async function(){await FinancePaymentConcerns.loadQueue();return true;})()');assert.equal(await scope('window.__queueReads'),0);await scope(`(async function(){S.demoLogin=true;nav('approvals',null);S.demoLogin=false;await FinancePaymentConcerns.loadQueue();await FinancePaymentConcerns.loadQueue();return true;})()`);assert.equal(await scope('window.__queueReads'),1);assert.match(await scope("el('payment-concern-queue').innerText"),/連線中斷|重試/);await b('scrollintoview','#payment-concern-queue');await b('screenshot',path.join(out,'queue-failure-390.png'));await scope(`(async function(){getSb=window.__queueOld;await FinancePaymentConcerns.loadQueue(true);return true;})()`);assert.match(await scope("el('payment-concern-queue').innerText"),/未結疑義 0 筆/);
 const actualSource=fs.readFileSync(path.join(root,'index.html'),'utf8');assert.equal(actualSource,source);evidence.ok=true;if(fs.existsSync(path.join(out,'failure.json')))fs.unlinkSync(path.join(out,'failure.json'));fs.writeFileSync(path.join(out,'evidence.json'),JSON.stringify(evidence,null,2));console.log('PASS startup pipeline and visible queue failure: '+out);
})().catch(e=>{console.error(e);fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify({error:e.message,evidence},null,2));process.exitCode=1;}).finally(async()=>{await b('close').catch(()=>{});server.close();});
