const assert=require('node:assert/strict');
const {create,ttl}=require('../assets/engines/diagnostic-outbox-engine.js');
let now=Date.parse('2026-09-07T12:00:00Z'),saved='';
const storage={getItem:()=>saved,setItem:(key,value)=>saved=value};
const a={owner:'auth-a',tenantId:'tenant-a',dataEnv:'production'},b={...a,owner:'auth-b'},c={...a,tenantId:'tenant-b'};
let box=create(storage,()=>now);
const event={id:'ops-1',time:new Date(now).toISOString(),type:'auth_recovery',severity:'warn',page:'newreq',meta:{code:'JWT_EXPIRED',token:'secret'},user:'private@example.com',detail:'私人單據資料',remoteAuditStatus:'failed'};
assert.equal(box.save([event],a),true);
assert.equal(saved.includes('private'),false);assert.equal(saved.includes('secret'),false);assert.equal(saved.includes('私人'),false);
box=create(storage,()=>now);assert.equal(box.pending(a).length,1);assert.equal(box.pending(b).length,0);assert.equal(box.pending(c).length,0);
assert.equal(box.pending(a)[0].code,'JWT_EXPIRED');
box.save([{...event,id:'ops-2'}],b);box.save([{...event,remoteAuditStatus:'synced'}],a);
assert.equal(box.pending(a).length,0);assert.equal(box.pending(b).length,1);
box.save(Array.from({length:120},(_,i)=>({...event,id:'ops-'+i})),a);assert.equal(JSON.parse(saved).length,100);
box.clear(b);assert.equal(box.pending(b).length,0);assert.ok(box.pending(a).length>0);
now+=ttl+1;assert.equal(box.pending(a).length,0);
saved='{bad';assert.deepEqual(box.pending(a),[]);
const broken=create({getItem(){throw Error('denied');},setItem(){throw Error('quota');}},()=>now);
assert.equal(broken.save([{...event,time:new Date(now).toISOString()}],a),false);
assert.equal(box.save([event],{}),false);
console.log('PASS diagnostic outbox: minimal fields, reload, account/tenant isolation, acknowledgement, retention, quota and corrupt storage');
