import {PGlite}from'@electric-sql/pglite';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{randomUUID}from'node:crypto';
const db=new PGlite();const user=randomUUID(),other=randomUUID(),sid=randomUUID(),otherSid=randomUUID(),tenant=randomUUID();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create table auth.identities(id uuid,user_id uuid,provider text,provider_id text,identity_data jsonb,created_at timestamptz default now());create table auth.sessions(id uuid primary key,user_id uuid,not_after timestamptz);create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;create function auth.uid() returns uuid language sql stable as $$select nullif(auth.jwt()->>'sub','')::uuid$$;create table public.finance_users(id text,name text,email text,tenant_id uuid,active boolean,auth_user_id uuid,google_link_status text,created_at timestamptz default now());create function public.current_tenant_id()returns uuid language sql stable as $$select nullif(current_setting('app.current_tenant_id',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.jwt(),auth.uid() to authenticated;`);
const source=await readFile(new URL('fixtures/finance_statement_source_authority_20260913.sql',import.meta.url),'utf8');
for(const name of ['finance_verified_google_email','current_finance_user','finance_current_verified_google_email_v2']){const start=source.indexOf('CREATE OR REPLACE FUNCTION public.'+name+'(');const end=source.indexOf('$function$;',start)+'$function$;'.length;await db.exec(source.slice(start,end));}
await db.exec(await readFile(new URL('../supabase/migrations/20260927180201_finance_portal_session_logout.sql',import.meta.url),'utf8'));
for(const[id,email,subject]of[[user,'qa@suiyuecare.com','synthetic-sub'],[other,'other@suiyuecare.com','other-sub']]){await db.query('insert into auth.users values($1,$2,now())',[id,email]);await db.query("insert into auth.identities values($1,$2,'google',$3,$4,now())",[randomUUID(),id,subject,{sub:subject,email,email_verified:true}]);}
await db.query('insert into auth.sessions values($1,$2,null),($3,$4,null)',[sid,user,otherSid,other]);await db.query("insert into finance_users(id,name,email,tenant_id,active,auth_user_id,google_link_status)values('qa','Synthetic','qa@suiyuecare.com',$1,true,$2,'bound')",[tenant,user]);
async function asUser(sessionId,work){await db.exec('begin');try{await db.query("select set_config('request.jwt.claims',$1,true),set_config('app.current_tenant_id',$2,true)",[JSON.stringify({sub:user,session_id:sessionId,role:'authenticated'}),tenant]);await db.exec('set local role authenticated');const r=await work();await db.exec('commit');return r;}catch(e){await db.exec('rollback');throw e;}}
assert.equal((await asUser(sid,()=>db.query('select (public.current_finance_user()).id id'))).rows[0].id,'qa');
for(const wrong of[null,otherSid,'wrong'])assert.equal((await asUser(wrong,()=>db.query('select (public.current_finance_user()).id id,public.finance_current_verified_google_email_v2() email'))).rows[0].id,null);
await assert.rejects(()=>asUser(sid,()=>db.query("select public.portal_revoke_google_sessions('synthetic-sub','qa@suiyuecare.com')")),/permission denied/);
await db.exec('begin;set local role service_role');await db.query("select public.portal_revoke_google_sessions('different-sub','qa@suiyuecare.com')");await db.exec('commit');assert.equal((await db.query('select count(*)::int n from auth.sessions')).rows[0].n,2);
await db.exec('begin;set local role service_role');const revoked=(await db.query("select public.portal_revoke_google_sessions('synthetic-sub','qa@suiyuecare.com') v")).rows[0].v;await db.exec('commit');assert.equal(revoked.revoked,true);assert.equal((await db.query('select count(*)::int n from auth.sessions')).rows[0].n,1);
assert.equal((await asUser(sid,()=>db.query('select (public.current_finance_user()).id id,public.finance_current_verified_google_email_v2() email'))).rows[0].id,null);await assert.rejects(()=>asUser(sid,()=>db.query('select public.portal_session_status()')),/FINANCE_AUTH_SESSION_REVOKED/);
await db.exec((await readFile(new URL('finance_portal_session_logout_postflight.sql',import.meta.url),'utf8')).replace(/^\\set ON_ERROR_STOP on\n/,''));
const seals=(await db.query("select md5(pg_get_functiondef('public.current_finance_user()'::regprocedure)) current_seal,md5(pg_get_functiondef('public.finance_current_verified_google_email_v2()'::regprocedure)) read_seal,(select md5(prosrc)from pg_proc where oid='public.current_finance_user()'::regprocedure) current_prosrc,(select md5(prosrc)from pg_proc where oid='public.finance_current_verified_google_email_v2()'::regprocedure) read_prosrc,md5(pg_get_functiondef('public.finance_auth_session_active()'::regprocedure)) session_seal,md5(pg_get_functiondef('public.portal_session_status()'::regprocedure)) status_seal,md5(pg_get_functiondef('public.portal_revoke_google_sessions(text,text)'::regprocedure)) revoke_seal")).rows[0];console.log(JSON.stringify({verified:true,seals}));await db.close();
