// Synthetic browser -> real SQL posting -> ledger -> callback. No live data/banking.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import http from 'node:http';
const db=new PGlite();let checks=0;
const eq=(a,b,msg)=>{assert.deepEqual(a,b,msg);checks++};
const reject=async(fn,pattern)=>{await assert.rejects(fn,pattern);checks++};
const tenant=randomUUID(),employer=randomUUID(),applicant=randomUUID(),accountant=randomUUID(),director=randomUUID(),ceo=randomUUID();
async function role(name,id=''){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec(`set role ${name}`);}
async function rpc(name,args={}){return(await db.query(`select public.${name}(${Object.keys(args).map((k,i)=>`${k}=>$${i+1}`).join(',')}) r`,Object.values(args))).rows[0].r;}
const ev=k=>({kind:k,reference:'SYNTHETIC',sha256:'a'.repeat(64),...(['bank_batch_validation','bank_upload','bank_disbursement'].includes(k)?{totalNetCents:123456}:{})});
try {
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema private;grant usage on schema auth to authenticated,service_role;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table public.finance_users(id text primary key,tenant_id uuid,auth_user_id uuid,name text,active boolean,role text);
create function public.current_finance_user() returns public.finance_users language sql stable security definer set search_path='' as $$select f from public.finance_users f where auth_user_id=auth.uid() and active$$;
create function public.current_finance_user_id() returns text language sql stable as $$select (public.current_finance_user()).id$$;
create function public.current_tenant_id() returns uuid language sql stable as $$select (public.current_finance_user()).tenant_id$$;
create function public.current_finance_user_name() returns text language sql stable as $$select (public.current_finance_user()).name$$;
create function private.finance_require_authenticated_tenant() returns uuid language sql stable as $$select public.current_tenant_id()$$;
create function public.current_finance_role() returns text language sql stable as $$select (public.current_finance_user()).role$$;
create function public.finance_current_verified_google_email_v2() returns text language sql stable as $$select case when auth.uid() is not null then 'synthetic@example.invalid' end$$;
create function public.is_finance_accounting() returns boolean language sql stable as $$select public.current_finance_role() in('accountant','ceo','admin_director')$$;
create function private.finance_expense_optional_permission_allows(uuid,text,text,jsonb) returns boolean language sql stable as $$select current_setting('test.membership_denied',true) is distinct from 'yes'$$;
create table public.system_settings(tenant_id uuid,key text,value jsonb);
create table public.period_closes(tenant_id uuid,data_environment text,entity_id text,period text,status text);
create table public.voucher_serials(tenant_id uuid,data_environment text,kind text,year integer,last_no integer,updated_at timestamptz,unique(data_environment,kind,year));
create table public.vouchers(id text primary key,no text,request_id text,entity_id text,entity_name text,voucher_date date,description text,entries jsonb,total numeric,creator text,posted boolean,posted_at timestamptz,posting_locked_at timestamptz,voided_at timestamptz,data_environment text,tenant_id uuid,adjusts_voucher_no text,adjustment_type text,created_at timestamptz default now());
create table public.ledger_entries(id uuid primary key default gen_random_uuid(),entry_date date,description text,entity_id text,department_code text,debit numeric,credit numeric,account_code text,account_name text,reference_no text,posting_key text unique,source_type text,source_id text,source_no text,voucher_no text,data_environment text,tenant_id uuid,voided_at timestamptz);
create unique index existing_ledger_key on public.ledger_entries(data_environment,posting_key) where posting_key is not null;
create table public.file_attachments(tenant_id uuid,record_type text,record_no text,data_environment text,bucket_id text,storage_path text);
create table public.cash_movement_evidence_links(tenant_id uuid,entity_id text,data_environment text,amount numeric);
create table public.finance_ledger_source_chains(tenant_id uuid,entity_id text,data_environment text,amount numeric);
create table public.accounting_posting_locks(tenant_id uuid,entity_id text,data_environment text,amount numeric);
create table public.cash_flow_bank_support_cases(tenant_id uuid,entity_id text,data_environment text,amount numeric);
`);
const baseline=JSON.parse(await fs.readFile(new URL('./fixtures/finance_hr_voucher_baseline_20260922.json',import.meta.url),'utf8'));
for(const f of baseline)await db.exec(f.definition);
await db.exec(`create trigger immutable before update or delete on public.vouchers for each row execute function public.prevent_posted_voucher_mutation();create trigger immutable before update or delete on public.ledger_entries for each row execute function public.prevent_posted_ledger_mutation();
do $$declare t text;begin foreach t in array array['vouchers','ledger_entries','file_attachments','cash_movement_evidence_links','finance_ledger_source_chains','accounting_posting_locks','cash_flow_bank_support_cases'] loop execute format('alter table public.%I enable row level security',t);execute format('grant select,insert,update,delete on public.%I to authenticated',t);execute format('create policy existing_accounting on public.%I for all to authenticated using(true) with check(true)',t);end loop;end $$;`);
for(const migration of ['20260922072109_finance_hr_private_bridge_v1.sql','20260922075604_finance_hr_voucher_posting_v1.sql'])await db.exec(await fs.readFile(new URL('../supabase/migrations/'+migration,import.meta.url),'utf8'));
await db.query(`insert into public.finance_users values ('accountant',$1,$2,'Accounting',true,'accountant'),('director',$1,$3,'Director',true,'admin_director'),('ceo',$1,$4,'CEO',true,'ceo')`,[tenant,accountant,director,ceo]);
await db.query(`insert into public.system_settings values($1,'accounts','[{"c":"2134","n":"應付薪資","on":true},{"c":"1112","n":"銀行存款","on":true},{"c":"1144","n":"進項稅額","on":true},{"c":"9999","n":"停用科目","on":false}]')`,[tenant]);
await db.query(`insert into finance_hr_private.finance_hr_salary_readers(tenant_id,source_employer_id,finance_user_id,business_role,verified_at,verified_by,evidence_reference,effective_from) values($1,$2,'accountant','accounting',now(),'fixture','SYNTHETIC',now()),($1,$2,'ceo','ceo',now(),'fixture','SYNTHETIC',now())`,[tenant,employer]);
await db.query(`insert into finance_hr_private.finance_hr_routes(tenant_id,source_employer_id,source_applicant_id,legal_entity_code,version,bank_actor,account_actor,cashier_actor,voucher_actor,verified_at,verified_by,evidence_reference,effective_from,active) values($1,$2,$3,'E1',1,'accountant','ceo','ceo','accountant',now(),'fixture','SYNTHETIC',now(),true)`,[tenant,employer,applicant]);
const source={totalNetCents:123456,lines:[{employeeId:randomUUID(),kind:'addition',amountCents:123456}]};
const hash=(await db.query('select finance_hr_private.finance_hr_hash($1) h',[source])).rows[0].h;
async function intake(){const id=randomUUID();await role('service_role');await rpc('finance_hr_intake',{p_event_id:randomUUID(),p_envelope:{schemaVersion:1,obligationId:id,flowId:id,sourceEmployerId:employer,originalApplicantId:applicant,revision:1,sourceHash:hash,source,payDate:'2026-10-15',period:'2026-09',kind:'monthly',amountMeaning:'calculated_net',paymentReady:false}});return id;}
async function prepare(id){for(const [n,action,user] of [[1,'bank_batch_validation',accountant],[2,'bank_upload',accountant],[3,'accounting_review',ceo],[4,'bank_disbursement',ceo]]){await role('authenticated',user);await rpc('finance_hr_command',{p_obligation_id:id,p_expected_version:n,p_request_id:randomUUID(),p_action:action,p_evidence:ev(action)});}await role('service_role');await rpc('finance_hr_applicant_confirm',{p_obligation_id:id,p_expected_version:5,p_request_id:randomUUID(),p_hr_actor_id:applicant,p_source_hash:hash,p_evidence:ev('applicant_confirmation')});}
const obligation=await intake();const entries=[{t:'dr',ac:'2134',amt:1234.56},{t:'cr',ac:'1112',amt:1234.56}];
const args={p_obligation_id:obligation,p_expected_version:6,p_request_id:randomUUID(),p_voucher_date:'2026-10-14',p_entries:entries,p_evidence:ev('posted_voucher')};
await role('authenticated',accountant);await reject(()=>rpc('finance_hr_post_voucher',{...args,p_expected_version:1}),/ACTION_OUT_OF_ORDER/);
await prepare(obligation);
await role('authenticated',director);await reject(()=>rpc('finance_hr_post_voucher',args),/FORBIDDEN/);await reject(()=>rpc('finance_hr_voucher_options',{p_obligation_id:obligation}),/FORBIDDEN/);
await role('authenticated',ceo);await reject(()=>rpc('finance_hr_post_voucher',args),/NOT_ASSIGNEE/);
await role('authenticated',accountant);eq((await rpc('finance_hr_voucher_options',{p_obligation_id:obligation})).accounts.map(x=>x.code),['1112','2134']);
await reject(()=>rpc('finance_hr_post_voucher',{...args,p_expected_version:5}),/VERSION_CONFLICT/);
await reject(()=>rpc('finance_hr_post_voucher',{...args,p_entries:[entries[0],{...entries[1],amt:1}]}),/UNBALANCED_OR_AMOUNT_MISMATCH/);
await reject(()=>rpc('finance_hr_post_voucher',{...args,p_entries:[{...entries[0],ac:'9999'},entries[1]]}),/INVALID_ACCOUNT_OR_AMOUNT/);
await reject(()=>rpc('finance_hr_post_voucher',{...args,p_entries:[{...entries[0],ac:'1144'},entries[1]]}),/INVALID_ENTRY/);
await db.exec("select set_config('test.membership_denied','yes',false)");await reject(()=>rpc('finance_hr_post_voucher',args),/ACCOUNTING_PERMISSION_REQUIRED/);await db.exec("select set_config('test.membership_denied','no',false)");
await role('postgres');await db.query("insert into public.period_closes values($1,'production','E1','2026-10','closed')",[tenant]);await role('authenticated',accountant);await reject(()=>rpc('finance_hr_post_voucher',args),/會計期間已關閉/);await role('postgres');await db.exec('delete from public.period_closes');
// A forced ledger failure rolls back voucher, number reservation, claim and event.
await db.exec("create function public.synthetic_failure() returns trigger language plpgsql as $$begin raise exception 'synthetic ledger failure';end$$;create trigger synthetic_failure before insert on public.ledger_entries for each row execute function public.synthetic_failure()");
await role('authenticated',accountant);await reject(()=>rpc('finance_hr_post_voucher',args),/synthetic ledger failure/);
await role('postgres');eq((await db.query('select count(*)::int n from public.vouchers')).rows[0].n,0);eq((await db.query('select count(*)::int n from finance_hr_private.finance_hr_postings')).rows[0].n,0);eq((await db.query('select count(*)::int n from public.voucher_serials')).rows[0].n,0);await db.exec('drop trigger synthetic_failure on public.ledger_entries');
await role('authenticated',accountant);const posted=await rpc('finance_hr_post_voucher',args);eq(posted.obligation.status,'closed');eq(posted.obligation.financeVersion,7);eq(posted.voucherNo,'HRV2026-00001');eq((await rpc('finance_hr_post_voucher',args)).replayed,true);await reject(()=>rpc('finance_hr_post_voucher',{...args,p_entries:[{...entries[0],ac:'1112'},entries[1]]}),/REPLAY_CONFLICT/);
const voucher=(await db.query('select * from public.vouchers')).rows[0];eq(voucher.request_id,'hr:'+obligation);eq(voucher.posted,true);eq(voucher.voucher_date.toISOString().slice(0,10),'2026-10-14','actual payment can precede the planned 15th payday');eq(voucher.total,'1234.56');eq((await db.query('select count(*)::int n from public.ledger_entries')).rows[0].n,2);eq((await db.query('select sum(debit-credit)::text n from public.ledger_entries')).rows[0].n,'0.00');eq(JSON.stringify(voucher).includes(source.lines[0].employeeId),false);
await reject(()=>db.query("update public.vouchers set voided_at=now() where id=$1",[voucher.id]),/immutable/);await reject(()=>db.exec('delete from public.ledger_entries'),/immutable/);
await reject(()=>rpc('reverse_voucher',{p_voucher_id:voucher.id,p_reason:'SYNTHETIC',p_reversal_date:'2026-10-16'}),/ATOMIC_POSTING_REQUIRED/);
await reject(()=>rpc('post_adjustment_voucher',{p_source_voucher_id:voucher.id,p_reason:'SYNTHETIC',p_entries:entries,p_voucher_date:'2026-10-16'}),/ATOMIC_POSTING_REQUIRED/);
await reject(()=>db.query("insert into public.vouchers(id,request_id,tenant_id) values('FORGED',$1,$2)",['hr:'+obligation,tenant]),/ATOMIC_POSTING_REQUIRED/);
await reject(()=>db.query("insert into public.ledger_entries(voucher_no,source_type,source_id,tenant_id) values($1,'hr_payroll',$2,$3)",[voucher.id,obligation,tenant]),/ATOMIC_POSTING_REQUIRED/);
// Derived SQL surfaces use the same complete-company denial, including aggregate-only rows.
await role('postgres');for(const t of ['cash_movement_evidence_links','finance_ledger_source_chains','accounting_posting_locks','cash_flow_bank_support_cases'])await db.query(`insert into public.${t} values($1,'E1','production',1234.56)`,[tenant]);
await db.query("insert into public.file_attachments values($1,'vouchers',$2,'production','finance-attachments','synthetic/payroll.pdf')",[tenant,voucher.id]);
await role('authenticated',director);for(const t of ['vouchers','ledger_entries','cash_movement_evidence_links','finance_ledger_source_chains','accounting_posting_locks','cash_flow_bank_support_cases','file_attachments'])await reject(()=>db.query('select * from public.'+t),/COMPLETE_REPORT_AUTHORIZATION_REQUIRED/);
for(const version of [2,3])await reject(()=>rpc('finance_executive_dashboard_v'+version,{p_start:'2026-01-01',p_end:'2026-12-31',p_previous_start:'2025-01-01',p_previous_end:'2025-12-31',p_trend_start:'2025-01-01',p_entity_id:'E1',p_data_environment:'production'}),/COMPLETE_REPORT_AUTHORIZATION_REQUIRED/);
for(const environment of ['', ' production ', null])await reject(()=>rpc('finance_executive_dashboard_v2',{p_start:'2026-01-01',p_end:'2026-12-31',p_previous_start:'2025-01-01',p_previous_end:'2025-12-31',p_trend_start:'2025-01-01',p_entity_id:'E1',p_data_environment:environment}),/COMPLETE_REPORT_AUTHORIZATION_REQUIRED/);
await reject(()=>rpc('finance_hr_accounting_scope',{p_tenant:tenant,p_entity:'E1',p_environment:'unknown'}),/INVALID_ENVIRONMENT/);
await reject(()=>rpc('finance_hr_attachment_scope',{p_tenant:tenant,p_record_type:'vouchers',p_record_no:voucher.id,p_environment:'test'}),/COMPLETE_REPORT_AUTHORIZATION_REQUIRED/);
await reject(()=>rpc('finance_can_read_voucher_attachment_v2',{p_storage_path:'synthetic/payroll.pdf'}),/COMPLETE_REPORT_AUTHORIZATION_REQUIRED/);
await role('postgres');await db.exec('grant usage on schema private to authenticated;grant execute on function private.finance_audit_source_v1(uuid,text,text),private.finance_ar_reconciliation_scope_v1(uuid,text,date,text,text) to authenticated');await role('authenticated',director);
await reject(()=>db.query("select private.finance_audit_source_v1($1,'E1','production')",[tenant]),/COMPLETE_REPORT_AUTHORIZATION_REQUIRED/);await reject(()=>db.query("select private.finance_ar_reconciliation_scope_v1($1,'production',current_date,'E1',null)",[tenant]),/COMPLETE_REPORT_AUTHORIZATION_REQUIRED/);
await role('authenticated',accountant);eq(await rpc('finance_can_read_voucher_attachment_v2',{p_storage_path:'synthetic/payroll.pdf'}),true);eq((await rpc('finance_hr_voucher_options',{p_obligation_id:obligation})).voucher.id,voucher.id);
// Exercise a same-transaction caller: a forged extra ordinal is denied, an
// exact duplicate ordinal hits the database uniqueness guard. Roll back the post.
const atomicId=await intake();await prepare(atomicId);await role('authenticated',accountant);await db.exec('begin');
const atomic=await rpc('finance_hr_post_voucher',{...args,p_obligation_id:atomicId,p_request_id:randomUUID()});
const cloneSQL="insert into public.ledger_entries(entry_date,description,entity_id,department_code,debit,credit,account_code,account_name,reference_no,posting_key,source_type,source_id,source_no,voucher_no,data_environment,tenant_id) select entry_date,description,entity_id,department_code,debit,credit,account_code,account_name,reference_no,posting_key||$1,source_type,source_id,source_no,voucher_no,data_environment,tenant_id from public.ledger_entries where voucher_no=$2 limit 1";
await db.exec('savepoint extra');await reject(()=>db.query(cloneSQL,[':extra',atomic.voucherId]),/ATOMIC_POSTING_REQUIRED/);await db.exec('rollback to savepoint extra');
await reject(()=>db.query(cloneSQL,['',atomic.voucherId]),/duplicate key/);await db.exec('rollback');
await role('postgres');
const pins=(await db.query("select n.nspname||'.'||p.proname name,md5(p.prosrc) body_md5 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='finance_hr_private' or (n.nspname='public' and p.proname like 'finance_hr_%') or p.proname in('finance_executive_dashboard_v2','finance_executive_dashboard_v3','finance_audit_source_v1','finance_ar_reconciliation_scope_v1','finance_can_read_voucher_attachment_v2') order by 1")).rows;await fs.writeFile('/tmp/finance-hr-voucher-function-pins.json',JSON.stringify(pins,null,2));
const postflight=(await fs.readFile(new URL('./finance_hr_bridge_postflight.sql',import.meta.url),'utf8')).replace(/^\\set ON_ERROR_STOP on\r?\n/,'');
await db.exec(postflight);checks++;
await db.exec('begin');await db.exec("create or replace function finance_hr_private.finance_hr_accounting_scope(p_tenant uuid,p_entity text,p_environment text) returns boolean language plpgsql stable security definer set search_path='' as $$begin return true;end$$");await reject(()=>db.exec(postflight),/differs from sealed source/);await db.exec('rollback');
await db.exec('begin;drop policy hr_salary_complete_scope on public.ledger_entries');await reject(()=>db.exec(postflight),/policy/);await db.exec('rollback');await db.exec(postflight);checks++;

if(process.env.HR_BRIDGE_BROWSER==='1'){
 const id=await intake();await prepare(id);let active=accountant, loseNextPost=true;
 const engine=await fs.readFile(new URL('../assets/engines/hr-bridge-engine.js',import.meta.url),'utf8'),css=await fs.readFile(new URL('../assets/styles/finance-core.css',import.meta.url),'utf8');
 const server=http.createServer(async(req,res)=>{try{if(req.method==='POST'){let raw='';for await(const c of req)raw+=c;const {name,args}=JSON.parse(raw);if(!['finance_hr_snapshot','finance_hr_voucher_options','finance_hr_post_voucher'].includes(name))throw Error('unexpected RPC');await role('authenticated',active);let data;try{data={data:await rpc(name,args),error:null}}catch(e){data={data:null,error:{message:e.message,code:e.code}}}if(name==='finance_hr_post_voucher' && !data.error && loseNextPost){loseNextPost=false;res.statusCode=502;res.setHeader('content-type','application/json');res.end(JSON.stringify({data:null,error:{message:'SYNTHETIC_AMBIGUOUS_COMMITTED_RESULT'}}));return}res.setHeader('content-type','application/json');res.end(JSON.stringify(data));return}if(req.url==='/engine.js'){res.setHeader('content-type','application/javascript');res.end(engine);return}if(req.url==='/style.css'){res.setHeader('content-type','text/css');res.end(css);return}res.setHeader('content-type','text/html');res.end('<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/style.css"><body style="display:block;padding:12px;height:auto;overflow:auto"><main id="bridge"></main><script src="/engine.js"></script><script>FinanceHrBridge.mount(document.querySelector("#bridge"),{userId:"accountant",isCurrent:()=>true,client:{rpc:async(name,args)=>(await fetch("/rpc",{method:"POST",body:JSON.stringify({name,args})})).json(),functions:{invoke:async()=>({data:{accepted:true,callbackPending:false}})}}});</script></html>');}catch(e){res.statusCode=500;res.end('fixture failure')}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const {chromium}=await import('playwright');const browser=await chromium.launch();try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);const card=page.locator('section.card').filter({hasText:id});await card.locator('[data-voucher]').waitFor();for(const width of [1280,390,320]){await page.setViewportSize({width,height:960});eq(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'responsive '+width)}
 await card.locator('input[name=voucherDate]').fill('2026-10-14');await card.locator('[data-entry-account]').nth(0).selectOption('2134');await card.locator('[data-entry-account]').nth(1).selectOption('1112');await card.locator('[data-entry-amount]').nth(1).fill('1');await card.locator('input[name=reference]').fill('SYNTHETIC-POSTING');await card.locator('input[type=file]').setInputFiles({name:'evidence.pdf',mimeType:'application/pdf',buffer:Buffer.from('synthetic evidence')});await card.locator('input[name=reviewed]').check();await card.locator('button[type=submit]').click();await page.getByText('借方與貸方都必須等於核准實發總額，尚未入帳。').waitFor();checks++;await card.locator('[data-entry-amount]').nth(1).fill('1234.56');await card.locator('button[type=submit]').click();await page.getByText('目前未能確認完成。請保留佐證並重新讀取狀態；相同內容重試會避免重複登錄。').waitFor();checks++;await page.getByRole('button',{name:'重新讀取',exact:true}).click();await card.getByText('已入帳結案 · 預定發放 2026-10-15',{exact:true}).waitFor();await card.getByText('查看已入帳傳票 HRV2026-00002').click();await card.getByText('借方 2134 應付薪資：$1,234.56',{exact:true}).waitFor();checks++;await page.screenshot({path:'/tmp/finance-hr-voucher-complete-mobile.png',fullPage:true});eq(errors,[]);
 await role('postgres');eq((await db.query('select count(*)::int n from public.ledger_entries where source_id=$1',[id])).rows[0].n,2);eq((await db.query('select payload->>\'status\' status from finance_hr_private.finance_hr_callback_outbox where obligation_id=$1 and finance_version=7',[id])).rows[0].status,'closed');
 }finally{await browser.close();await new Promise(r=>server.close(r));}
}
console.log(JSON.stringify({ok:true,checks,posting:'actual voucher and ledger via dedicated SQL RPC',bank:'synthetic evidence only'}));
}finally{await db.close()}
