// Actual PostgreSQL payroll transaction tests; synthetic identities/evidence only.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();let checks=0;
const eq=(a,b,m)=>{assert.deepEqual(a,b,m);checks++};
const reject=async(fn,p)=>{await assert.rejects(fn,p);checks++};
const tenant=randomUUID(),employer=randomUUID(),applicant=randomUUID(),accountant=randomUUID(),ceo=randomUUID(),director=randomUUID();
async function role(name,id=''){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec(`set role ${name}`)}
async function rpc(name,args={}){return(await db.query(`select public.${name}(${Object.keys(args).map((k,i)=>`${k}=>$${i+1}`).join(',')}) r`,Object.values(args))).rows[0].r}
try{
 // Reuse the sealed HR baseline fixture, not the test assertions or live data.
 const original=await fs.readFile(new URL('./test_hr_voucher_posting.mjs',import.meta.url),'utf8');
 let setup=original.slice(original.indexOf('await db.exec(`create role anon'),original.indexOf("eq((await db.query(\"select position"));
 setup=setup.replaceAll("new URL('./fixtures/", "new URL('./fixtures/").replace(",'20260927175827_finance_hr_native_contractor_bridge.sql','20260927180005_finance_hr_contractor_settlement_caption.sql'",'');
 await new (Object.getPrototypeOf(async function(){}).constructor)('db','fs','base',setup.replaceAll('import.meta.url','base'))(db,fs,import.meta.url);
 await db.exec(`create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint);create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,owner_id text,metadata jsonb,unique(bucket_id,name));alter table storage.objects enable row level security;grant usage on schema storage to authenticated,anon;revoke all on schema private from public,anon,authenticated;grant select,insert,update,delete on storage.objects to authenticated,anon;create policy legacy_owner on storage.objects for all to authenticated using(true) with check(true);create policy legacy_anon on storage.objects for select to anon using(true);
 create function private.finance_reporting_actor_v1(text,text) returns jsonb language plpgsql stable security definer set search_path='' as $$begin if current_setting('test.report_denied',true)='yes' then raise exception 'SYNTHETIC_REPORT_SCOPE_DENIED' using errcode='42501';end if;return '{}'::jsonb;end$$;`);
 // Install the actual existing HR-directory export boundary in this isolated
 // fixture. These tables contain fictional rows only; production is never read.
 await db.exec(`alter table public.finance_users add column shared_identity_employee_no text,add column entity_id text,add column department_code text,add column job_title text,add column org_status text;
 create table public.companies(id text,code text,name text,legal_name text,tax_id text,status text,deleted_at timestamptz);
 create table public.employees(id text,metadata jsonb,company_id text,employee_no text,full_name text,hire_date date,termination_date date,employment_status text,deleted_at timestamptz);
 create table public.finance_department_units(id text,tenant_id uuid,code text,name text,parent_unit_id text,primary_entity_code text,active boolean,unit_type text);
 create table private.finance_membership_org_versions_v1(id text,version_no bigint,status text,effective_at timestamptz,published_at timestamptz,snapshot jsonb);`);
 await db.exec(await fs.readFile(new URL('../supabase/migrations/20260924043205_finance_hr_directory_export_adopted.sql',import.meta.url),'utf8'));
 await db.exec(await fs.readFile(new URL('../supabase/migrations/20260927153326_finance_payroll_accrual_v1.sql',import.meta.url),'utf8'));
 for(const migration of ['20260927175827_finance_hr_native_contractor_bridge.sql','20260927180005_finance_hr_contractor_settlement_caption.sql'])await db.exec(await fs.readFile(new URL('../supabase/migrations/'+migration,import.meta.url),'utf8'));
 eq((await db.query("select position('FINANCE_HR_SETTLEMENT_MUST_CLEAR_ACCRUED_PAYABLE' in prosrc)>0 preserved from pg_proc where oid='finance_hr_private.finance_hr_post_voucher(uuid,integer,uuid,date,jsonb,jsonb)'::regprocedure")).rows[0].preserved,true,'contractor caption preserves anti-double-expense guard');
 for(const r of ['anon','authenticated']){eq((await db.query('select has_schema_privilege($1,\'private\',\'USAGE\') allowed',[r])).rows[0].allowed,false,'private namespace remains denied');await role(r);await reject(()=>rpc('finance_hr_directory_transport',{command:'snapshot',payload:{}}),/permission denied/);await reject(()=>db.query("select private.hr_directory_export('snapshot','{}')"),/permission denied/);await role('postgres');}
 await db.query(`insert into public.finance_users(id,tenant_id,auth_user_id,name,active,role) values('accountant',$1,$2,'Accountant',true,'accountant'),('ceo',$1,$3,'CEO',true,'ceo'),('director',$1,$4,'Director',true,'admin_director')`,[tenant,accountant,ceo,director]);
 await db.query(`insert into public.system_settings values($1,'accounts','[{"c":"6201","n":"薪資","on":true},{"c":"6203","n":"雇主成本","on":true},{"c":"2134","n":"應付薪資","on":true},{"c":"2140","n":"扣款","on":true},{"c":"2150","n":"雇主應付","on":true},{"c":"1112","n":"銀行","on":true}]'),($1,'departments','[{"c":"D1","n":"第一課","eid":"E1","active":true},{"c":"D2","n":"第二課","eid":"E1","active":true},{"c":"D3","n":"其他公司","eid":"E2","active":true},{"c":"D4","eid":"E1","active":false}]')`,[tenant]);
 await db.query(`insert into finance_hr_private.finance_hr_salary_readers(tenant_id,source_employer_id,finance_user_id,business_role,verified_at,verified_by,evidence_reference,effective_from) values($1,$2,'accountant','accounting',now(),'fixture','SYNTHETIC',now()),($1,$2,'ceo','ceo',now(),'fixture','SYNTHETIC',now());`,[tenant,employer]);
 await db.query(`insert into finance_hr_private.finance_hr_routes(tenant_id,source_employer_id,source_applicant_id,legal_entity_code,version,bank_actor,account_actor,cashier_actor,voucher_actor,verified_at,verified_by,evidence_reference,effective_from,active) values($1,$2,$3,'E1',1,'accountant','ceo','ceo','accountant',now(),'fixture','SYNTHETIC',now(),true)`,[tenant,employer,applicant]);
 async function intake(){const id=randomUUID(),source={totalNetCents:123456,lines:[{employeeId:randomUUID(),kind:'addition',amountCents:130000},{employeeId:randomUUID(),kind:'deduction',amountCents:6544}]};source.lines[1].employeeId=source.lines[0].employeeId;await role('postgres');const hash=(await db.query('select finance_hr_private.finance_hr_hash($1) h',[source])).rows[0].h;await role('service_role');await rpc('finance_hr_intake',{p_event_id:randomUUID(),p_envelope:{schemaVersion:1,obligationId:id,flowId:id,sourceEmployerId:employer,originalApplicantId:applicant,revision:1,sourceHash:hash,source,payDate:'2026-07-15',period:'2026-06',kind:'monthly',amountMeaning:'calculated_net',paymentReady:false}});return id}
 const contractorId=randomUUID(),contractorCase=randomUUID(),settlementId=randomUUID(),taxRunId=randomUUID();
 const contractorSource={totalNetCents:123456,settlementId,taxRunId,serviceId:randomUUID(),ruleYear:2026,ruleRevision:1,recipients:[{contractorId,payeeName:'SYNTHETIC',incomeCode:'50',grossCents:130000,withholdingCents:6544,supplementaryCents:0,netCents:123456,settlementId,taxRunId}]};
 await role('postgres');const contractorHash=(await db.query('select finance_hr_private.finance_hr_hash($1) h',[contractorSource])).rows[0].h;
 await role('service_role');await rpc('finance_hr_intake',{p_event_id:randomUUID(),p_envelope:{schemaVersion:1,obligationId:contractorCase,flowId:contractorCase,sourceEmployerId:employer,originalApplicantId:applicant,revision:1,sourceHash:contractorHash,source:contractorSource,payDate:'2026-07-15',period:'2026-06',kind:'contractor',amountMeaning:'calculated_net'}});
 await role('authenticated',accountant);await reject(()=>rpc('finance_payroll_accrual_evidence_prepare_v1',{p_request_id:randomUUID(),p_obligation_id:contractorCase}),/PAYROLL_ACCRUAL_FORBIDDEN/);
 const obligation=await intake();const entries=[{t:'dr',ac:'6201',amt:'1300.00',dept:'D1',component:'gross_salary'},{t:'cr',ac:'2140',amt:'65.44',dept:'D1',component:'deduction'},{t:'cr',ac:'2134',amt:'1234.56',dept:'D1',component:'net_payable'},{t:'dr',ac:'6203',amt:'100.01',dept:'D1',component:'employer_cost'},{t:'cr',ac:'2150',amt:'100.01',dept:'D1',component:'employer_payable'}];
 async function draft(obl=obligation,id=randomUUID()){await role('authenticated',accountant);const prepared=await rpc('finance_payroll_accrual_evidence_prepare_v1',{p_request_id:id,p_obligation_id:obl});await db.query('insert into storage.objects(bucket_id,name,owner_id,metadata) values($1,$2,$3,$4)',[prepared.bucket,prepared.path,accountant,{size:15}]);return {p_request_id:id,p_obligation_id:obl,p_entries:entries,p_evidence:{...prepared,reference:'SYNTHETIC-PAYROLL-202606',sha256:'a'.repeat(64)}}}
 const args=await draft();
 await role('postgres');await db.exec("update public.finance_users set role=null where id='accountant'");await role('authenticated',accountant);await reject(()=>rpc('finance_payroll_accrual_save_v1',args),/FORBIDDEN/);await reject(()=>rpc('finance_payroll_accrual_list_v1',{p_period:'2026-06'}),/FORBIDDEN/);await role('postgres');await db.exec("update public.finance_users set role='accountant' where id='accountant'");
 await role('anon');await reject(()=>rpc('finance_payroll_accrual_list_v1'),/permission denied/);eq((await db.query('select count(*)::int n from storage.objects')).rows[0].n,0,'legacy anon policy cannot expose evidence');
 await role('authenticated',director);await reject(()=>rpc('finance_payroll_accrual_save_v1',args),/FORBIDDEN/);eq((await db.query('select count(*)::int n from storage.objects')).rows[0].n,0);
 await role('authenticated',accountant);
 for(const bad of [{...entries[0],t:null},{...entries[0],t:undefined},{...entries[0],ac:null},{...entries[0],dept:'D3'},{...entries[0],dept:'D4'},{...entries[0],amt:'1300.001'},{...entries[0],ac:'1112'}])await reject(()=>rpc('finance_payroll_accrual_save_v1',{...args,p_entries:[bad,...entries.slice(1)]}),/INVALID/);
 await reject(()=>rpc('finance_payroll_accrual_save_v1',{...args,p_evidence:{...args.p_evidence,sha256:'invalid'}}),/EVIDENCE_REQUIRED/);
 await reject(()=>rpc('finance_payroll_accrual_save_v1',{...args,p_entries:entries.map((x,i)=>({...x,amt:i===0?'1400':i===1?'165.44':x.amt}))}),/APPROVED_GROSS_DEDUCTION_MISMATCH/);
 await reject(()=>rpc('finance_payroll_accrual_save_v1',{...args,p_entries:entries.map((x,i)=>({...x,dept:i===2?'D2':'D1'}))}),/DEPARTMENT_BALANCE_MISMATCH/);
 const submitted=await rpc('finance_payroll_accrual_save_v1',args);eq(submitted.accrual.status,'submitted');eq((await rpc('finance_payroll_accrual_save_v1',args)).replayed,true);
 const duplicate=await draft();await reject(()=>rpc('finance_payroll_accrual_save_v1',duplicate),/ALREADY_SUBMITTED/);
 eq((await rpc('finance_payroll_accrual_list_v1',{p_period:'2026-06'})).items.length,1);await db.exec("select set_config('test.report_denied','yes',false)");await reject(()=>rpc('finance_payroll_accrual_list_v1',{p_period:'2026-06'}),/REPORT_SCOPE_DENIED/);await db.exec("select set_config('test.report_denied','no',false)");await reject(()=>rpc('finance_payroll_accrual_list_v1'),/PERIOD_REQUIRED/);
 await reject(()=>rpc('finance_payroll_accrual_save_v1',{...args,p_evidence:{...args.p_evidence,reference:'changed'}}),/REPLAY_CONFLICT/);
 eq((await db.query('select count(*)::int n from public.vouchers')).rows[0].n,0);
 await reject(()=>rpc('finance_payroll_accrual_review_v1',{p_id:args.p_request_id,p_expected_version:1,p_reason:'checked'}),/INDEPENDENT_REVIEW/);
 eq((await db.query('delete from storage.objects returning name')).rows.length,0,'immutable evidence cannot be deleted through permissive legacy policy');
 await role('postgres');await db.query("insert into public.period_closes values($1,'production','E1','2026-06','closed')",[tenant]);await role('authenticated',ceo);
 const review={p_id:args.p_request_id,p_expected_version:1,p_reason:'原始核准清冊與部門分攤已覆核'};
 await reject(()=>db.query('select private.finance_payroll_accrual_review_v1($1,1,$2,null)',[args.p_request_id,'checked']),/permission denied for schema private/);await role('postgres');await reject(()=>db.query('select private.finance_payroll_accrual_review_v1($1,1,$2,null)',[args.p_request_id,'checked']),/OPERATION_REQUIRED/);await role('authenticated',ceo);
 await reject(()=>rpc('finance_payroll_accrual_review_v1',review),/期間已關閉/);
 await role('postgres');await db.exec("delete from public.period_closes;create function public.synthetic_failure() returns trigger language plpgsql as $$begin raise exception 'synthetic ledger failure';end$$;create trigger synthetic_failure before insert on public.ledger_entries for each row execute function public.synthetic_failure()");await role('authenticated',ceo);
 await reject(()=>rpc('finance_payroll_accrual_review_v1',review),/synthetic ledger failure/);
 await role('postgres');eq((await db.query('select count(*)::int n from public.vouchers')).rows[0].n,0);eq((await db.query('select count(*)::int n from public.voucher_serials')).rows[0].n,0);eq((await db.query('select status from private.finance_payroll_accruals_v1')).rows[0].status,'submitted');await db.exec('drop trigger synthetic_failure on public.ledger_entries');await role('authenticated',ceo);
 const posted=await rpc('finance_payroll_accrual_review_v1',review);eq(posted.accrual.status,'posted');eq((await rpc('finance_payroll_accrual_review_v1',review)).replayed,true);await reject(()=>rpc('finance_payroll_accrual_review_v1',{...review,p_reason:'changed'}),/VERSION_CONFLICT/);
 const voucher=(await db.query('select * from public.vouchers')).rows[0];eq(voucher.voucher_date.toISOString().slice(0,10),'2026-06-30');eq(Number(voucher.total),1400.01);eq(Number((await db.query('select sum(debit-credit)::text n from public.ledger_entries')).rows[0].n),0);eq(Number((await db.query("select sum(debit-credit)::text n from public.ledger_entries where account_code~'^[56]' and department_code='D1'")).rows[0].n),1400.01);
 await reject(()=>db.query("insert into public.ledger_entries(voucher_no,source_type,source_id,tenant_id) values($1,'payroll_accrual',$2,$3)",[voucher.id,args.p_request_id,tenant]),/ATOMIC_POST_REQUIRED/);
 await role('authenticated',director);await reject(()=>db.query('select * from public.vouchers'),/COMPLETE_REPORT_AUTHORIZATION/);await reject(()=>db.query('select * from public.ledger_entries'),/COMPLETE_REPORT_AUTHORIZATION/);
 await role('postgres');eq((await db.query('select status,version,total_net_cents from finance_hr_private.finance_hr_obligations where obligation_id=$1',[obligation])).rows[0],{status:'awaiting_payment_validation',version:1,total_net_cents:123456});
 async function prepareNet(id){const h=(await db.query('select source_hash from finance_hr_private.finance_hr_obligations where obligation_id=$1',[id])).rows[0].source_hash;for(const[n,action,user]of[[1,'bank_batch_validation',accountant],[2,'bank_upload',accountant],[3,'accounting_review',ceo],[4,'bank_disbursement',ceo]]){await role('authenticated',user);await rpc('finance_hr_command',{p_obligation_id:id,p_expected_version:n,p_request_id:randomUUID(),p_action:action,p_evidence:{kind:action,reference:'SYNTHETIC',sha256:'a'.repeat(64),totalNetCents:123456}})}await role('service_role');await rpc('finance_hr_applicant_confirm',{p_obligation_id:id,p_expected_version:5,p_request_id:randomUUID(),p_hr_actor_id:applicant,p_source_hash:h,p_evidence:{kind:'applicant_confirmation',reference:'SYNTHETIC',sha256:'a'.repeat(64)}});await role('authenticated',accountant)}
 const netArgs=id=>({p_obligation_id:id,p_expected_version:6,p_request_id:randomUUID(),p_voucher_date:'2026-07-15',p_entries:[{t:'dr',ac:'2134',amt:1234.56},{t:'cr',ac:'1112',amt:1234.56}],p_evidence:{kind:'posted_voucher',reference:'SYNTHETIC',sha256:'a'.repeat(64)}});
 await prepareNet(obligation);const net=netArgs(obligation);await reject(()=>rpc('finance_hr_post_voucher',{...net,p_entries:[{...net.p_entries[0],ac:'6201'},net.p_entries[1]]}),/MUST_CLEAR_ACCRUED_PAYABLE/);await rpc('finance_hr_post_voucher',net);await role('postgres');eq(Number((await db.query("select sum(debit-credit)::text n from public.ledger_entries where account_code~'^[56]'" )).rows[0].n),1400.01,'net settlement never repeats gross payroll cost');
 const historical=await intake();await role('postgres');await prepareNet(historical);const oldNet=netArgs(historical);await rpc('finance_hr_post_voucher',{...oldNet,p_entries:[{...oldNet.p_entries[0],ac:'6201'},oldNet.p_entries[1]]});const historicalDraft=await draft(historical);await reject(()=>rpc('finance_payroll_accrual_save_v1',historicalDraft),/SETTLEMENT_ALREADY_EXPENSED/);
 const correction=await intake(),correctionArgs=await draft(correction);await rpc('finance_payroll_accrual_save_v1',correctionArgs);await role('authenticated',ceo);const returned=await rpc('finance_payroll_accrual_return_v1',{p_id:correctionArgs.p_request_id,p_expected_version:1,p_reason:'分攤文件請重新確認'});eq(returned.accrual.status,'returned');const replacement=await draft(correction);eq((await rpc('finance_payroll_accrual_save_v1',replacement)).accrual.status,'submitted');await role('postgres');eq((await db.query('select count(*)::int n from private.finance_payroll_accrual_events_v1 where accrual_id=$1',[correctionArgs.p_request_id])).rows[0].n,2);
 await db.query(`update public.system_settings set value=value||'[{"c":"2141","n":"應付薪資甲","on":true},{"c":"2142","n":"應付薪資乙","on":true}]'::jsonb where tenant_id=$1 and key='accounts'`,[tenant]);
 const splitId=await intake(),split=await draft(splitId);split.p_entries=[...entries.slice(0,2),{...entries[2],ac:'2141',amt:'1000'},{...entries[2],ac:'2142',amt:'234.56'},...entries.slice(3)];await rpc('finance_payroll_accrual_save_v1',split);await role('authenticated',ceo);await rpc('finance_payroll_accrual_review_v1',{p_id:split.p_request_id,p_expected_version:1,p_reason:'SYNTHETIC SPLIT CHECKED'});await role('postgres');await prepareNet(splitId);const splitNet=netArgs(splitId);await reject(()=>rpc('finance_hr_post_voucher',{...splitNet,p_entries:[{...splitNet.p_entries[0],ac:'2141'},splitNet.p_entries[1]]}),/MUST_CLEAR_ACCRUED_PAYABLE/);await rpc('finance_hr_post_voucher',{...splitNet,p_entries:[{t:'dr',ac:'2141',amt:1000},{t:'dr',ac:'2142',amt:234.56},splitNet.p_entries[1]]});checks++;
 const priorId=await intake();await role('postgres');await prepareNet(priorId);await rpc('finance_hr_post_voucher',netArgs(priorId));const prior=await draft(priorId);prior.p_entries=entries.map(x=>x.component==='net_payable'?{...x,ac:'2141'}:x);await reject(()=>rpc('finance_payroll_accrual_save_v1',prior),/PRIOR_SETTLEMENT_PAYABLE_MISMATCH/);
 const noFileId=await intake();await role('authenticated',accountant);const noFileKey=randomUUID(),noFile=await rpc('finance_payroll_accrual_evidence_prepare_v1',{p_request_id:noFileKey,p_obligation_id:noFileId});await reject(()=>rpc('finance_payroll_accrual_save_v1',{...args,p_request_id:noFileKey,p_obligation_id:noFileId,p_evidence:{...args.p_evidence,...noFile}}),/PERSISTED_EVIDENCE_REQUIRED/);
 const departmentalId=await intake(),departmental=await draft(departmentalId);departmental.p_entries=[{...entries[0],amt:'800'},{...entries[1],amt:'40'},{...entries[2],amt:'760'},{...entries[0],dept:'D2',amt:'500'},{...entries[1],dept:'D2',amt:'25.44'},{...entries[2],dept:'D2',amt:'474.56'},...entries.slice(3)];await rpc('finance_payroll_accrual_save_v1',departmental);await role('authenticated',ceo);const departmentalPost=await rpc('finance_payroll_accrual_review_v1',{p_id:departmental.p_request_id,p_expected_version:1,p_reason:'SYNTHETIC DEPARTMENT COST VERIFIED'});eq((await db.query("select department_code,sum(debit-credit)::numeric(18,2)::text cost from public.ledger_entries where voucher_no=$1 and account_code~'^[56]' group by department_code order by department_code",[departmentalPost.accrual.voucherId])).rows,[{department_code:'D1',cost:'900.01'},{department_code:'D2',cost:'500.00'}]);
 await role('postgres');
 const pins=(await db.query("select n.nspname||'.'||p.proname name,md5(p.prosrc) body_md5 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.proname like 'finance_payroll_%' or (n.nspname='finance_hr_private' and p.proname in('finance_hr_accounting_scope','finance_hr_post_voucher')) order by 1")).rows;await fs.writeFile('/tmp/finance-payroll-accrual-pins.json',JSON.stringify(pins,null,2));
 const postflight=(await fs.readFile(new URL('./finance_payroll_accrual_v1_postflight.sql',import.meta.url),'utf8')).replace(/^\\set ON_ERROR_STOP on\r?\n/,'');await db.exec(postflight);checks++;
 const directoryPostflight=(await fs.readFile(new URL('./finance_hr_directory_export_postflight.sql',import.meta.url),'utf8')).replace(/^\\set ON_ERROR_STOP on\r?\n/,'');await db.exec(directoryPostflight);checks++;
 await role('service_role');await db.exec(`select set_config('request.jwt.claims','{"role":"service_role"}',false)`);eq((await rpc('finance_hr_directory_transport',{command:'snapshot',payload:{}})).schemaVersion,1,'service-only directory export remains operational');await role('postgres');
 for(const[tamper,pattern]of[["alter function public.finance_payroll_accrual_list_v1(text,text) security invoker",/bounded postgres definer/],["grant execute on function public.finance_payroll_accrual_list_v1(text,text) to anon",/ACL changed/],["drop policy payroll_evidence_no_anon_v1 on storage.objects",/Storage policy missing/],["alter table private.finance_payroll_accruals_v1 no force row level security",/RLS missing/],["grant usage on schema private to authenticated",/namespace isolation/]]){await db.exec('begin');await db.exec(tamper);await reject(()=>db.exec(postflight),pattern);await db.exec('rollback');}
 console.log(JSON.stringify({ok:true,checks,ledger:'actual synthetic PostgreSQL',source:'approved gross and deductions; independent review; salary month'}));
}finally{await db.close()}
